-- Backfill explained_samples batch 29 (BST/AVL/Trie/N-ary), converted from backfill-explained-samples-batch29.mjs
-- Idempotent: only updates rows that do not already hold >= 3 samples.

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[4,2,5,1,3]","3.714286"],"expected":"4","explanation_md":"Canonical LC example. Walk the BST guided by the BST property: at each node, compare target to node.val and descend left if target < node.val else right, tracking the running closest. Start at root 4: |4-3.714| = 0.286, best=4. 3.714 < 4 so go left to 2: |2-3.714| = 1.714, worse, keep best=4. 3.714 > 2 so go right to 3: |3-3.714| = 0.714, worse, keep 4. 3.714 > 3 so go right (none). Return 4. The BST guide means we touch O(h) nodes, not all n.","viz_anchor":null},
{"inputs":["[1]","4.428571"],"expected":"1","explanation_md":"Edge case: single node tree. There is no descent to make — the one value IS the answer regardless of how far the target sits. Best initialized to root.val = 1, then loop exits since root.left and root.right are both null. Return 1. A bug that initialized best to None or to 0 would fail this trivial case; always seed best with the root value before descending.","viz_anchor":null},
{"inputs":["[2,1,3]","0.5"],"expected":"1","explanation_md":"Algorithmically interesting: target sits LEFT of the entire tree. Start at 2: diff = 1.5, best=2. 0.5 < 2, go left to 1: diff = 0.5, best=1. 0.5 < 1, go left (none). Return 1. The naive in-order traversal collecting all values would also work but costs O(n) — the guided descent costs O(log n) on a balanced tree. The key insight: once we move left because target < node, the right subtree CANNOT contain anything closer (every value there is > node, hence farther from target than node itself).","viz_anchor":null}
]'::jsonb WHERE id = 'closest-binary-search-tree-value' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[4,2,5,1,3]","3.714286","2"],"expected":"[4,3]","explanation_md":"Canonical LC example. Two clean approaches: (1) in-order traversal into a sorted list, then two-pointer slide on the k-window; (2) two stacks (predecessor + successor) seeded by walking down from root, advancing whichever is closer to target. In-order: [1,2,3,4,5]. The k=2 window minimizing sum-of-|x - 3.714| centers at 3.714: candidates {3,4} with diffs {0.714, 0.286}. Return [4,3]. The two-stack version runs in O(h + k); the sorted-list version in O(n).","viz_anchor":null},
{"inputs":["[1]","0.000000","1"],"expected":"[1]","explanation_md":"Edge case: single node, k=1. In-order list is [1]. Only one candidate exists — return [1] regardless of target distance. Both predecessor and successor stacks are empty after seeding, so the heap-style merge terminates immediately with the one value already collected. Guard against k > n only if the spec allows it; LC guarantees k <= n.","viz_anchor":null},
{"inputs":["[3,1,4,null,2]","2.000000","3"],"expected":"[2,1,3]","explanation_md":"Algorithmically interesting: target is an EXACT match to a node, k spans both sides. In-order: [1,2,3,4]. Distances from 2.0: [1,0,1,2]. Pick the 3 smallest — {2,1,3}. The two-stack merge: succ stack starts at [2], pred stack at [1]. Pop succ -> 2 (diff 0). Advance: 2 has no right child via this seeding, succ becomes the in-order successor 3. Pop pred -> 1 (diff 1). Pop succ -> 3 (diff 1). Result [2,1,3]. A naive sort-by-distance approach would also work but is O(n log n) vs the two-stack O(h + k).","viz_anchor":null}
]'::jsonb WHERE id = 'closest-binary-search-tree-value-ii' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[1,3,null,null,2]"],"expected":"[3,1,null,null,2]","explanation_md":"Canonical LC example. Two nodes were swapped — find them via in-order traversal. In-order of the broken tree: [3,2,1] (since left subtree of root 1 is 3->2). A correct BST inorder must be strictly increasing. First descent (3 -> 2): we hit the FIRST violation, mark first = 3, second = 2 (tentative). Next pair (2 -> 1): another violation — overwrite second = 1. Final swap: 3 and 1. Result tree inorder becomes [1,2,3]. The O(1)-space Morris variant works too; the recursive version uses O(h) stack.","viz_anchor":null},
{"inputs":["[3,1,4,null,null,2]"],"expected":"[2,1,4,null,null,3]","explanation_md":"Edge case: the two swapped nodes are NON-ADJACENT in the in-order sequence. In-order of broken tree: [1,3,2,4]. First dip (3 -> 2): first = 3, second = 2. No more dips. The single-pass detector handles both adjacent (one violation) and non-adjacent (two violations) by only assigning first ONCE but always overwriting second. Swap 3 and 2 -> in-order becomes [1,2,3,4]. The trick: the second swapped node is the LAST node that violated the increasing order.","viz_anchor":null},
{"inputs":["[2,1]"],"expected":"[2,1]","explanation_md":"Algorithmically interesting: already a valid BST. Inorder traversal: [1,2] — strictly increasing, no violations detected, first and second remain null. Swap does nothing. Return tree unchanged. This guards the algorithm: ALWAYS run the detector, but only perform the swap when first is not null. A buggy implementation that unconditionally swapped tree.val with itself or with null would corrupt valid input.","viz_anchor":null}
]'::jsonb WHERE id = 'recover-binary-search-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[2,1,3]","1"],"expected":"2","explanation_md":"Canonical LC example. Successor = smallest node with value > p.val. Walk from root tracking the BEST candidate seen so far. Start at 2: 2 > 1, candidate = 2, go left. At 1: 1 is not > 1, go right (null). Loop ends — return candidate 2. The O(h) descent beats the O(n) parent-pointer walk that uses the textbook successor rule (if right subtree, take its leftmost; else climb until you came from the left).","viz_anchor":null},
{"inputs":["[5,3,6,2,4,null,null,1]","6"],"expected":"null","explanation_md":"Edge case: p is the maximum element — no successor exists. Descend from root 5: 5 not > 6, go right. At 6: 6 not > 6, go right (null). Loop ends with candidate still null. Return null. Many naive implementations forget to return null and instead return the last visited node, leaking the wrong answer. The candidate-only invariant guards this: only nodes strictly greater than p update the candidate.","viz_anchor":null},
{"inputs":["[5,3,6,2,4,null,null,1]","4"],"expected":"5","explanation_md":"Algorithmically interesting: p has no right child, so successor must come from an ANCESTOR. Trace: 5 > 4, candidate = 5, go left. At 3: 3 not > 4, go right. At 4: 4 not > 4, go right (null). Candidate = 5. Return 5. The right-subtree rule alone fails here; the descent-with-candidate pattern handles both branches uniformly. Intuition: every time we go LEFT (because node > p), we update the candidate — the eventual candidate is the deepest such ancestor, which is exactly the in-order successor.","viz_anchor":null}
]'::jsonb WHERE id = 'inorder-successor-in-bst' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[5,3,6,2,4,null,7]","9"],"expected":"true","explanation_md":"Canonical LC example. Two clean approaches: (1) in-order traversal -> sorted list, then two-pointer; (2) BFS/DFS with a hash set of complements. In-order: [2,3,4,5,6,7]. Two pointers l=0 (2), r=5 (7): sum=9 -> return true. Approach 1 is O(n) time + O(n) space, exploits the BST property fully. Approach 2 ignores the BST property but is also O(n) and more flexible.","viz_anchor":null},
{"inputs":["[1]","2"],"expected":"false","explanation_md":"Edge case: single node, target = 2 * root.val. The hash-set approach checks: is (target - 1) = 1 already in the set? No, set is empty. Add 1, traversal ends. Return false. The BST has only one node, so by definition no pair of DISTINCT nodes can sum to anything — the \"distinct\" requirement is what blocks the trivial 1 + 1 = 2 match. A bug that allowed reusing the same node would wrongly return true.","viz_anchor":null},
{"inputs":["[5,3,6,2,4,null,7]","28"],"expected":"false","explanation_md":"Algorithmically interesting: max possible pair sum is 6 + 7 = 13, far below 28 — every pair fails. Hash-set traversal walks all 6 nodes, checking complement (28 - val) each time: 23, 25, 24, 26, 22, 21 — none ever exist in the set. Return false. The two-pointer approach is even cleaner: after sorted = [2,3,4,5,6,7], l=0, r=5, sum=9, advance l. Keep moving until l >= r without ever hitting 28. The early-exit case never triggers here.","viz_anchor":null}
]'::jsonb WHERE id = 'two-sum-iv-input-is-a-bst' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[1,null,2,2]"],"expected":"[2]","explanation_md":"Canonical LC example. BST in-order traversal yields a NON-DECREASING sequence, so all equal values cluster together. Single pass: track curr_val, curr_count, max_count, modes list. Inorder: 1, 2, 2. At 1: curr_val=1, curr_count=1, max_count=1, modes=[1]. At first 2: new value -> curr_count=1, equal to max -> modes.append(2) -> [1,2]. At second 2: curr_count=2 > max=1 -> max_count=2, modes=[2]. Return [2]. O(n) time, O(1) extra (modes list aside) without a hashmap.","viz_anchor":null},
{"inputs":["[0]"],"expected":"[0]","explanation_md":"Edge case: single node. Inorder: [0]. curr_val=0, curr_count=1, max_count=1, modes=[0]. Return [0]. The init must seed curr_val to None and max_count to 0 so the FIRST node correctly creates the first cluster. A bug that initialized max_count=1 with empty modes would miss the only value and return [].","viz_anchor":null},
{"inputs":["[1,1,2,null,null,2,3]"],"expected":"[1,2]","explanation_md":"Algorithmically interesting: TIED modes. This tree is not strictly a BST (duplicates allowed). Inorder: 1, 1, 2, 2, 3. At first 1: count=1, max=1, modes=[1]. At second 1: count=2 > max -> max=2, modes=[1]. At first 2: new value, count=1, less than max=2, do nothing. At second 2: count=2 == max -> modes.append(2) -> [1,2]. At 3: count=1 < max, ignored. Return [1,2]. The == max branch is what enables multiple modes; forgetting it returns only the FIRST mode encountered.","viz_anchor":null}
]'::jsonb WHERE id = 'find-mode-in-binary-search-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[1,0,2]","1","2"],"expected":"[1,null,2]","explanation_md":"Canonical LC example. Recursive descent that returns the trimmed subtree root. At node 1 (in [1,2]): root.left = trim(0), root.right = trim(2), return 1. At node 0: 0 < low=1, so the WHOLE node and its left subtree are out of range, but right subtree might still be valid. Return trim(right) = trim(null) = null. At node 2: in range, recurse both sides (null). Return 2. Final tree: 1 with right=2, left=null. The BST property is what makes this O(n): when node.val < low, we never need to inspect node.left.","viz_anchor":null},
{"inputs":["[1]","2","3"],"expected":"null","explanation_md":"Edge case: every node trimmed away. trim(1) sees 1 < low=2, so return trim(right) = trim(null) = null. Final tree is null. The caller must accept null as a valid return — never blow up on the empty-tree case. A buggy iterative version that mutates root.left/root.right in place may forget to handle the case where ROOT ITSELF must be removed.","viz_anchor":null},
{"inputs":["[3,0,4,null,2,null,null,1]","1","3"],"expected":"[3,2,null,1]","explanation_md":"Algorithmically interesting: skipping a node but preserving its descendants. trim(3): in range, recurse. trim(0): 0 < 1, return trim(0.right). 0.right is 2 (in range). trim(2): recurse left and right. trim(1): in range, leaf — return 1. So trim(2) = node 2 with left=1. That node 2 becomes 3.left. trim(4): 4 > high=3, return trim(4.left) = null. Final tree: 3 -> left = 2 -> left = 1. The replacement of node 0 by its grandchild 2 is what the recursion encodes cleanly: \"return the surviving subtree, whatever it is.\"","viz_anchor":null}
]'::jsonb WHERE id = 'trim-a-binary-search-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["3"],"expected":"5","explanation_md":"Canonical LC example. This counts the n-th Catalan number C(n). DP: G[n] = sum over i in 1..n of G[i-1] * G[n-i]. Trace: G[0]=1, G[1]=1, G[2] = G[0]*G[1] + G[1]*G[0] = 2, G[3] = G[0]*G[2] + G[1]*G[1] + G[2]*G[0] = 2 + 1 + 2 = 5. Intuition: pick root i, left subtree formed from {1..i-1} (G[i-1] shapes), right subtree from {i+1..n} (G[n-i] shapes, shape only depends on count). Multiply and sum over roots. Return 5.","viz_anchor":null},
{"inputs":["1"],"expected":"1","explanation_md":"Edge case: single value. Only one BST: a single node. G[1] = G[0]*G[0] = 1*1 = 1. The base case G[0] = 1 (empty tree counts as ONE valid arrangement) is critical — if you set G[0] = 0, every product collapses to 0 and the whole table goes wrong. Return 1.","viz_anchor":null},
{"inputs":["5"],"expected":"42","explanation_md":"Algorithmically interesting: growth is super-exponential. Continuing: G[4] = G[0]G[3] + G[1]G[2] + G[2]G[1] + G[3]G[0] = 5 + 2 + 2 + 5 = 14. G[5] = G[0]G[4] + G[1]G[3] + G[2]G[2] + G[3]G[1] + G[4]G[0] = 14 + 5 + 4 + 5 + 14 = 42. Return 42. Closed form: C(n) = binomial(2n, n) / (n + 1); for n=5: 252 / 6 = 42 — matches. The O(n^2) DP is fine for n <= 19 (the LC constraint); larger n needs the BigInt-safe closed form.","viz_anchor":null}
]'::jsonb WHERE id = 'unique-binary-search-trees' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["3"],"expected":"[[1,null,2,null,3],[1,null,3,2],[2,1,3],[3,1,null,null,2],[3,2,null,1]]","explanation_md":"Canonical LC example. Recursive constructor: build(lo, hi) returns the list of all BST shapes using values [lo..hi]. For each root i in [lo..hi], take the cross product of build(lo, i-1) and build(i+1, hi). build(1,3): roots 1, 2, 3. root 1: left=build(1,0)=[null], right=build(2,3). root 2: left=[1], right=[3] -> one tree. root 3: left=build(2,3) which gives [2,3] and [3,2] orderings. The five resulting trees match the Catalan count 5.","viz_anchor":null},
{"inputs":["1"],"expected":"[[1]]","explanation_md":"Edge case: single value. build(1,1): root must be 1. left = build(1,0) = [null], right = build(2,1) = [null]. One tree: a leaf with value 1. Return [[1]]. The [null] sentinel is what lets the cross product still produce one tree; a bug that returned [] for the empty range would multiply to zero trees.","viz_anchor":null},
{"inputs":["2"],"expected":"[[1,null,2],[2,1]]","explanation_md":"Algorithmically interesting: two roots, two shapes. build(1,2): root 1 -> left=[null], right=build(2,2)=[2] -> tree (1, null, 2). root 2 -> left=build(1,1)=[1], right=[null] -> tree (2, 1, null). Two trees total — matches Catalan C(2) = 2. The memoization on (lo, hi) saves work for large n but the tree-NODES still all need to be distinct objects, otherwise mutating one shape corrupts another sharing nodes.","viz_anchor":null}
]'::jsonb WHERE id = 'unique-binary-search-trees-ii' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[-10,-3,0,5,9]"],"expected":"[0,-3,9,-10,null,5]","explanation_md":"Canonical LC example. Pick the MIDDLE element as root, recurse on left half for left subtree, right half for right subtree. This guarantees height-balance because both halves differ in size by at most 1. Indices 0..4: mid = 2 -> root = 0. Left [-10,-3]: mid=1 -> root=-3, left=[-10] -> leaf. Right [5,9]: mid=1 -> root=9, left=[5] -> leaf. Result tree: 0 with left subtree (-3 with left -10) and right subtree (9 with left 5). Returns the height-balanced BST in O(n) time and O(log n) recursion depth.","viz_anchor":null},
{"inputs":["[1]"],"expected":"[1]","explanation_md":"Edge case: single element. mid = 0, root = 1, left = build([]) = null, right = build([]) = null. Returns a one-node tree. The base case for empty slice returns None — without it, the recursion would infinite-loop trying to split an empty range. Always check lo > hi before computing mid.","viz_anchor":null},
{"inputs":["[1,3]"],"expected":"[3,1]","explanation_md":"Algorithmically interesting: even-length array forces a choice. mid = (0+1)//2 = 0 -> root = 1, OR mid = (0+1+1)//2 = 1 -> root = 3. Either yields a height-balanced tree, but LC tolerates both shapes. Using lo + (hi - lo + 1) // 2 picks the RIGHT-middle (3), giving tree [3, 1]. Picking left-middle gives [1, null, 3] — also balanced. The grader accepts any valid balanced BST.","viz_anchor":null}
]'::jsonb WHERE id = 'convert-sorted-array-to-binary-search-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[-10,-3,0,5,9]"],"expected":"[0,-3,9,-10,null,5]","explanation_md":"Canonical LC example. Slow + fast pointer finds the middle of the linked list, that becomes root. Then recurse on left half (head up to but not including mid) and right half (mid.next onward). Trace: head = -10 -> -3 -> 0 -> 5 -> 9. Fast/slow lands on 0. Detach the list at the previous node so left half is [-10,-3] and right half is [5,9]. Recurse on each, applying the same midpoint rule. The classic in-order trick: simulate inorder traversal of the FUTURE tree by walking the list while building nodes top-down. O(n) time, O(log n) depth.","viz_anchor":null},
{"inputs":["[]"],"expected":"[]","explanation_md":"Edge case: empty list. The recursion sees head == null and returns null immediately. Result: empty tree. A bug that always dereferenced head before the null check would crash here. Same null guard handles the empty SUB-list during recursion when the input is non-empty.","viz_anchor":null},
{"inputs":["[1,3]"],"expected":"[3,1]","explanation_md":"Algorithmically interesting: 2-node list. Fast/slow with fast starting at head: slow stays at 1, fast jumps to 3 on first move, fast.next is null, loop exits. slow = 1, but the convention is mid = slow.next when fast starts at head — pick which slow lands on by initial fast-pointer offset. Picking 3 as root: left = [1], right = []. Tree [3, 1]. Either child as root is balanced; LC accepts both.","viz_anchor":null}
]'::jsonb WHERE id = 'convert-sorted-list-to-binary-search-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[1,null,2,null,3,null,4,null,null]"],"expected":"[2,1,3,null,null,null,4]","explanation_md":"Canonical LC example. Two-pass approach: (1) in-order traversal flattens BST to sorted array, (2) build a balanced BST from that array using the middle-as-root rule. Inorder of right-skewed [1,2,3,4]: [1,2,3,4]. Mid index = 1 -> root = 2. Left [1] -> leaf. Right [3,4] -> mid 1 -> root=4, left=[3]. Result: 2 with left=1 and right=(4 with left=3). Height becomes 3 instead of 4 — balanced. O(n) total. Day-Stout-Warren is the in-place alternative if memory matters.","viz_anchor":null},
{"inputs":["[2,1,3]"],"expected":"[2,1,3]","explanation_md":"Edge case: already balanced. Inorder: [1,2,3]. Mid=1 -> root=2, left=[1], right=[3]. The rebuilt tree is structurally identical to the input. Doing the work even when unnecessary is fine — recognizing the already-balanced case as a no-op optimization is OPTIONAL; the simple algorithm just always rebuilds and is O(n). A premature optimization checking \"is the input balanced?\" costs another O(n) traversal anyway.","viz_anchor":null},
{"inputs":["[1,null,2,null,3,null,4,null,5,null,6,null,7]"],"expected":"[4,2,6,1,3,5,7]","explanation_md":"Algorithmically interesting: maximum height reduction. Right-skewed chain of 7 nodes has height 7. Inorder: [1,2,3,4,5,6,7]. Mid=3 -> root=4. Left [1,2,3]: mid=1 -> root=2, left=[1], right=[3]. Right [5,6,7]: mid=1 -> root=6, left=[5], right=[7]. Final perfect tree of height 3 (log2(7) = ~2.8 + 1). Massive height drop from 7 -> 3 = 4x faster lookups. The middle-as-root choice is what makes the result OPTIMALLY balanced.","viz_anchor":null}
]'::jsonb WHERE id = 'balance-a-binary-search-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[4,1,6,0,2,5,7,null,null,null,3,null,null,null,8]"],"expected":"[30,36,21,36,35,26,15,null,null,null,33,null,null,null,8]","explanation_md":"Canonical LC example. REVERSE in-order traversal (right -> node -> left) visits nodes from LARGEST to SMALLEST. Maintain a running accumulator: when visiting a node, accumulator += node.val, then assign node.val = accumulator. Tree values in reverse inorder: 8, 7, 6, 5, 4, 3, 2, 1, 0. Running sums: 8, 15, 21, 26, 30, 33, 35, 36, 36. Reassign each node in place. Node 8 -> 8, node 7 -> 15, node 6 -> 21, etc. O(n) time, O(h) recursion depth. The BST property is essential: in-order = sorted order = easy running sum.","viz_anchor":null},
{"inputs":["[0,null,1]"],"expected":"[1,null,1]","explanation_md":"Edge case: tiny 2-node tree. Reverse inorder visits 1 first: acc = 0 + 1 = 1, node.val = 1. Then 0: acc = 1 + 0 = 1, node.val = 1. Result tree: root 1, right 1. Both nodes hold the same value because every node n MUST sum together with everything >= n, and the largest node has no greater values to add — so it keeps its own value. A bug starting acc = -1 or pre-adding the root would offset every node by a constant.","viz_anchor":null},
{"inputs":["[5,2,13]"],"expected":"[18,20,13]","explanation_md":"Algorithmically interesting: small canonical sample. Reverse inorder: 13, 5, 2. acc starts at 0. Visit 13: acc = 13, node = 13. Visit 5: acc = 18, node = 18. Visit 2: acc = 20, node = 20. Final tree: root 18, left 20, right 13. Verify: 2 was the smallest, so it sums with everything (2 + 5 + 13 = 20). 5 was middle (5 + 13 = 18). 13 was largest (13). Matches expected exactly.","viz_anchor":null}
]'::jsonb WHERE id = 'binary-search-tree-to-greater-sum-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[3,9,20,null,null,15,7]"],"expected":"[3.0,14.5,11.0]","explanation_md":"Canonical LC example. BFS level by level: each iteration of the outer loop processes one level, summing values and counting nodes. Level 0: [3] -> 3/1 = 3.0. Level 1: [9, 20] -> 29/2 = 14.5. Level 2: [15, 7] -> 22/2 = 11.0. Append each level average to the result. The queue holds the current level; we count size BEFORE iterating so newly enqueued children are not mixed in. O(n) time, O(width) space.","viz_anchor":null},
{"inputs":["[1]"],"expected":"[1.0]","explanation_md":"Edge case: single node. BFS queue starts with [1]. Level 0 size = 1. Sum = 1, average = 1.0. No children enqueued, queue empty, loop exits. Return [1.0]. The float conversion matters — integer division in Python 2 (or careless C++ int/int) would return 1 not 1.0. Always coerce to float before dividing.","viz_anchor":null},
{"inputs":["[3,9,20,15,7]"],"expected":"[3.0,14.5,11.0]","explanation_md":"Algorithmically interesting: same averages as the canonical case but with 9 having children. Level 0: [3] -> 3.0. Level 1: [9, 20] -> 14.5. Level 2: [15, 7] -> 11.0 (15 is child of 9, 7 is child of 20 — both at level 2). Identical output to the LC sample because the values per level are the same. The structure differs (9 has both children, 20 has none) but BFS averaging is structure-agnostic at the level granularity.","viz_anchor":null}
]'::jsonb WHERE id = 'average-of-levels-in-binary-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[4,1,3,null,null,2]","5"],"expected":"[5,4,null,1,3,null,null,2]","explanation_md":"Canonical LC example. Append val to the END of the original array, then rebuild the maximum tree. Trick: since val is APPENDED, it lies in the rightmost subtree of every ancestor. Walk down the right spine: if val > current.val, val becomes the new root, the old subtree becomes val.left. Otherwise descend to current.right and recurse. Here val=5 > root.val=4, so 5 becomes root, old tree [4,1,3,null,null,2] becomes 5.left. Result tree: 5 at root, left = the original tree, right = null.","viz_anchor":null},
{"inputs":["[5,2,4,null,1]","3"],"expected":"[5,2,4,null,1,null,3]","explanation_md":"Edge case: val slides INTO the right subtree. val=3 < root.val=5 -> descend to right child 4. 3 < 4 -> descend to 4.right (null). val replaces null. Result: insert 3 as 4.right. The tree structure: 5, left=2 (with right child 1), right=4 (with right child 3). The right-spine walk is the entire algorithm — no left subtree ever changes.","viz_anchor":null},
{"inputs":["[2,1,null,null,3]","4"],"expected":"[4,2,null,1,null,null,3]","explanation_md":"Algorithmically interesting: val becomes the new ROOT. val=4 > root.val=2 -> 4 is the new root, old tree [2,1,null,null,3] becomes 4.left. Result: 4 with left = the original tree. Note this loses the \"3\" sub-relationship visually but preserves the maximum-tree invariant: 4 is the max of the appended array, and the LEFT subtree must contain the maximum-tree of everything to its left in the array.","viz_anchor":null}
]'::jsonb WHERE id = 'maximum-binary-tree-ii' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[5,1,5,5,5,null,5]"],"expected":"4","explanation_md":"Canonical LC example. Post-order recursion that returns \"is this subtree univalue?\" while incrementing a counter. Trace bottom-up: leaves 5 (left-left), 5 (left-right), 5 (right-right) — three univalue subtrees so far, count=3. Subtree rooted at 1: children are 5 and 5 (both univalue) but 1 != 5 -> NOT univalue. Subtree rooted at right-5: child is 5, child univalue and root.val == child.val -> univalue, count=4. Root 5: left subtree not univalue -> root not univalue. Final count = 4.","viz_anchor":null},
{"inputs":["[1]"],"expected":"1","explanation_md":"Edge case: single leaf. Every leaf is trivially univalue (it equals itself). Recursion returns true, count incremented to 1. Return 1. The null subtree must also return true (vacuously univalue) so a leaf with two null children evaluates to true on both subcalls and counts itself.","viz_anchor":null},
{"inputs":["[5,5,5,5,5,null,5]"],"expected":"6","explanation_md":"Algorithmically interesting: all 5s. Three leaves at the bottom: count=3. Subtree rooted at left-5: both children are leaves with value 5, root = 5 -> univalue, count=4. Subtree rooted at right-5: one child leaf with value 5, univalue, count=5. Root subtree: both children univalue and root.val == both children -> univalue, count=6. Total 6. The order of \"is univalue\" check + count is what matters: a parent can only count as univalue if BOTH children are univalue AND match parent.val.","viz_anchor":null}
]'::jsonb WHERE id = 'count-univalue-subtrees' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[8,3,10,1,6,null,14,null,null,4,7,13]"],"expected":"7","explanation_md":"Canonical LC example. DFS carrying (min_ancestor, max_ancestor) along the CURRENT root-to-node path — never global extremes. At each node, candidate diff = max(|node.val - min|, |node.val - max|), update the global answer, then recurse with the extremes extended by node.val. Trace: root 8 -> extremes (8,8). Path 8->3: diff |3-8| = 5, extremes become (3,8). Path 8->3->1: diff = max(|1-3|, |1-8|) = 7 — the eventual answer. Path 8->3->6: extremes (3,8), diff = max(3,2) = 3. Path 8->10->14->13: extremes (8,14), diff = max(|13-8|, |13-14|) = 5. Global max = 7, from the ancestor pair (8, 1). Node 1 and node 14 sit in different subtrees, so they never compare — only min and max of each path matter, which is why two scalars replace the whole ancestor set.","viz_anchor":null},
{"inputs":["[1,null,2,null,0,3]"],"expected":"3","explanation_md":"Edge case: right-skewed chain. Path 1 -> 2 -> 0 -> 3. min and max along the path update: at 1: (1,1). At 2: (1,2). At 0: (0,2), candidate diff vs ancestors = max(|0-1|, |0-2|) = 2. At 3: ancestors are 1, 2, 0 -> min=0, max=2. Candidate diff = max(|3-0|, |3-2|) = 3. Update global to 3. Return 3.","viz_anchor":null},
{"inputs":["[2,null,0,1]"],"expected":"2","explanation_md":"Algorithmically interesting: only 3 nodes but max diff at the bottom. Path 2 -> 0 -> 1. At 0: diff vs ancestor 2 is 2. At 1: ancestors are 2, 0 -> min=0, max=2. Diff = max(|1-0|, |1-2|) = 1. Global max stays 2. Return 2. The key insight: we only need MIN and MAX of the ancestor set, not every individual ancestor — those two extremes give the maximum possible absolute difference.","viz_anchor":null}
]'::jsonb WHERE id = 'maximum-difference-between-node-and-ancestor' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["7","[[0,1],[0,2],[1,4],[1,5],[2,3],[2,6]]","[false,false,true,false,true,true,false]"],"expected":"8","explanation_md":"Canonical LC example. Build the undirected tree from edges, root at 0, DFS post-order. Rule: cost(u) = sum over children v of (cost(v) + 2) for every child whose subtree holds an apple (cost(v) > 0 or hasApple[v]); apple-free subtrees contribute 0. Apples sit at vertices 2, 4, 5. Trace bottom-up: cost(4) = 0 but hasApple[4] -> child 4 contributes 0+2 = 2 to node 1. cost(5) = 0, hasApple[5] -> contributes 2. cost(1) = 2 + 2 = 4. cost(3) = 0 and no apple -> contributes 0. cost(6) = 0, no apple -> 0. cost(2) = 0 from children, but hasApple[2] is true, so node 2 itself forces its edge. At root: child 1 contributes cost(1)+2 = 6; child 2 contributes cost(2)+2 = 2. cost(0) = 6 + 2 = 8. Return 8. Every kept edge is walked exactly twice (down and back), which is where the +2 per contributing child comes from.","viz_anchor":null},
{"inputs":["1","[]","[false]"],"expected":"0","explanation_md":"Edge case: single node, no apples. Tree is just root 0 with no children. DFS at 0: no children, no apples on root. Return 0. The boundary case where the start node itself has an apple still returns 0 — you do not pay edge cost to \"stay at the root\"; only edge traversals cost time.","viz_anchor":null},
{"inputs":["7","[[0,1],[0,2],[1,4],[1,5],[2,3],[2,6]]","[false,false,false,false,false,false,false]"],"expected":"0","explanation_md":"Algorithmically interesting: no apples at all. Every subtree returns cost = 0 because no descendant has an apple, so no edge is ever traversed. Root cost = 0. Return 0. This case tests the \"skip subtrees without apples\" pruning — a buggy implementation that always added 2 per edge would return 12 (6 edges * 2). The check `if cost(v) > 0 or hasApple[v]` is exactly what prunes apple-free branches.","viz_anchor":null}
]'::jsonb WHERE id = 'minimum-time-to-collect-all-apples-in-a-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[3,9,20,null,null,15,7]"],"expected":"[[9],[3,15],[20],[7]]","explanation_md":"Canonical LC example. Assign (col, row) coords: root at (0,0), left child = (col-1, row+1), right = (col+1, row+1). Group by col, within each col sort by row then by value. Coords: 3=(0,0), 9=(-1,1), 20=(1,1), 15=(0,2), 7=(2,2). Columns -1: [9]. Column 0: [3 at row 0, 15 at row 2] -> [3,15]. Column 1: [20]. Column 2: [7]. Sort columns ascending: [[9],[3,15],[20],[7]]. The within-col tie-break by value matters when two nodes share both col AND row.","viz_anchor":null},
{"inputs":["[1]"],"expected":"[[1]]","explanation_md":"Edge case: single node. Only coord is (0,0). One column with one value. Return [[1]]. The output is always a list-of-lists, never a flat list — wrap even single-element results.","viz_anchor":null},
{"inputs":["[1,2,3,4,6,5,7]"],"expected":"[[4],[2],[1,5,6],[3],[7]]","explanation_md":"Algorithmically interesting: TIE on both col AND row. Coords: 1=(0,0), 2=(-1,1), 3=(1,1), 4=(-2,2), 6=(0,2), 5=(0,2), 7=(2,2). Note 5 and 6 are BOTH at col 0 row 2 — same coord. Tie-break by VALUE ascending -> [5,6]. Column 0 contains: 1 at row 0, then [5,6] at row 2 -> [1,5,6]. The strict ordering (row, value) on ties is what makes this problem harder than standard vertical traversal — without value tiebreak the output is non-deterministic.","viz_anchor":null}
]'::jsonb WHERE id = 'vertical-order-traversal-of-a-binary-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[1,null,2,3,4]"],"expected":"[1,3,4,2]","explanation_md":"Canonical LC example. Boundary = root + left-boundary (top-down, exclude leaves) + leaves left-to-right + right-boundary (bottom-up, exclude leaves). Tree: 1 with right child 2 (which has children 3 and 4). Root = 1. Left boundary: walk left from root — root has no left child, so left boundary is empty. Leaves: 3, 4 (in-order DFS finds these). Right boundary: walk right from root — 1 -> 2, 2 has children (not a leaf), so add 2; 2 has no further right path that is non-leaf. Reversed right boundary = [2]. Concat: [1] + [] + [3, 4] + [2] = [1, 3, 4, 2].","viz_anchor":null},
{"inputs":["[1]"],"expected":"[1]","explanation_md":"Edge case: single node. Root IS the entire boundary. Skip left/right boundary descents (no children). Leaves include only root, but the standard algorithm avoids double-counting root: return just [root]. A bug that always ran the leaf-collector pass would add root again, returning [1,1].","viz_anchor":null},
{"inputs":["[1,2,3,4,5,6,null,null,null,7,8,9,10]"],"expected":"[1,2,4,7,8,9,10,6,3]","explanation_md":"Algorithmically interesting: full balanced-ish tree. Root = 1. Left boundary top-down (exclude leaves): 1 -> 2 -> 4 -> 7 — but 7 is a leaf, stop before. So left boundary = [2, 4]. Leaves DFS LTR: 7, 8, 9, 10, 6. Right boundary top-down (exclude leaves): 1 -> 3 -> 6 (leaf stop). So right boundary = [3]. Reversed = [3]. Concat: [1] + [2, 4] + [7, 8, 9, 10, 6] + [3] = [1,2,4,7,8,9,10,6,3]. The three separate DFS passes (left, leaves, right) make the algorithm O(n) total.","viz_anchor":null}
]'::jsonb WHERE id = 'boundary-of-binary-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[1,2,3,4,5]"],"expected":"[[4,5,3],[2],[1]]","explanation_md":"Canonical LC example. Each node has a \"level from bottom\" = 1 + max(level(left), level(right)), with leaves at level 0. Group nodes by this level. Tree: 1 has children 2, 3. 2 has children 4, 5. Leaves 4, 5, 3 are all level 0 -> group 0 = [4,5,3]. Node 2 has children at level 0 -> level 1 -> group 1 = [2]. Node 3 was a leaf already collected. Node 1 has children at levels 1 (via 2) and 0 (via 3) -> level 2 -> group 2 = [1]. Return [[4,5,3], [2], [1]]. Simulates iteratively stripping leaves but does it in ONE post-order pass.","viz_anchor":null},
{"inputs":["[1]"],"expected":"[[1]]","explanation_md":"Edge case: single node. Root IS a leaf at level 0. Group 0 = [1]. Return [[1]]. The post-order computes level(root) = 1 + max(-1, -1) = 0 if we treat null subtrees as level -1; or simply return 0 when both children are null and otherwise 1 + max(child levels).","viz_anchor":null},
{"inputs":["[1,2,3,4,5,6,null,null,null,7,8]"],"expected":"[[7,8,6,3],[5,4],[2],[1]]","explanation_md":"Algorithmically interesting: unbalanced tree forces non-trivial level computation. Leaves at level 0: 7, 8, 6, 3 -> group 0. Node 4 has child 7 at level 0 -> level 1. Node 5 has child 8 at level 0 -> level 1. Group 1 = [4, 5] (or [5,4] depending on traversal order). Node 2 has children 4 (lvl 1) and 5 (lvl 1) -> level 2. Group 2 = [2]. Node 1 has children 2 (lvl 2) and 3 (lvl 0) -> level 3. Group 3 = [1]. Order within a group is DFS-visit order; the expected uses [5,4] meaning right-first DFS.","viz_anchor":null}
]'::jsonb WHERE id = 'find-leaves-of-binary-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[1,null,3,2,4,null,5,6]"],"expected":"3","explanation_md":"Canonical LC example. N-ary tree DFS: depth(node) = 1 if leaf, else 1 + max(depth(child) for child in node.children). Root 1 has children [3, 2, 4]. depth(3): children [5, 6] (both leaves) -> 1 + max(1, 1) = 2. depth(2): leaf -> 1. depth(4): leaf -> 1. depth(1) = 1 + max(2, 1, 1) = 3. Return 3. Works for arbitrary branching factor; binary-tree variant is just children=[left, right].","viz_anchor":null},
{"inputs":["[]"],"expected":"0","explanation_md":"Edge case: empty tree. Depth convention: empty tree = 0. Root is null -> return 0. The single-node case (just [1]) returns 1, not 0 — the convention is that a leaf has depth 1 (counting nodes on the path), and depth(null) = 0.","viz_anchor":null},
{"inputs":["[1,null,2,3,4,5,null,null,6,7,null,8,null,9,10,null,null,11,null,12,null,13,null,null,14]"],"expected":"5","explanation_md":"Algorithmically interesting: deep skewed n-ary tree. The deepest path threads down via 1 -> child -> ... -> 14. Counting levels: 1 (level 1) -> children at level 2 -> grandchildren at level 3 -> level 4 -> 14 at level 5. The DFS bottoms out at every leaf, and the max() over children at each level propagates the deepest count up. O(n) since each node is visited exactly once. Return 5.","viz_anchor":null}
]'::jsonb WHERE id = 'maximum-depth-of-n-ary-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[1,null,3,2,4,null,5,6]"],"expected":"3","explanation_md":"Canonical LC example. Diameter = longest path between any two leaves (counted in EDGES). At each node, depth(node) = 1 + max(depth(child)). The candidate diameter THROUGH this node = sum of top-2 child depths (or top-1 if only one child). Trace: depth(3) = 1 + max(depth(5)=1, depth(6)=1) = 2. Through 3, top-2 depths are (1,1), diameter candidate = 1+1 = 2. Depth(2)=1, depth(4)=1. Through root 1, depths of children [3,2,4] are [2,1,1]. Top-2 = (2,1), candidate = 2+1 = 3. Max over all nodes = 3. Return 3.","viz_anchor":null},
{"inputs":["[1]"],"expected":"0","explanation_md":"Edge case: single node. No edges, no path. Return 0. The depth is 1 but the diameter (in edges) is 0. A bug that returned depth instead of diameter would wrongly answer 1.","viz_anchor":null},
{"inputs":["[1,null,2,3,4,5,null,null,6,7,null,8,null,9,10,null,null,11,null,12,null,13,null,null,14]"],"expected":"8","explanation_md":"Algorithmically interesting: deep tree forces diameter to span via the root. The deepest two branches from root 1 have depths 5 and 3 (or 4 and 4 depending on layout). Diameter = sum - 2 = 4 + 4 = 8 (path is 8 edges). The \"via root\" path beats any subtree-internal path because the root has children leading to two deep leaves. The top-2 trick at each node finds the optimum: for each node, take the deepest plus second-deepest child path lengths.","viz_anchor":null}
]'::jsonb WHERE id = 'diameter-of-n-ary-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[1,null,3,2,4,null,5,6]"],"expected":"[[1],[3,2,4],[5,6]]","explanation_md":"Canonical LC example. BFS with level batching: process current level fully before descending. Level 0 queue = [1], output [[1]]. Enqueue 1.children = [3,2,4]. Level 1: pop all three, output [[1],[3,2,4]]. Enqueue 3.children = [5,6], 2.children = [], 4.children = []. Level 2: pop 5, 6, output [[1],[3,2,4],[5,6]]. Queue empty. Return. Each level is one BFS \"batch\" — count children before iterating so the next-level enqueues are not mixed in.","viz_anchor":null},
{"inputs":["[]"],"expected":"[]","explanation_md":"Edge case: empty tree. Root is null, BFS never starts. Return empty list []. A bug that always created at least one level would return [[]].","viz_anchor":null},
{"inputs":["[1,null,2,3,4,5,null,null,6,7,null,8,null,9,10,null,null,11,null,12,null,13,null,null,14]"],"expected":"[[1],[2,3,4,5],[6,7,8,9,10],[11,12,13],[14]]","explanation_md":"Algorithmically interesting: 5 levels. BFS batches: L0=[1], L1=[2,3,4,5], L2=[6,7,8,9,10], L3=[11,12,13], L4=[14]. Each level pops queue.size() nodes, appending values to the current level list and enqueueing all children. Total nodes visited = 14, each once. Queue peak size = max level width = 5. The structure traversal pattern is identical for binary trees with children=[left,right].","viz_anchor":null}
]'::jsonb WHERE id = 'n-ary-tree-level-order-traversal' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[1,null,3,2,4,null,5,6]"],"expected":"[1,3,5,6,2,4]","explanation_md":"Canonical LC example. Preorder = visit node, then recurse children in order. Trace: visit 1 -> [1]. Recurse children [3,2,4]. Visit 3 -> [1,3]. Recurse 3.children [5,6]. Visit 5 -> [1,3,5]. Visit 6 -> [1,3,5,6]. Back to 1.children: visit 2 -> [1,3,5,6,2]. Visit 4 -> [1,3,5,6,2,4]. Iterative version uses a stack: push children in REVERSE order so leftmost pops first.","viz_anchor":null},
{"inputs":["[]"],"expected":"[]","explanation_md":"Edge case: empty tree. Root null, output []. The recursive base case must be the first line: if not root: return. Otherwise iterating root.children on a null root would crash.","viz_anchor":null},
{"inputs":["[1,null,2,3,4,5,null,null,6,7,null,8,null,9,10,null,null,11,null,12,null,13,null,null,14]"],"expected":"[1,2,3,6,7,11,14,8,12,9,10,13,4,5]","explanation_md":"Algorithmically interesting: deep n-ary tree preorder reveals DFS path. Output reflects DFS visit order: root 1 first, then dive into leftmost subtree (2), descend fully (3, then 6, then 7, then 11, then 14...), then backtrack to next branch. The stack-based iterative version pushes children in reverse so left children pop next, matching the recursive order exactly.","viz_anchor":null}
]'::jsonb WHERE id = 'n-ary-tree-preorder-traversal' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[1,null,3,2,4,null,5,6]"],"expected":"[5,6,3,2,4,1]","explanation_md":"Canonical LC example. Postorder = recurse children in order, then visit node. Trace: recurse 1.children [3,2,4]. Recurse 3.children [5,6]: 5 visited -> [5]; 6 visited -> [5,6]; then 3 -> [5,6,3]. Back to 1.children: 2 visited -> [5,6,3,2]; 4 visited -> [5,6,3,2,4]; then 1 -> [5,6,3,2,4,1]. The iterative trick: push node, push children in normal order, but reverse the final output (or use the \"modified preorder\" with children reversed then reverse the output).","viz_anchor":null},
{"inputs":["[]"],"expected":"[]","explanation_md":"Edge case: empty tree. Output []. Same null-guard as preorder. The empty list as base case is what lets nested calls cleanly aggregate via list extension.","viz_anchor":null},
{"inputs":["[1,null,2,3,4,5,null,null,6,7,null,8,null,9,10,null,null,11,null,12,null,13,null,null,14]"],"expected":"[2,6,14,11,8,12,7,9,10,3,13,4,5,1]","explanation_md":"Algorithmically interesting: deep tree postorder visits leaves first. Output ends in root 1 (last visited). Each subtree is fully consumed before its parent fires. Notice 14, 11, 8, 12 cluster — these are descendants of one subtree visited bottom-up. Root 1 appears LAST because postorder is the only traversal where root is final. This property is what makes postorder the right traversal for deletion (free children before parent) and for expression-tree evaluation.","viz_anchor":null}
]'::jsonb WHERE id = 'n-ary-tree-postorder-traversal' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[10,4,6]"],"expected":"true","explanation_md":"Canonical LC example. The simplest possible tree problem: a 3-node tree, return root.val == left.val + right.val. Here 10 == 4 + 6 -> true. No recursion, no traversal. The problem exists to teach the basic TreeNode access pattern. O(1) time, O(1) space.","viz_anchor":null},
{"inputs":["[5,3,1]"],"expected":"false","explanation_md":"Edge case: sum does not match. 5 != 3 + 1 = 4. Return false. The constraint guarantees the tree always has both children, so we never check for null. A defensive coder might still add the null check; harmless but unnecessary given the constraint.","viz_anchor":null},
{"inputs":["[0,0,0]"],"expected":"true","explanation_md":"Algorithmically interesting: all zeros. 0 == 0 + 0 -> true. The trivial all-zero case still satisfies the equality. A bug that treated 0 as \"no value\" or short-circuited on falsy could mis-handle this. Always use strict equality on numeric comparison.","viz_anchor":null}
]'::jsonb WHERE id = 'root-equals-sum-of-children' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[\"FindElements\",\"find\",\"find\"]","[[[-1,null,-1]],[1],[2]]"],"expected":"[null,false,true]","explanation_md":"Canonical LC example. Recovery rule: root = 0, left child of x = 2x+1, right child of x = 2x+2. DFS the contaminated tree, assigning correct values + adding to a hashset. Tree [-1, null, -1]: root has only right child. root = 0, right child = 2*0+2 = 2. Set = {0, 2}. Query find(1): 1 not in set -> false. Query find(2): 2 in set -> true. Output [null, false, true] (null for constructor return). O(1) lookup per query after O(n) build.","viz_anchor":null},
{"inputs":["[\"FindElements\",\"find\"]","[[[-1]],[0]]"],"expected":"[null,true]","explanation_md":"Edge case: single-node tree. Root contaminated as -1 becomes 0. Set = {0}. find(0): true. The constructor must assign root = 0 BEFORE any find query. Forgetting the assignment leaves set = {} and every find returns false.","viz_anchor":null},
{"inputs":["[\"FindElements\",\"find\",\"find\",\"find\",\"find\"]","[[[-1,-1,-1,-1,-1,-1]],[1],[3],[5],[7]]"],"expected":"[null,true,true,true,false]","explanation_md":"Algorithmically interesting: query exactly at the recovered boundary. Tree of 6 nodes, BFS-complete. Recover with root = 0, left = 2x+1, right = 2x+2: root=0, its children 1 and 2, node 1''s children 3 and 4, node 2''s left child 5. Set = {0,1,2,3,4,5}. Queries: find(1) -> true. find(3) -> true. find(5) -> true (the last recovered value). find(7) -> false — 7 WOULD be the left child of node 3 (2*3+1), but that node does not exist in the tree, so it was never recovered. The hashset is built once in O(n); each query is O(1) membership, never a tree walk.","viz_anchor":null}
]'::jsonb WHERE id = 'find-elements-in-a-contaminated-binary-tree' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);

UPDATE "PGcode_problems" SET explained_samples = '[
{"inputs":["[-1,2,0,2,0]"],"expected":"3","explanation_md":"Canonical LC example. Build children list from parents array. Tree rooted at 0 with parent[i] indicating i''s parent. For each node u, deleting it splits the tree into: each child-subtree + (n - subtree(u)) representing \"the rest\" (parent side). Score = product of all non-zero piece sizes. Trace n=5. children[2]=[0], children[0]=[1,3], children[1]=[], children[3]=[4], children[4]=[]. subtree sizes: 1=1, 4=1, 3=2, 0=4 (covers 0,1,3,4), 2=5. Score(0): children sizes (1, 2) and rest = 5 - 4 = 1 -> 1*2*1 = 2. Score(1): children sizes (), rest = 5-1=4 -> 4. Score(2): children (4), rest=0 (root removed) -> just 4. Score(3): children (1), rest=5-2=3 -> 1*3=3. Score(4): children (), rest=4 -> 4. Max = 4, count of nodes achieving 4 = 3 (nodes 1, 2, 4). Return 3.","viz_anchor":null},
{"inputs":["[-1,2,0]"],"expected":"2","explanation_md":"Edge case: tiny tree. n=3. children[2]=[0], children[0]=[1]. Sizes: 1=1, 0=2, 2=3. Score(0): child (1), rest = 3-2 = 1 -> 1*1 = 1. Score(1): no children, rest = 3-1 = 2 -> 2. Score(2): child (2 covers 0,1), rest = 0 -> just 2. Max score = 2, achieved by nodes 1 and 2 -> count = 2. Return 2. The rest-of-tree term (n - subtree_size) drops out when u is the root.","viz_anchor":null},
{"inputs":["[-1,0,0,0]"],"expected":"3","explanation_md":"Algorithmically interesting: star-shaped tree. Node 0 has children 1, 2, 3. Sizes: 1=2=3=1, 0=4. Score(0): children (1,1,1), rest = 0 -> 1*1*1 = 1. Score(1): no children, rest = 4-1 = 3 -> 3. Score(2): same as 1 -> 3. Score(3): same -> 3. Max = 3, achieved by 3 nodes -> count = 3. Return 3. The star case exposes the difference between removing the HUB (small score) vs. removing a SPOKE (large rest, score = n-1).","viz_anchor":null}
]'::jsonb WHERE id = 'count-nodes-with-the-highest-score' AND (explained_samples IS NULL OR jsonb_typeof(explained_samples) <> 'array' OR jsonb_array_length(explained_samples) < 3);
