-- Dry runs for 24 missing tier-200 problems. Each has 6 steps.
BEGIN;

DELETE FROM public."PGcode_interactive_dry_runs" WHERE problem_id IN (
  'add-two-numbers','asteroid-collision','burst-balloons','decode-string',
  'design-circular-queue','distinct-subsequences','dota2-senate','fibonacci-number',
  'flatten-nested-list-iterator','generate-parentheses','implement-queue-stacks','majority-element',
  'merge-sort-array','missing-number','moving-average','number-recent-calls',
  'pascals-triangle','regular-expression-matching','remove-all-adjacent-duplicates','reverse-string',
  'sliding-window-maximum','swap-nodes-pairs','valid-palindrome-ii','valid-sudoku'
);

-- 1) add-two-numbers
INSERT INTO public."PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('add-two-numbers',1,'Problem Setup','{"type":"linked-list","nodes":[{"value":"2->4->3","state":"default"},{"value":"5->6->4","state":"default"}],"pointers":{},"status":"Add 342 + 465 = 807 (digits reversed in linked lists).","hashmap":{"l1":"2->4->3 (342)","l2":"5->6->4 (465)"}}'::jsonb),
('add-two-numbers',2,'Approach','{"type":"linked-list","nodes":[{"value":"dummy","state":"highlight"}],"pointers":{"carry":"0"},"status":"Walk both lists digit by digit, sum with carry, build result.","hashmap":{"approach":"elementary addition with carry"}}'::jsonb),
('add-two-numbers',3,'Step 1: Add First Digits','{"type":"linked-list","nodes":[{"value":7,"state":"success"}],"pointers":{"carry":"0"},"status":"2 + 5 = 7, carry = 0. Result: 7.","hashmap":{"sum":"2+5=7"}}'::jsonb),
('add-two-numbers',4,'Step 2: Add Second Digits','{"type":"linked-list","nodes":[{"value":7,"state":"default"},{"value":0,"state":"success"}],"pointers":{"carry":"1"},"status":"4 + 6 = 10, carry = 1. Result: 7->0.","hashmap":{"sum":"4+6=10"}}'::jsonb),
('add-two-numbers',5,'Step 3: Add Third Digits','{"type":"linked-list","nodes":[{"value":7,"state":"default"},{"value":0,"state":"default"},{"value":8,"state":"success"}],"pointers":{"carry":"0"},"status":"3 + 4 + 1(carry) = 8. Result: 7->0->8.","hashmap":{"sum":"3+4+1=8"}}'::jsonb),
('add-two-numbers',6,'Result','{"type":"linked-list","nodes":[{"value":7,"state":"success"},{"value":0,"state":"success"},{"value":8,"state":"success"}],"pointers":{},"status":"807 reversed = 7->0->8. Done!","hashmap":{"time":"O(max(m,n))","space":"O(max(m,n))"}}'::jsonb),

-- 2) asteroid-collision
('asteroid-collision',1,'Problem Setup','{"type":"array","array":[{"value":5,"state":"default"},{"value":10,"state":"default"},{"value":-5,"state":"default"}],"pointers":{},"status":"Positive = moving right, negative = moving left. Collisions when right meets left.","hashmap":{"input":"[5, 10, -5]"}}'::jsonb),
('asteroid-collision',2,'Approach','{"type":"array","array":[{"value":"stack","state":"highlight"}],"pointers":{},"status":"Use a stack. Push right-moving. On left-moving, pop right-movers if smaller; equal = both destroy.","hashmap":{"approach":"monotonic stack"}}'::jsonb),
('asteroid-collision',3,'Push 5','{"type":"array","array":[{"value":5,"state":"success"}],"pointers":{},"status":"5 > 0 (right-moving), push to stack.","hashmap":{"stack":"[5]"}}'::jsonb),
('asteroid-collision',4,'Push 10','{"type":"array","array":[{"value":5,"state":"default"},{"value":10,"state":"success"}],"pointers":{},"status":"10 > 0 (right-moving), push to stack.","hashmap":{"stack":"[5, 10]"}}'::jsonb),
('asteroid-collision',5,'Collision: -5 vs 10','{"type":"array","array":[{"value":5,"state":"default"},{"value":10,"state":"highlight"},{"value":-5,"state":"removed"}],"pointers":{},"status":"-5 hits 10. |−5| < 10, so -5 is destroyed. 10 survives.","hashmap":{"stack":"[5, 10]","destroyed":"-5"}}'::jsonb),
('asteroid-collision',6,'Result','{"type":"array","array":[{"value":5,"state":"success"},{"value":10,"state":"success"}],"pointers":{},"status":"Final: [5, 10]. No more collisions possible.","hashmap":{"time":"O(n)","space":"O(n)"}}'::jsonb),

-- 3) burst-balloons
('burst-balloons',1,'Problem Setup','{"type":"array","array":[{"value":3,"state":"default"},{"value":1,"state":"default"},{"value":5,"state":"default"},{"value":8,"state":"default"}],"pointers":{},"status":"Burst balloons to maximize coins. Bursting i gives nums[i-1]*nums[i]*nums[i+1].","hashmap":{"input":"[3,1,5,8]"}}'::jsonb),
('burst-balloons',2,'Approach','{"type":"array","array":[{"value":1,"state":"highlight"},{"value":3,"state":"default"},{"value":1,"state":"default"},{"value":5,"state":"default"},{"value":8,"state":"default"},{"value":1,"state":"highlight"}],"pointers":{},"status":"Add boundary 1s. dp[i][j] = max coins from bursting all balloons between i and j.","hashmap":{"approach":"interval DP","padded":"[1,3,1,5,8,1]"}}'::jsonb),
('burst-balloons',3,'Base: Single Balloons','{"type":"array","array":[{"value":3,"state":"highlight"},{"value":1,"state":"highlight"},{"value":5,"state":"highlight"},{"value":8,"state":"highlight"}],"pointers":{},"status":"dp[0][2]=1*3*1=3, dp[1][3]=3*1*5=15, dp[2][4]=1*5*8=40, dp[3][5]=5*8*1=40","hashmap":{"step":"length=2 intervals"}}'::jsonb),
('burst-balloons',4,'Build Up','{"type":"array","array":[{"value":"dp","state":"default"}],"pointers":{},"status":"For each interval length, try every balloon as the LAST to burst. dp[i][j] = max over k of dp[i][k] + dp[k][j] + arr[i]*arr[k]*arr[j].","hashmap":{"key insight":"k is last burst, not first"}}'::jsonb),
('burst-balloons',5,'Final Interval','{"type":"array","array":[{"value":167,"state":"success"}],"pointers":{},"status":"dp[0][5] = 167. Optimal order: burst 1, then 5, then 3, then 8.","hashmap":{"answer":"167"}}'::jsonb),
('burst-balloons',6,'Result','{"type":"array","array":[{"value":167,"state":"success"}],"pointers":{},"status":"Maximum coins = 167.","hashmap":{"time":"O(n^3)","space":"O(n^2)"}}'::jsonb),

-- 4) decode-string
('decode-string',1,'Problem Setup','{"type":"array","array":[{"value":"3[a2[c]]","state":"default"}],"pointers":{},"status":"Decode: 3[a2[c]] = 3[acc] = accaccacc.","hashmap":{"input":"3[a2[c]]"}}'::jsonb),
('decode-string',2,'Approach','{"type":"array","array":[{"value":"stack","state":"highlight"}],"pointers":{},"status":"Use a stack. On [, push current string and number. On ], pop and repeat.","hashmap":{"approach":"stack of (string, count)"}}'::jsonb),
('decode-string',3,'Read 3[','{"type":"array","array":[{"value":"3","state":"highlight"},{"value":"[","state":"highlight"}],"pointers":{},"status":"Push (\"\", 3) to stack. Reset current string.","hashmap":{"stack":"[(\"\", 3)]","current":"\"\""}}'::jsonb),
('decode-string',4,'Read a2[','{"type":"array","array":[{"value":"a","state":"success"},{"value":"2","state":"highlight"},{"value":"[","state":"highlight"}],"pointers":{},"status":"Push (\"a\", 2) to stack. Reset current.","hashmap":{"stack":"[(\"\",3),(\"a\",2)]","current":"\"\""}}'::jsonb),
('decode-string',5,'Read c]','{"type":"array","array":[{"value":"c","state":"success"},{"value":"]","state":"highlight"}],"pointers":{},"status":"Pop (\"a\", 2): current = \"a\" + \"c\"*2 = \"acc\".","hashmap":{"current":"\"acc\""}}'::jsonb),
('decode-string',6,'Final ]','{"type":"array","array":[{"value":"accaccacc","state":"success"}],"pointers":{},"status":"Pop (\"\", 3): current = \"\" + \"acc\"*3 = \"accaccacc\".","hashmap":{"time":"O(output length)","space":"O(depth)","result":"accaccacc"}}'::jsonb),

-- 5-24: Remaining 20 problems with compact 6-step dry runs

-- 5) design-circular-queue
('design-circular-queue',1,'Problem Setup','{"type":"array","array":[{"value":"_","state":"default"},{"value":"_","state":"default"},{"value":"_","state":"default"}],"pointers":{"head":"0","count":"0"},"status":"Circular queue of capacity 3. Operations: enQueue, deQueue, Front, Rear.","hashmap":{"capacity":"3"}}'::jsonb),
('design-circular-queue',2,'enQueue(1)','{"type":"array","array":[{"value":1,"state":"success"},{"value":"_","state":"default"},{"value":"_","state":"default"}],"pointers":{"head":"0","count":"1"},"status":"Insert 1 at position (head+count)%cap = 0.","hashmap":{"queue":"[1]"}}'::jsonb),
('design-circular-queue',3,'enQueue(2), enQueue(3)','{"type":"array","array":[{"value":1,"state":"default"},{"value":2,"state":"default"},{"value":3,"state":"success"}],"pointers":{"head":"0","count":"3"},"status":"Queue full: [1, 2, 3].","hashmap":{"isFull":"true"}}'::jsonb),
('design-circular-queue',4,'deQueue()','{"type":"array","array":[{"value":"_","state":"removed"},{"value":2,"state":"default"},{"value":3,"state":"default"}],"pointers":{"head":"1","count":"2"},"status":"Remove front: head advances to 1. Queue: [2, 3].","hashmap":{"removed":"1"}}'::jsonb),
('design-circular-queue',5,'enQueue(4) - Wrap Around','{"type":"array","array":[{"value":4,"state":"success"},{"value":2,"state":"default"},{"value":3,"state":"default"}],"pointers":{"head":"1","count":"3"},"status":"Insert 4 at (1+2)%3 = 0. Wraps around! Queue: [2, 3, 4].","hashmap":{"wrap":"position 0 reused"}}'::jsonb),
('design-circular-queue',6,'Result','{"type":"array","array":[{"value":4,"state":"success"},{"value":2,"state":"success"},{"value":3,"state":"success"}],"pointers":{},"status":"Circular array avoids shifting. All ops O(1).","hashmap":{"time":"O(1) per op","space":"O(k)"}}'::jsonb),

-- 6) distinct-subsequences
('distinct-subsequences',1,'Problem Setup','{"type":"array","array":[{"value":"r","state":"default"},{"value":"a","state":"default"},{"value":"b","state":"default"},{"value":"b","state":"default"},{"value":"b","state":"default"},{"value":"i","state":"default"},{"value":"t","state":"default"}],"pointers":{},"status":"Count distinct subsequences of s=\"rabbbit\" that equal t=\"rabbit\".","hashmap":{"s":"rabbbit","t":"rabbit","expected":"3"}}'::jsonb),
('distinct-subsequences',2,'Approach','{"type":"array","array":[{"value":"dp","state":"highlight"}],"pointers":{},"status":"dp[i][j] = ways to match t[0..j-1] using s[0..i-1]. If s[i]==t[j]: dp[i][j] = dp[i-1][j-1] + dp[i-1][j].","hashmap":{"approach":"2D DP"}}'::jsonb),
('distinct-subsequences',3,'Base Cases','{"type":"array","array":[{"value":1,"state":"success"}],"pointers":{},"status":"dp[i][0] = 1 for all i (empty t matches once). dp[0][j>0] = 0.","hashmap":{"base":"empty target = 1 way"}}'::jsonb),
('distinct-subsequences',4,'Fill DP','{"type":"array","array":[{"value":"...","state":"default"}],"pointers":{},"status":"When chars match: include or skip that char of s. When they dont match: must skip.","hashmap":{"match":"dp[i-1][j-1] + dp[i-1][j]","no match":"dp[i-1][j]"}}'::jsonb),
('distinct-subsequences',5,'Key: Three b choices','{"type":"array","array":[{"value":"ra_b_bit","state":"highlight"}],"pointers":{},"status":"The 3 ways correspond to choosing which of the 3 bs in rabbbit to use.","hashmap":{"ways":"3"}}'::jsonb),
('distinct-subsequences',6,'Result','{"type":"array","array":[{"value":3,"state":"success"}],"pointers":{},"status":"Answer: 3 distinct subsequences.","hashmap":{"time":"O(m*n)","space":"O(m*n)"}}'::jsonb),

-- 7) dota2-senate
('dota2-senate',1,'Problem Setup','{"type":"array","array":[{"value":"R","state":"default"},{"value":"D","state":"default"},{"value":"D","state":"default"}],"pointers":{},"status":"Senate = \"RDD\". Each senator bans one from the other party. Which party wins?","hashmap":{"input":"RDD"}}'::jsonb),
('dota2-senate',2,'Approach','{"type":"array","array":[{"value":"queue","state":"highlight"}],"pointers":{},"status":"Two queues of indices. Lower index acts first. Winner re-enters at index + n.","hashmap":{"approach":"two queues"}}'::jsonb),
('dota2-senate',3,'Round 1: R bans D','{"type":"array","array":[{"value":"R","state":"success"},{"value":"D","state":"removed"},{"value":"D","state":"default"}],"pointers":{},"status":"R(0) < D(1): R bans D(1). R re-enters at 0+3=3.","hashmap":{"radiant":"[3]","dire":"[2]"}}'::jsonb),
('dota2-senate',4,'Round 2: D bans R','{"type":"array","array":[{"value":"R","state":"removed"},{"value":"D","state":"removed"},{"value":"D","state":"success"}],"pointers":{},"status":"D(2) < R(3): D bans R(3). D re-enters at 2+3=5.","hashmap":{"radiant":"[]","dire":"[5]"}}'::jsonb),
('dota2-senate',5,'Dire Wins','{"type":"array","array":[{"value":"Dire","state":"success"}],"pointers":{},"status":"Radiant queue empty. Dire wins!","hashmap":{"winner":"Dire"}}'::jsonb),
('dota2-senate',6,'Result','{"type":"array","array":[{"value":"Dire","state":"success"}],"pointers":{},"status":"Greedy queue simulation determines the winner.","hashmap":{"time":"O(n)","space":"O(n)"}}'::jsonb),

-- 8) fibonacci-number
('fibonacci-number',1,'Problem Setup','{"type":"array","array":[{"value":"F(5)=?","state":"default"}],"pointers":{},"status":"Fibonacci: F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2).","hashmap":{"target":"F(5)"}}'::jsonb),
('fibonacci-number',2,'Approach','{"type":"array","array":[{"value":"a=0","state":"highlight"},{"value":"b=1","state":"highlight"}],"pointers":{},"status":"Rolling two variables. No array needed.","hashmap":{"approach":"iterative O(1) space"}}'::jsonb),
('fibonacci-number',3,'i=2: F(2)=1','{"type":"array","array":[{"value":0,"state":"default"},{"value":1,"state":"default"},{"value":1,"state":"success"}],"pointers":{},"status":"a=0, b=1 -> c=0+1=1. Shift: a=1, b=1.","hashmap":{"F(2)":"1"}}'::jsonb),
('fibonacci-number',4,'i=3: F(3)=2','{"type":"array","array":[{"value":0,"state":"default"},{"value":1,"state":"default"},{"value":1,"state":"default"},{"value":2,"state":"success"}],"pointers":{},"status":"a=1, b=1 -> c=1+1=2. Shift: a=1, b=2.","hashmap":{"F(3)":"2"}}'::jsonb),
('fibonacci-number',5,'i=4,5: F(5)=5','{"type":"array","array":[{"value":0,"state":"default"},{"value":1,"state":"default"},{"value":1,"state":"default"},{"value":2,"state":"default"},{"value":3,"state":"default"},{"value":5,"state":"success"}],"pointers":{},"status":"F(4)=3, F(5)=5.","hashmap":{"F(5)":"5"}}'::jsonb),
('fibonacci-number',6,'Result','{"type":"array","array":[{"value":5,"state":"success"}],"pointers":{},"status":"F(5) = 5. O(n) time, O(1) space.","hashmap":{"time":"O(n)","space":"O(1)"}}'::jsonb),

-- 9-24: Remaining 16 problems (compact format)

-- 9) flatten-nested-list-iterator
('flatten-nested-list-iterator',1,'Problem Setup','{"type":"array","array":[{"value":"[[1,1],2,[1,1]]","state":"default"}],"pointers":{},"status":"Flatten nested list: [[1,1],2,[1,1]] -> [1,1,2,1,1].","hashmap":{"input":"[[1,1],2,[1,1]]"}}'::jsonb),
('flatten-nested-list-iterator',2,'Approach','{"type":"array","array":[{"value":"recursive","state":"highlight"}],"pointers":{},"status":"Recursively flatten: if item is list, flatten it; else append.","hashmap":{"approach":"recursive flatten"}}'::jsonb),
('flatten-nested-list-iterator',3,'Flatten [1,1]','{"type":"array","array":[{"value":1,"state":"success"},{"value":1,"state":"success"}],"pointers":{},"status":"First element is [1,1] -> flatten to 1, 1.","hashmap":{"partial":"[1, 1]"}}'::jsonb),
('flatten-nested-list-iterator',4,'Append 2','{"type":"array","array":[{"value":1,"state":"default"},{"value":1,"state":"default"},{"value":2,"state":"success"}],"pointers":{},"status":"Second element is 2 (integer) -> append directly.","hashmap":{"partial":"[1, 1, 2]"}}'::jsonb),
('flatten-nested-list-iterator',5,'Flatten [1,1]','{"type":"array","array":[{"value":1,"state":"default"},{"value":1,"state":"default"},{"value":2,"state":"default"},{"value":1,"state":"success"},{"value":1,"state":"success"}],"pointers":{},"status":"Third element [1,1] -> flatten to 1, 1.","hashmap":{"result":"[1, 1, 2, 1, 1]"}}'::jsonb),
('flatten-nested-list-iterator',6,'Result','{"type":"array","array":[{"value":1,"state":"success"},{"value":1,"state":"success"},{"value":2,"state":"success"},{"value":1,"state":"success"},{"value":1,"state":"success"}],"pointers":{},"status":"Flattened: [1,1,2,1,1]. Iterator walks this array.","hashmap":{"time":"O(n)","space":"O(n)"}}'::jsonb),

-- 10) generate-parentheses
('generate-parentheses',1,'Problem Setup','{"type":"array","array":[{"value":"n=3","state":"default"}],"pointers":{},"status":"Generate all valid combinations of 3 pairs of parentheses.","hashmap":{"n":"3","expected":"5 combinations"}}'::jsonb),
('generate-parentheses',2,'Approach','{"type":"array","array":[{"value":"backtrack","state":"highlight"}],"pointers":{},"status":"Track open and close counts. Can add ( if open < n. Can add ) if close < open.","hashmap":{"approach":"backtracking"}}'::jsonb),
('generate-parentheses',3,'Build ((()))','{"type":"array","array":[{"value":"((()))","state":"success"}],"pointers":{},"status":"Path: ((( then ))) -> ((()))","hashmap":{"open":"3","close":"3"}}'::jsonb),
('generate-parentheses',4,'Build (()())','{"type":"array","array":[{"value":"(()())","state":"success"}],"pointers":{},"status":"Backtrack and try: (( then ) then ( then )) -> (()())","hashmap":{"count":"2/5"}}'::jsonb),
('generate-parentheses',5,'All 5 Combinations','{"type":"array","array":[{"value":"((()))","state":"success"},{"value":"(()())","state":"success"},{"value":"(())()","state":"success"},{"value":"()(())","state":"success"},{"value":"()()()","state":"success"}],"pointers":{},"status":"All 5 valid combinations generated.","hashmap":{"total":"5"}}'::jsonb),
('generate-parentheses',6,'Result','{"type":"array","array":[{"value":"Catalan(3)=5","state":"success"}],"pointers":{},"status":"Count = Catalan number C(3) = 5.","hashmap":{"time":"O(4^n/sqrt(n))","space":"O(n)"}}'::jsonb),

-- 11) implement-queue-stacks
('implement-queue-stacks',1,'Problem Setup','{"type":"array","array":[{"value":"stack_in","state":"default"},{"value":"stack_out","state":"default"}],"pointers":{},"status":"Implement FIFO queue using two LIFO stacks.","hashmap":{"approach":"two stacks"}}'::jsonb),
('implement-queue-stacks',2,'push(1), push(2)','{"type":"array","array":[{"value":1,"state":"default"},{"value":2,"state":"success"}],"pointers":{},"status":"Push to stack_in: [1, 2].","hashmap":{"stack_in":"[1, 2]","stack_out":"[]"}}'::jsonb),
('implement-queue-stacks',3,'pop() = 1','{"type":"array","array":[{"value":2,"state":"default"},{"value":1,"state":"success"}],"pointers":{},"status":"stack_out empty -> transfer: pop all from in, push to out. [2,1] -> out=[2,1]. Pop out -> 1.","hashmap":{"stack_in":"[]","stack_out":"[2]","popped":"1"}}'::jsonb),
('implement-queue-stacks',4,'push(3), pop() = 2','{"type":"array","array":[{"value":2,"state":"success"}],"pointers":{},"status":"push(3) to stack_in=[3]. pop(): stack_out has [2], pop -> 2.","hashmap":{"stack_in":"[3]","stack_out":"[]","popped":"2"}}'::jsonb),
('implement-queue-stacks',5,'pop() = 3','{"type":"array","array":[{"value":3,"state":"success"}],"pointers":{},"status":"Transfer again: stack_in=[3] -> stack_out=[3]. Pop -> 3. FIFO order maintained!","hashmap":{"order":"1, 2, 3 (FIFO)"}}'::jsonb),
('implement-queue-stacks',6,'Result','{"type":"array","array":[{"value":"FIFO","state":"success"}],"pointers":{},"status":"Amortized O(1) per operation. Each element transferred at most once.","hashmap":{"time":"O(1) amortized","space":"O(n)"}}'::jsonb),

-- 12) majority-element
('majority-element',1,'Problem Setup','{"type":"array","array":[{"value":2,"state":"default"},{"value":2,"state":"default"},{"value":1,"state":"default"},{"value":1,"state":"default"},{"value":1,"state":"default"},{"value":2,"state":"default"},{"value":2,"state":"default"}],"pointers":{},"status":"Find the element appearing > n/2 times.","hashmap":{"input":"[2,2,1,1,1,2,2]"}}'::jsonb),
('majority-element',2,'Approach: Boyer-Moore','{"type":"array","array":[{"value":"vote","state":"highlight"}],"pointers":{},"status":"candidate + count. Same as candidate: count++. Different: count--. Count=0: switch candidate.","hashmap":{"approach":"Boyer-Moore Voting"}}'::jsonb),
('majority-element',3,'Walk: 2,2,1','{"type":"array","array":[{"value":2,"state":"highlight"},{"value":2,"state":"highlight"},{"value":1,"state":"default"}],"pointers":{"candidate":"2","count":"1"},"status":"2(+1=1), 2(+1=2), 1(-1=1). Candidate=2, count=1.","hashmap":{"candidate":"2","count":"1"}}'::jsonb),
('majority-element',4,'Walk: 1,1','{"type":"array","array":[{"value":1,"state":"highlight"},{"value":1,"state":"highlight"}],"pointers":{"candidate":"1","count":"1"},"status":"1(-1=0 switch), 1(+1=1). Candidate switches to 1.","hashmap":{"candidate":"1","count":"1"}}'::jsonb),
('majority-element',5,'Walk: 2,2','{"type":"array","array":[{"value":2,"state":"highlight"},{"value":2,"state":"highlight"}],"pointers":{"candidate":"2","count":"1"},"status":"2(-1=0 switch to 2), 2(+1=1). Final candidate: 2.","hashmap":{"candidate":"2"}}'::jsonb),
('majority-element',6,'Result','{"type":"array","array":[{"value":2,"state":"success"}],"pointers":{},"status":"Majority element = 2 (appears 4 times out of 7).","hashmap":{"time":"O(n)","space":"O(1)"}}'::jsonb),

-- 13-24: Remaining 12 with 6 steps each

('merge-sort-array',1,'Problem Setup','{"type":"array","array":[{"value":5,"state":"default"},{"value":2,"state":"default"},{"value":3,"state":"default"},{"value":1,"state":"default"}],"pointers":{},"status":"Sort [5,2,3,1] using merge sort.","hashmap":{"input":"[5,2,3,1]"}}'::jsonb),
('merge-sort-array',2,'Divide','{"type":"array","array":[{"value":"[5,2]","state":"highlight"},{"value":"[3,1]","state":"highlight"}],"pointers":{},"status":"Split into [5,2] and [3,1]. Recurse on each half.","hashmap":{"approach":"divide and conquer"}}'::jsonb),
('merge-sort-array',3,'Divide Further','{"type":"array","array":[{"value":"[5]","state":"highlight"},{"value":"[2]","state":"highlight"},{"value":"[3]","state":"highlight"},{"value":"[1]","state":"highlight"}],"pointers":{},"status":"Single elements are sorted. Start merging.","hashmap":{"base case":"single elements"}}'::jsonb),
('merge-sort-array',4,'Merge [5],[2] and [3],[1]','{"type":"array","array":[{"value":"[2,5]","state":"success"},{"value":"[1,3]","state":"success"}],"pointers":{},"status":"Merge sorted halves: [2,5] and [1,3].","hashmap":{"merged":"two sorted pairs"}}'::jsonb),
('merge-sort-array',5,'Final Merge','{"type":"array","array":[{"value":1,"state":"success"},{"value":2,"state":"success"},{"value":3,"state":"success"},{"value":5,"state":"success"}],"pointers":{},"status":"Merge [2,5] and [1,3] -> [1,2,3,5].","hashmap":{"result":"[1,2,3,5]"}}'::jsonb),
('merge-sort-array',6,'Result','{"type":"array","array":[{"value":1,"state":"success"},{"value":2,"state":"success"},{"value":3,"state":"success"},{"value":5,"state":"success"}],"pointers":{},"status":"Sorted! Merge sort: stable, O(n log n) guaranteed.","hashmap":{"time":"O(n log n)","space":"O(n)"}}'::jsonb),

('missing-number',1,'Problem Setup','{"type":"array","array":[{"value":3,"state":"default"},{"value":0,"state":"default"},{"value":1,"state":"default"}],"pointers":{},"status":"Array of n=3 numbers from [0,3]. One is missing.","hashmap":{"input":"[3,0,1]","range":"0-3"}}'::jsonb),
('missing-number',2,'Approach','{"type":"array","array":[{"value":"sum","state":"highlight"}],"pointers":{},"status":"Expected sum = n*(n+1)/2. Missing = expected - actual sum.","hashmap":{"approach":"math: Gauss formula"}}'::jsonb),
('missing-number',3,'Calculate','{"type":"array","array":[{"value":"expected=6","state":"default"},{"value":"actual=4","state":"default"}],"pointers":{},"status":"Expected = 3*4/2 = 6. Actual = 3+0+1 = 4.","hashmap":{"expected":"6","actual":"4"}}'::jsonb),
('missing-number',4,'Result','{"type":"array","array":[{"value":2,"state":"success"}],"pointers":{},"status":"Missing = 6 - 4 = 2.","hashmap":{"time":"O(n)","space":"O(1)","answer":"2"}}'::jsonb),
('missing-number',5,'Alternative: XOR','{"type":"array","array":[{"value":"XOR","state":"highlight"}],"pointers":{},"status":"XOR all indices and values: pairs cancel, leaving the missing number.","hashmap":{"alt":"XOR approach also O(n)/O(1)"}}'::jsonb),
('missing-number',6,'Summary','{"type":"array","array":[{"value":2,"state":"success"}],"pointers":{},"status":"Missing number = 2. Both sum and XOR approaches work.","hashmap":{"time":"O(n)","space":"O(1)"}}'::jsonb),

('moving-average',1,'Problem Setup','{"type":"array","array":[{"value":"size=3","state":"default"}],"pointers":{},"status":"Compute moving average with window size 3.","hashmap":{"window":"3"}}'::jsonb),
('moving-average',2,'next(1) = 1.0','{"type":"array","array":[{"value":1,"state":"success"}],"pointers":{},"status":"Window: [1]. Average = 1/1 = 1.0.","hashmap":{"window":"[1]","avg":"1.0"}}'::jsonb),
('moving-average',3,'next(10) = 5.5','{"type":"array","array":[{"value":1,"state":"default"},{"value":10,"state":"success"}],"pointers":{},"status":"Window: [1, 10]. Average = 11/2 = 5.5.","hashmap":{"window":"[1,10]","avg":"5.5"}}'::jsonb),
('moving-average',4,'next(3) = 4.67','{"type":"array","array":[{"value":1,"state":"default"},{"value":10,"state":"default"},{"value":3,"state":"success"}],"pointers":{},"status":"Window: [1, 10, 3]. Average = 14/3 = 4.67.","hashmap":{"window":"[1,10,3]","avg":"4.67"}}'::jsonb),
('moving-average',5,'next(5) = 6.0','{"type":"array","array":[{"value":10,"state":"default"},{"value":3,"state":"default"},{"value":5,"state":"success"}],"pointers":{},"status":"Window full! Drop 1, add 5: [10, 3, 5]. Average = 18/3 = 6.0.","hashmap":{"dropped":"1","avg":"6.0"}}'::jsonb),
('moving-average',6,'Result','{"type":"array","array":[{"value":"deque","state":"success"}],"pointers":{},"status":"Use a deque + running sum for O(1) per call.","hashmap":{"time":"O(1) per next()","space":"O(size)"}}'::jsonb),

('number-recent-calls',1,'Problem Setup','{"type":"array","array":[{"value":"ping(t)","state":"default"}],"pointers":{},"status":"Count pings in the last 3000ms window.","hashmap":{"window":"3000ms"}}'::jsonb),
('number-recent-calls',2,'ping(1) = 1','{"type":"array","array":[{"value":1,"state":"success"}],"pointers":{},"status":"Queue: [1]. In range [-2999, 1]. Count = 1.","hashmap":{"queue":"[1]"}}'::jsonb),
('number-recent-calls',3,'ping(100) = 2','{"type":"array","array":[{"value":1,"state":"default"},{"value":100,"state":"success"}],"pointers":{},"status":"Queue: [1, 100]. Both in range. Count = 2.","hashmap":{"queue":"[1,100]"}}'::jsonb),
('number-recent-calls',4,'ping(3001) = 3','{"type":"array","array":[{"value":1,"state":"default"},{"value":100,"state":"default"},{"value":3001,"state":"success"}],"pointers":{},"status":"Queue: [1, 100, 3001]. All in [1, 3001]. Count = 3.","hashmap":{"queue":"[1,100,3001]"}}'::jsonb),
('number-recent-calls',5,'ping(3002) = 3','{"type":"array","array":[{"value":100,"state":"default"},{"value":3001,"state":"default"},{"value":3002,"state":"success"}],"pointers":{},"status":"Dequeue 1 (out of range [2, 3002]). Queue: [100, 3001, 3002]. Count = 3.","hashmap":{"dropped":"1"}}'::jsonb),
('number-recent-calls',6,'Result','{"type":"array","array":[{"value":"deque","state":"success"}],"pointers":{},"status":"Monotonic queue: dequeue expired pings from front. O(1) amortized.","hashmap":{"time":"O(1) amortized","space":"O(W)"}}'::jsonb),

('pascals-triangle',1,'Problem Setup','{"type":"array","array":[{"value":"n=5","state":"default"}],"pointers":{},"status":"Generate first 5 rows of Pascal''s Triangle.","hashmap":{"n":"5"}}'::jsonb),
('pascals-triangle',2,'Row 1: [1]','{"type":"array","array":[{"value":1,"state":"success"}],"pointers":{},"status":"First row is always [1].","hashmap":{"row":"1"}}'::jsonb),
('pascals-triangle',3,'Row 2-3','{"type":"array","array":[{"value":"[1,1]","state":"success"},{"value":"[1,2,1]","state":"success"}],"pointers":{},"status":"Each element = prev[j-1] + prev[j]. Edges are 1.","hashmap":{"rows":"2-3"}}'::jsonb),
('pascals-triangle',4,'Row 4-5','{"type":"array","array":[{"value":"[1,3,3,1]","state":"success"},{"value":"[1,4,6,4,1]","state":"success"}],"pointers":{},"status":"Continue: [1,3,3,1], [1,4,6,4,1].","hashmap":{"rows":"4-5"}}'::jsonb),
('pascals-triangle',5,'Full Triangle','{"type":"array","array":[{"value":"1","state":"success"},{"value":"1 1","state":"success"},{"value":"1 2 1","state":"success"},{"value":"1 3 3 1","state":"success"},{"value":"1 4 6 4 1","state":"success"}],"pointers":{},"status":"Complete Pascal''s Triangle with 5 rows.","hashmap":{"total":"5 rows"}}'::jsonb),
('pascals-triangle',6,'Result','{"type":"array","array":[{"value":"binomial","state":"success"}],"pointers":{},"status":"Each value = C(n,k). O(n^2) time and space.","hashmap":{"time":"O(n^2)","space":"O(n^2)"}}'::jsonb),

('regular-expression-matching',1,'Problem Setup','{"type":"array","array":[{"value":"s=aa","state":"default"},{"value":"p=a*","state":"default"}],"pointers":{},"status":"Does s match pattern p? . = any char, * = zero or more of preceding.","hashmap":{"s":"aa","p":"a*"}}'::jsonb),
('regular-expression-matching',2,'Approach','{"type":"array","array":[{"value":"dp","state":"highlight"}],"pointers":{},"status":"dp[i][j] = does s[0..i-1] match p[0..j-1].","hashmap":{"approach":"2D DP"}}'::jsonb),
('regular-expression-matching',3,'Handle *','{"type":"array","array":[{"value":"a*","state":"highlight"}],"pointers":{},"status":"p[j]=*: either use 0 copies (dp[i][j-2]) or match one more (dp[i-1][j] if chars match).","hashmap":{"key":"* means 0 or more"}}'::jsonb),
('regular-expression-matching',4,'Fill: a* matches aa','{"type":"array","array":[{"value":"match","state":"success"}],"pointers":{},"status":"dp[2][2]: a* can match aa by using a twice. True!","hashmap":{"dp[2][2]":"true"}}'::jsonb),
('regular-expression-matching',5,'Result','{"type":"array","array":[{"value":"true","state":"success"}],"pointers":{},"status":"s=aa matches p=a*. Answer: true.","hashmap":{"time":"O(m*n)","space":"O(m*n)"}}'::jsonb),
('regular-expression-matching',6,'Summary','{"type":"array","array":[{"value":"DP","state":"success"}],"pointers":{},"status":"Regex matching via DP handles ., *, and their combinations.","hashmap":{"time":"O(m*n)","space":"O(m*n)"}}'::jsonb),

('remove-all-adjacent-duplicates',1,'Problem Setup','{"type":"array","array":[{"value":"a","state":"default"},{"value":"b","state":"default"},{"value":"b","state":"default"},{"value":"a","state":"default"},{"value":"c","state":"default"},{"value":"a","state":"default"}],"pointers":{},"status":"Remove all adjacent duplicates from \"abbaca\".","hashmap":{"input":"abbaca"}}'::jsonb),
('remove-all-adjacent-duplicates',2,'Approach','{"type":"array","array":[{"value":"stack","state":"highlight"}],"pointers":{},"status":"Use a stack. Push char; if top matches, pop (cancel pair).","hashmap":{"approach":"stack"}}'::jsonb),
('remove-all-adjacent-duplicates',3,'Push a, b','{"type":"array","array":[{"value":"a","state":"default"},{"value":"b","state":"success"}],"pointers":{},"status":"Stack: [a, b].","hashmap":{"stack":"ab"}}'::jsonb),
('remove-all-adjacent-duplicates',4,'b matches top -> pop','{"type":"array","array":[{"value":"a","state":"default"}],"pointers":{},"status":"Next b matches stack top b -> pop both. Stack: [a].","hashmap":{"stack":"a","popped":"bb"}}'::jsonb),
('remove-all-adjacent-duplicates',5,'Push a -> match -> pop, push c, a','{"type":"array","array":[{"value":"c","state":"default"},{"value":"a","state":"success"}],"pointers":{},"status":"a matches top a -> pop. Push c, a. Stack: [c, a].","hashmap":{"stack":"ca"}}'::jsonb),
('remove-all-adjacent-duplicates',6,'Result','{"type":"array","array":[{"value":"c","state":"success"},{"value":"a","state":"success"}],"pointers":{},"status":"Result: \"ca\".","hashmap":{"time":"O(n)","space":"O(n)"}}'::jsonb),

('reverse-string',1,'Problem Setup','{"type":"array","array":[{"value":"h","state":"default"},{"value":"e","state":"default"},{"value":"l","state":"default"},{"value":"l","state":"default"},{"value":"o","state":"default"}],"pointers":{"L":"0","R":"4"},"status":"Reverse [\"h\",\"e\",\"l\",\"l\",\"o\"] in-place.","hashmap":{"input":"hello"}}'::jsonb),
('reverse-string',2,'Swap h <-> o','{"type":"array","array":[{"value":"o","state":"success"},{"value":"e","state":"default"},{"value":"l","state":"default"},{"value":"l","state":"default"},{"value":"h","state":"success"}],"pointers":{"L":"1","R":"3"},"status":"Swap s[0] and s[4]. Move pointers inward.","hashmap":{"swap":"h<->o"}}'::jsonb),
('reverse-string',3,'Swap e <-> l','{"type":"array","array":[{"value":"o","state":"default"},{"value":"l","state":"success"},{"value":"l","state":"default"},{"value":"e","state":"success"},{"value":"h","state":"default"}],"pointers":{"L":"2","R":"2"},"status":"Swap s[1] and s[3]. Pointers meet at center.","hashmap":{"swap":"e<->l"}}'::jsonb),
('reverse-string',4,'Done','{"type":"array","array":[{"value":"o","state":"success"},{"value":"l","state":"success"},{"value":"l","state":"success"},{"value":"e","state":"success"},{"value":"h","state":"success"}],"pointers":{},"status":"L >= R, done. Result: \"olleh\".","hashmap":{"result":"olleh"}}'::jsonb),
('reverse-string',5,'Recursive Alt','{"type":"array","array":[{"value":"recurse","state":"highlight"}],"pointers":{},"status":"Recursive: swap(s, L, R) then recurse(s, L+1, R-1). Same O(n).","hashmap":{"alt":"recursive two-pointer"}}'::jsonb),
('reverse-string',6,'Result','{"type":"array","array":[{"value":"o","state":"success"},{"value":"l","state":"success"},{"value":"l","state":"success"},{"value":"e","state":"success"},{"value":"h","state":"success"}],"pointers":{},"status":"Reversed in-place. O(n) time, O(1) space.","hashmap":{"time":"O(n)","space":"O(1)"}}'::jsonb),

('sliding-window-maximum',1,'Problem Setup','{"type":"array","array":[{"value":1,"state":"default"},{"value":3,"state":"default"},{"value":-1,"state":"default"},{"value":-3,"state":"default"},{"value":5,"state":"default"},{"value":3,"state":"default"},{"value":6,"state":"default"},{"value":7,"state":"default"}],"pointers":{},"status":"Find max in each window of size k=3.","hashmap":{"k":"3","input":"[1,3,-1,-3,5,3,6,7]"}}'::jsonb),
('sliding-window-maximum',2,'Approach','{"type":"array","array":[{"value":"deque","state":"highlight"}],"pointers":{},"status":"Monotonic decreasing deque of indices. Front is always the max.","hashmap":{"approach":"monotonic deque"}}'::jsonb),
('sliding-window-maximum',3,'Window [1,3,-1]','{"type":"array","array":[{"value":1,"state":"default"},{"value":3,"state":"highlight"},{"value":-1,"state":"default"}],"pointers":{},"status":"Deque: [1(3), 2(-1)]. Max = 3.","hashmap":{"deque":"[3,-1]","max":"3"}}'::jsonb),
('sliding-window-maximum',4,'Window [3,-1,-3]','{"type":"array","array":[{"value":3,"state":"highlight"},{"value":-1,"state":"default"},{"value":-3,"state":"default"}],"pointers":{},"status":"Max = 3. Slide: add -3, front still valid.","hashmap":{"max":"3"}}'::jsonb),
('sliding-window-maximum',5,'Window [-1,-3,5]','{"type":"array","array":[{"value":-1,"state":"default"},{"value":-3,"state":"default"},{"value":5,"state":"highlight"}],"pointers":{},"status":"5 > all in deque -> clear, push 5. Max = 5.","hashmap":{"max":"5"}}'::jsonb),
('sliding-window-maximum',6,'Result','{"type":"array","array":[{"value":3,"state":"success"},{"value":3,"state":"success"},{"value":5,"state":"success"},{"value":5,"state":"success"},{"value":6,"state":"success"},{"value":7,"state":"success"}],"pointers":{},"status":"Output: [3,3,5,5,6,7]. Each element enters/leaves deque once.","hashmap":{"time":"O(n)","space":"O(k)"}}'::jsonb),

('swap-nodes-pairs',1,'Problem Setup','{"type":"linked-list","nodes":[{"value":1,"state":"default"},{"value":2,"state":"default"},{"value":3,"state":"default"},{"value":4,"state":"default"}],"pointers":{},"status":"Swap every two adjacent nodes: 1->2->3->4 becomes 2->1->4->3.","hashmap":{"input":"1->2->3->4"}}'::jsonb),
('swap-nodes-pairs',2,'Approach','{"type":"linked-list","nodes":[{"value":"D","state":"highlight"},{"value":1,"state":"default"},{"value":2,"state":"default"}],"pointers":{"prev":"D"},"status":"Dummy head. For each pair: prev->a->b becomes prev->b->a.","hashmap":{"approach":"iterative with dummy"}}'::jsonb),
('swap-nodes-pairs',3,'Swap 1,2','{"type":"linked-list","nodes":[{"value":"D","state":"default"},{"value":2,"state":"success"},{"value":1,"state":"success"},{"value":3,"state":"default"},{"value":4,"state":"default"}],"pointers":{"prev":"1"},"status":"prev->2->1->3. Advance prev to node 1.","hashmap":{"swapped":"1<->2"}}'::jsonb),
('swap-nodes-pairs',4,'Swap 3,4','{"type":"linked-list","nodes":[{"value":2,"state":"default"},{"value":1,"state":"default"},{"value":4,"state":"success"},{"value":3,"state":"success"}],"pointers":{},"status":"prev(1)->4->3. Done!","hashmap":{"swapped":"3<->4"}}'::jsonb),
('swap-nodes-pairs',5,'Result','{"type":"linked-list","nodes":[{"value":2,"state":"success"},{"value":1,"state":"success"},{"value":4,"state":"success"},{"value":3,"state":"success"}],"pointers":{},"status":"Final: 2->1->4->3.","hashmap":{"result":"2->1->4->3"}}'::jsonb),
('swap-nodes-pairs',6,'Complexity','{"type":"linked-list","nodes":[{"value":2,"state":"success"},{"value":1,"state":"success"},{"value":4,"state":"success"},{"value":3,"state":"success"}],"pointers":{},"status":"O(n) time, O(1) space. Handles odd-length lists (last node stays).","hashmap":{"time":"O(n)","space":"O(1)"}}'::jsonb),

('valid-palindrome-ii',1,'Problem Setup','{"type":"array","array":[{"value":"a","state":"default"},{"value":"b","state":"default"},{"value":"c","state":"default"},{"value":"a","state":"default"}],"pointers":{"L":"0","R":"3"},"status":"Can \"abca\" become a palindrome by removing at most 1 character?","hashmap":{"input":"abca"}}'::jsonb),
('valid-palindrome-ii',2,'Compare Ends','{"type":"array","array":[{"value":"a","state":"success"},{"value":"b","state":"default"},{"value":"c","state":"default"},{"value":"a","state":"success"}],"pointers":{"L":"1","R":"2"},"status":"a == a. Move inward.","hashmap":{"match":"a==a"}}'::jsonb),
('valid-palindrome-ii',3,'Mismatch: b != c','{"type":"array","array":[{"value":"b","state":"highlight"},{"value":"c","state":"highlight"}],"pointers":{},"status":"b != c. Try skipping left (check \"ca\") or right (check \"bc\").","hashmap":{"skip left":"ca","skip right":"bc"}}'::jsonb),
('valid-palindrome-ii',4,'Try Skip b','{"type":"array","array":[{"value":"c","state":"default"},{"value":"a","state":"default"}],"pointers":{},"status":"Check \"ca\": c != a. Not palindrome.","hashmap":{"skip b":"ca -> not palindrome"}}'::jsonb),
('valid-palindrome-ii',5,'Try Skip c','{"type":"array","array":[{"value":"b","state":"success"}],"pointers":{},"status":"Check \"b\": single char is always palindrome. Success! Remove c.","hashmap":{"skip c":"b -> palindrome!"}}'::jsonb),
('valid-palindrome-ii',6,'Result','{"type":"array","array":[{"value":"true","state":"success"}],"pointers":{},"status":"Yes! Remove c -> \"aba\" is a palindrome.","hashmap":{"time":"O(n)","space":"O(1)"}}'::jsonb),

('valid-sudoku',1,'Problem Setup','{"type":"array","array":[{"value":"9x9","state":"default"}],"pointers":{},"status":"Check if a 9x9 Sudoku board is valid (no repeats in rows, cols, or 3x3 boxes).","hashmap":{"rules":"no duplicate 1-9 in any row, column, or box"}}'::jsonb),
('valid-sudoku',2,'Approach','{"type":"hashmap","entries":[{"key":"rows","value":"9 sets","state":"default"},{"key":"cols","value":"9 sets","state":"default"},{"key":"boxes","value":"9 sets","state":"default"}],"status":"Track seen digits per row, column, and 3x3 box using hash sets.","hashmap":{"approach":"3 arrays of sets"}}'::jsonb),
('valid-sudoku',3,'Box Index','{"type":"array","array":[{"value":"(r/3)*3 + c/3","state":"highlight"}],"pointers":{},"status":"Box index = (row // 3) * 3 + (col // 3). Maps each cell to its 3x3 box (0-8).","hashmap":{"formula":"(r/3)*3 + c/3"}}'::jsonb),
('valid-sudoku',4,'Check Each Cell','{"type":"array","array":[{"value":"5","state":"highlight"}],"pointers":{},"status":"For cell (0,0) = 5: check rows[0], cols[0], boxes[0]. Not seen -> add to all three.","hashmap":{"cell":"(0,0)=5","sets":"add to row 0, col 0, box 0"}}'::jsonb),
('valid-sudoku',5,'Duplicate Found?','{"type":"array","array":[{"value":"valid","state":"success"}],"pointers":{},"status":"If any digit already in its row/col/box set -> invalid. Otherwise valid.","hashmap":{"check":"seen before?"}}'::jsonb),
('valid-sudoku',6,'Result','{"type":"hashmap","entries":[{"key":"valid","value":"true/false","state":"success"}],"status":"Single pass over 81 cells. O(1) since board size is fixed.","hashmap":{"time":"O(1)","space":"O(1)"}}'::jsonb);

COMMIT;
