-- ============================================================
-- Delete all placeholder problems generated by seed_200.js and
-- seed_500.sql. These have IDs like 'arrays-pattern-1' or are
-- marked with roadmap_set='500' and contain generic stub content.
--
-- Safe to re-run. Deletes children first, then parents.
-- ============================================================

-- 1) Clean any interactive content tied to placeholders
DELETE FROM public."PGcode_interactive_questions"
WHERE dry_run_step_id IN (
  SELECT id FROM public."PGcode_interactive_dry_runs"
  WHERE problem_id LIKE '%-pattern-%'
     OR problem_id IN (SELECT id FROM public."PGcode_problems" WHERE roadmap_set = '500')
);

DELETE FROM public."PGcode_interactive_dry_runs"
WHERE problem_id LIKE '%-pattern-%'
   OR problem_id IN (SELECT id FROM public."PGcode_problems" WHERE roadmap_set = '500');

-- 2) Clean starter code templates
DELETE FROM public."PGcode_problem_templates"
WHERE problem_id LIKE '%-pattern-%'
   OR problem_id IN (SELECT id FROM public."PGcode_problems" WHERE roadmap_set = '500');

-- 3) Delete the placeholder problem rows themselves
DELETE FROM public."PGcode_problems" WHERE id LIKE '%-pattern-%';
DELETE FROM public."PGcode_problems" WHERE roadmap_set = '500';

-- 4) Sanity check
SELECT topic_id, COUNT(*) AS problem_count
FROM public."PGcode_problems"
GROUP BY topic_id
ORDER BY topic_id;
