#!/usr/bin/env node
// Build WAVE 34Y: minimum-number-of-taps-to-open-to-water-a-garden + the-k-strongest-values-in-an-array
// Appends two RICH_CONTENT entries to src/content/problemContent.js using SAFE replace (function form).

import fs from "node:fs";
import path from "node:path";

const FILE = path.resolve("src/content/problemContent.js");

function makeLcg(seed) {
  let s = seed >>> 0;
  return function () {
    s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
    return s;
  };
}

// ============================================================
// PROBLEM 1: minimum-number-of-taps-to-open-to-water-a-garden (LC 1326)
//   minTaps(n: int, ranges: List[int]) -> int
//   Garden on x-axis from 0..n. Tap i is at position i and waters [i - ranges[i], i + ranges[i]].
//   Return the minimum number of taps to open to water the entire garden [0, n].
//   Return -1 if impossible.
//
//   Greedy "jump game" reduction:
//     1) Build maxReach[start] = largest end achievable from any interval that starts <= start
//     2) Sweep with three pointers: cur_end (current coverage end), far (farthest reachable in this
//        jump), taps (count). When i hits cur_end, we must jump: taps += 1, cur_end = far.
//     3) If at any point i > far, impossible -> -1.
// ============================================================
function buildProblem1() {
  const lcg = makeLcg(0xA10F358A);

  function ref(n, ranges) {
    // Build maxEnd[start] = max(i + ranges[i]) for any tap whose interval covers `start`
    // i.e. for each tap, set start = max(0, i - r), end = min(n, i + r);
    // maxEnd[start] = max(maxEnd[start], end)
    const maxEnd = new Array(n + 1).fill(0);
    for (let i = 0; i <= n; i++) {
      const r = ranges[i];
      const s = Math.max(0, i - r);
      const e = Math.min(n, i + r);
      if (e > maxEnd[s]) maxEnd[s] = e;
    }
    let taps = 0;
    let curEnd = 0;
    let far = 0;
    for (let i = 0; i <= n; i++) {
      if (i > far) return -1;
      if (i > curEnd) {
        taps++;
        curEnd = far;
        if (i > curEnd) return -1;
      }
      if (maxEnd[i] > far) far = maxEnd[i];
    }
    if (curEnd < n) {
      // Need one more jump to finish the garden
      if (far >= n) {
        taps++;
        curEnd = far;
      } else {
        return -1;
      }
    }
    return taps;
  }

  const cases = [];

  // Canonical LC samples
  cases.push([5, [3, 4, 1, 1, 0, 0]]); // -> 1
  cases.push([3, [0, 0, 0, 0]]); // -> -1
  cases.push([7, [1, 2, 1, 0, 2, 1, 0, 1]]); // -> 3
  cases.push([8, [4, 0, 0, 0, 0, 0, 0, 0, 4]]); // -> 2
  cases.push([8, [4, 0, 0, 0, 4, 0, 0, 0, 4]]); // -> 1

  // Tiny gardens
  cases.push([0, [0]]); // -> 0 (garden is just point 0; no taps needed if ranges[0]=0? Actually 0 covers itself.)
  cases.push([0, [5]]); // -> 0
  cases.push([1, [0, 0]]); // -> -1
  cases.push([1, [1, 0]]); // -> 1
  cases.push([1, [0, 1]]); // -> 1
  cases.push([1, [1, 1]]); // -> 1
  cases.push([2, [0, 0, 0]]); // -> -1
  cases.push([2, [1, 0, 1]]); // -> 2
  cases.push([2, [2, 0, 0]]); // -> 1
  cases.push([2, [0, 0, 2]]); // -> 1
  cases.push([2, [1, 1, 1]]); // -> 2

  // All same range
  cases.push([10, [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]); // -> 5
  cases.push([10, [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]); // -> 3 (intervals length 4 each)
  cases.push([10, [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]]); // -> 1

  // One mega tap at center
  cases.push([9, [0, 0, 0, 0, 4, 0, 0, 0, 0, 0]]); // tap 4 -> [0,8]; need someone for 9. -1
  cases.push([9, [0, 0, 0, 0, 5, 0, 0, 0, 0, 0]]); // -> 1
  cases.push([6, [0, 0, 0, 3, 0, 0, 0]]); // -> 1
  cases.push([7, [0, 0, 0, 3, 0, 0, 0, 0]]); // tap 3 -> [0,6]; need 7. -1

  // Gap somewhere
  cases.push([6, [1, 0, 1, 0, 1, 0, 1]]); // -> -1 (gap between 1..2 -> no, tap 0 covers [0,1], tap 2 covers [1,3], tap 4 covers [3,5], tap 6 covers [5,6] wait but 5..6 connect. let ref decide)
  cases.push([4, [0, 5, 0, 3, 4]]); // multiple options
  cases.push([5, [3, 4, 1, 1, 0, 0]]); // already there but include with edit -> 1

  // Larger crafted
  cases.push([20, [3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3]]); // -> 4
  cases.push([20, [0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0]]); // -> 2
  cases.push([20, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]); // -> 1

  // Pure greedy stress
  cases.push([15, [1, 2, 3, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1]]); // varied
  cases.push([12, [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2]]); // -> 3
  cases.push([12, [3, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 3]]); // -> 3
  cases.push([12, [4, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 4]]); // -> 2

  // Generated by LCG (deterministic)
  while (cases.length < 30) {
    const n = 1 + (lcg() % 18);
    const ranges = new Array(n + 1);
    for (let i = 0; i <= n; i++) {
      ranges[i] = lcg() % 6;
    }
    cases.push([n, ranges]);
  }

  const test_cases = cases.map(([n, ranges]) => ({
    inputs: [String(n), JSON.stringify(ranges)],
    expected: String(ref(n, ranges))
  }));

  return {
    slug: "minimum-number-of-taps-to-open-to-water-a-garden",
    obj: {
      description: "There is a one-dimensional garden on the x-axis. The garden starts at the point `0` and ends at the point `n`. (i.e., the length of the garden is `n`.)\n\nThere are `n + 1` taps located at points `[0, 1, ..., n]` in the garden.\n\nGiven an integer `n` and an integer array `ranges` of length `n + 1` where `ranges[i]` (`0 <= i <= n`) means the `i`-th tap can water the area `[i - ranges[i], i + ranges[i]]` if it was open.\n\nReturn the **minimum number of taps** that should be open to water the whole garden. If the garden cannot be watered, return `-1`.\n\n**Example 1**\n\n```\nInput:  n = 5, ranges = [3, 4, 1, 1, 0, 0]\nOutput: 1\nExplanation: tap 1 (at point 1) waters [1-4, 1+4] = [-3, 5], which covers [0, 5].\n```\n\n**Example 2**\n\n```\nInput:  n = 3, ranges = [0, 0, 0, 0]\nOutput: -1\nExplanation: every tap waters only its own point, so [0, 3] cannot be covered.\n```\n\nThis is **LeetCode 1326**. The canonical solution **reduces the problem to Jump Game II**: for every tap, compute the interval `[max(0, i - r), min(n, i + r)]`, then keep `maxEnd[s] = max end across taps whose left endpoint is exactly s`. Walk the line with a greedy sweep that tracks `curEnd` (current coverage) and `far` (farthest reachable in this jump). Every time the index passes `curEnd`, commit a new tap and jump to `far`.",
      method_name: "minTaps",
      params: [
        { name: "n", type: "int" },
        { name: "ranges", type: "List[int]" }
      ],
      return_type: "int",
      tags: ["greedy", "array", "dynamic-programming", "jump-game"],
      pattern: "**Reduce to Jump Game II.** Each tap `i` with range `r` defines an interval `[max(0, i - r), min(n, i + r)]`. The minimum number of taps that cover `[0, n]` equals the minimum number of intervals whose union covers `[0, n]` — a classic greedy interval-jump problem.\n\n**Step 1 — compute reachability.** Build an array `maxEnd[s]` of length `n + 1`. For each tap, let `s = max(0, i - r)` and `e = min(n, i + r)`; update `maxEnd[s] = max(maxEnd[s], e)`. Now `maxEnd[s]` is the farthest the garden can be watered starting from position `s` or earlier.\n\n**Step 2 — greedy sweep.** Walk `i` from `0` to `n`, maintaining:\n- `curEnd` — the farthest position the currently opened taps water.\n- `far` — the farthest position we could jump to using the best tap discovered so far.\n- `taps` — number of taps opened.\n\n```\nfor i in 0..n:\n    if i > far: return -1                # gap: no tap reaches here\n    if i > curEnd:                       # need to open another tap\n        taps += 1\n        curEnd = far\n        if i > curEnd: return -1\n    far = max(far, maxEnd[i])\nif curEnd < n: taps += 1                 # finish the right side\nreturn taps\n```\n\n**Why this is correct.** When the sweep reaches `i`, every tap whose left endpoint is `<= i` has been considered, so `far` is the optimal endpoint achievable by opening *one more* tap whose left endpoint is `<= i`. The moment the sweep would advance past `curEnd`, we must commit to one extra tap — the greedy choice is the tap that extends coverage farthest, i.e. `far`. Any other tap is dominated by it (it covers a subset of what `far` does on the right). The argument is identical to the proof for Jump Game II.\n\n**Why `maxEnd[s]` collapses the n^2 search.** Without it, finding the best tap at every step would scan all `n + 1` taps. With `maxEnd[s]`, every relevant tap is touched exactly once during the sweep — `O(n)` total.\n\n**Boundary trim.** Clamping intervals to `[0, n]` is what makes the sweep exact at both ends. A tap at position `0` with range `5` only matters up to `n`; the clamp prevents over-counting reach beyond the garden.\n\n**Edge cases that bite.**\n- `n = 0`: the garden is a single point `{0}` and tap `0` covers it regardless of `ranges[0]`. Some references return `1`; the cleaner reading of the spec returns `0` because no tap is needed when the garden has length 0. Test against the LeetCode judge first — most editorial code returns `1`.\n- A tap with range `0` is useful only if its position is the **only** way to cover that single point. If a neighboring tap with range `>= 1` reaches it, the zero-range tap is dominated.\n- Gap detection: if `curEnd` cannot advance to the next `i`, the only honest answer is `-1`. Don't silently skip — the garden is genuinely unwaterable.\n\n**Why this beats DP.** A DP over `[0, n]` runs in `O(n * n)` if you check every tap per cell, or `O(n)` with a heap, but the greedy sweep is `O(n)` time, `O(n)` space, no comparisons against tap indices — the cleanest formulation.",
      follow_up: "**Variant 1 — Video Stitching (LC 1024).** Identical reduction: each clip `[s, e]` plays the role of a tap interval. Same `maxEnd[s]` array, same greedy sweep.\n\n**Variant 2 — Minimum number of arrows to burst balloons (LC 452).** Each balloon is an interval; sort by right endpoint and greedily shoot the rightmost end of the current cluster. Different greedy proof but the same family.\n\n**Variant 3 — Real-valued ranges.** If the taps live on the real line and ranges are floats, you can't index `maxEnd[s]` directly. Sort intervals by left endpoint, sweep them with a max-heap keyed on right endpoint, and pop the best reach each time `curEnd` is exceeded. `O(n log n)`.\n\n**Variant 4 — Weighted taps.** Each tap has an open cost; minimize total cost instead of count. Now the greedy is wrong — solve with DP: `dp[i] = min over all taps that cover [s, e] with s <= i of dp[s - 1] + cost`. Use a segment tree on `dp` for `O(n log n)`.\n\n**Variant 5 — Online taps.** Taps arrive one by one and you must answer the minimum count after each arrival. Maintain a sorted interval set and an aggregate `maxEnd` per left endpoint; reuse the greedy result by patching the affected range.\n\n**Implementation pitfalls.**\n1. **Forgetting the final `if curEnd < n: taps += 1`.** When the sweep finishes at `i = n` with `curEnd < n` but `far >= n`, you still need one extra tap. Without this, you under-count by one on cases like `n = 5, ranges = [3, 4, 1, 1, 0, 0]`.\n2. **Returning the wrong sentinel on the impossible case.** The spec wants `-1`, not `0` or a thrown exception.\n3. **Mis-indexing `ranges`.** The array has length `n + 1` (taps at `0..n`), not `n`. Off-by-one here gives wrong reach for the rightmost tap.\n4. **Not clamping the interval to `[0, n]`.** Without clamping, `maxEnd` can grow past `n`, and the final sweep can claim `far = n + 3`, which still works for correctness but reports a wrong farthest in tooling/visualization.\n5. **Treating a tap with `range = 0` as useless.** It covers exactly one point — if that point is unreachable from any other interval, the zero-range tap is essential.\n6. **Confusing the sweep variable with the tap index.** `i` is a **position** in `0..n`, not a tap index — `maxEnd[i]` is the best end for any tap whose left endpoint is `<= i`.",
      complexity: {
        time: "**O(n)** for both the `maxEnd` precompute and the greedy sweep. Each cell is visited a constant number of times.",
        space: "**O(n)** auxiliary for the `maxEnd` array of length `n + 1`. No recursion, no stacks beyond `taps`, `curEnd`, `far`.",
        notes: "The greedy approach beats DP (`O(n^2)` naive or `O(n log n)` with a heap) by exploiting the structure of left-endpoint-sorted intervals. For `n <= 10^4` the sweep finishes in well under 1 ms.",
        optimal: "**O(n) is tight.** Every tap must be inspected at least once to know its reach, so the lower bound is `Omega(n)`."
      },
      constraints: [
        "1 <= n <= 10^4",
        "ranges.length == n + 1",
        "0 <= ranges[i] <= 100",
        "Each tap i covers the interval [i - ranges[i], i + ranges[i]]",
        "The garden to cover is [0, n]"
      ],
      hints: [
        "**Reduce to Jump Game II.** Each tap `i` with range `r` defines an interval `[max(0, i - r), min(n, i + r)]`. The problem becomes: minimum intervals whose union covers `[0, n]`.",
        "**Precompute `maxEnd[s]`.** For every tap, take the **max** end achievable starting at left endpoint `s`. This collapses the per-step search.",
        "**Greedy sweep with three pointers.** `curEnd` (current coverage end), `far` (best reach committable in this jump), `taps` (count). Open a new tap only when `i` passes `curEnd`.",
        "**Detect impossible early.** If `i > far`, no tap reaches `i` and the garden is unwaterable — return `-1`.",
        "**Don't forget the final commit.** After the sweep, if `curEnd < n` but `far >= n`, increment `taps` once more to finish the right side."
      ],
      test_cases,
      solutions: {
        python: "from typing import List\n\n\nclass Solution:\n    def minTaps(self, n: int, ranges: List[int]) -> int:\n        max_end = [0] * (n + 1)\n        for i, r in enumerate(ranges):\n            s = max(0, i - r)\n            e = min(n, i + r)\n            if e > max_end[s]:\n                max_end[s] = e\n        taps = 0\n        cur_end = 0\n        far = 0\n        for i in range(n + 1):\n            if i > far:\n                return -1\n            if i > cur_end:\n                taps += 1\n                cur_end = far\n                if i > cur_end:\n                    return -1\n            if max_end[i] > far:\n                far = max_end[i]\n        if cur_end < n:\n            if far >= n:\n                taps += 1\n            else:\n                return -1\n        return taps\n",
        javascript: "var minTaps = function(n, ranges) {\n    const maxEnd = new Array(n + 1).fill(0);\n    for (let i = 0; i <= n; i++) {\n        const r = ranges[i];\n        const s = Math.max(0, i - r);\n        const e = Math.min(n, i + r);\n        if (e > maxEnd[s]) maxEnd[s] = e;\n    }\n    let taps = 0;\n    let curEnd = 0;\n    let far = 0;\n    for (let i = 0; i <= n; i++) {\n        if (i > far) return -1;\n        if (i > curEnd) {\n            taps++;\n            curEnd = far;\n            if (i > curEnd) return -1;\n        }\n        if (maxEnd[i] > far) far = maxEnd[i];\n    }\n    if (curEnd < n) {\n        if (far >= n) {\n            taps++;\n        } else {\n            return -1;\n        }\n    }\n    return taps;\n};\n",
        java: "public class Solution {\n    public int minTaps(int n, int[] ranges) {\n        int[] maxEnd = new int[n + 1];\n        for (int i = 0; i <= n; i++) {\n            int r = ranges[i];\n            int s = Math.max(0, i - r);\n            int e = Math.min(n, i + r);\n            if (e > maxEnd[s]) maxEnd[s] = e;\n        }\n        int taps = 0;\n        int curEnd = 0;\n        int far = 0;\n        for (int i = 0; i <= n; i++) {\n            if (i > far) return -1;\n            if (i > curEnd) {\n                taps++;\n                curEnd = far;\n                if (i > curEnd) return -1;\n            }\n            if (maxEnd[i] > far) far = maxEnd[i];\n        }\n        if (curEnd < n) {\n            if (far >= n) {\n                taps++;\n            } else {\n                return -1;\n            }\n        }\n        return taps;\n    }\n}\n",
        cpp: "#include <vector>\n#include <algorithm>\nusing namespace std;\n\nclass Solution {\npublic:\n    int minTaps(int n, vector<int>& ranges) {\n        vector<int> maxEnd(n + 1, 0);\n        for (int i = 0; i <= n; i++) {\n            int r = ranges[i];\n            int s = max(0, i - r);\n            int e = min(n, i + r);\n            if (e > maxEnd[s]) maxEnd[s] = e;\n        }\n        int taps = 0;\n        int curEnd = 0;\n        int far = 0;\n        for (int i = 0; i <= n; i++) {\n            if (i > far) return -1;\n            if (i > curEnd) {\n                taps++;\n                curEnd = far;\n                if (i > curEnd) return -1;\n            }\n            if (maxEnd[i] > far) far = maxEnd[i];\n        }\n        if (curEnd < n) {\n            if (far >= n) {\n                taps++;\n            } else {\n                return -1;\n            }\n        }\n        return taps;\n    }\n};\n"
      }
    }
  };
}

// ============================================================
// PROBLEM 2: the-k-strongest-values-in-an-array (LC 1471)
//   getStrongest(arr: List[int], k: int) -> List[int]
//   Definition: a value v1 is "stronger" than v2 if |v1 - m| > |v2 - m| OR
//   (|v1 - m| == |v2 - m| AND v1 > v2), where m is the median of arr after sorting
//   (median = arr_sorted[(n - 1) / 2], integer-division of (n-1)/2).
//   Return any list of the k strongest values.
//
//   Canonical: sort, m = arr_sorted[(n - 1) / 2], use two pointers from both ends and pick the
//   value with the strictly larger |x - m|; tie-break by larger value (which is always the
//   right pointer because the array is sorted).
// ============================================================
function buildProblem2() {
  const lcg = makeLcg(0xA10F358B);

  function ref(arr, k) {
    const a = arr.slice().sort((x, y) => x - y);
    const n = a.length;
    const m = a[(n - 1) >> 1]; // floor((n - 1) / 2)
    const out = [];
    let l = 0, r = n - 1;
    while (out.length < k) {
      const dl = Math.abs(a[l] - m);
      const dr = Math.abs(a[r] - m);
      // dl > dr -> left wins; dr > dl -> right wins; equal -> tie-break by larger value (right, since sorted)
      if (dl > dr) {
        out.push(a[l]);
        l++;
      } else {
        out.push(a[r]);
        r--;
      }
    }
    // The canonical solution returns the values in the order they are picked.
    // LC accepts any order, but to keep the test deterministic we sort the result here.
    return out.slice().sort((x, y) => x - y);
  }

  const cases = [];

  // Canonical LC samples
  cases.push([[1, 2, 3, 4, 5], 2]); // m=3, picks 5,1 -> sorted [1,5]
  cases.push([[1, 1, 3, 5, 5], 2]); // m=3, picks 5,5 -> [5,5]
  cases.push([[6, 7, 11, 7, 6, 8], 5]); // m=7, picks 11,8,6,6,7 -> sorted [6,6,7,8,11]

  // Single element
  cases.push([[1], 1]);
  cases.push([[-5], 1]);
  cases.push([[1000000], 1]);

  // Two elements
  cases.push([[1, 2], 1]);
  cases.push([[1, 2], 2]);
  cases.push([[5, 5], 2]);
  cases.push([[5, 5], 1]);

  // All same
  cases.push([[7, 7, 7, 7, 7], 3]);
  cases.push([[0, 0, 0, 0], 2]);

  // Already sorted
  cases.push([[1, 2, 3, 4, 5, 6, 7], 3]);
  cases.push([[1, 2, 3, 4, 5, 6, 7], 7]);

  // Reverse sorted
  cases.push([[7, 6, 5, 4, 3, 2, 1], 3]);
  cases.push([[10, 9, 8, 7, 6], 2]);

  // Negative numbers
  cases.push([[-7, -3, -1, 0, 1, 3, 7], 4]);
  cases.push([[-100, -50, 0, 50, 100], 3]);
  cases.push([[-5, -4, -3, -2, -1], 2]);

  // Equal distances tied by value
  cases.push([[1, 2, 3, 4, 5], 4]); // m=3, distances 2,1,0,1,2 -> picks 5,1,4,2
  cases.push([[1, 1, 1, 1, 5, 5, 5, 5], 3]); // m=1, picks 5,5,5
  cases.push([[1, 2, 2, 2, 3, 4, 4, 4, 5], 4]); // m=3, picks 5,1,4,4

  // Large spread
  cases.push([[1, 2, 3, 4, 5, 100], 1]); // m=arr[(6-1)/2]=arr[2]=3, distances 2,1,0,1,2,97 -> 100
  cases.push([[1, 2, 3, 4, 5, 100], 3]);

  // k = full length
  cases.push([[3, 1, 4, 1, 5, 9, 2, 6], 8]);

  // Mixed with duplicates
  cases.push([[2, 2, 3, 3, 4, 4, 5, 5], 4]);
  cases.push([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 5]);

  // LC sample variant with bigger k
  cases.push([[6, 7, 11, 7, 6, 8], 3]);
  cases.push([[1, 1, 3, 5, 5], 4]);

  // Generated by LCG (deterministic)
  while (cases.length < 30) {
    const n = 1 + (lcg() % 14);
    const arr = new Array(n);
    for (let i = 0; i < n; i++) {
      // values in [-50, 50] to exercise sign / median branches
      arr[i] = (lcg() % 101) - 50;
    }
    const k = 1 + (lcg() % n);
    cases.push([arr, k]);
  }

  const test_cases = cases.map(([arr, k]) => ({
    inputs: [JSON.stringify(arr), String(k)],
    expected: JSON.stringify(ref(arr, k))
  }));

  return {
    slug: "the-k-strongest-values-in-an-array",
    obj: {
      description: "Given an array of integers `arr` and an integer `k`.\n\nA value `arr[i]` is said to be **stronger** than a value `arr[j]` if `|arr[i] - m| > |arr[j] - m|` where `m` is the **median** of the array.\n\nIf `|arr[i] - m| == |arr[j] - m|`, then `arr[i]` is said to be stronger than `arr[j]` if `arr[i] > arr[j]`.\n\nReturn a list of the **strongest** `k` values in the array. The answer can be returned in **any arbitrary order**.\n\nThe **median** is the middle value in an ordered integer list. More formally, if the length of the list is `n`, the median is the element in position `((n - 1) / 2)` in the **sorted** non-decreasing list (0-indexed).\n\n- For `arr = [6, -3, 7, 2, 11]`, `n = 5` and the median is obtained by sorting the array `arr = [-3, 2, 6, 7, 11]` and the median is `arr[m]` where `m = ((5 - 1) / 2) = 2`. The median is `6`.\n- For `arr = [-7, 22, 17, 3]`, `n = 4` and the median is obtained by sorting the array `arr = [-7, 3, 17, 22]` and the median is `arr[m]` where `m = ((4 - 1) / 2) = 1`. The median is `3`.\n\n**Example 1**\n\n```\nInput:  arr = [1,2,3,4,5], k = 2\nOutput: [5,1]\nExplanation: median = 3. Distances: |1-3|=2, |2-3|=1, |3-3|=0, |4-3|=1, |5-3|=2.\nThe two strongest are 5 and 1 (tie on distance, but 5 > 4 and 1 > 2 by the tie-break direction).\n```\n\n**Example 2**\n\n```\nInput:  arr = [1,1,3,5,5], k = 2\nOutput: [5,5]\n```\n\nThis is **LeetCode 1471**. The canonical solution **sorts the array**, computes the median at index `(n - 1) / 2`, then runs **two pointers** from both ends, repeatedly picking the side whose distance from the median is strictly larger; on a tie, the right pointer wins because the array is sorted and the right side carries the larger value.",
      method_name: "getStrongest",
      params: [
        { name: "arr", type: "List[int]" },
        { name: "k", type: "int" }
      ],
      return_type: "List[int]",
      tags: ["array", "two-pointers", "sorting"],
      pattern: "**Sort + two pointers from the ends.** After sorting, the most extreme values live at index `0` and index `n - 1`. The median sits at index `(n - 1) / 2`. The strongest value at any moment is whichever endpoint is **farther from the median** — and when tied, the **right** endpoint wins because sorting guarantees `arr[r] >= arr[l]`.\n\n**The skeleton.**\n\n```\nsort(arr)\nm = arr[(n - 1) // 2]\nl, r = 0, n - 1\nout = []\nwhile len(out) < k:\n    if abs(arr[l] - m) > abs(arr[r] - m):\n        out.append(arr[l]); l += 1\n    else:\n        out.append(arr[r]); r -= 1\nreturn out\n```\n\n**Why this is correct.** After sorting, the function `|x - m|` is **bitonic**: it decreases as we move from index `0` toward the median, hits zero at the median, then increases toward index `n - 1`. Both extremes are local maxima of distance. Any value that is NOT at an extreme is strictly dominated by at least one extreme — `arr[l]` and `arr[r]` are the largest candidates of their respective halves.\n\n**Why the tie-break is automatically correct.** On a tie (`|arr[l] - m| == |arr[r] - m|`), the spec says the **larger** value wins. After sorting, `arr[r] >= arr[l]`, so taking the right side respects the tie-break without an extra comparison.\n\n**Why the strict inequality matters.** Using `>=` on the left would break the tie incorrectly when both sides have the same distance — it would pick the smaller value. Always use **strict greater than** on the left.\n\n**Median definition.** The problem uses the **lower median** for even-length arrays: `m = arr_sorted[(n - 1) / 2]`, integer division. For `n = 4`, `(n - 1) / 2 = 1`; for `n = 5`, `(n - 1) / 2 = 2`. Be careful — many median problems use the **upper median** `arr[n / 2]` or the **average** for even `n`. This one does not.\n\n**Worked example.** `arr = [6, 7, 11, 7, 6, 8]`, `k = 5`.\n\n```\nsorted = [6, 6, 7, 7, 8, 11]\nn = 6, m = sorted[(6-1)/2] = sorted[2] = 7\ndistances: |6-7|=1, |6-7|=1, |7-7|=0, |7-7|=0, |8-7|=1, |11-7|=4\nl=0 (dist=1), r=5 (dist=4) -> right wins -> out=[11], r=4\nl=0 (dist=1), r=4 (dist=1) -> tie -> right wins -> out=[11,8], r=3\nl=0 (dist=1), r=3 (dist=0) -> left wins -> out=[11,8,6], l=1\nl=1 (dist=1), r=3 (dist=0) -> left wins -> out=[11,8,6,6], l=2\nl=2 (dist=0), r=3 (dist=0) -> tie -> right wins -> out=[11,8,6,6,7], done\n```\n\n**Why this beats a heap.** A `max-heap` keyed on `(distance, value)` is `O(n log n)` for the build plus `O(k log n)` for the pops. The two-pointer sweep is `O(n log n)` for the sort and `O(k)` for the sweep — same big-O for `k = n`, strictly better for small `k`. The two-pointer approach is also simpler (no custom comparator) and has better cache behavior.\n\n**Why a `nth_element` (partial sort) doesn't help.** You need both the median AND the extreme values; a full sort gets you both in `O(n log n)`, while quickselect for median + selection of top-k by distance ends up being `O(n)` average but `O(n^2)` worst-case and harder to write correctly.",
      follow_up: "**Variant 1 — top-k weakest values.** Flip the tie-break and pick the side whose distance is **smaller**. The straightforward implementation reverses the comparator and walks from the **median outwards** (which requires binary search to find the median's neighbors).\n\n**Variant 2 — top-k strongest in a stream.** Maintain a sorted multi-set with a running median pointer. Each insert is `O(log n)`. The two-pointer sweep is replaced by repeated extraction of the more-distant endpoint.\n\n**Variant 3 — weighted strength.** Each `arr[i]` has a weight `w_i`; strength becomes `w_i * |arr[i] - m|`. The bitonic property is lost; reduce to a heap keyed on weighted distance.\n\n**Variant 4 — multidimensional values.** Strength uses Euclidean distance from a centroid. Compute the centroid, then partial-sort by distance and take the top-k. `O(n log n)` with a heap.\n\n**Variant 5 — k-th strongest value (single value, not a list).** Quickselect over the distance-then-value ordering. Average `O(n)`.\n\n**Variant 6 — top-k strongest with custom median rule (e.g. upper median).** Identical algorithm; only the index `(n - 1) / 2` changes to `n / 2`.\n\n**Implementation pitfalls.**\n1. **Using the wrong median index.** This problem wants `arr_sorted[(n - 1) / 2]`, not `arr_sorted[n / 2]`. They differ for **odd-length** arrays? No — actually they differ for **even-length** arrays: `(4 - 1) / 2 = 1` vs `4 / 2 = 2`. Pick the lower median.\n2. **Tie-break on the wrong side.** On equal distance, take the **right** pointer (the larger value). Using `>=` on the left flips this.\n3. **Returning fewer than `k` values.** If `k == arr.length`, the loop must continue until both pointers cross. The condition `len(out) < k` handles this cleanly; conditioning on `l <= r` instead would terminate early.\n4. **Sorting the result.** LC accepts **any order**, but if you sort the output to make tests deterministic, your tests must compare sorted vs sorted. Both directions are valid.\n5. **Overflow.** `|arr[i] - m|` fits in `int` because constraints cap `arr[i]` at `10^5`. No `long` needed.\n6. **Mutating the input.** If callers reuse `arr`, sort a copy.\n7. **Off-by-one on median for `n = 1`.** `(1 - 1) / 2 = 0`, so `m = arr[0]`. The loop yields exactly one value. Don't special-case it.",
      complexity: {
        time: "**O(n log n)** dominated by the sort. The two-pointer sweep is `O(k) <= O(n)`. Median lookup is `O(1)` after sorting.",
        space: "**O(1)** auxiliary if the sort is in-place; `O(n)` for the output of size `k`. Sorting a copy bumps auxiliary to `O(n)`.",
        notes: "Quickselect + selection by distance is theoretically `O(n)` average but much harder to write, and produces the same big-O as sort + two-pointer in practice for `n <= 10^5`. Stick with sort.",
        optimal: "**O(n log n) is tight** under the comparison model when `k` is large. With value-bounded inputs you can radix-sort to `O(n)`, but the comparison lower bound is `Omega(n log n)`."
      },
      constraints: [
        "1 <= arr.length <= 10^5",
        "-10^5 <= arr[i] <= 10^5",
        "1 <= k <= arr.length",
        "Median m = sorted(arr)[(n - 1) / 2] (lower median)",
        "Strength order: |v - m| desc, then v desc",
        "Return order: any permutation of the top-k values"
      ],
      hints: [
        "**Sort the array first.** After sorting, the median is `arr[(n - 1) / 2]` and the extremes live at index `0` and `n - 1`.",
        "**Two pointers from both ends.** The strongest at any step is whichever endpoint is farther from the median.",
        "**Tie-break by taking the right pointer.** Sorting guarantees `arr[r] >= arr[l]`, so the right side wins on equal distance — which matches the spec's value-tie-break.",
        "**Use strict `>` for the left side.** Using `>=` flips the tie-break.",
        "**Stop when you have `k` values.** The loop is `while len(out) < k`."
      ],
      test_cases,
      solutions: {
        python: "from typing import List\n\n\nclass Solution:\n    def getStrongest(self, arr: List[int], k: int) -> List[int]:\n        a = sorted(arr)\n        n = len(a)\n        m = a[(n - 1) // 2]\n        out = []\n        l, r = 0, n - 1\n        while len(out) < k:\n            dl = abs(a[l] - m)\n            dr = abs(a[r] - m)\n            if dl > dr:\n                out.append(a[l])\n                l += 1\n            else:\n                out.append(a[r])\n                r -= 1\n        return sorted(out)\n",
        javascript: "var getStrongest = function(arr, k) {\n    const a = arr.slice().sort((x, y) => x - y);\n    const n = a.length;\n    const m = a[(n - 1) >> 1];\n    const out = [];\n    let l = 0, r = n - 1;\n    while (out.length < k) {\n        const dl = Math.abs(a[l] - m);\n        const dr = Math.abs(a[r] - m);\n        if (dl > dr) {\n            out.push(a[l]);\n            l++;\n        } else {\n            out.push(a[r]);\n            r--;\n        }\n    }\n    return out.slice().sort((x, y) => x - y);\n};\n",
        java: "import java.util.*;\n\npublic class Solution {\n    public int[] getStrongest(int[] arr, int k) {\n        int n = arr.length;\n        int[] a = arr.clone();\n        Arrays.sort(a);\n        int m = a[(n - 1) / 2];\n        int[] out = new int[k];\n        int idx = 0;\n        int l = 0, r = n - 1;\n        while (idx < k) {\n            int dl = Math.abs(a[l] - m);\n            int dr = Math.abs(a[r] - m);\n            if (dl > dr) {\n                out[idx++] = a[l++];\n            } else {\n                out[idx++] = a[r--];\n            }\n        }\n        Arrays.sort(out);\n        return out;\n    }\n}\n",
        cpp: "#include <vector>\n#include <algorithm>\n#include <cstdlib>\nusing namespace std;\n\nclass Solution {\npublic:\n    vector<int> getStrongest(vector<int>& arr, int k) {\n        vector<int> a = arr;\n        sort(a.begin(), a.end());\n        int n = (int)a.size();\n        int m = a[(n - 1) / 2];\n        vector<int> out;\n        out.reserve(k);\n        int l = 0, r = n - 1;\n        while ((int)out.size() < k) {\n            int dl = std::abs(a[l] - m);\n            int dr = std::abs(a[r] - m);\n            if (dl > dr) {\n                out.push_back(a[l]);\n                l++;\n            } else {\n                out.push_back(a[r]);\n                r--;\n            }\n        }\n        sort(out.begin(), out.end());\n        return out;\n    }\n};\n"
      }
    }
  };
}

// ============================================================
// Compose block and SAFE-replace into problemContent.js
// ============================================================
function buildBlock(p1, p2) {
  const j1 = JSON.stringify(p1.obj, null, 2);
  const j2 = JSON.stringify(p2.obj, null, 2);
  return [
    "",
    "// ===== WAVE 34Y START =====",
    "// === WAVE 34Y " + p1.slug + " START ===",
    ";(function(){",
    "  const _key = " + JSON.stringify(p1.slug) + ";",
    "  const _entry = " + j1 + ";",
    "  RICH_CONTENT[_key] = _entry;",
    "})();",
    "// === WAVE 34Y " + p1.slug + " END ===",
    "// === WAVE 34Y " + p2.slug + " START ===",
    ";(function(){",
    "  const _key = " + JSON.stringify(p2.slug) + ";",
    "  const _entry = " + j2 + ";",
    "  RICH_CONTENT[_key] = _entry;",
    "})();",
    "// === WAVE 34Y " + p2.slug + " END ===",
    "// ===== WAVE 34Y END =====",
    ""
  ].join("\n");
}

const p1 = buildProblem1();
const p2 = buildProblem2();

if (p1.obj.test_cases.length < 25) {
  console.error("P1 has only " + p1.obj.test_cases.length + " test cases");
  process.exit(1);
}
if (p2.obj.test_cases.length < 25) {
  console.error("P2 has only " + p2.obj.test_cases.length + " test cases");
  process.exit(1);
}

const block = buildBlock(p1, p2);

let src = fs.readFileSync(FILE, "utf8");

// guard: don't double-write
if (src.indexOf("WAVE 34Y START") !== -1) {
  console.error("WAVE 34Y already present; aborting to avoid duplicate.");
  process.exit(1);
}

// guard: ensure neither slug is already in the file as a RICH_CONTENT entry
if (src.indexOf("RICH_CONTENT[\"" + p1.slug + "\"]") !== -1) {
  console.error("Slug " + p1.slug + " already present in RICH_CONTENT");
  process.exit(1);
}
if (src.indexOf("RICH_CONTENT[\"" + p2.slug + "\"]") !== -1) {
  console.error("Slug " + p2.slug + " already present in RICH_CONTENT");
  process.exit(1);
}

// SAFE replace (function form) — anchor on the WAVE 34X END marker and append block after it.
const ANCHOR = "// ===== WAVE 34X END =====";
if (src.indexOf(ANCHOR) === -1) {
  console.error("Anchor " + ANCHOR + " not found");
  process.exit(1);
}

const next = src.replace(ANCHOR, function (m) {
  return m + "\n" + block;
});

if (next === src) {
  console.error("No-op replace; aborting");
  process.exit(1);
}

fs.writeFileSync(FILE, next);

console.log("DONE wave34y " + p1.slug + " + " + p2.slug);
process.exit(0);
