#!/usr/bin/env node
// Builds scripts/fix_round1.sql containing UPDATEs for the 32 fixable problems
// found by verify_solutions.mjs. Run from PGcode/.
//
// Strategy by problem class:
//   A. Solution code wrap (sort output / return mutated input / fix bug)
//   B. Problem metadata fix (return_type, method_name, params)
//   C. Test case fix (jsonb_set on individual expected, or full array rewrite)
//
// Skipped (need driver-level work, separate session):
//   min-stack, implement-trie, design-add-search, clone-graph, linked-list-cycle

import { writeFileSync } from 'node:fs';

const out = [];
out.push('-- Auto-generated by scripts/build_fix_round1.mjs');
out.push('-- Round 1 of test-data + solution-code fixes after verify_solutions.mjs sweep');
out.push('BEGIN;');
out.push('');

// ─── Helper: SQL-escape a python string for embedding ───
const sq = (s) => "'" + s.replace(/'/g, "''") + "'";
const jb = (obj) => sq(JSON.stringify(obj)) + '::jsonb';

// ─── Helper: emit solution code update ───
function setSolution(id, code) {
  out.push(`-- ${id}: solution code`);
  out.push(`UPDATE public."PGcode_solution_approaches"`);
  out.push(`   SET code_python = ${sq(code)}`);
  out.push(` WHERE problem_id = '${id}' AND approach_number = 1;`);
  out.push('');
}

// ─── Helper: emit single test case expected fix ───
function fixExpected(id, idx0, newExpected) {
  out.push(`-- ${id}: test #${idx0 + 1} expected`);
  out.push(`UPDATE public."PGcode_problems"`);
  out.push(`   SET test_cases = jsonb_set(test_cases, '{${idx0},expected}', ${sq(JSON.stringify(newExpected))}::jsonb)`);
  out.push(` WHERE id = '${id}';`);
  out.push('');
}

// ─── Helper: emit single test case full replacement (e.g. inputs+expected) ───
function replaceCase(id, idx0, tcObj) {
  out.push(`-- ${id}: replace test #${idx0 + 1}`);
  out.push(`UPDATE public."PGcode_problems"`);
  out.push(`   SET test_cases = jsonb_set(test_cases, '{${idx0}}', ${jb(tcObj)})`);
  out.push(` WHERE id = '${id}';`);
  out.push('');
}

// ─── Helper: replace entire test_cases array ───
function setAllCases(id, cases) {
  out.push(`-- ${id}: replace all test_cases (sorted to match canonical solution)`);
  out.push(`UPDATE public."PGcode_problems"`);
  out.push(`   SET test_cases = ${jb(cases)}`);
  out.push(` WHERE id = '${id}';`);
  out.push('');
}

// ─── Helper: metadata update ───
function setMeta(id, fields) {
  const sets = Object.entries(fields).map(([k, v]) => {
    if (typeof v === 'string') return `${k} = ${sq(v)}`;
    return `${k} = ${jb(v)}`;
  }).join(', ');
  out.push(`-- ${id}: metadata`);
  out.push(`UPDATE public."PGcode_problems" SET ${sets} WHERE id = '${id}';`);
  out.push('');
}

// ─── Helper: build a test_cases entry from inputs+expected ───
const tc = (inputs, expected) => ({ inputs, expected });

// ╔══════════════════════════════════════════════════════════╗
// ║   FIX SET A — Order-sensitive (sort solution + tests)    ║
// ╚══════════════════════════════════════════════════════════╝

// group-anagrams
setSolution('group-anagrams', `class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        groups = {}
        for word in strs:
            key = [0] * 26
            for ch in word:
                key[ord(ch) - ord('a')] += 1
            t = tuple(key)
            if t not in groups:
                groups[t] = []
            groups[t].append(word)
        result = [sorted(g) for g in groups.values()]
        result.sort(key=lambda g: g[0])
        return result
`);

// All group-anagrams expected → sorted (computed in previous step, hard-coded here)
setAllCases('group-anagrams', [
  tc(['["eat","tea","tan","ate","nat","bat"]'], '[["ate","eat","tea"],["bat"],["nat","tan"]]'),
  tc(['[""]'], '[[""]]'),
  tc(['["a"]'], '[["a"]]'),
  tc(['[]'], '[]'),
  tc(['["abc","bca","cab"]'], '[["abc","bca","cab"]]'),
  tc(['["abc","def"]'], '[["abc"],["def"]]'),
  tc(['["ab","ba","abc"]'], '[["ab","ba"],["abc"]]'),
  tc(['["listen","silent","enlist"]'], '[["enlist","listen","silent"]]'),
  tc(['["a","b","c"]'], '[["a"],["b"],["c"]]'),
  tc(['["aaa","aaa"]'], '[["aaa","aaa"]]'),
  tc(['["abc","cba","bac","xyz"]'], '[["abc","bac","cba"],["xyz"]]'),
  tc(['["",""]'], '[["",""]]'),
  tc(['["ab","ab"]'], '[["ab","ab"]]'),
  tc(['["ab","cd","ba","dc"]'], '[["ab","ba"],["cd","dc"]]'),
  tc(['["hello","ohlel","world"]'], '[["hello","ohlel"],["world"]]'),
  tc(['["rat","tar","art"]'], '[["art","rat","tar"]]'),
  tc(['["abcd","bcda","cdab","dabc"]'], '[["abcd","bcda","cdab","dabc"]]'),
  tc(['["aab","aba","baa"]'], '[["aab","aba","baa"]]'),
  tc(['["abc","abd"]'], '[["abc"],["abd"]]'),
  tc(['["x","y","x"]'], '[["x","x"],["y"]]'),
  tc(['["dog","god","cat","tac","act"]'], '[["act","cat","tac"],["dog","god"]]'),
  tc(['["stop","tops","pots","opts","spot"]'], '[["opts","pots","spot","stop","tops"]]'),
  tc(['["a","aa","aaa"]'], '[["a"],["aa"],["aaa"]]'),
  tc(['["ac","ca","bd","db","abc"]'], '[["abc"],["ac","ca"],["bd","db"]]'),
  tc(['["abcdef","fedcba"]'], '[["abcdef","fedcba"]]'),
]);

// subsets — sort solution output and tests
setSolution('subsets', `class Solution:
    def subsets(self, nums: List[int]) -> List[List[int]]:
        result = []
        path = []
        def dfs(i):
            if i == len(nums):
                result.append(path.copy())
                return
            path.append(nums[i])
            dfs(i + 1)
            path.pop()
            dfs(i + 1)
        dfs(0)
        result = [sorted(s) for s in result]
        result.sort(key=lambda s: (len(s), s))
        return result
`);

// Sort expected for subsets matching: by (length, lex)
function subsetsSort(exp) {
  const arr = exp.map(s => [...s].sort((a,b)=>a-b));
  arr.sort((a,b) => {
    if (a.length !== b.length) return a.length - b.length;
    for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return a[i] - b[i];
    return 0;
  });
  return arr;
}
const subsetsCases = [
  [['[1,2,3]'], [[],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3]]],
  [['[0]'], [[],[0]]],
  [['[1]'], [[],[1]]],
  [['[]'], [[]]],
  [['[1,2]'], [[],[1],[2],[1,2]]],
  [['[-1]'], [[],[-1]]],
  [['[9]'], [[],[9]]],
  [['[1,2,3,4]'], [[],[1],[2],[3],[4],[1,2],[1,3],[1,4],[2,3],[2,4],[3,4],[1,2,3],[1,2,4],[1,3,4],[2,3,4],[1,2,3,4]]],
  [['[5]'], [[],[5]]],
  [['[2]'], [[],[2]]],
  [['[3]'], [[],[3]]],
  [['[100]'], [[],[100]]],
  [['[-5]'], [[],[-5]]],
  [['[1,3]'], [[],[1],[3],[1,3]]],
  [['[2,3]'], [[],[2],[3],[2,3]]],
  [['[4,5]'], [[],[4],[5],[4,5]]],
  [['[0,1]'], [[],[0],[1],[0,1]]],
  [['[-1,0]'], [[],[-1],[0],[-1,0]]],
  [['[-1,1]'], [[],[-1],[1],[-1,1]]],
  [['[10,20]'], [[],[10],[20],[10,20]]],
  [['[1,2,4]'], [[],[1],[2],[4],[1,2],[1,4],[2,4],[1,2,4]]],
  [['[2,4,6]'], [[],[2],[4],[6],[2,4],[2,6],[4,6],[2,4,6]]],
  [['[1,3,5]'], [[],[1],[3],[5],[1,3],[1,5],[3,5],[1,3,5]]],
  [['[-1,0,1]'], [[],[-1],[0],[1],[-1,0],[-1,1],[0,1],[-1,0,1]]],
];
setAllCases('subsets', subsetsCases.map(([inputs, exp]) =>
  tc(inputs, JSON.stringify(subsetsSort(exp)))
));

// pacific-atlantic — sort outer
setSolution('pacific-atlantic', `class Solution:
    def pacificAtlantic(self, heights: List[List[int]]) -> List[List[int]]:
        rows, cols = len(heights), len(heights[0])
        pac = set()
        atl = set()
        def dfs(r, c, visited):
            visited.add((r, c))
            for dr, dc in ((1,0),(-1,0),(0,1),(0,-1)):
                nr, nc = r + dr, c + dc
                if (0 <= nr < rows and 0 <= nc < cols and (nr, nc) not in visited
                        and heights[nr][nc] >= heights[r][c]):
                    dfs(nr, nc, visited)
        for c in range(cols):
            dfs(0, c, pac)
            dfs(rows - 1, c, atl)
        for r in range(rows):
            dfs(r, 0, pac)
            dfs(r, cols - 1, atl)
        return sorted([list(cell) for cell in pac & atl])
`);
const paCases = [
  [['[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]'], [[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]],
  [['[[1]]'], [[0,0]]],
  [['[[1,2],[4,3]]'], [[0,1],[1,0],[1,1]]],
  [['[[3,3,3],[3,1,3],[3,3,3]]'], [[0,0],[0,1],[0,2],[1,0],[1,2],[2,0],[2,1],[2,2]]],
  [['[[1,2,3],[8,9,4],[7,6,5]]'], [[0,0],[0,2],[1,0],[1,2],[2,0],[2,1],[2,2]]],
  [['[[10,10,10],[10,1,10],[10,10,10]]'], [[0,0],[0,1],[0,2],[1,0],[1,2],[2,0],[2,1],[2,2]]],
];
function paSort(exp) {
  return [...exp].sort((a,b) => JSON.stringify(a) < JSON.stringify(b) ? -1 : JSON.stringify(a) > JSON.stringify(b) ? 1 : 0);
}
setAllCases('pacific-atlantic', paCases.map(([inputs, exp]) => tc(inputs, JSON.stringify(paSort(exp)))));

// k-closest-points — sort outer
setSolution('k-closest-points', `class Solution:
    def kClosest(self, points: List[List[int]], k: int) -> List[List[int]]:
        import heapq
        heap = []
        for x, y in points:
            d = x * x + y * y
            heapq.heappush(heap, (-d, x, y))
            if len(heap) > k:
                heapq.heappop(heap)
        return sorted([[x, y] for _, x, y in heap])
`);
const kcCases = [
  [['[[1,3],[-2,2]]','1'], [[-2,2]]],
  [['[[3,3],[5,-1],[-2,4]]','2'], [[-2,4],[3,3]]],
  [['[[0,0]]','1'], [[0,0]]],
  [['[[1,0],[0,1]]','2'], [[0,1],[1,0]]],
  [['[[1,1],[2,2],[3,3]]','1'], [[1,1]]],
  [['[[1,1],[2,2],[3,3]]','2'], [[1,1],[2,2]]],
  [['[[1,1],[2,2],[3,3]]','3'], [[1,1],[2,2],[3,3]]],
  [['[[0,1],[1,0]]','1'], [[0,1]]],
  [['[[1,0]]','1'], [[1,0]]],
  [['[[0,1]]','1'], [[0,1]]],
  [['[[1,2],[3,4],[5,6]]','1'], [[1,2]]],
  [['[[1,2],[3,4],[5,6]]','2'], [[1,2],[3,4]]],
  [['[[-1,-1],[1,1]]','1'], [[-1,-1]]],
  [['[[-1,-1],[1,1]]','2'], [[-1,-1],[1,1]]],
  [['[[2,2],[-2,-2]]','1'], [[-2,-2]]],
  [['[[2,2],[-2,-2]]','2'], [[-2,-2],[2,2]]],
  [['[[1,0],[0,1],[-1,0],[0,-1]]','2'], [[-1,0],[0,-1]]],
  [['[[1,0],[0,1],[-1,0],[0,-1]]','4'], [[-1,0],[0,-1],[0,1],[1,0]]],
  [['[[10,10]]','1'], [[10,10]]],
  [['[[5,5],[4,4],[3,3],[2,2],[1,1]]','1'], [[1,1]]],
  [['[[5,5],[4,4],[3,3],[2,2],[1,1]]','3'], [[1,1],[2,2],[3,3]]],
  [['[[1,3],[-2,2],[2,-2]]','2'], [[-2,2],[2,-2]]],
  [['[[0,0],[1,1]]','1'], [[0,0]]],
  [['[[0,0],[1,1],[2,2]]','2'], [[0,0],[1,1]]],
  [['[[6,10],[-3,3],[-2,5],[0,2]]','3'], [[-2,5],[-3,3],[0,2]]],
];
setAllCases('k-closest-points', kcCases.map(([inputs, exp]) => tc(inputs, JSON.stringify(paSort(exp)))));

// word-search-ii — sort solution + tests
setSolution('word-search-ii', `class Solution:
    def findWords(self, board: List[List[str]], words: List[str]) -> List[str]:
        root = {}
        for w in words:
            node = root
            for ch in w:
                node = node.setdefault(ch, {})
            node['$'] = w
        rows, cols = len(board), len(board[0])
        result = []
        def dfs(r, c, node):
            ch = board[r][c]
            child = node.get(ch)
            if not child:
                return
            if '$' in child:
                result.append(child['$'])
                del child['$']
            board[r][c] = '#'
            for dr, dc in ((1,0),(-1,0),(0,1),(0,-1)):
                nr, nc = r + dr, c + dc
                if 0 <= nr < rows and 0 <= nc < cols and board[nr][nc] != '#':
                    dfs(nr, nc, child)
            board[r][c] = ch
        for r in range(rows):
            for c in range(cols):
                dfs(r, c, root)
        return sorted(result)
`);
const wsCases = [
  [['[["o","a","a","n"],["e","t","a","e"],["i","h","k","r"],["i","f","l","v"]]','["oath","pea","eat","rain"]'], ['eat','oath']],
  [['[["a","b"],["c","d"]]','["abcb"]'], []],
  [['[["a"]]','["a"]'], ['a']],
  [['[["a","b"],["a","a"]]','["aba","baa","bab","aaab","aaa"]'], ['aaa','aaab','aba','baa']],
  [['[["a"]]','["b"]'], []],
  [['[["a","a"],["a","a"]]','["aaaa"]'], ['aaaa']],
];
setAllCases('word-search-ii', wsCases.map(([inputs, exp]) => tc(inputs, JSON.stringify([...exp].sort()))));

// top-k-frequent — fix expected to match deterministic bucket-sort order
// Solution iterates dict insertion order. For [4,4,4,3,3,2,2,1] k=2: returns [4,3].
// We'll just run the solution's expected output as the new expected.
// Failing test #5 only — fix expected to "[4,3]"
fixExpected('top-k-frequent', 4, '[4,3]');

// alien-dictionary — replace test #6 with one that has a unique answer
replaceCase('alien-dictionary', 5, tc(['["wrt","wrf","er","ett","rftt"]'], '"wertf"'));

// ╔══════════════════════════════════════════════════════════╗
// ║   FIX SET B — In-place mutation (return mutated input)   ║
// ╚══════════════════════════════════════════════════════════╝

setSolution('move-zeroes', `class Solution:
    def moveZeroes(self, nums: List[int]) -> List[int]:
        slow = 0
        for fast in range(len(nums)):
            if nums[fast] != 0:
                nums[slow], nums[fast] = nums[fast], nums[slow]
                slow += 1
        return nums
`);

setSolution('sort-colors', `class Solution:
    def sortColors(self, nums: List[int]) -> List[int]:
        low, mid, high = 0, 0, len(nums) - 1
        while mid <= high:
            if nums[mid] == 0:
                nums[low], nums[mid] = nums[mid], nums[low]
                low += 1
                mid += 1
            elif nums[mid] == 1:
                mid += 1
            else:
                nums[mid], nums[high] = nums[high], nums[mid]
                high -= 1
        return nums
`);

setSolution('rotate-image', `class Solution:
    def rotate(self, matrix: List[List[int]]) -> List[List[int]]:
        n = len(matrix)
        for i in range(n):
            for j in range(i + 1, n):
                matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]
        for row in matrix:
            row.reverse()
        return matrix
`);
setMeta('rotate-image', { return_type: 'List[List[int]]' });

setSolution('set-matrix-zeroes', `class Solution:
    def setZeroes(self, matrix: List[List[int]]) -> List[List[int]]:
        m, n = len(matrix), len(matrix[0])
        firstRowZero = any(matrix[0][j] == 0 for j in range(n))
        firstColZero = any(matrix[i][0] == 0 for i in range(m))
        for i in range(1, m):
            for j in range(1, n):
                if matrix[i][j] == 0:
                    matrix[i][0] = 0
                    matrix[0][j] = 0
        for i in range(1, m):
            for j in range(1, n):
                if matrix[i][0] == 0 or matrix[0][j] == 0:
                    matrix[i][j] = 0
        if firstRowZero:
            for j in range(n):
                matrix[0][j] = 0
        if firstColZero:
            for i in range(m):
                matrix[i][0] = 0
        return matrix
`);
setMeta('set-matrix-zeroes', { return_type: 'List[List[int]]' });

setSolution('reorder-list', `class Solution:
    def reorderList(self, head: Optional[ListNode]) -> Optional[ListNode]:
        if not head or not head.next:
            return head
        slow = fast = head
        while fast and fast.next:
            slow = slow.next
            fast = fast.next.next
        prev = None
        curr = slow.next
        slow.next = None
        while curr:
            nxt = curr.next
            curr.next = prev
            prev = curr
            curr = nxt
        first, second = head, prev
        while second:
            t1, t2 = first.next, second.next
            first.next = second
            second.next = t1
            first, second = t1, t2
        return head
`);
setMeta('reorder-list', { return_type: 'Optional[ListNode]' });

// ╔══════════════════════════════════════════════════════════╗
// ║   FIX SET C — Method/metadata mismatches                 ║
// ╚══════════════════════════════════════════════════════════╝

setMeta('kth-largest-element', { method_name: 'findKthLargest' });

// meeting-rooms: solution defines canAttendMeetings but DB expects minMeetingRooms.
// Replace solution with the proper Meeting Rooms II algorithm.
setSolution('meeting-rooms', `class Solution:
    def minMeetingRooms(self, intervals: List[List[int]]) -> int:
        if not intervals:
            return 0
        starts = sorted(i[0] for i in intervals)
        ends = sorted(i[1] for i in intervals)
        rooms = 0
        max_rooms = 0
        e = 0
        for s in starts:
            if s < ends[e]:
                rooms += 1
                if rooms > max_rooms:
                    max_rooms = rooms
            else:
                e += 1
        return max_rooms
`);

// non-overlapping-intervals: add empty guard
setSolution('non-overlapping-intervals', `class Solution:
    def eraseOverlapIntervals(self, intervals: List[List[int]]) -> int:
        if not intervals:
            return 0
        intervals.sort(key=lambda x: x[1])
        kept = 1
        end = intervals[0][1]
        for i in range(1, len(intervals)):
            if intervals[i][0] >= end:
                kept += 1
                end = intervals[i][1]
        return len(intervals) - kept
`);

// encode-decode-strings: add a `solve` roundtrip method, change method_name to it
setSolution('encode-decode-strings', `class Solution:
    def encode(self, strs: List[str]) -> str:
        return ''.join(f"{len(w)}#{w}" for w in strs)

    def decode(self, s: str) -> List[str]:
        result = []
        i = 0
        while i < len(s):
            j = i
            while s[j] != '#':
                j += 1
            length = int(s[i:j])
            result.append(s[j + 1 : j + 1 + length])
            i = j + 1 + length
        return result

    def solve(self, strs: List[str]) -> List[str]:
        return self.decode(self.encode(strs))
`);
setMeta('encode-decode-strings', { method_name: 'solve' });

// ╔══════════════════════════════════════════════════════════╗
// ║   FIX SET D — Wrong-expected test cases (one-liners)     ║
// ╚══════════════════════════════════════════════════════════╝

// two-sum: replace 3 broken test cases with valid unique-answer ones
replaceCase('two-sum', 18, tc(['[1,3,5,7,9,11]','18'], '[3,5]'));
replaceCase('two-sum', 19, tc(['[1,4,6,8,10]','12'], '[1,3]'));
replaceCase('two-sum', 20, tc(['[-5,-3,1,4,7,9]','-1'], '[0,3]'));

// two-sum-ii: 1-indexed answer. Replace test #13.
// Original: nums=[2,4,6,8,10,12] target=14. Solution returns [1,6] (1-indexed: nums[0]+nums[5]=2+12=14)
// Other valid: 4+10=14 → [2,5], 6+8=14 → [3,4]. Two-pointer finds 2+12 first (left=0,right=5).
// So solution returns [1,6] correctly. Expected was [2,6] (wrong: nums[1]+nums[5]=4+12=16). Fix to [1,6].
fixExpected('two-sum-ii', 12, '[1,6]');

// target-sum #18: [2,2,2] target=0 → 0 ways (subsets sum to 0,2,4,6 only, can't get half=0).
// Wait: positive_sum + negative_sum = total=6. positive_sum - negative_sum = target=0.
// → positive_sum = 3, but no subset of [2,2,2] sums to 3. So 0 ways. Solution returns 0.
fixExpected('target-sum', 17, '0');

// swim-in-water #5: grid=[[0,1],[3,2]] min-max path = 0→1→2 = 2. Expected 3 wrong.
fixExpected('swim-in-water', 4, '2');

// coin-change #10: coins=[2,3,7] amount=12 → min coins. 7+3+2=12 (3 coins). Expected 2 wrong.
fixExpected('coin-change', 9, '3');

// gas-station #6: gas=[1,2,3,4,5] cost=[5,4,3,2,1]. Algo returns 2. Expected 4 wrong.
fixExpected('gas-station', 5, '2');

// hand-of-straights #17: [1,1,2,2,3,3,4,4,5,5,6,6] groupSize=2. Can form 6 pairs. true.
fixExpected('hand-of-straights', 16, 'true');

// max-subarray #21: [10,-3,-4,7,6,5,-4,-1] Kadane = 21. Expected 17 wrong.
fixExpected('max-subarray', 20, '21');

// last-stone-weight #16: [7,6,7,6,9] → 9-7=2, 7-6=1, 6-2=4, 4-1=3 → 3. Expected 1 wrong.
fixExpected('last-stone-weight', 15, '3');

// longest-repeating-char #7: "ABAB" k=0 → max-same-run=1.
fixExpected('longest-repeating-char', 6, '1');

// car-fleet #17: target=12 pos=[0,5,10] speed=[3,2,1].
// Sorted by pos desc: 10(eta=2), 5(eta=3.5), 0(eta=4). All distinct etas → 3 fleets.
fixExpected('car-fleet', 16, '3');

// trapping-rain-water #16: [3,1,2,1,3] = 2+1+2 = 5.
fixExpected('trapping-rain-water', 15, '5');

// counting-bits #25: bin(24)=11000=2 bits, last entry should be 2.
fixExpected('counting-bits', 24, '[0,1,1,2,1,2,2,3,1,2,2,3,2,3,3,4,1,2,2,3,2,3,3,4,2]');

// word-search #21: ABCCEDF — F is at (1,1), D is at (2,1), they are adjacent. Path exists.
fixExpected('word-search', 20, 'true');

// find-min-rotated #21: [2,2,2,0,2,2] has duplicates which standard binary search can't handle.
// Replace with a non-duplicate rotated array.
replaceCase('find-min-rotated', 20, tc(['[7,8,9,1,2,3,4,5,6]'], '1'));

// network-delay #23: invalid input (n=1 with edge to node 2). Replace with valid.
replaceCase('network-delay', 22, tc(['[]','1','1'], '0'));

writeFileSync('scripts/fix_round1.sql', out.join('\n') + '\nCOMMIT;\n');
console.log('Wrote scripts/fix_round1.sql (' + out.length + ' lines)');
