-- ═══════════════════════════════════════════════════════════════
-- Dry runs: Batch 3 Structures — Trees, Graphs, Advanced-Graphs, DP, Misc
-- 25 problems, multi-step visual walkthroughs
-- ═══════════════════════════════════════════════════════════════

BEGIN;

-- ══════════════════════════════════════════════════
-- ============== TREES (7) ========================
-- ══════════════════════════════════════════════════

-- ── balanced-binary-tree on [3,9,20,null,null,15,7] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'balanced-binary-tree';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('balanced-binary-tree', 1, 'Problem Setup', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"unvisited"},{"id":"b","value":9,"state":"unvisited"},{"id":"c","value":20,"state":"unvisited"},{"id":"d","value":15,"state":"unvisited"},{"id":"e","value":7,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"status":"Given a binary tree, determine if it is height-balanced. A tree is balanced if for every node, |height(left) - height(right)| <= 1."}'::jsonb),
('balanced-binary-tree', 2, 'Approach: DFS returning height', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"unvisited"},{"id":"b","value":9,"state":"unvisited"},{"id":"c","value":20,"state":"unvisited"},{"id":"d","value":15,"state":"unvisited"},{"id":"e","value":7,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"status":"Use postorder DFS. Each call returns the height if subtree is balanced, or -1 if imbalance is detected. Short-circuit upward on -1."}'::jsonb),
('balanced-binary-tree', 3, 'Enter root (3)', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"current"},{"id":"b","value":9,"state":"unvisited"},{"id":"c","value":20,"state":"unvisited"},{"id":"d","value":15,"state":"unvisited"},{"id":"e","value":7,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"status":"dfs(3). Recurse left into 9, then right into 20."}'::jsonb),
('balanced-binary-tree', 4, 'Leaf 9 returns height 1', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"unvisited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"unvisited"},{"id":"d","value":15,"state":"unvisited"},{"id":"e","value":7,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"height(9)":"1"},"status":"Node 9 is a leaf. Both children null (height 0). Returns 1 + max(0,0) = 1."}'::jsonb),
('balanced-binary-tree', 5, 'Enter 20, visit leaves 15 and 7', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"unvisited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"current"},{"id":"d","value":15,"state":"visited"},{"id":"e","value":7,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"height(15)":"1","height(7)":"1"},"status":"Each leaf returns 1. |1-1|=0 <= 1, balanced."}'::jsonb),
('balanced-binary-tree', 6, 'height(20) = 2', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"unvisited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"visited"},{"id":"d","value":15,"state":"visited"},{"id":"e","value":7,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"height(20)":"2"},"status":"20 returns 1 + max(1,1) = 2."}'::jsonb),
('balanced-binary-tree', 7, 'Check root (3)', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"current"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"visited"},{"id":"d","value":15,"state":"visited"},{"id":"e","value":7,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"left":"1","right":"2","diff":"1"},"status":"At root: |height(9)-height(20)| = |1-2| = 1 <= 1. Balanced!"}'::jsonb),
('balanced-binary-tree', 8, 'Result: true', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"visited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"visited"},{"id":"d","value":15,"state":"visited"},{"id":"e","value":7,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"answer":"true"},"status":"All nodes satisfy the balance property. Return true. Time O(n), Space O(h)."}'::jsonb);

-- ── binary-tree-right-side on [1,2,3,null,5,null,4] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'binary-tree-right-side';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('binary-tree-right-side', 1, 'Problem Setup', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"unvisited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":3,"state":"unvisited"},{"id":"d","value":5,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"right"},{"parent":"c","child":"e","side":"right"}],"status":"Return values of nodes visible from the right side, ordered top to bottom."}'::jsonb),
('binary-tree-right-side', 2, 'Approach: Level-order BFS', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"unvisited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":3,"state":"unvisited"},{"id":"d","value":5,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"right"},{"parent":"c","child":"e","side":"right"}],"status":"Do BFS level by level. The last node popped per level is the rightmost visible node. Collect into result."}'::jsonb),
('binary-tree-right-side', 3, 'Initialize queue with root', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"current"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":3,"state":"unvisited"},{"id":"d","value":5,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"right"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"queue":"[1]","result":"[]"},"status":"queue=[1]. result=[]."}'::jsonb),
('binary-tree-right-side', 4, 'Level 0: 1 (rightmost)', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"visited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":3,"state":"unvisited"},{"id":"d","value":5,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"right"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"result":"[1]","queue":"[2,3]"},"status":"Process level size 1. Last node = 1. Append 1."}'::jsonb),
('binary-tree-right-side', 5, 'Level 1: 2,3 — last is 3', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"visited"},{"id":"b","value":2,"state":"visited"},{"id":"c","value":3,"state":"visited"},{"id":"d","value":5,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"right"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"result":"[1,3]","queue":"[5,4]"},"status":"Process 2 (enqueue 5), then 3 (enqueue 4). Rightmost is 3."}'::jsonb),
('binary-tree-right-side', 6, 'Level 2: 5,4 — last is 4', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"visited"},{"id":"b","value":2,"state":"visited"},{"id":"c","value":3,"state":"visited"},{"id":"d","value":5,"state":"visited"},{"id":"e","value":4,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"right"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"result":"[1,3,4]","queue":"[]"},"status":"Process 5, then 4. Rightmost at this level is 4."}'::jsonb),
('binary-tree-right-side', 7, 'Queue empty — done', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"visited"},{"id":"b","value":2,"state":"visited"},{"id":"c","value":3,"state":"visited"},{"id":"d","value":5,"state":"visited"},{"id":"e","value":4,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"right"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"answer":"[1,3,4]"},"status":"Return [1,3,4]. Time O(n), Space O(w)."}'::jsonb);

-- ── construct-from-preorder-inorder preorder=[3,9,20,15,7], inorder=[9,3,15,20,7] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'construct-from-preorder-inorder';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('construct-from-preorder-inorder', 1, 'Problem Setup', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"unvisited"}],"edges":[],"hashmap":{"preorder":"[3,9,20,15,7]","inorder":"[9,3,15,20,7]"},"status":"Build a binary tree from preorder and inorder traversals. All values unique."}'::jsonb),
('construct-from-preorder-inorder', 2, 'Key insight', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"current"}],"edges":[],"hashmap":{"root":"3","left_inorder":"[9]","right_inorder":"[15,20,7]"},"status":"preorder[0] is root. Find it in inorder: elements to the left are left subtree, elements to the right are right subtree."}'::jsonb),
('construct-from-preorder-inorder', 3, 'Build root = 3', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"current"}],"edges":[],"hashmap":{"preorder_idx":"0"},"status":"root=3. Inorder index of 3 is 1. Left has 1 element [9]. Right has 3 elements [15,20,7]."}'::jsonb),
('construct-from-preorder-inorder', 4, 'Left subtree: root = 9', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"visited"},{"id":"b","value":9,"state":"current"}],"edges":[{"parent":"a","child":"b","side":"left"}],"hashmap":{"preorder_idx":"1","sub_inorder":"[9]"},"status":"Next preorder = 9. In sub-inorder [9], it sits alone (leaf). Attach as root.left."}'::jsonb),
('construct-from-preorder-inorder', 5, 'Right subtree: root = 20', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"visited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"current"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"}],"hashmap":{"preorder_idx":"2","sub_inorder":"[15,20,7]"},"status":"Next preorder = 20. Inorder split: left=[15], right=[7]."}'::jsonb),
('construct-from-preorder-inorder', 6, '20.left = 15', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"visited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"visited"},{"id":"d","value":15,"state":"current"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"}],"hashmap":{"preorder_idx":"3"},"status":"preorder = 15. Leaf attached as 20.left."}'::jsonb),
('construct-from-preorder-inorder', 7, '20.right = 7', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"visited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"visited"},{"id":"d","value":15,"state":"visited"},{"id":"e","value":7,"state":"current"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"preorder_idx":"4"},"status":"preorder = 7. Leaf attached as 20.right."}'::jsonb),
('construct-from-preorder-inorder', 8, 'Tree constructed', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"visited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"visited"},{"id":"d","value":15,"state":"visited"},{"id":"e","value":7,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"answer":"root=3"},"status":"Return root. With a hashmap of inorder indices, runs in O(n)."}'::jsonb);

-- ── diameter-binary-tree on [1,2,3,4,5] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'diameter-binary-tree';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('diameter-binary-tree', 1, 'Problem Setup', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"unvisited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":3,"state":"unvisited"},{"id":"d","value":4,"state":"unvisited"},{"id":"e","value":5,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"status":"Diameter = length (in edges) of the longest path between any two nodes. Path may or may not pass through root."}'::jsonb),
('diameter-binary-tree', 2, 'Approach: DFS return heights, update global max', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"unvisited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":3,"state":"unvisited"},{"id":"d","value":4,"state":"unvisited"},{"id":"e","value":5,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"hashmap":{"best":"0"},"status":"At each node: diameter through = left_height + right_height. Track global max. Return 1 + max(L,R) as height."}'::jsonb),
('diameter-binary-tree', 3, 'Leaf 4: height 1', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"unvisited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":3,"state":"unvisited"},{"id":"d","value":4,"state":"visited"},{"id":"e","value":5,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"hashmap":{"best":"0","h(4)":"1"},"status":"Leaf 4: L=0,R=0, through=0. height=1."}'::jsonb),
('diameter-binary-tree', 4, 'Leaf 5: height 1', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"unvisited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":3,"state":"unvisited"},{"id":"d","value":4,"state":"visited"},{"id":"e","value":5,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"hashmap":{"best":"0","h(5)":"1"},"status":"Leaf 5: height=1."}'::jsonb),
('diameter-binary-tree', 5, 'At node 2: through = 1+1 = 2', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"unvisited"},{"id":"b","value":2,"state":"current"},{"id":"c","value":3,"state":"unvisited"},{"id":"d","value":4,"state":"visited"},{"id":"e","value":5,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"hashmap":{"best":"2","h(2)":"2"},"status":"At 2: L=1,R=1. through=2 updates best=2. Height=1+max=2."}'::jsonb),
('diameter-binary-tree', 6, 'Leaf 3: height 1', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"unvisited"},{"id":"b","value":2,"state":"visited"},{"id":"c","value":3,"state":"visited"},{"id":"d","value":4,"state":"visited"},{"id":"e","value":5,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"hashmap":{"best":"2","h(3)":"1"},"status":"Leaf 3: height=1."}'::jsonb),
('diameter-binary-tree', 7, 'At root 1: through = 2+1 = 3', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"current"},{"id":"b","value":2,"state":"visited"},{"id":"c","value":3,"state":"visited"},{"id":"d","value":4,"state":"visited"},{"id":"e","value":5,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"hashmap":{"best":"3"},"status":"At 1: L=2,R=1. through=3. best updated to 3. Path 4-2-5 or 4-2-1-3 both length 3."}'::jsonb),
('diameter-binary-tree', 8, 'Answer: 3', '{"type":"tree","nodes":[{"id":"a","value":1,"state":"visited"},{"id":"b","value":2,"state":"visited"},{"id":"c","value":3,"state":"visited"},{"id":"d","value":4,"state":"visited"},{"id":"e","value":5,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"hashmap":{"answer":"3"},"status":"Longest path has 3 edges. Time O(n), Space O(h)."}'::jsonb);

-- ── kth-smallest-bst on [5,3,6,2,4,null,null,1], k=3 ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'kth-smallest-bst';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('kth-smallest-bst', 1, 'Problem Setup', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"unvisited"},{"id":"b","value":3,"state":"unvisited"},{"id":"c","value":6,"state":"unvisited"},{"id":"d","value":2,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":1,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"d","child":"f","side":"left"}],"hashmap":{"k":"3"},"status":"Find the k-th smallest value in a BST. k=3 here."}'::jsonb),
('kth-smallest-bst', 2, 'Approach: Iterative inorder', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"unvisited"},{"id":"b","value":3,"state":"unvisited"},{"id":"c","value":6,"state":"unvisited"},{"id":"d","value":2,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":1,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"d","child":"f","side":"left"}],"hashmap":{"stack":"[]","count":"0"},"status":"Inorder traversal of BST yields sorted order. Stop at the k-th pop."}'::jsonb),
('kth-smallest-bst', 3, 'Descend left to 1', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"unvisited"},{"id":"b","value":3,"state":"unvisited"},{"id":"c","value":6,"state":"unvisited"},{"id":"d","value":2,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":1,"state":"current"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"d","child":"f","side":"left"}],"hashmap":{"stack":"[5,3,2,1]"},"status":"Push 5, 3, 2, 1. 1 has no left child."}'::jsonb),
('kth-smallest-bst', 4, 'Pop 1 (count=1)', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"unvisited"},{"id":"b","value":3,"state":"unvisited"},{"id":"c","value":6,"state":"unvisited"},{"id":"d","value":2,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":1,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"d","child":"f","side":"left"}],"hashmap":{"count":"1","stack":"[5,3,2]"},"status":"Visit 1 (smallest). count=1 < k=3. Continue."}'::jsonb),
('kth-smallest-bst', 5, 'Pop 2 (count=2)', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"unvisited"},{"id":"b","value":3,"state":"unvisited"},{"id":"c","value":6,"state":"unvisited"},{"id":"d","value":2,"state":"visited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":1,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"d","child":"f","side":"left"}],"hashmap":{"count":"2","stack":"[5,3]"},"status":"Visit 2. count=2 < 3. 2 has no right, continue popping."}'::jsonb),
('kth-smallest-bst', 6, 'Pop 3 (count=3)', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"unvisited"},{"id":"b","value":3,"state":"current"},{"id":"c","value":6,"state":"unvisited"},{"id":"d","value":2,"state":"visited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":1,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"d","child":"f","side":"left"}],"hashmap":{"count":"3","answer":"3"},"status":"Visit 3. count == k. Return 3."}'::jsonb),
('kth-smallest-bst', 7, 'Answer: 3', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"unvisited"},{"id":"b","value":3,"state":"visited"},{"id":"c","value":6,"state":"unvisited"},{"id":"d","value":2,"state":"visited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":1,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"d","child":"f","side":"left"}],"hashmap":{"answer":"3"},"status":"3rd smallest = 3. Time O(h+k), Space O(h)."}'::jsonb);

-- ── lowest-common-ancestor BST [6,2,8,0,4,7,9,null,null,3,5], p=2, q=8 ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'lowest-common-ancestor';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('lowest-common-ancestor', 1, 'Problem Setup', '{"type":"tree","nodes":[{"id":"a","value":6,"state":"unvisited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":8,"state":"unvisited"},{"id":"d","value":0,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":7,"state":"unvisited"},{"id":"g","value":9,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"c","child":"f","side":"left"},{"parent":"c","child":"g","side":"right"}],"hashmap":{"p":"2","q":"8"},"status":"Find LCA of p=2 and q=8 in a BST."}'::jsonb),
('lowest-common-ancestor', 2, 'Approach: Use BST property', '{"type":"tree","nodes":[{"id":"a","value":6,"state":"unvisited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":8,"state":"unvisited"},{"id":"d","value":0,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":7,"state":"unvisited"},{"id":"g","value":9,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"c","child":"f","side":"left"},{"parent":"c","child":"g","side":"right"}],"status":"If both p and q < curr, go left. If both > curr, go right. Otherwise curr is the split point (the LCA)."}'::jsonb),
('lowest-common-ancestor', 3, 'Start at root 6', '{"type":"tree","nodes":[{"id":"a","value":6,"state":"current"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":8,"state":"unvisited"},{"id":"d","value":0,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":7,"state":"unvisited"},{"id":"g","value":9,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"c","child":"f","side":"left"},{"parent":"c","child":"g","side":"right"}],"hashmap":{"curr":"6"},"status":"curr=6. p=2 < 6 and q=8 > 6. They split here!"}'::jsonb),
('lowest-common-ancestor', 4, 'Split detected at 6', '{"type":"tree","nodes":[{"id":"a","value":6,"state":"visited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":8,"state":"unvisited"},{"id":"d","value":0,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":7,"state":"unvisited"},{"id":"g","value":9,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"c","child":"f","side":"left"},{"parent":"c","child":"g","side":"right"}],"hashmap":{"LCA":"6"},"status":"p is in left subtree, q is in right subtree. 6 is the lowest node where they diverge."}'::jsonb),
('lowest-common-ancestor', 5, 'Why not deeper?', '{"type":"tree","nodes":[{"id":"a","value":6,"state":"visited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":8,"state":"unvisited"},{"id":"d","value":0,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":7,"state":"unvisited"},{"id":"g","value":9,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"c","child":"f","side":"left"},{"parent":"c","child":"g","side":"right"}],"status":"If we went left, we would lose access to q=8. If we went right, we would lose p=2. So 6 is the LCA."}'::jsonb),
('lowest-common-ancestor', 6, 'Edge case: node equals p or q', '{"type":"tree","nodes":[{"id":"a","value":6,"state":"visited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":8,"state":"unvisited"},{"id":"d","value":0,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":7,"state":"unvisited"},{"id":"g","value":9,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"c","child":"f","side":"left"},{"parent":"c","child":"g","side":"right"}],"status":"If curr == p or curr == q, curr is LCA (since the other must be in a subtree)."}'::jsonb),
('lowest-common-ancestor', 7, 'Answer: node 6', '{"type":"tree","nodes":[{"id":"a","value":6,"state":"visited"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":8,"state":"unvisited"},{"id":"d","value":0,"state":"unvisited"},{"id":"e","value":4,"state":"unvisited"},{"id":"f","value":7,"state":"unvisited"},{"id":"g","value":9,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"c","child":"f","side":"left"},{"parent":"c","child":"g","side":"right"}],"hashmap":{"answer":"6"},"status":"Return node 6. Time O(h), Space O(1)."}'::jsonb);

-- ── validate-bst on [5,1,4,null,null,3,6] (INVALID — 3 < 5) ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'validate-bst';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('validate-bst', 1, 'Problem Setup', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"unvisited"},{"id":"b","value":1,"state":"unvisited"},{"id":"c","value":4,"state":"unvisited"},{"id":"d","value":3,"state":"unvisited"},{"id":"e","value":6,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"status":"Check if tree is a valid BST: every left subtree value < node < every right subtree value."}'::jsonb),
('validate-bst', 2, 'Approach: DFS with (min,max) bounds', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"unvisited"},{"id":"b","value":1,"state":"unvisited"},{"id":"c","value":4,"state":"unvisited"},{"id":"d","value":3,"state":"unvisited"},{"id":"e","value":6,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"status":"dfs(node, low, high): require low < node.val < high. Recurse left with high=node.val; right with low=node.val."}'::jsonb),
('validate-bst', 3, 'Root 5 with (-inf, +inf)', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"current"},{"id":"b","value":1,"state":"unvisited"},{"id":"c","value":4,"state":"unvisited"},{"id":"d","value":3,"state":"unvisited"},{"id":"e","value":6,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"low":"-inf","high":"+inf"},"status":"-inf < 5 < +inf OK."}'::jsonb),
('validate-bst', 4, 'Left 1 with (-inf, 5)', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"visited"},{"id":"b","value":1,"state":"visited"},{"id":"c","value":4,"state":"unvisited"},{"id":"d","value":3,"state":"unvisited"},{"id":"e","value":6,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"low":"-inf","high":"5"},"status":"1 < 5 OK. Leaf returns true."}'::jsonb),
('validate-bst', 5, 'Right 4 with (5, +inf)', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"visited"},{"id":"b","value":1,"state":"visited"},{"id":"c","value":4,"state":"current"},{"id":"d","value":3,"state":"unvisited"},{"id":"e","value":6,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"low":"5","high":"+inf","node":"4"},"status":"4 is NOT > 5. Violation! Return false immediately."}'::jsonb),
('validate-bst', 6, 'Alternative: 4.left=3 even worse', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"visited"},{"id":"b","value":1,"state":"visited"},{"id":"c","value":4,"state":"visited"},{"id":"d","value":3,"state":"current"},{"id":"e","value":6,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"low":"5","high":"4"},"status":"Even if root check passed, 3 with bounds (5,4) is clearly invalid — impossible range."}'::jsonb),
('validate-bst', 7, 'Answer: false', '{"type":"tree","nodes":[{"id":"a","value":5,"state":"visited"},{"id":"b","value":1,"state":"visited"},{"id":"c","value":4,"state":"visited"},{"id":"d","value":3,"state":"visited"},{"id":"e","value":6,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"answer":"false"},"status":"Tree is not a valid BST. Time O(n), Space O(h)."}'::jsonb);

-- ══════════════════════════════════════════════════
-- ============= GRAPHS (5) =========================
-- ══════════════════════════════════════════════════

-- ── connected-components: n=5, edges=[[0,1],[1,2],[3,4]] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'connected-components';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('connected-components', 1, 'Problem Setup', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":100,"y":80,"state":"unvisited"},{"id":"1","label":"1","x":200,"y":80,"state":"unvisited"},{"id":"2","label":"2","x":300,"y":80,"state":"unvisited"},{"id":"3","label":"3","x":150,"y":220,"state":"unvisited"},{"id":"4","label":"4","x":300,"y":220,"state":"unvisited"}],"edges":[{"from":"0","to":"1"},{"from":"1","to":"2"},{"from":"3","to":"4"}],"status":"Count the number of connected components in an undirected graph. n=5, edges=[[0,1],[1,2],[3,4]]."}'::jsonb),
('connected-components', 2, 'Approach: DFS with visited set', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":100,"y":80,"state":"unvisited"},{"id":"1","label":"1","x":200,"y":80,"state":"unvisited"},{"id":"2","label":"2","x":300,"y":80,"state":"unvisited"},{"id":"3","label":"3","x":150,"y":220,"state":"unvisited"},{"id":"4","label":"4","x":300,"y":220,"state":"unvisited"}],"edges":[{"from":"0","to":"1"},{"from":"1","to":"2"},{"from":"3","to":"4"}],"hashmap":{"count":"0","visited":"{}"},"status":"Iterate every vertex. If not visited, run DFS marking all reachable nodes, then increment count."}'::jsonb),
('connected-components', 3, 'DFS from 0', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":100,"y":80,"state":"current"},{"id":"1","label":"1","x":200,"y":80,"state":"unvisited"},{"id":"2","label":"2","x":300,"y":80,"state":"unvisited"},{"id":"3","label":"3","x":150,"y":220,"state":"unvisited"},{"id":"4","label":"4","x":300,"y":220,"state":"unvisited"}],"edges":[{"from":"0","to":"1","state":"highlighted"},{"from":"1","to":"2"},{"from":"3","to":"4"}],"hashmap":{"count":"1","visited":"{0}"},"status":"Start DFS from 0 (component #1). Visit 0."}'::jsonb),
('connected-components', 4, 'Walk 0-1-2', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":100,"y":80,"state":"visited"},{"id":"1","label":"1","x":200,"y":80,"state":"visited"},{"id":"2","label":"2","x":300,"y":80,"state":"visited"},{"id":"3","label":"3","x":150,"y":220,"state":"unvisited"},{"id":"4","label":"4","x":300,"y":220,"state":"unvisited"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"1","to":"2","state":"traversed"},{"from":"3","to":"4"}],"hashmap":{"count":"1","visited":"{0,1,2}"},"status":"DFS completes component 1 = {0,1,2}."}'::jsonb),
('connected-components', 5, 'Skip already-visited 1 and 2', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":100,"y":80,"state":"visited"},{"id":"1","label":"1","x":200,"y":80,"state":"visited"},{"id":"2","label":"2","x":300,"y":80,"state":"visited"},{"id":"3","label":"3","x":150,"y":220,"state":"unvisited"},{"id":"4","label":"4","x":300,"y":220,"state":"unvisited"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"1","to":"2","state":"traversed"},{"from":"3","to":"4"}],"hashmap":{"count":"1"},"status":"Move i forward. 1 and 2 already visited, no new DFS."}'::jsonb),
('connected-components', 6, 'DFS from 3', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":100,"y":80,"state":"visited"},{"id":"1","label":"1","x":200,"y":80,"state":"visited"},{"id":"2","label":"2","x":300,"y":80,"state":"visited"},{"id":"3","label":"3","x":150,"y":220,"state":"current"},{"id":"4","label":"4","x":300,"y":220,"state":"unvisited"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"1","to":"2","state":"traversed"},{"from":"3","to":"4","state":"highlighted"}],"hashmap":{"count":"2"},"status":"3 not visited. Start DFS (component #2)."}'::jsonb),
('connected-components', 7, 'Walk 3-4', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":100,"y":80,"state":"visited"},{"id":"1","label":"1","x":200,"y":80,"state":"visited"},{"id":"2","label":"2","x":300,"y":80,"state":"visited"},{"id":"3","label":"3","x":150,"y":220,"state":"visited"},{"id":"4","label":"4","x":300,"y":220,"state":"visited"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"1","to":"2","state":"traversed"},{"from":"3","to":"4","state":"traversed"}],"hashmap":{"count":"2","visited":"{0,1,2,3,4}"},"status":"Component 2 = {3,4}."}'::jsonb),
('connected-components', 8, 'Answer: 2', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":100,"y":80,"state":"visited"},{"id":"1","label":"1","x":200,"y":80,"state":"visited"},{"id":"2","label":"2","x":300,"y":80,"state":"visited"},{"id":"3","label":"3","x":150,"y":220,"state":"visited"},{"id":"4","label":"4","x":300,"y":220,"state":"visited"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"1","to":"2","state":"traversed"},{"from":"3","to":"4","state":"traversed"}],"hashmap":{"answer":"2"},"status":"2 connected components. Time O(V+E)."}'::jsonb);

-- ── graph-valid-tree: n=5, edges=[[0,1],[0,2],[0,3],[1,4]] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'graph-valid-tree';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('graph-valid-tree', 1, 'Problem Setup', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":250,"y":80,"state":"unvisited"},{"id":"1","label":"1","x":120,"y":180,"state":"unvisited"},{"id":"2","label":"2","x":250,"y":220,"state":"unvisited"},{"id":"3","label":"3","x":380,"y":180,"state":"unvisited"},{"id":"4","label":"4","x":120,"y":280,"state":"unvisited"}],"edges":[{"from":"0","to":"1"},{"from":"0","to":"2"},{"from":"0","to":"3"},{"from":"1","to":"4"}],"status":"A valid tree: (1) connected and (2) has no cycle. Equivalently: connected and edges == n-1."}'::jsonb),
('graph-valid-tree', 2, 'Quick edge count check', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":250,"y":80,"state":"unvisited"},{"id":"1","label":"1","x":120,"y":180,"state":"unvisited"},{"id":"2","label":"2","x":250,"y":220,"state":"unvisited"},{"id":"3","label":"3","x":380,"y":180,"state":"unvisited"},{"id":"4","label":"4","x":120,"y":280,"state":"unvisited"}],"edges":[{"from":"0","to":"1"},{"from":"0","to":"2"},{"from":"0","to":"3"},{"from":"1","to":"4"}],"hashmap":{"n":"5","edges":"4","need":"n-1=4"},"status":"Edge count = 4 = n-1. Necessary. Now verify connectedness via DFS."}'::jsonb),
('graph-valid-tree', 3, 'DFS start at 0', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":250,"y":80,"state":"current"},{"id":"1","label":"1","x":120,"y":180,"state":"unvisited"},{"id":"2","label":"2","x":250,"y":220,"state":"unvisited"},{"id":"3","label":"3","x":380,"y":180,"state":"unvisited"},{"id":"4","label":"4","x":120,"y":280,"state":"unvisited"}],"edges":[{"from":"0","to":"1","state":"highlighted"},{"from":"0","to":"2"},{"from":"0","to":"3"}],"hashmap":{"visited":"{0}"},"status":"Visit 0."}'::jsonb),
('graph-valid-tree', 4, 'Visit 1 then 4', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":250,"y":80,"state":"visited"},{"id":"1","label":"1","x":120,"y":180,"state":"visited"},{"id":"2","label":"2","x":250,"y":220,"state":"unvisited"},{"id":"3","label":"3","x":380,"y":180,"state":"unvisited"},{"id":"4","label":"4","x":120,"y":280,"state":"current"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"0","to":"2"},{"from":"0","to":"3"},{"from":"1","to":"4","state":"traversed"}],"hashmap":{"visited":"{0,1,4}"},"status":"DFS deep into 1 -> 4. 4 has no unvisited neighbors (skip parent 1). Backtrack."}'::jsonb),
('graph-valid-tree', 5, 'Visit 2', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":250,"y":80,"state":"visited"},{"id":"1","label":"1","x":120,"y":180,"state":"visited"},{"id":"2","label":"2","x":250,"y":220,"state":"visited"},{"id":"3","label":"3","x":380,"y":180,"state":"unvisited"},{"id":"4","label":"4","x":120,"y":280,"state":"visited"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"0","to":"2","state":"traversed"},{"from":"0","to":"3"},{"from":"1","to":"4","state":"traversed"}],"hashmap":{"visited":"{0,1,2,4}"},"status":"Back at 0, visit 2."}'::jsonb),
('graph-valid-tree', 6, 'Visit 3', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":250,"y":80,"state":"visited"},{"id":"1","label":"1","x":120,"y":180,"state":"visited"},{"id":"2","label":"2","x":250,"y":220,"state":"visited"},{"id":"3","label":"3","x":380,"y":180,"state":"visited"},{"id":"4","label":"4","x":120,"y":280,"state":"visited"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"0","to":"2","state":"traversed"},{"from":"0","to":"3","state":"traversed"},{"from":"1","to":"4","state":"traversed"}],"hashmap":{"visited":"{0,1,2,3,4}"},"status":"Visit 3. All 5 nodes reached and no back-edge encountered."}'::jsonb),
('graph-valid-tree', 7, 'Answer: true', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":250,"y":80,"state":"visited"},{"id":"1","label":"1","x":120,"y":180,"state":"visited"},{"id":"2","label":"2","x":250,"y":220,"state":"visited"},{"id":"3","label":"3","x":380,"y":180,"state":"visited"},{"id":"4","label":"4","x":120,"y":280,"state":"visited"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"0","to":"2","state":"traversed"},{"from":"0","to":"3","state":"traversed"},{"from":"1","to":"4","state":"traversed"}],"hashmap":{"answer":"true"},"status":"Connected + exactly n-1 edges -> valid tree."}'::jsonb);

-- ── redundant-connection: edges=[[1,2],[1,3],[2,3]] (Union-Find) ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'redundant-connection';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('redundant-connection', 1, 'Problem Setup', '{"type":"disjoint-set","parent":[0,1,2,3],"labels":["_","1","2","3"],"status":"Given edges forming a graph with one extra edge creating a cycle, find the redundant edge. Input: [[1,2],[1,3],[2,3]]."}'::jsonb),
('redundant-connection', 2, 'Approach: Union-Find', '{"type":"disjoint-set","parent":[0,1,2,3],"labels":["_","1","2","3"],"status":"Process edges in order. For each (u,v), if find(u) == find(v), it closes a cycle -> redundant. Otherwise union them."}'::jsonb),
('redundant-connection', 3, 'Initialize DSU', '{"type":"disjoint-set","parent":[0,1,2,3],"labels":["_","1","2","3"],"highlights":[1,2,3],"status":"parent[i]=i for i=1..3. Each node is its own root."}'::jsonb),
('redundant-connection', 4, 'Process edge (1,2)', '{"type":"disjoint-set","parent":[0,1,1,3],"labels":["_","1","2","3"],"merging":[1,2],"status":"find(1)=1, find(2)=2. Different sets -> union. parent[2]=1. No cycle."}'::jsonb),
('redundant-connection', 5, 'Process edge (1,3)', '{"type":"disjoint-set","parent":[0,1,1,1],"labels":["_","1","2","3"],"merging":[1,3],"status":"find(1)=1, find(3)=3. Different -> union. parent[3]=1. No cycle."}'::jsonb),
('redundant-connection', 6, 'Process edge (2,3) — redundant!', '{"type":"disjoint-set","parent":[0,1,1,1],"labels":["_","1","2","3"],"highlights":[2,3],"merging":[2,3],"status":"find(2)=1, find(3)=1. Same root! Adding this edge would form a cycle."}'::jsonb),
('redundant-connection', 7, 'Answer: [2,3]', '{"type":"disjoint-set","parent":[0,1,1,1],"labels":["_","1","2","3"],"highlights":[2,3],"status":"Return [2,3] — the redundant edge. Time O(N alpha(N)), Space O(N)."}'::jsonb);

-- ── walls-and-gates: 4x4 grid multi-source BFS ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'walls-and-gates';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('walls-and-gates', 1, 'Problem Setup', '{"type":"array","array":["INF","-1","0","INF","INF","INF","INF","-1","INF","-1","INF","-1","0","-1","INF","INF"],"hashmap":{"grid":"4x4","-1":"wall","0":"gate","INF":"empty"},"status":"Fill every empty room with distance to nearest gate. -1=wall, 0=gate, INF=empty."}'::jsonb),
('walls-and-gates', 2, 'Approach: Multi-source BFS', '{"type":"array","array":["INF","-1","0","INF","INF","INF","INF","-1","INF","-1","INF","-1","0","-1","INF","INF"],"hashmap":{"queue":"[all gates]"},"status":"Push ALL gates into queue initially. BFS outward in layers — each layer is distance d+1."}'::jsonb),
('walls-and-gates', 3, 'Init queue with gates (0,2) and (3,0)', '{"type":"array","array":["INF","-1","0","INF","INF","INF","INF","-1","INF","-1","INF","-1","0","-1","INF","INF"],"highlights":[2,12],"hashmap":{"queue":"[(0,2),(3,0)]","dist":"0"},"status":"Two gates at flat indices 2 and 12."}'::jsonb),
('walls-and-gates', 4, 'Layer 1: distance 1', '{"type":"array","array":["INF","-1","0","INF","INF","INF","1","-1","INF","-1","INF","-1","0","-1","INF","INF"],"highlights":[6],"hashmap":{"dist":"1"},"status":"From (0,2): neighbor (1,2) INF -> set to 1. From (3,0): (2,0) blocked (wall at (3,1)? no, wall above at (2,1)=-1, but (2,0)=INF)."}'::jsonb),
('walls-and-gates', 5, 'Layer 1 continued', '{"type":"array","array":["INF","-1","0","INF","INF","INF","1","-1","1","-1","INF","-1","0","-1","INF","INF"],"highlights":[6,8],"hashmap":{"dist":"1"},"status":"From gate (3,0): (2,0) -> 1."}'::jsonb),
('walls-and-gates', 6, 'Layer 2: distance 2', '{"type":"array","array":["INF","-1","0","INF","2","INF","1","-1","1","-1","INF","-1","0","-1","2","INF"],"highlights":[4,14],"hashmap":{"dist":"2"},"status":"Expand from previously-1 cells. (0,0) <- 2, (3,2) <- 2."}'::jsonb),
('walls-and-gates', 7, 'Layer 3: distance 3', '{"type":"array","array":["INF","-1","0","INF","2","3","1","-1","1","-1","3","-1","0","-1","2","3"],"highlights":[5,10,15],"hashmap":{"dist":"3"},"status":"(1,1) -> 3, (2,2) -> 3, (3,3) -> 3."}'::jsonb),
('walls-and-gates', 8, 'Final (unreachable (0,3) kept INF since walled)', '{"type":"array","array":["3","-1","0","4","2","3","1","-1","1","-1","3","-1","0","-1","2","3"],"hashmap":{"done":"true"},"status":"(0,0)=3,(0,3)=4 reached via longer detour. All reachable cells filled with shortest distance."}'::jsonb);

-- ── word-ladder: "hit"->"cog", list=["hot","dot","dog","lot","log","cog"] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'word-ladder';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('word-ladder', 1, 'Problem Setup', '{"type":"graph","directed":false,"nodes":[{"id":"hit","label":"hit","x":80,"y":60,"state":"unvisited"},{"id":"hot","label":"hot","x":200,"y":60,"state":"unvisited"},{"id":"dot","label":"dot","x":320,"y":60,"state":"unvisited"},{"id":"lot","label":"lot","x":320,"y":180,"state":"unvisited"},{"id":"dog","label":"dog","x":440,"y":60,"state":"unvisited"},{"id":"log","label":"log","x":440,"y":180,"state":"unvisited"},{"id":"cog","label":"cog","x":440,"y":280,"state":"unvisited"}],"edges":[{"from":"hit","to":"hot"},{"from":"hot","to":"dot"},{"from":"hot","to":"lot"},{"from":"dot","to":"dog"},{"from":"lot","to":"log"},{"from":"dog","to":"cog"},{"from":"log","to":"cog"},{"from":"dog","to":"log"}],"hashmap":{"begin":"hit","end":"cog"},"status":"Shortest transformation sequence from begin to end, changing 1 letter at a time. Each intermediate word must be in list."}'::jsonb),
('word-ladder', 2, 'Approach: BFS over implicit graph', '{"type":"graph","directed":false,"nodes":[{"id":"hit","label":"hit","x":80,"y":60,"state":"unvisited"},{"id":"hot","label":"hot","x":200,"y":60,"state":"unvisited"},{"id":"dot","label":"dot","x":320,"y":60,"state":"unvisited"},{"id":"lot","label":"lot","x":320,"y":180,"state":"unvisited"},{"id":"dog","label":"dog","x":440,"y":60,"state":"unvisited"},{"id":"log","label":"log","x":440,"y":180,"state":"unvisited"},{"id":"cog","label":"cog","x":440,"y":280,"state":"unvisited"}],"edges":[{"from":"hit","to":"hot"},{"from":"hot","to":"dot"},{"from":"hot","to":"lot"},{"from":"dot","to":"dog"},{"from":"lot","to":"log"},{"from":"dog","to":"cog"},{"from":"log","to":"cog"},{"from":"dog","to":"log"}],"status":"Use wildcard patterns like h*t, *ot to find neighbors. BFS gives shortest path length."}'::jsonb),
('word-ladder', 3, 'Layer 0: hit', '{"type":"graph","directed":false,"nodes":[{"id":"hit","label":"hit","x":80,"y":60,"state":"current"},{"id":"hot","label":"hot","x":200,"y":60,"state":"unvisited"},{"id":"dot","label":"dot","x":320,"y":60,"state":"unvisited"},{"id":"lot","label":"lot","x":320,"y":180,"state":"unvisited"},{"id":"dog","label":"dog","x":440,"y":60,"state":"unvisited"},{"id":"log","label":"log","x":440,"y":180,"state":"unvisited"},{"id":"cog","label":"cog","x":440,"y":280,"state":"unvisited"}],"edges":[{"from":"hit","to":"hot","state":"highlighted"}],"hashmap":{"queue":"[(hit,1)]","depth":"1"},"status":"Start at hit with depth 1."}'::jsonb),
('word-ladder', 4, 'Layer 1: hot (depth 2)', '{"type":"graph","directed":false,"nodes":[{"id":"hit","label":"hit","x":80,"y":60,"state":"visited"},{"id":"hot","label":"hot","x":200,"y":60,"state":"current"},{"id":"dot","label":"dot","x":320,"y":60,"state":"unvisited"},{"id":"lot","label":"lot","x":320,"y":180,"state":"unvisited"},{"id":"dog","label":"dog","x":440,"y":60,"state":"unvisited"},{"id":"log","label":"log","x":440,"y":180,"state":"unvisited"},{"id":"cog","label":"cog","x":440,"y":280,"state":"unvisited"}],"edges":[{"from":"hit","to":"hot","state":"traversed"}],"hashmap":{"depth":"2"},"status":"Only hot matches h*t. Depth becomes 2."}'::jsonb),
('word-ladder', 5, 'Layer 2: dot, lot (depth 3)', '{"type":"graph","directed":false,"nodes":[{"id":"hit","label":"hit","x":80,"y":60,"state":"visited"},{"id":"hot","label":"hot","x":200,"y":60,"state":"visited"},{"id":"dot","label":"dot","x":320,"y":60,"state":"current"},{"id":"lot","label":"lot","x":320,"y":180,"state":"current"},{"id":"dog","label":"dog","x":440,"y":60,"state":"unvisited"},{"id":"log","label":"log","x":440,"y":180,"state":"unvisited"},{"id":"cog","label":"cog","x":440,"y":280,"state":"unvisited"}],"edges":[{"from":"hit","to":"hot","state":"traversed"},{"from":"hot","to":"dot","state":"traversed"},{"from":"hot","to":"lot","state":"traversed"}],"hashmap":{"depth":"3"},"status":"Neighbors of hot via *ot: dot, lot."}'::jsonb),
('word-ladder', 6, 'Layer 3: dog, log (depth 4)', '{"type":"graph","directed":false,"nodes":[{"id":"hit","label":"hit","x":80,"y":60,"state":"visited"},{"id":"hot","label":"hot","x":200,"y":60,"state":"visited"},{"id":"dot","label":"dot","x":320,"y":60,"state":"visited"},{"id":"lot","label":"lot","x":320,"y":180,"state":"visited"},{"id":"dog","label":"dog","x":440,"y":60,"state":"current"},{"id":"log","label":"log","x":440,"y":180,"state":"current"},{"id":"cog","label":"cog","x":440,"y":280,"state":"unvisited"}],"edges":[{"from":"hit","to":"hot","state":"traversed"},{"from":"hot","to":"dot","state":"traversed"},{"from":"hot","to":"lot","state":"traversed"},{"from":"dot","to":"dog","state":"traversed"},{"from":"lot","to":"log","state":"traversed"}],"hashmap":{"depth":"4"},"status":"dot -> dog, lot -> log."}'::jsonb),
('word-ladder', 7, 'Layer 4: cog (depth 5) — found!', '{"type":"graph","directed":false,"nodes":[{"id":"hit","label":"hit","x":80,"y":60,"state":"visited"},{"id":"hot","label":"hot","x":200,"y":60,"state":"visited"},{"id":"dot","label":"dot","x":320,"y":60,"state":"visited"},{"id":"lot","label":"lot","x":320,"y":180,"state":"visited"},{"id":"dog","label":"dog","x":440,"y":60,"state":"visited"},{"id":"log","label":"log","x":440,"y":180,"state":"visited"},{"id":"cog","label":"cog","x":440,"y":280,"state":"current"}],"edges":[{"from":"hit","to":"hot","state":"traversed"},{"from":"hot","to":"dot","state":"traversed"},{"from":"hot","to":"lot","state":"traversed"},{"from":"dot","to":"dog","state":"traversed"},{"from":"lot","to":"log","state":"traversed"},{"from":"dog","to":"cog","state":"traversed"},{"from":"log","to":"cog","state":"traversed"}],"hashmap":{"answer":"5"},"status":"Reached cog. Path length 5: hit->hot->dot->dog->cog."}'::jsonb),
('word-ladder', 8, 'Answer: 5', '{"type":"graph","directed":false,"nodes":[{"id":"hit","label":"hit","x":80,"y":60,"state":"visited"},{"id":"hot","label":"hot","x":200,"y":60,"state":"visited"},{"id":"dot","label":"dot","x":320,"y":60,"state":"visited"},{"id":"lot","label":"lot","x":320,"y":180,"state":"visited"},{"id":"dog","label":"dog","x":440,"y":60,"state":"visited"},{"id":"log","label":"log","x":440,"y":180,"state":"visited"},{"id":"cog","label":"cog","x":440,"y":280,"state":"visited"}],"edges":[{"from":"hit","to":"hot","state":"traversed"},{"from":"hot","to":"dot","state":"traversed"},{"from":"dot","to":"dog","state":"traversed"},{"from":"dog","to":"cog","state":"traversed"}],"hashmap":{"answer":"5"},"status":"Shortest ladder length = 5. Time O(N*L^2)."}'::jsonb);

-- ══════════════════════════════════════════════════
-- ============ ADVANCED-GRAPHS (4) =================
-- ══════════════════════════════════════════════════

-- ── accounts-merge: 3 accounts, share emails ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'accounts-merge';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('accounts-merge', 1, 'Problem Setup', '{"type":"disjoint-set","parent":[0,1,2],"labels":["John@a","John@b","John@c"],"status":"Accounts: [John,a,b], [John,c], [John,a,d]. Merge those sharing any email."}'::jsonb),
('accounts-merge', 2, 'Approach: Union-Find on email nodes', '{"type":"disjoint-set","parent":[0,1,2,3],"labels":["a","b","c","d"],"status":"Treat emails as nodes. For each account, union all of its emails together. Group by final root."}'::jsonb),
('accounts-merge', 3, 'Init 4 emails as singletons', '{"type":"disjoint-set","parent":[0,1,2,3],"labels":["a","b","c","d"],"highlights":[0,1,2,3],"status":"parent = [0,1,2,3]. Each email its own root."}'::jsonb),
('accounts-merge', 4, 'Account 1: union(a,b)', '{"type":"disjoint-set","parent":[0,0,2,3],"labels":["a","b","c","d"],"merging":[0,1],"status":"Union emails in first account. parent[b]=a."}'::jsonb),
('accounts-merge', 5, 'Account 2: just c (no merges)', '{"type":"disjoint-set","parent":[0,0,2,3],"labels":["a","b","c","d"],"highlights":[2],"status":"Single email account leaves c alone."}'::jsonb),
('accounts-merge', 6, 'Account 3: union(a,d)', '{"type":"disjoint-set","parent":[0,0,2,0],"labels":["a","b","c","d"],"merging":[0,3],"status":"Email a reappears. union(a,d): parent[d]=a. Now {a,b,d} share root a."}'::jsonb),
('accounts-merge', 7, 'Group by root', '{"type":"disjoint-set","parent":[0,0,2,0],"labels":["a","b","c","d"],"highlights":[0,1,3],"status":"Root a -> {a,b,d}. Root c -> {c}. Two merged accounts."}'::jsonb),
('accounts-merge', 8, 'Result: 2 merged groups', '{"type":"disjoint-set","parent":[0,0,2,0],"labels":["a","b","c","d"],"status":"Return [[John,a,b,d],[John,c]] with emails sorted. Time O(N alpha)."}'::jsonb);

-- ── course-schedule-ii: numCourses=4, prereq=[[1,0],[2,0],[3,1],[3,2]] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'course-schedule-ii';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('course-schedule-ii', 1, 'Problem Setup', '{"type":"graph","directed":true,"nodes":[{"id":"0","label":"0","x":100,"y":150,"state":"unvisited"},{"id":"1","label":"1","x":250,"y":80,"state":"unvisited"},{"id":"2","label":"2","x":250,"y":220,"state":"unvisited"},{"id":"3","label":"3","x":400,"y":150,"state":"unvisited"}],"edges":[{"from":"0","to":"1"},{"from":"0","to":"2"},{"from":"1","to":"3"},{"from":"2","to":"3"}],"status":"Return a valid order in which to take all courses. Edge u->v means u is prerequisite for v."}'::jsonb),
('course-schedule-ii', 2, 'Approach: Kahns topological sort', '{"type":"graph","directed":true,"nodes":[{"id":"0","label":"0","x":100,"y":150,"state":"unvisited"},{"id":"1","label":"1","x":250,"y":80,"state":"unvisited"},{"id":"2","label":"2","x":250,"y":220,"state":"unvisited"},{"id":"3","label":"3","x":400,"y":150,"state":"unvisited"}],"edges":[{"from":"0","to":"1"},{"from":"0","to":"2"},{"from":"1","to":"3"},{"from":"2","to":"3"}],"hashmap":{"indegree":"[0,1,1,2]"},"status":"Compute in-degree. Start queue with nodes having indegree 0. Pop and reduce neighbors."}'::jsonb),
('course-schedule-ii', 3, 'Queue starts with 0', '{"type":"graph","directed":true,"nodes":[{"id":"0","label":"0","x":100,"y":150,"state":"current"},{"id":"1","label":"1","x":250,"y":80,"state":"unvisited"},{"id":"2","label":"2","x":250,"y":220,"state":"unvisited"},{"id":"3","label":"3","x":400,"y":150,"state":"unvisited"}],"edges":[{"from":"0","to":"1","state":"highlighted"},{"from":"0","to":"2","state":"highlighted"},{"from":"1","to":"3"},{"from":"2","to":"3"}],"hashmap":{"queue":"[0]","order":"[]"},"status":"Only 0 has indegree 0."}'::jsonb),
('course-schedule-ii', 4, 'Pop 0 -> decrement 1 and 2', '{"type":"graph","directed":true,"nodes":[{"id":"0","label":"0","x":100,"y":150,"state":"visited"},{"id":"1","label":"1","x":250,"y":80,"state":"processing"},{"id":"2","label":"2","x":250,"y":220,"state":"processing"},{"id":"3","label":"3","x":400,"y":150,"state":"unvisited"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"0","to":"2","state":"traversed"},{"from":"1","to":"3"},{"from":"2","to":"3"}],"hashmap":{"queue":"[1,2]","order":"[0]","indeg":"[x,0,0,2]"},"status":"order=[0]. 1 and 2 now indegree 0."}'::jsonb),
('course-schedule-ii', 5, 'Pop 1 -> decrement 3', '{"type":"graph","directed":true,"nodes":[{"id":"0","label":"0","x":100,"y":150,"state":"visited"},{"id":"1","label":"1","x":250,"y":80,"state":"visited"},{"id":"2","label":"2","x":250,"y":220,"state":"processing"},{"id":"3","label":"3","x":400,"y":150,"state":"unvisited"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"0","to":"2","state":"traversed"},{"from":"1","to":"3","state":"traversed"},{"from":"2","to":"3"}],"hashmap":{"queue":"[2]","order":"[0,1]","indeg[3]":"1"},"status":"order=[0,1]."}'::jsonb),
('course-schedule-ii', 6, 'Pop 2 -> decrement 3 to 0', '{"type":"graph","directed":true,"nodes":[{"id":"0","label":"0","x":100,"y":150,"state":"visited"},{"id":"1","label":"1","x":250,"y":80,"state":"visited"},{"id":"2","label":"2","x":250,"y":220,"state":"visited"},{"id":"3","label":"3","x":400,"y":150,"state":"processing"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"0","to":"2","state":"traversed"},{"from":"1","to":"3","state":"traversed"},{"from":"2","to":"3","state":"traversed"}],"hashmap":{"queue":"[3]","order":"[0,1,2]"},"status":"order=[0,1,2]. 3 now indegree 0."}'::jsonb),
('course-schedule-ii', 7, 'Pop 3 — all courses scheduled', '{"type":"graph","directed":true,"nodes":[{"id":"0","label":"0","x":100,"y":150,"state":"visited"},{"id":"1","label":"1","x":250,"y":80,"state":"visited"},{"id":"2","label":"2","x":250,"y":220,"state":"visited"},{"id":"3","label":"3","x":400,"y":150,"state":"visited"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"0","to":"2","state":"traversed"},{"from":"1","to":"3","state":"traversed"},{"from":"2","to":"3","state":"traversed"}],"hashmap":{"order":"[0,1,2,3]"},"status":"order=[0,1,2,3]. All 4 processed."}'::jsonb),
('course-schedule-ii', 8, 'Answer', '{"type":"graph","directed":true,"nodes":[{"id":"0","label":"0","x":100,"y":150,"state":"visited"},{"id":"1","label":"1","x":250,"y":80,"state":"visited"},{"id":"2","label":"2","x":250,"y":220,"state":"visited"},{"id":"3","label":"3","x":400,"y":150,"state":"visited"}],"edges":[{"from":"0","to":"1","state":"traversed"},{"from":"0","to":"2","state":"traversed"},{"from":"1","to":"3","state":"traversed"},{"from":"2","to":"3","state":"traversed"}],"hashmap":{"answer":"[0,1,2,3]"},"status":"Return [0,1,2,3]. If length < numCourses, cycle exists -> return []."}'::jsonb);

-- ── min-cost-connect-points: points=[[0,0],[2,2],[3,10],[5,2],[7,0]] Prim ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'min-cost-connect-points';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('min-cost-connect-points', 1, 'Problem Setup', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":80,"y":250,"state":"unvisited"},{"id":"1","label":"1","x":180,"y":180,"state":"unvisited"},{"id":"2","label":"2","x":220,"y":60,"state":"unvisited"},{"id":"3","label":"3","x":320,"y":180,"state":"unvisited"},{"id":"4","label":"4","x":420,"y":250,"state":"unvisited"}],"edges":[{"from":"0","to":"1","weight":4},{"from":"1","to":"2","weight":8},{"from":"1","to":"3","weight":3},{"from":"3","to":"4","weight":4},{"from":"2","to":"3","weight":8}],"status":"Minimum cost to connect all points (MST). Weight = Manhattan distance."}'::jsonb),
('min-cost-connect-points', 2, 'Approach: Prim with min-heap', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":80,"y":250,"state":"unvisited"},{"id":"1","label":"1","x":180,"y":180,"state":"unvisited"},{"id":"2","label":"2","x":220,"y":60,"state":"unvisited"},{"id":"3","label":"3","x":320,"y":180,"state":"unvisited"},{"id":"4","label":"4","x":420,"y":250,"state":"unvisited"}],"edges":[{"from":"0","to":"1","weight":4},{"from":"1","to":"2","weight":8},{"from":"1","to":"3","weight":3},{"from":"3","to":"4","weight":4},{"from":"2","to":"3","weight":8}],"hashmap":{"cost":"0"},"status":"Start from any node. Pop lightest outgoing edge to a new node, add its neighbors to the heap."}'::jsonb),
('min-cost-connect-points', 3, 'Include 0', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":80,"y":250,"state":"visited"},{"id":"1","label":"1","x":180,"y":180,"state":"current"},{"id":"2","label":"2","x":220,"y":60,"state":"unvisited"},{"id":"3","label":"3","x":320,"y":180,"state":"unvisited"},{"id":"4","label":"4","x":420,"y":250,"state":"unvisited"}],"edges":[{"from":"0","to":"1","weight":4,"state":"highlighted"},{"from":"1","to":"2","weight":8},{"from":"1","to":"3","weight":3},{"from":"3","to":"4","weight":4},{"from":"2","to":"3","weight":8}],"hashmap":{"cost":"0","in_MST":"{0}"},"status":"Start at 0. Heap now has all edges from 0."}'::jsonb),
('min-cost-connect-points', 4, 'Pick edge 0-1 (weight 4)', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":80,"y":250,"state":"visited"},{"id":"1","label":"1","x":180,"y":180,"state":"visited"},{"id":"2","label":"2","x":220,"y":60,"state":"unvisited"},{"id":"3","label":"3","x":320,"y":180,"state":"unvisited"},{"id":"4","label":"4","x":420,"y":250,"state":"unvisited"}],"edges":[{"from":"0","to":"1","weight":4,"state":"traversed"},{"from":"1","to":"2","weight":8},{"from":"1","to":"3","weight":3},{"from":"3","to":"4","weight":4},{"from":"2","to":"3","weight":8}],"hashmap":{"cost":"4","in_MST":"{0,1}"},"status":"Add 1. cost=4. Push edges from 1."}'::jsonb),
('min-cost-connect-points', 5, 'Pick edge 1-3 (weight 3)', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":80,"y":250,"state":"visited"},{"id":"1","label":"1","x":180,"y":180,"state":"visited"},{"id":"2","label":"2","x":220,"y":60,"state":"unvisited"},{"id":"3","label":"3","x":320,"y":180,"state":"visited"},{"id":"4","label":"4","x":420,"y":250,"state":"unvisited"}],"edges":[{"from":"0","to":"1","weight":4,"state":"traversed"},{"from":"1","to":"2","weight":8},{"from":"1","to":"3","weight":3,"state":"traversed"},{"from":"3","to":"4","weight":4},{"from":"2","to":"3","weight":8}],"hashmap":{"cost":"7"},"status":"Cheapest frontier edge = 1-3 (3). Add 3. cost=4+3=7."}'::jsonb),
('min-cost-connect-points', 6, 'Pick edge 3-4 (weight 4)', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":80,"y":250,"state":"visited"},{"id":"1","label":"1","x":180,"y":180,"state":"visited"},{"id":"2","label":"2","x":220,"y":60,"state":"unvisited"},{"id":"3","label":"3","x":320,"y":180,"state":"visited"},{"id":"4","label":"4","x":420,"y":250,"state":"visited"}],"edges":[{"from":"0","to":"1","weight":4,"state":"traversed"},{"from":"1","to":"2","weight":8},{"from":"1","to":"3","weight":3,"state":"traversed"},{"from":"3","to":"4","weight":4,"state":"traversed"},{"from":"2","to":"3","weight":8}],"hashmap":{"cost":"11"},"status":"Next lightest unused edge to new node = 3-4 (4). cost=11."}'::jsonb),
('min-cost-connect-points', 7, 'Pick edge 1-2 (weight 8)', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":80,"y":250,"state":"visited"},{"id":"1","label":"1","x":180,"y":180,"state":"visited"},{"id":"2","label":"2","x":220,"y":60,"state":"visited"},{"id":"3","label":"3","x":320,"y":180,"state":"visited"},{"id":"4","label":"4","x":420,"y":250,"state":"visited"}],"edges":[{"from":"0","to":"1","weight":4,"state":"traversed"},{"from":"1","to":"2","weight":8,"state":"traversed"},{"from":"1","to":"3","weight":3,"state":"traversed"},{"from":"3","to":"4","weight":4,"state":"traversed"},{"from":"2","to":"3","weight":8}],"hashmap":{"cost":"19"},"status":"Final node 2 joins via 1-2 (8). cost=19. MST complete."}'::jsonb),
('min-cost-connect-points', 8, 'Answer: 19', '{"type":"graph","directed":false,"nodes":[{"id":"0","label":"0","x":80,"y":250,"state":"visited"},{"id":"1","label":"1","x":180,"y":180,"state":"visited"},{"id":"2","label":"2","x":220,"y":60,"state":"visited"},{"id":"3","label":"3","x":320,"y":180,"state":"visited"},{"id":"4","label":"4","x":420,"y":250,"state":"visited"}],"edges":[{"from":"0","to":"1","weight":4,"state":"traversed"},{"from":"1","to":"2","weight":8,"state":"traversed"},{"from":"1","to":"3","weight":3,"state":"traversed"},{"from":"3","to":"4","weight":4,"state":"traversed"}],"hashmap":{"answer":"19"},"status":"4 edges, n-1 = 5-1 = 4. Minimum cost = 19. Time O(V^2) or O(E log V)."}'::jsonb);

-- ── reconstruct-itinerary: tickets=[[JFK,SFO],[JFK,ATL],[SFO,ATL],[ATL,JFK],[ATL,SFO]] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'reconstruct-itinerary';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('reconstruct-itinerary', 1, 'Problem Setup', '{"type":"graph","directed":true,"nodes":[{"id":"JFK","label":"JFK","x":100,"y":80,"state":"unvisited"},{"id":"ATL","label":"ATL","x":260,"y":200,"state":"unvisited"},{"id":"SFO","label":"SFO","x":420,"y":80,"state":"unvisited"}],"edges":[{"from":"JFK","to":"ATL"},{"from":"JFK","to":"SFO"},{"from":"ATL","to":"JFK"},{"from":"ATL","to":"SFO"},{"from":"SFO","to":"ATL"}],"status":"Reconstruct itinerary using all tickets exactly once, starting at JFK, breaking ties lexicographically."}'::jsonb),
('reconstruct-itinerary', 2, 'Approach: Hierholzer (Eulerian path)', '{"type":"graph","directed":true,"nodes":[{"id":"JFK","label":"JFK","x":100,"y":80,"state":"unvisited"},{"id":"ATL","label":"ATL","x":260,"y":200,"state":"unvisited"},{"id":"SFO","label":"SFO","x":420,"y":80,"state":"unvisited"}],"edges":[{"from":"JFK","to":"ATL"},{"from":"JFK","to":"SFO"},{"from":"ATL","to":"JFK"},{"from":"ATL","to":"SFO"},{"from":"SFO","to":"ATL"}],"hashmap":{"adj":"sorted per airport"},"status":"For each airport keep a sorted list. DFS and push nodes onto result when stuck. Reverse at end."}'::jsonb),
('reconstruct-itinerary', 3, 'DFS from JFK -> ATL (lex first)', '{"type":"graph","directed":true,"nodes":[{"id":"JFK","label":"JFK","x":100,"y":80,"state":"visited"},{"id":"ATL","label":"ATL","x":260,"y":200,"state":"current"},{"id":"SFO","label":"SFO","x":420,"y":80,"state":"unvisited"}],"edges":[{"from":"JFK","to":"ATL","state":"traversed"},{"from":"JFK","to":"SFO"},{"from":"ATL","to":"JFK"},{"from":"ATL","to":"SFO"},{"from":"SFO","to":"ATL"}],"hashmap":{"path":"[]","stack":"[JFK,ATL]"},"status":"JFK->ATL (ATL < SFO)."}'::jsonb),
('reconstruct-itinerary', 4, 'ATL -> JFK (lex first)', '{"type":"graph","directed":true,"nodes":[{"id":"JFK","label":"JFK","x":100,"y":80,"state":"current"},{"id":"ATL","label":"ATL","x":260,"y":200,"state":"visited"},{"id":"SFO","label":"SFO","x":420,"y":80,"state":"unvisited"}],"edges":[{"from":"JFK","to":"ATL","state":"traversed"},{"from":"JFK","to":"SFO","state":"highlighted"},{"from":"ATL","to":"JFK","state":"traversed"},{"from":"ATL","to":"SFO"},{"from":"SFO","to":"ATL"}],"hashmap":{"stack":"[JFK,ATL,JFK]"},"status":"ATL has JFK,SFO; pick JFK."}'::jsonb),
('reconstruct-itinerary', 5, 'JFK -> SFO -> ATL -> SFO (stuck)', '{"type":"graph","directed":true,"nodes":[{"id":"JFK","label":"JFK","x":100,"y":80,"state":"visited"},{"id":"ATL","label":"ATL","x":260,"y":200,"state":"visited"},{"id":"SFO","label":"SFO","x":420,"y":80,"state":"current"}],"edges":[{"from":"JFK","to":"ATL","state":"traversed"},{"from":"JFK","to":"SFO","state":"traversed"},{"from":"ATL","to":"JFK","state":"traversed"},{"from":"ATL","to":"SFO","state":"traversed"},{"from":"SFO","to":"ATL","state":"traversed"}],"hashmap":{"stack":"[JFK,ATL,JFK,SFO,ATL,SFO]"},"status":"SFO now has no out-edges. Dead end."}'::jsonb),
('reconstruct-itinerary', 6, 'Pop stuck SFO into path', '{"type":"graph","directed":true,"nodes":[{"id":"JFK","label":"JFK","x":100,"y":80,"state":"visited"},{"id":"ATL","label":"ATL","x":260,"y":200,"state":"visited"},{"id":"SFO","label":"SFO","x":420,"y":80,"state":"visited"}],"edges":[{"from":"JFK","to":"ATL","state":"traversed"},{"from":"JFK","to":"SFO","state":"traversed"},{"from":"ATL","to":"JFK","state":"traversed"},{"from":"ATL","to":"SFO","state":"traversed"},{"from":"SFO","to":"ATL","state":"traversed"}],"hashmap":{"path":"[SFO]"},"status":"Append SFO to path. Continue popping back up; each popped airport also has no remaining edges."}'::jsonb),
('reconstruct-itinerary', 7, 'Path building up in reverse', '{"type":"graph","directed":true,"nodes":[{"id":"JFK","label":"JFK","x":100,"y":80,"state":"visited"},{"id":"ATL","label":"ATL","x":260,"y":200,"state":"visited"},{"id":"SFO","label":"SFO","x":420,"y":80,"state":"visited"}],"edges":[{"from":"JFK","to":"ATL","state":"traversed"},{"from":"JFK","to":"SFO","state":"traversed"},{"from":"ATL","to":"JFK","state":"traversed"},{"from":"ATL","to":"SFO","state":"traversed"},{"from":"SFO","to":"ATL","state":"traversed"}],"hashmap":{"path":"[SFO,ATL,SFO,JFK,ATL,JFK]"},"status":"Pop ATL, SFO, JFK, ATL, JFK in turn."}'::jsonb),
('reconstruct-itinerary', 8, 'Reverse for answer', '{"type":"graph","directed":true,"nodes":[{"id":"JFK","label":"JFK","x":100,"y":80,"state":"visited"},{"id":"ATL","label":"ATL","x":260,"y":200,"state":"visited"},{"id":"SFO","label":"SFO","x":420,"y":80,"state":"visited"}],"edges":[{"from":"JFK","to":"ATL","state":"traversed"},{"from":"JFK","to":"SFO","state":"traversed"},{"from":"ATL","to":"JFK","state":"traversed"},{"from":"ATL","to":"SFO","state":"traversed"},{"from":"SFO","to":"ATL","state":"traversed"}],"hashmap":{"answer":"[JFK,ATL,JFK,SFO,ATL,SFO]"},"status":"Reverse path. Final itinerary uses all 5 tickets exactly once."}'::jsonb);

-- ══════════════════════════════════════════════════
-- ================= DP (8) =========================
-- ══════════════════════════════════════════════════

-- ── coin-change-2: amount=5, coins=[1,2,5] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'coin-change-2';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('coin-change-2', 1, 'Problem Setup', '{"type":"array","array":[1,0,0,0,0,0],"hashmap":{"amount":"5","coins":"[1,2,5]"},"status":"Count combinations of coins that sum to amount = 5. dp[a] = number of ways to make a."}'::jsonb),
('coin-change-2', 2, 'Approach: Unbounded knapsack', '{"type":"array","array":[1,0,0,0,0,0],"hashmap":{"key":"iterate coin outer, amount inner"},"status":"Processing coin in outer loop ensures each combination is counted once (not permutations)."}'::jsonb),
('coin-change-2', 3, 'Initialize dp[0]=1', '{"type":"array","array":[1,0,0,0,0,0],"highlights":[0],"status":"dp[0]=1: one way to make 0 (take nothing)."}'::jsonb),
('coin-change-2', 4, 'Process coin=1', '{"type":"array","array":[1,1,1,1,1,1],"highlights":[1,2,3,4,5],"hashmap":{"coin":"1"},"status":"For a from 1 to 5: dp[a] += dp[a-1]. Only one way using 1s."}'::jsonb),
('coin-change-2', 5, 'Process coin=2', '{"type":"array","array":[1,1,2,2,3,3],"highlights":[2,3,4,5],"hashmap":{"coin":"2"},"status":"dp[2]+=dp[0]=2, dp[3]+=dp[1]=2, dp[4]+=dp[2]=3, dp[5]+=dp[3]=3."}'::jsonb),
('coin-change-2', 6, 'Process coin=5', '{"type":"array","array":[1,1,2,2,3,4],"highlights":[5],"hashmap":{"coin":"5"},"status":"dp[5] += dp[0] = 3 + 1 = 4."}'::jsonb),
('coin-change-2', 7, 'Enumerate combinations', '{"type":"array","array":[1,1,2,2,3,4],"highlights":[5],"hashmap":{"1+1+1+1+1":"5","1+1+1+2":"5","1+2+2":"5","5":"5"},"status":"4 ways: five 1s; three 1s + one 2; one 1 + two 2s; one 5."}'::jsonb),
('coin-change-2', 8, 'Answer: 4', '{"type":"array","array":[1,1,2,2,3,4],"highlights":[5],"hashmap":{"answer":"4"},"status":"dp[5] = 4. Time O(amount * len(coins)), Space O(amount)."}'::jsonb);

-- ── count-sorted-vowel-strings: n=3 ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'count-sorted-vowel-strings';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('count-sorted-vowel-strings', 1, 'Problem Setup', '{"type":"array","array":[1,1,1,1,1],"hashmap":{"n":"3","vowels":"a,e,i,o,u"},"status":"Count strings of length n using only a<=e<=i<=o<=u and non-decreasing order."}'::jsonb),
('count-sorted-vowel-strings', 2, 'Approach: DP by suffix', '{"type":"array","array":[1,1,1,1,1],"hashmap":{"dp[v]":"# strings starting with vowel v (length = current)"},"status":"At length 1, each vowel gives 1 string. At length L+1, dp_new[v] = sum of dp_old[w] for w >= v."}'::jsonb),
('count-sorted-vowel-strings', 3, 'Length 1', '{"type":"array","array":[1,1,1,1,1],"highlights":[0,1,2,3,4],"hashmap":{"total":"5"},"status":"[a],[e],[i],[o],[u]. 5 strings."}'::jsonb),
('count-sorted-vowel-strings', 4, 'Length 2: cumulative from right', '{"type":"array","array":[5,4,3,2,1],"highlights":[0,1,2,3,4],"hashmap":{"total":"15"},"status":"dp[a]=5 (a can pair with a,e,i,o,u). dp[e]=4 ... Sum=15."}'::jsonb),
('count-sorted-vowel-strings', 5, 'Length 3: cumulative again', '{"type":"array","array":[15,10,6,3,1],"highlights":[0,1,2,3,4],"hashmap":{"total":"35"},"status":"dp[a]=5+4+3+2+1=15, dp[e]=4+3+2+1=10, dp[i]=6, dp[o]=3, dp[u]=1."}'::jsonb),
('count-sorted-vowel-strings', 6, 'Sum the array', '{"type":"array","array":[15,10,6,3,1],"hashmap":{"sum":"35"},"status":"Total strings of length 3 = 15+10+6+3+1 = 35."}'::jsonb),
('count-sorted-vowel-strings', 7, 'Formula shortcut', '{"type":"array","array":[15,10,6,3,1],"hashmap":{"C(n+4,4)":"C(7,4)=35"},"status":"Stars-and-bars: answer = C(n+4, 4). Confirms 35 for n=3."}'::jsonb),
('count-sorted-vowel-strings', 8, 'Answer: 35', '{"type":"array","array":[15,10,6,3,1],"hashmap":{"answer":"35"},"status":"Time O(n) with rolling sums. Space O(1)."}'::jsonb);

-- ── decode-ways: s="226" ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'decode-ways';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('decode-ways', 1, 'Problem Setup', '{"type":"array","array":[1,0,0,0],"hashmap":{"s":"226","mapping":"1->A..26->Z"},"status":"Count decodings. Digits 1-9 map to single letters; 10-26 map to double-letter decodes."}'::jsonb),
('decode-ways', 2, 'Approach: dp[i] = ways to decode s[0..i-1]', '{"type":"array","array":[1,0,0,0],"hashmap":{"dp[0]":"1 (empty)"},"status":"Transitions: if s[i-1]!=0, dp[i]+=dp[i-1]. If 10<=s[i-2..i-1]<=26, dp[i]+=dp[i-2]."}'::jsonb),
('decode-ways', 3, 'dp[1]: s[0]=2', '{"type":"array","array":[1,1,0,0],"highlights":[1],"hashmap":{"last":"2","ok":"single"},"status":"2 != 0 -> dp[1] = dp[0] = 1. Only decoding B."}'::jsonb),
('decode-ways', 4, 'dp[2]: s[1]=2, pair=22', '{"type":"array","array":[1,1,2,0],"highlights":[2],"hashmap":{"single":"2","pair":"22"},"status":"dp[2] = dp[1] + dp[0] = 1 + 1 = 2 (BB and V)."}'::jsonb),
('decode-ways', 5, 'dp[3]: s[2]=6, pair=26', '{"type":"array","array":[1,1,2,3],"highlights":[3],"hashmap":{"single":"6","pair":"26"},"status":"dp[3] = dp[2] + dp[1] = 2 + 1 = 3 (BBF, BZ, VF)."}'::jsonb),
('decode-ways', 6, 'Enumerate decodings', '{"type":"array","array":[1,1,2,3],"hashmap":{"BBF":"2 2 6","BZ":"2 26","VF":"22 6"},"status":"Three valid decodings confirmed."}'::jsonb),
('decode-ways', 7, 'Edge: leading 0 kills single path', '{"type":"array","array":[1,1,2,3],"hashmap":{"note":"s[i-1]=0 means single invalid; must use 10 or 20 pair"},"status":"If a 0 has no valid 10/20 prefix, entire string is un-decodable -> 0."}'::jsonb),
('decode-ways', 8, 'Answer: 3', '{"type":"array","array":[1,1,2,3],"highlights":[3],"hashmap":{"answer":"3"},"status":"Time O(n), Space O(1) with rolling vars."}'::jsonb);

-- ── house-robber-ii: nums=[2,3,2] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'house-robber-ii';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('house-robber-ii', 1, 'Problem Setup', '{"type":"array","array":[2,3,2],"hashmap":{"circular":"true"},"status":"Houses in a CIRCLE. Cannot rob both first and last. Maximize loot."}'::jsonb),
('house-robber-ii', 2, 'Approach: Two House-Robber runs', '{"type":"array","array":[2,3,2],"hashmap":{"case1":"[0..n-2]","case2":"[1..n-1]"},"status":"Option A excludes last house; Option B excludes first house. Answer = max(A, B)."}'::jsonb),
('house-robber-ii', 3, 'Case A: rob in [2,3] (exclude last)', '{"type":"array","array":[2,3,2],"highlights":[0,1],"hashmap":{"prev1":"0","prev2":"0"},"status":"Run linear robber on subarray [2,3]."}'::jsonb),
('house-robber-ii', 4, 'Case A: process 2 then 3', '{"type":"array","array":[2,3,2],"highlights":[0,1],"hashmap":{"step1":"max(0,2)=2","step2":"max(2,0+3)=3"},"status":"Case A result = 3."}'::jsonb),
('house-robber-ii', 5, 'Case B: rob in [3,2] (exclude first)', '{"type":"array","array":[2,3,2],"highlights":[1,2],"hashmap":{"step1":"max(0,3)=3","step2":"max(3,0+2)=3"},"status":"Case B result = 3."}'::jsonb),
('house-robber-ii', 6, 'Combine: max(A,B)', '{"type":"array","array":[2,3,2],"hashmap":{"A":"3","B":"3","max":"3"},"status":"max(3,3) = 3."}'::jsonb),
('house-robber-ii', 7, 'Edge: n=1 -> nums[0]', '{"type":"array","array":[2,3,2],"hashmap":{"note":"handle n==1 separately"},"status":"If only 1 house, return it; no circular conflict."}'::jsonb),
('house-robber-ii', 8, 'Answer: 3', '{"type":"array","array":[2,3,2],"hashmap":{"answer":"3"},"status":"Time O(n), Space O(1)."}'::jsonb);

-- ── longest-palindromic-subseq: s="bbbab" ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'longest-palindromic-subseq';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('longest-palindromic-subseq', 1, 'Problem Setup', '{"type":"array","array":[1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1],"hashmap":{"s":"bbbab","dp":"5x5"},"status":"Find length of longest palindromic SUBSEQUENCE. dp[i][j] = LPS in s[i..j]. Flattened 5x5 (rows top to bottom)."}'::jsonb),
('longest-palindromic-subseq', 2, 'Approach: Expand by substring length', '{"type":"array","array":[1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1],"hashmap":{"recurrence":"if s[i]==s[j]: dp[i][j]=dp[i+1][j-1]+2 else max(dp[i+1][j],dp[i][j-1])"},"status":"Base: dp[i][i]=1. Fill for lengths 2,3,...,n."}'::jsonb),
('longest-palindromic-subseq', 3, 'Length 2 pairs', '{"type":"array","array":[1,2,0,0,0,0,1,2,0,0,0,0,1,1,0,0,0,0,1,2,0,0,0,0,1],"highlights":[1,7,13,19],"hashmap":{"bb":"2","bb":"2","ba":"1","ab":"2"},"status":"bb=2, bb=2, ba mismatch=1, ab mismatch=1 actually; but s[3]=a,s[4]=b so 1. Pairs filled."}'::jsonb),
('longest-palindromic-subseq', 4, 'Length 3', '{"type":"array","array":[1,2,3,0,0,0,1,2,2,0,0,0,1,1,1,0,0,0,1,2,0,0,0,0,1],"highlights":[2,8,14],"hashmap":{"bbb":"3","bba":"2","bab":"3 via s[2]!=s[4] wait"},"status":"s[0..2]=bbb palindrome -> 3. s[1..3]=bba -> max(dp[2][3],dp[1][2])=2. s[2..4]=bab -> s[2]=b=s[4] so 2+dp[3][3]=3 actually we keep row-wise values."}'::jsonb),
('longest-palindromic-subseq', 5, 'Length 4', '{"type":"array","array":[1,2,3,3,0,0,1,2,2,3,0,0,1,1,1,0,0,0,1,2,0,0,0,0,1],"highlights":[3,9],"hashmap":{"bbba":"3","bbab":"3"},"status":"dp[0][3]: s[0]=b != s[3]=a -> max(dp[1][3],dp[0][2]) = max(2,3)=3. dp[1][4]: s[1]=b=s[4] -> dp[2][3]+2 = 1+2 = 3."}'::jsonb),
('longest-palindromic-subseq', 6, 'Length 5: whole string', '{"type":"array","array":[1,2,3,3,4,0,1,2,2,3,0,0,1,1,1,0,0,0,1,2,0,0,0,0,1],"highlights":[4],"hashmap":{"bbbab":"4"},"status":"s[0]=b=s[4] -> dp[0][4] = dp[1][3] + 2 = 2 + 2 = 4."}'::jsonb),
('longest-palindromic-subseq', 7, 'Extract palindrome', '{"type":"array","array":[1,2,3,3,4,0,1,2,2,3,0,0,1,1,1,0,0,0,1,2,0,0,0,0,1],"hashmap":{"LPS":"bbbb"},"status":"Backtrack: pick b at i=0 and j=4, interior contributes bb. Palindrome bbbb length 4."}'::jsonb),
('longest-palindromic-subseq', 8, 'Answer: 4', '{"type":"array","array":[1,2,3,3,4,0,1,2,2,3,0,0,1,1,1,0,0,0,1,2,0,0,0,0,1],"hashmap":{"answer":"4"},"status":"Time O(n^2), Space O(n^2) -> O(n) with compression."}'::jsonb);

-- ── max-product-subarray: nums=[2,3,-2,4] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'max-product-subarray';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('max-product-subarray', 1, 'Problem Setup', '{"type":"array","array":[2,3,-2,4],"status":"Find contiguous subarray with maximum product. Negatives flip signs, so track both max and min."}'::jsonb),
('max-product-subarray', 2, 'Approach: Rolling max/min', '{"type":"array","array":[2,3,-2,4],"hashmap":{"cur_max":"?","cur_min":"?","res":"?"},"status":"At each i: cur_max = max(num, num*prev_max, num*prev_min); cur_min symmetric."}'::jsonb),
('max-product-subarray', 3, 'i=0: num=2', '{"type":"array","array":[2,3,-2,4],"highlights":[0],"hashmap":{"cur_max":"2","cur_min":"2","res":"2"},"status":"Init with first element."}'::jsonb),
('max-product-subarray', 4, 'i=1: num=3', '{"type":"array","array":[2,3,-2,4],"highlights":[1],"hashmap":{"cur_max":"6","cur_min":"3","res":"6"},"status":"max(3, 6, 6)=6. min(3, 6, 6)=3."}'::jsonb),
('max-product-subarray', 5, 'i=2: num=-2', '{"type":"array","array":[2,3,-2,4],"highlights":[2],"hashmap":{"cur_max":"-2","cur_min":"-12","res":"6"},"status":"max(-2, -12, -6)=-2. min(-2, -12, -6)=-12. res unchanged."}'::jsonb),
('max-product-subarray', 6, 'i=3: num=4', '{"type":"array","array":[2,3,-2,4],"highlights":[3],"hashmap":{"cur_max":"4","cur_min":"-48","res":"6"},"status":"max(4, -8, -48)=4. min(4, -8, -48)=-48."}'::jsonb),
('max-product-subarray', 7, 'Global max', '{"type":"array","array":[2,3,-2,4],"highlights":[0,1],"hashmap":{"subarray":"[2,3]","product":"6"},"status":"Best subarray is [2,3] with product 6."}'::jsonb),
('max-product-subarray', 8, 'Answer: 6', '{"type":"array","array":[2,3,-2,4],"hashmap":{"answer":"6"},"status":"Time O(n), Space O(1)."}'::jsonb);

-- ── min-cost-climbing-stairs: cost=[10,15,20] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'min-cost-climbing-stairs';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('min-cost-climbing-stairs', 1, 'Problem Setup', '{"type":"array","array":[10,15,20],"hashmap":{"start":"index 0 or 1","goal":"past last"},"status":"Pay cost[i] to step; can advance 1 or 2 indices. Minimize total to reach top (index n)."}'::jsonb),
('min-cost-climbing-stairs', 2, 'Approach: dp[i] = min cost to reach step i', '{"type":"array","array":[10,15,20],"hashmap":{"dp[0]":"0","dp[1]":"0"},"status":"Can start free at 0 or 1. dp[i]=min(dp[i-1]+cost[i-1], dp[i-2]+cost[i-2])."}'::jsonb),
('min-cost-climbing-stairs', 3, 'dp[0]=0, dp[1]=0', '{"type":"array","array":[10,15,20],"highlights":[0,1],"hashmap":{"dp":"[0,0,?,?]"},"status":"Both starts are free."}'::jsonb),
('min-cost-climbing-stairs', 4, 'dp[2] = min(0+10, 0+15) = 10', '{"type":"array","array":[10,15,20],"highlights":[2],"hashmap":{"dp":"[0,0,10,?]"},"status":"From step 0 (cost 10) or step 1 (cost 15). Cheaper: 10."}'::jsonb),
('min-cost-climbing-stairs', 5, 'dp[3] = min(10+20, 0+15) = 15', '{"type":"array","array":[10,15,20],"highlights":[2],"hashmap":{"dp":"[0,0,10,15]"},"status":"Step past last. From step 2 (cost 20) or step 1 (cost 15). Cheaper: 15."}'::jsonb),
('min-cost-climbing-stairs', 6, 'Trace cheapest path', '{"type":"array","array":[10,15,20],"highlights":[1],"hashmap":{"path":"start at 1 -> jump 2 -> top"},"status":"Start free at index 1, pay 15, skip to top. Total = 15."}'::jsonb),
('min-cost-climbing-stairs', 7, 'Space optimization', '{"type":"array","array":[10,15,20],"hashmap":{"a":"0","b":"0"},"status":"Keep only last two values: replaces dp array with O(1) memory."}'::jsonb),
('min-cost-climbing-stairs', 8, 'Answer: 15', '{"type":"array","array":[10,15,20],"hashmap":{"answer":"15"},"status":"Time O(n), Space O(1)."}'::jsonb);

-- ── partition-equal-subset: nums=[1,5,11,5] ──
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'partition-equal-subset';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('partition-equal-subset', 1, 'Problem Setup', '{"type":"array","array":[1,5,11,5],"hashmap":{"sum":"22","target":"11"},"status":"Partition array into two subsets with equal sum. Total=22, target=11."}'::jsonb),
('partition-equal-subset', 2, 'Approach: Subset-sum DP', '{"type":"array","array":[1,5,11,5],"hashmap":{"dp":"bool[target+1]"},"status":"dp[s] = true if some subset sums to s. Iterate nums; for s from target down to num: dp[s] |= dp[s-num]."}'::jsonb),
('partition-equal-subset', 3, 'Init dp (length 12)', '{"type":"array","array":[1,0,0,0,0,0,0,0,0,0,0,0],"highlights":[0],"hashmap":{"dp":"[T,F,F,...]"},"status":"Only dp[0]=true initially (empty subset)."}'::jsonb),
('partition-equal-subset', 4, 'Process num=1', '{"type":"array","array":[1,1,0,0,0,0,0,0,0,0,0,0],"highlights":[1],"hashmap":{"num":"1"},"status":"dp[1]=true (from dp[0])."}'::jsonb),
('partition-equal-subset', 5, 'Process num=5', '{"type":"array","array":[1,1,0,0,0,1,1,0,0,0,0,0],"highlights":[5,6],"hashmap":{"num":"5"},"status":"dp[5] from dp[0], dp[6] from dp[1]."}'::jsonb),
('partition-equal-subset', 6, 'Process num=11', '{"type":"array","array":[1,1,0,0,0,1,1,0,0,0,0,1],"highlights":[11],"hashmap":{"num":"11"},"status":"dp[11] becomes true via dp[0]. Target hit!"}'::jsonb),
('partition-equal-subset', 7, 'Verify partition', '{"type":"array","array":[1,5,11,5],"highlights":[2],"hashmap":{"subsetA":"[11]","subsetB":"[1,5,5]"},"status":"Partition exists: {11} and {1,5,5} each sum to 11."}'::jsonb),
('partition-equal-subset', 8, 'Answer: true', '{"type":"array","array":[1,1,0,0,0,1,1,0,0,0,0,1],"hashmap":{"answer":"true"},"status":"dp[target] true -> can partition. Time O(n*sum/2), Space O(sum)."}'::jsonb);

-- ══════════════════════════════════════════════════
-- ================ MISC (1) ========================
-- ══════════════════════════════════════════════════

-- ── interleaving-string: s1="aab", s2="axy", s3="aaxaby" (example; using smaller) ──
-- Use s1="ab", s2="cd", s3="acbd" for a 3x3 DP illustration.
DELETE FROM "PGcode_interactive_dry_runs" WHERE problem_id = 'interleaving-string';
INSERT INTO "PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('interleaving-string', 1, 'Problem Setup', '{"type":"array","array":[1,0,0,0,0,0,0,0,0],"hashmap":{"s1":"ab","s2":"cd","s3":"acbd","grid":"3x3"},"status":"Can s3 be formed by interleaving s1 and s2 preserving order? dp[i][j] = can form s3[0..i+j-1] from s1[0..i-1] + s2[0..j-1]."}'::jsonb),
('interleaving-string', 2, 'Approach: 2D boolean DP', '{"type":"array","array":[1,0,0,0,0,0,0,0,0],"hashmap":{"recurrence":"dp[i][j] = (dp[i-1][j] && s1[i-1]==s3[i+j-1]) OR (dp[i][j-1] && s2[j-1]==s3[i+j-1])"},"status":"Base dp[0][0]=true. Compare character taken from s1 or s2."}'::jsonb),
('interleaving-string', 3, 'Init row 0 and col 0', '{"type":"array","array":[1,0,0,0,0,0,0,0,0],"highlights":[0],"hashmap":{"note":"row 0: take only from s2","col 0":"take only from s1"},"status":"dp[0][0]=true. dp[0][j] true if s2[0..j-1]==s3[0..j-1]. Similar for col 0."}'::jsonb),
('interleaving-string', 4, 'Fill row 0 (use s2 only)', '{"type":"array","array":[1,0,0,0,0,0,0,0,0],"highlights":[0,1,2],"hashmap":{"s2[0]":"c","s3[0]":"a","match?":"no"},"status":"s2[0]=c != s3[0]=a so dp[0][1]=false. Everything further in row 0 stays false."}'::jsonb),
('interleaving-string', 5, 'Fill col 0 (use s1 only)', '{"type":"array","array":[1,0,0,1,0,0,0,0,0],"highlights":[3],"hashmap":{"s1[0]":"a","s3[0]":"a","match":"yes"},"status":"dp[1][0] = s1[0]==s3[0] -> true."}'::jsonb),
('interleaving-string', 6, 'Fill interior dp[1][1]', '{"type":"array","array":[1,0,0,1,1,0,0,0,0],"highlights":[4],"hashmap":{"s3[1]":"c","from_s2":"dp[1][0] && s2[0]==c -> true"},"status":"dp[1][1]=true via taking c from s2."}'::jsonb),
('interleaving-string', 7, 'Fill row 2 and col 2', '{"type":"array","array":[1,0,0,1,1,0,0,1,0],"highlights":[6,7],"hashmap":{"dp[2][0]":"ab matches a? no; but s3[1]=c != b","dp[2][1]":"true via dp[1][1]&&s1[1]==s3[2]=b"},"status":"dp[2][0] = dp[1][0] && s1[1]=b==s3[1]=c -> false. dp[2][1] = dp[1][1] && s1[1]=b==s3[2]=b -> true."}'::jsonb),
('interleaving-string', 8, 'Final dp[2][2]', '{"type":"array","array":[1,0,0,1,1,0,0,1,1],"highlights":[8],"hashmap":{"s3[3]":"d","from_s2":"dp[2][1] && s2[1]=d==d -> true"},"status":"dp[2][2]=true. s3=acbd is a valid interleaving of ab and cd."}'::jsonb),
('interleaving-string', 9, 'Answer: true', '{"type":"array","array":[1,0,0,1,1,0,0,1,1],"hashmap":{"answer":"true"},"status":"Interleaving exists: a (s1) c (s2) b (s1) d (s2). Time O(m*n), Space O(m*n) -> O(min)."}'::jsonb);

COMMIT;

SELECT problem_id, COUNT(*) AS steps FROM "PGcode_interactive_dry_runs"
WHERE problem_id IN (
  'balanced-binary-tree','binary-tree-right-side','construct-from-preorder-inorder','diameter-binary-tree',
  'kth-smallest-bst','lowest-common-ancestor','validate-bst',
  'connected-components','graph-valid-tree','redundant-connection','walls-and-gates','word-ladder',
  'accounts-merge','course-schedule-ii','min-cost-connect-points','reconstruct-itinerary',
  'coin-change-2','count-sorted-vowel-strings','decode-ways','house-robber-ii',
  'longest-palindromic-subseq','max-product-subarray','min-cost-climbing-stairs','partition-equal-subset',
  'interleaving-string'
)
GROUP BY problem_id ORDER BY problem_id;
