-- Dry runs: trees (4) + linkedlist (3)
BEGIN;

DELETE FROM public."PGcode_interactive_dry_runs" WHERE problem_id IN (
  'invert-binary-tree','max-depth-binary-tree','same-tree','subtree-of-another',
  'merge-two-sorted','linked-list-cycle','reorder-list'
);

-- ====================== TREES ======================

-- invert-binary-tree on [4,2,7,1,3,6,9]
INSERT INTO public."PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('invert-binary-tree', 1, 'Initial tree', '{"type":"tree","nodes":[{"id":"a","value":4,"state":"current"},{"id":"b","value":2,"state":"unvisited"},{"id":"c","value":7,"state":"unvisited"},{"id":"d","value":1,"state":"unvisited"},{"id":"e","value":3,"state":"unvisited"},{"id":"f","value":6,"state":"unvisited"},{"id":"g","value":9,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"c","child":"f","side":"left"},{"parent":"c","child":"g","side":"right"}],"status":"Call invert(4). Recurse on left (2) and right (7) first."}'::jsonb),
('invert-binary-tree', 2, 'Recurse into left subtree (2)', '{"type":"tree","nodes":[{"id":"a","value":4,"state":"unvisited"},{"id":"b","value":2,"state":"current"},{"id":"c","value":7,"state":"unvisited"},{"id":"d","value":1,"state":"unvisited"},{"id":"e","value":3,"state":"unvisited"},{"id":"f","value":6,"state":"unvisited"},{"id":"g","value":9,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"},{"parent":"c","child":"f","side":"left"},{"parent":"c","child":"g","side":"right"}],"status":"At node 2. Recurse left (1) and right (3); both are leaves."}'::jsonb),
('invert-binary-tree', 3, 'Swap children of node 2', '{"type":"tree","nodes":[{"id":"a","value":4,"state":"unvisited"},{"id":"b","value":2,"state":"visited"},{"id":"c","value":7,"state":"unvisited"},{"id":"d","value":1,"state":"visited"},{"id":"e","value":3,"state":"visited"},{"id":"f","value":6,"state":"unvisited"},{"id":"g","value":9,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"e","side":"left"},{"parent":"b","child":"d","side":"right"},{"parent":"c","child":"f","side":"left"},{"parent":"c","child":"g","side":"right"}],"status":"2.left and 2.right swapped: 3 is now left, 1 is now right."}'::jsonb),
('invert-binary-tree', 4, 'Recurse into right subtree (7)', '{"type":"tree","nodes":[{"id":"a","value":4,"state":"unvisited"},{"id":"b","value":2,"state":"visited"},{"id":"c","value":7,"state":"current"},{"id":"d","value":1,"state":"visited"},{"id":"e","value":3,"state":"visited"},{"id":"f","value":6,"state":"unvisited"},{"id":"g","value":9,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"e","side":"left"},{"parent":"b","child":"d","side":"right"},{"parent":"c","child":"f","side":"left"},{"parent":"c","child":"g","side":"right"}],"status":"At node 7. Recurse into children (6, 9) — both leaves."}'::jsonb),
('invert-binary-tree', 5, 'Swap children of node 7', '{"type":"tree","nodes":[{"id":"a","value":4,"state":"unvisited"},{"id":"b","value":2,"state":"visited"},{"id":"c","value":7,"state":"visited"},{"id":"d","value":1,"state":"visited"},{"id":"e","value":3,"state":"visited"},{"id":"f","value":6,"state":"visited"},{"id":"g","value":9,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"e","side":"left"},{"parent":"b","child":"d","side":"right"},{"parent":"c","child":"g","side":"left"},{"parent":"c","child":"f","side":"right"}],"status":"9 is now left, 6 is now right. Both subtrees inverted."}'::jsonb),
('invert-binary-tree', 6, 'Swap children of root (4)', '{"type":"tree","nodes":[{"id":"a","value":4,"state":"visited"},{"id":"b","value":2,"state":"visited"},{"id":"c","value":7,"state":"visited"},{"id":"d","value":1,"state":"visited"},{"id":"e","value":3,"state":"visited"},{"id":"f","value":6,"state":"visited"},{"id":"g","value":9,"state":"visited"}],"edges":[{"parent":"a","child":"c","side":"left"},{"parent":"a","child":"b","side":"right"},{"parent":"b","child":"e","side":"left"},{"parent":"b","child":"d","side":"right"},{"parent":"c","child":"g","side":"left"},{"parent":"c","child":"f","side":"right"}],"status":"Swap root 4''s children. Final order: 4,7,2,9,6,3,1."}'::jsonb);

-- max-depth-binary-tree on [3,9,20,null,null,15,7]
INSERT INTO public."PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('max-depth-binary-tree', 1, 'Start at root (3)', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"current"},{"id":"b","value":9,"state":"unvisited"},{"id":"c","value":20,"state":"unvisited"},{"id":"d","value":15,"state":"unvisited"},{"id":"e","value":7,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"depth(3)":"?"},"status":"Call depth(3) = 1 + max(depth(9), depth(20))."}'::jsonb),
('max-depth-binary-tree', 2, 'Recurse into 9', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"unvisited"},{"id":"b","value":9,"state":"current"},{"id":"c","value":20,"state":"unvisited"},{"id":"d","value":15,"state":"unvisited"},{"id":"e","value":7,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"depth(9)":"?"},"status":"9 is a leaf. depth(9) = 1 + max(0, 0) = 1."}'::jsonb),
('max-depth-binary-tree', 3, 'depth(9) = 1', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"unvisited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"unvisited"},{"id":"d","value":15,"state":"unvisited"},{"id":"e","value":7,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"depth(9)":"1"},"status":"Return 1 to caller."}'::jsonb),
('max-depth-binary-tree', 4, 'Recurse into 20', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"unvisited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"current"},{"id":"d","value":15,"state":"unvisited"},{"id":"e","value":7,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"depth(9)":"1","depth(20)":"?"},"status":"At 20. Recurse into 15 and 7."}'::jsonb),
('max-depth-binary-tree', 5, 'Leaves 15 and 7', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"unvisited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"unvisited"},{"id":"d","value":15,"state":"visited"},{"id":"e","value":7,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"depth(15)":"1","depth(7)":"1"},"status":"Both leaves return depth 1."}'::jsonb),
('max-depth-binary-tree', 6, 'depth(20) = 2', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"unvisited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"visited"},{"id":"d","value":15,"state":"visited"},{"id":"e","value":7,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"depth(9)":"1","depth(20)":"2"},"status":"1 + max(1, 1) = 2. Return 2 to root."}'::jsonb),
('max-depth-binary-tree', 7, 'depth(3) = 3', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"visited"},{"id":"b","value":9,"state":"visited"},{"id":"c","value":20,"state":"visited"},{"id":"d","value":15,"state":"visited"},{"id":"e","value":7,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"c","child":"d","side":"left"},{"parent":"c","child":"e","side":"right"}],"hashmap":{"depth(3)":"3"},"status":"1 + max(1, 2) = 3. Answer: 3."}'::jsonb);

-- same-tree: p=[1,2,3], q=[1,2,3]
INSERT INTO public."PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('same-tree', 1, 'Compare roots', '{"type":"tree","nodes":[{"id":"p","value":1,"state":"current"},{"id":"p2","value":2,"state":"unvisited"},{"id":"p3","value":3,"state":"unvisited"}],"edges":[{"parent":"p","child":"p2","side":"left"},{"parent":"p","child":"p3","side":"right"}],"hashmap":{"p.val":"1","q.val":"1"},"status":"Both p and q are non-null and p.val == q.val == 1. Recurse into children."}'::jsonb),
('same-tree', 2, 'Compare left children (2 vs 2)', '{"type":"tree","nodes":[{"id":"p","value":1,"state":"visited"},{"id":"p2","value":2,"state":"current"},{"id":"p3","value":3,"state":"unvisited"}],"edges":[{"parent":"p","child":"p2","side":"left"},{"parent":"p","child":"p3","side":"right"}],"hashmap":{"p.left.val":"2","q.left.val":"2"},"status":"Both are leaves with value 2. Match."}'::jsonb),
('same-tree', 3, 'Left subtrees return true', '{"type":"tree","nodes":[{"id":"p","value":1,"state":"visited"},{"id":"p2","value":2,"state":"visited"},{"id":"p3","value":3,"state":"unvisited"}],"edges":[{"parent":"p","child":"p2","side":"left"},{"parent":"p","child":"p3","side":"right"}],"hashmap":{"left":"true"},"status":"Left subtree comparison returns true."}'::jsonb),
('same-tree', 4, 'Compare right children (3 vs 3)', '{"type":"tree","nodes":[{"id":"p","value":1,"state":"visited"},{"id":"p2","value":2,"state":"visited"},{"id":"p3","value":3,"state":"current"}],"edges":[{"parent":"p","child":"p2","side":"left"},{"parent":"p","child":"p3","side":"right"}],"hashmap":{"p.right.val":"3","q.right.val":"3"},"status":"Both are leaves with value 3. Match."}'::jsonb),
('same-tree', 5, 'Return true', '{"type":"tree","nodes":[{"id":"p","value":1,"state":"visited"},{"id":"p2","value":2,"state":"visited"},{"id":"p3","value":3,"state":"visited"}],"edges":[{"parent":"p","child":"p2","side":"left"},{"parent":"p","child":"p3","side":"right"}],"hashmap":{"result":"true"},"status":"All comparisons succeeded. Trees are identical."}'::jsonb);

-- subtree-of-another: root=[3,4,5,1,2], subRoot=[4,1,2]
INSERT INTO public."PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('subtree-of-another', 1, 'Start at root (3)', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"current"},{"id":"b","value":4,"state":"unvisited"},{"id":"c","value":5,"state":"unvisited"},{"id":"d","value":1,"state":"unvisited"},{"id":"e","value":2,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"hashmap":{"target":"[4,1,2]"},"status":"Check sameTree(3, 4)? 3 != 4 — fail. Recurse into left and right."}'::jsonb),
('subtree-of-another', 2, 'Try from node 4', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"visited"},{"id":"b","value":4,"state":"current"},{"id":"c","value":5,"state":"unvisited"},{"id":"d","value":1,"state":"unvisited"},{"id":"e","value":2,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"hashmap":{"checking":"sameTree(4,4)"},"status":"Roots match (4 == 4). Compare children."}'::jsonb),
('subtree-of-another', 3, 'Compare left children (1 vs 1)', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"visited"},{"id":"b","value":4,"state":"current"},{"id":"c","value":5,"state":"unvisited"},{"id":"d","value":1,"state":"current"},{"id":"e","value":2,"state":"unvisited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"hashmap":{"checking":"1 == 1"},"status":"Both 1 leaves. Match."}'::jsonb),
('subtree-of-another', 4, 'Compare right children (2 vs 2)', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"visited"},{"id":"b","value":4,"state":"current"},{"id":"c","value":5,"state":"unvisited"},{"id":"d","value":1,"state":"visited"},{"id":"e","value":2,"state":"current"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"hashmap":{"checking":"2 == 2"},"status":"Both 2 leaves. Match."}'::jsonb),
('subtree-of-another', 5, 'Match found — return true', '{"type":"tree","nodes":[{"id":"a","value":3,"state":"visited"},{"id":"b","value":4,"state":"visited"},{"id":"c","value":5,"state":"unvisited"},{"id":"d","value":1,"state":"visited"},{"id":"e","value":2,"state":"visited"}],"edges":[{"parent":"a","child":"b","side":"left"},{"parent":"a","child":"c","side":"right"},{"parent":"b","child":"d","side":"left"},{"parent":"b","child":"e","side":"right"}],"hashmap":{"result":"true"},"status":"Subtree matches. Return true."}'::jsonb);

-- ====================== LINKEDLIST ======================

-- merge-two-sorted: list1=[1,2,4], list2=[1,3,4]
INSERT INTO public."PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('merge-two-sorted', 1, 'Initialize dummy + tail', '{"type":"linked-list","nodes":[{"value":1,"state":"current"},{"value":2,"state":"default"},{"value":4,"state":"default"}],"pointers":{"l1":0},"hashmap":{"list2":"[1,3,4]","tail":"dummy"},"status":"Compare list1[0]=1 and list2[0]=1. Equal — pick list1 first."}'::jsonb),
('merge-two-sorted', 2, 'Append 1 from list1', '{"type":"linked-list","nodes":[{"value":1,"state":"visited"},{"value":2,"state":"current"},{"value":4,"state":"default"}],"pointers":{"l1":1},"hashmap":{"result":"1","l2":"[1,3,4]","l2_idx":"0"},"status":"Advance l1. tail now points to 1."}'::jsonb),
('merge-two-sorted', 3, 'Append 1 from list2', '{"type":"linked-list","nodes":[{"value":1,"state":"visited"},{"value":2,"state":"current"},{"value":4,"state":"default"}],"pointers":{"l1":1},"hashmap":{"result":"1 -> 1","l2":"[3,4]","l2_idx":"1"},"status":"list2[0]=1 < list1[1]=2. Append 1 from list2."}'::jsonb),
('merge-two-sorted', 4, 'Append 2 from list1', '{"type":"linked-list","nodes":[{"value":1,"state":"visited"},{"value":2,"state":"visited"},{"value":4,"state":"current"}],"pointers":{"l1":2},"hashmap":{"result":"1 -> 1 -> 2","l2_idx":"1"},"status":"list1[1]=2 < list2[1]=3. Append 2."}'::jsonb),
('merge-two-sorted', 5, 'Append 3 from list2', '{"type":"linked-list","nodes":[{"value":1,"state":"visited"},{"value":2,"state":"visited"},{"value":4,"state":"current"}],"pointers":{"l1":2},"hashmap":{"result":"1 -> 1 -> 2 -> 3","l2_idx":"2"},"status":"list2[1]=3 < list1[2]=4. Append 3."}'::jsonb),
('merge-two-sorted', 6, 'Append 4 from list1', '{"type":"linked-list","nodes":[{"value":1,"state":"visited"},{"value":2,"state":"visited"},{"value":4,"state":"visited"}],"pointers":{"l1":3},"hashmap":{"result":"1 -> 1 -> 2 -> 3 -> 4","l2_idx":"2"},"status":"Equal — pick list1 first. Advance l1 past end."}'::jsonb),
('merge-two-sorted', 7, 'Splice remaining tail from list2', '{"type":"linked-list","nodes":[{"value":1,"state":"visited"},{"value":2,"state":"visited"},{"value":4,"state":"visited"}],"pointers":{},"hashmap":{"result":"1 -> 1 -> 2 -> 3 -> 4 -> 4","done":"true"},"status":"list1 exhausted. Splice list2''s remaining 4 onto tail. Final list: 1->1->2->3->4->4."}'::jsonb);

-- linked-list-cycle: [3,2,0,-4] with cycle at index 1
INSERT INTO public."PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('linked-list-cycle', 1, 'Start slow and fast at head', '{"type":"linked-list","nodes":[{"value":3,"state":"current"},{"value":2,"state":"default"},{"value":0,"state":"default"},{"value":-4,"state":"default"}],"pointers":{"slow":0,"fast":0},"hashmap":{"cycle_at":"index 1"},"status":"Both pointers at index 0."}'::jsonb),
('linked-list-cycle', 2, 'Step 1: slow +1, fast +2', '{"type":"linked-list","nodes":[{"value":3,"state":"visited"},{"value":2,"state":"current"},{"value":0,"state":"default"},{"value":-4,"state":"default"}],"pointers":{"slow":1,"fast":2},"hashmap":{},"status":"slow at 1, fast at 2. Not equal."}'::jsonb),
('linked-list-cycle', 3, 'Step 2', '{"type":"linked-list","nodes":[{"value":3,"state":"visited"},{"value":2,"state":"default"},{"value":0,"state":"current"},{"value":-4,"state":"default"}],"pointers":{"slow":2,"fast":1},"hashmap":{"note":"fast wraps via cycle"},"status":"slow at 2, fast at -4 then wraps back to 2 (index 1). Not equal yet."}'::jsonb),
('linked-list-cycle', 4, 'Step 3', '{"type":"linked-list","nodes":[{"value":3,"state":"visited"},{"value":2,"state":"default"},{"value":0,"state":"default"},{"value":-4,"state":"current"}],"pointers":{"slow":3,"fast":3},"hashmap":{},"status":"slow advances from 2 to -4 (index 3). fast advances from index 1 to -4 (index 3). They meet!"}'::jsonb),
('linked-list-cycle', 5, 'Cycle detected — return true', '{"type":"linked-list","nodes":[{"value":3,"state":"visited"},{"value":2,"state":"visited"},{"value":0,"state":"visited"},{"value":-4,"state":"visited"}],"pointers":{"slow":3,"fast":3},"hashmap":{"result":"true"},"status":"slow == fast inside the cycle. A cycle exists."}'::jsonb);

-- reorder-list: [1,2,3,4]
INSERT INTO public."PGcode_interactive_dry_runs" (problem_id, step_number, title, visual_state_data) VALUES
('reorder-list', 1, 'Original list', '{"type":"linked-list","nodes":[{"value":1,"state":"default"},{"value":2,"state":"default"},{"value":3,"state":"default"},{"value":4,"state":"default"}],"pointers":{"head":0},"hashmap":{"goal":"L0->Ln->L1->Ln-1->..."},"status":"Three phases: find middle, reverse second half, interleave."}'::jsonb),
('reorder-list', 2, 'Find middle via slow/fast', '{"type":"linked-list","nodes":[{"value":1,"state":"visited"},{"value":2,"state":"current"},{"value":3,"state":"default"},{"value":4,"state":"default"}],"pointers":{"slow":1,"fast":3},"hashmap":{},"status":"slow stops at index 1 (value 2). Second half starts at slow.next = index 2."}'::jsonb),
('reorder-list', 3, 'Split list at middle', '{"type":"linked-list","nodes":[{"value":1,"state":"default"},{"value":2,"state":"default"},{"value":3,"state":"highlighted"},{"value":4,"state":"highlighted"}],"pointers":{"first":0,"second_start":2},"hashmap":{"first_half":"1 -> 2","second_half":"3 -> 4"},"status":"Cut slow.next = null. Now two halves: [1,2] and [3,4]."}'::jsonb),
('reorder-list', 4, 'Reverse second half [3,4] -> [4,3]', '{"type":"linked-list","nodes":[{"value":1,"state":"default"},{"value":2,"state":"default"},{"value":4,"state":"highlighted"},{"value":3,"state":"highlighted"}],"pointers":{"first":0,"second":2},"hashmap":{"first_half":"1 -> 2","second_half":"4 -> 3"},"status":"Second half reversed in place using prev/curr walk."}'::jsonb),
('reorder-list', 5, 'Interleave: 1 -> 4', '{"type":"linked-list","nodes":[{"value":1,"state":"visited"},{"value":4,"state":"visited"},{"value":2,"state":"current"},{"value":3,"state":"highlighted"}],"pointers":{"first":2,"second":3},"hashmap":{"result":"1 -> 4 -> ..."},"status":"Splice 4 after 1 using t1 = first.next, t2 = second.next."}'::jsonb),
('reorder-list', 6, 'Interleave: 2 -> 3', '{"type":"linked-list","nodes":[{"value":1,"state":"visited"},{"value":4,"state":"visited"},{"value":2,"state":"visited"},{"value":3,"state":"visited"}],"pointers":{},"hashmap":{"result":"1 -> 4 -> 2 -> 3","done":"true"},"status":"Splice 3 after 2. Final list: 1 -> 4 -> 2 -> 3."}'::jsonb);

COMMIT;

SELECT problem_id, COUNT(*) AS steps FROM public."PGcode_interactive_dry_runs"
WHERE problem_id IN ('invert-binary-tree','max-depth-binary-tree','same-tree','subtree-of-another','merge-two-sorted','linked-list-cycle','reorder-list')
GROUP BY problem_id ORDER BY problem_id;
