-- Auto-generated by scripts/seed-cpp-templates.mjs
-- C++ starter templates for every problem with method_name + params metadata.
-- Safe to re-run: ON CONFLICT updates in place.

INSERT INTO public."PGcode_problem_templates" (problem_id, language, code) VALUES
  ('longest-consecutive', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int longestConsecutive(vector<int>& nums) {
        
    }
};$CPP$),
  ('product-except-self', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> productExceptSelf(vector<int>& nums) {
        
    }
};$CPP$),
  ('length-of-last-word', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int lengthOfLastWord(string& s) {
        
    }
};$CPP$),
  ('linked-list-cycle', 'cpp', $CPP$/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool hasCycle(ListNode* head, int pos) {
        
    }
};$CPP$),
  ('clone-graph', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> cloneGraph(vector<vector<int>>& adjList) {
        
    }
};$CPP$),
  ('remove-duplicates-sorted', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int removeDuplicates(vector<int>& nums) {
        
    }
};$CPP$),
  ('longest-common-prefix', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string longestCommonPrefix(vector<string>& strs) {
        
    }
};$CPP$),
  ('roman-to-integer', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int romanToInt(string& s) {
        
    }
};$CPP$),
  ('find-needle-haystack', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int strStr(string& haystack, string& needle) {
        
    }
};$CPP$),
  ('search-rotated', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int search(vector<int>& nums, int target) {
        
    }
};$CPP$),
  ('implement-trie', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    List Trie(List[List] operations) {
        
    }
};$CPP$),
  ('design-add-search', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    List WordDictionary(List[List] operations) {
        
    }
};$CPP$),
  ('lowest-common-ancestor', 'cpp', $CPP$/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int lowestCommonAncestor(TreeNode* root, int p, int q) {
        
    }
};$CPP$),
  ('reverse-words-in-string', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string reverseWords(string& s) {
        
    }
};$CPP$),
  ('group-anagrams', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<string>> groupAnagrams(vector<string>& strs) {
        
    }
};$CPP$),
  ('alien-dictionary', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string alienOrder(vector<string>& words) {
        
    }
};$CPP$),
  ('rotate-image', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> rotate(vector<vector<int>>& matrix) {
        
    }
};$CPP$),
  ('palindromic-substrings', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int countSubstrings(string& s) {
        
    }
};$CPP$),
  ('set-matrix-zeroes', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> setZeroes(vector<vector<int>>& matrix) {
        
    }
};$CPP$),
  ('reorder-list', 'cpp', $CPP$/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    ListNode* reorderList(ListNode* head) {
        
    }
};$CPP$),
  ('walls-and-gates', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> wallsAndGates(vector<vector<int>>& rooms) {
        
    }
};$CPP$),
  ('climbing-stairs', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int climbStairs(int n) {
        
    }
};$CPP$),
  ('house-robber', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int rob(vector<int>& nums) {
        
    }
};$CPP$),
  ('subsets', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> subsets(vector<int>& nums) {
        
    }
};$CPP$),
  ('kth-largest-element', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int findKthLargest(vector<int>& nums, int k) {
        
    }
};$CPP$),
  ('encode-decode-strings', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<string> solve(vector<string>& strs) {
        
    }
};$CPP$),
  ('two-sum', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        
    }
};$CPP$),
  ('combination-sum', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> combinationSum(vector<int>& candidates, int target) {
        
    }
};$CPP$),
  ('max-subarray', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int maxSubArray(vector<int>& nums) {
        
    }
};$CPP$),
  ('num-islands', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int numIslands(vector<vector<string>>& grid) {
        
    }
};$CPP$),
  ('trapping-rain-water', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int trap(vector<int>& height) {
        
    }
};$CPP$),
  ('word-search', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool exist(vector<vector<string>>& board, string& word) {
        
    }
};$CPP$),
  ('happy-number', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isHappy(int n) {
        
    }
};$CPP$),
  ('graph-valid-tree', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool validTree(int n, vector<vector<int>>& edges) {
        
    }
};$CPP$),
  ('string-to-integer-atoi', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int myAtoi(string& s) {
        
    }
};$CPP$),
  ('add-binary', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string addBinary(string& a, string& b) {
        
    }
};$CPP$),
  ('count-and-say', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string countAndSay(int n) {
        
    }
};$CPP$),
  ('spiral-matrix', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> spiralOrder(vector<vector<int>>& matrix) {
        
    }
};$CPP$),
  ('container-most-water', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int maxArea(vector<int>& height) {
        
    }
};$CPP$),
  ('min-stack', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    List MinStack(List[List] operations) {
        
    }
};$CPP$),
  ('eval-rpn', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int evalRPN(vector<string>& tokens) {
        
    }
};$CPP$),
  ('daily-temperatures', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> dailyTemperatures(vector<int>& temperatures) {
        
    }
};$CPP$),
  ('largest-rect-histogram', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int largestRectangleArea(vector<int>& heights) {
        
    }
};$CPP$),
  ('longest-palindromic-substring', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string longestPalindrome(string& s) {
        
    }
};$CPP$),
  ('move-zeroes', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> moveZeroes(vector<int>& nums) {
        
    }
};$CPP$),
  ('reverse-linked-list', 'cpp', $CPP$/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    ListNode* reverseList(ListNode* head) {
        
    }
};$CPP$),
  ('meeting-rooms', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int minMeetingRooms(vector<vector<int>>& intervals) {
        
    }
};$CPP$),
  ('sort-colors', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> sortColors(vector<int>& nums) {
        
    }
};$CPP$),
  ('connected-components', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int countComponents(int n, vector<vector<int>>& edges) {
        
    }
};$CPP$),
  ('redundant-connection', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> findRedundantConnection(vector<vector<int>>& edges) {
        
    }
};$CPP$),
  ('squares-sorted-array', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> sortedSquares(vector<int>& nums) {
        
    }
};$CPP$),
  ('is-subsequence', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isSubsequence(string& s, string& t) {
        
    }
};$CPP$),
  ('longest-repeating-char', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int characterReplacement(string& s, int k) {
        
    }
};$CPP$),
  ('longest-substr-no-repeat', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int lengthOfLongestSubstring(string& s) {
        
    }
};$CPP$),
  ('min-window-substring', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string minWindow(string& s, string& t) {
        
    }
};$CPP$),
  ('permutation-in-string', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool checkInclusion(string& s1, string& s2) {
        
    }
};$CPP$),
  ('car-fleet', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int carFleet(int target, vector<int>& position, vector<int>& speed) {
        
    }
};$CPP$),
  ('top-k-frequent', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> topKFrequent(vector<int>& nums, int k) {
        
    }
};$CPP$),
  ('merge-two-sorted', 'cpp', $CPP$/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    ListNode* mergeTwoLists(ListNode* list1, ListNode* list2) {
        
    }
};$CPP$),
  ('max-depth-binary-tree', 'cpp', $CPP$/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int maxDepth(TreeNode* root) {
        
    }
};$CPP$),
  ('same-tree', 'cpp', $CPP$/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isSameTree(TreeNode* p, TreeNode* q) {
        
    }
};$CPP$),
  ('subtree-of-another', 'cpp', $CPP$/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isSubtree(TreeNode* root, TreeNode* subRoot) {
        
    }
};$CPP$),
  ('level-order-traversal', 'cpp', $CPP$/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> levelOrder(TreeNode* root) {
        
    }
};$CPP$),
  ('word-search-ii', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<string> findWords(vector<vector<string>>& board, vector<string>& words) {
        
    }
};$CPP$),
  ('pacific-atlantic', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> pacificAtlantic(vector<vector<int>>& heights) {
        
    }
};$CPP$),
  ('valid-anagram', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isAnagram(string& s, string& t) {
        
    }
};$CPP$),
  ('gas-station', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {
        
    }
};$CPP$),
  ('task-scheduler', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int leastInterval(vector<string>& tasks, int n) {
        
    }
};$CPP$),
  ('insert-interval', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> insert(vector<vector<int>>& intervals, vector<int>& newInterval) {
        
    }
};$CPP$),
  ('merge-intervals', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> merge(vector<vector<int>>& intervals) {
        
    }
};$CPP$),
  ('non-overlapping-intervals', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int eraseOverlapIntervals(vector<vector<int>>& intervals) {
        
    }
};$CPP$),
  ('invert-binary-tree', 'cpp', $CPP$/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    TreeNode* invertTree(TreeNode* root) {
        
    }
};$CPP$),
  ('jump-game', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool canJump(vector<int>& nums) {
        
    }
};$CPP$),
  ('hand-of-straights', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isNStraightHand(vector<int>& hand, int groupSize) {
        
    }
};$CPP$),
  ('find-min-rotated', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int findMin(vector<int>& nums) {
        
    }
};$CPP$),
  ('three-sum', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> threeSum(vector<int>& nums) {
        
    }
};$CPP$),
  ('koko-bananas', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int minEatingSpeed(vector<int>& piles, int h) {
        
    }
};$CPP$),
  ('best-time-to-buy-sell-stock', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int maxProfit(vector<int>& prices) {
        
    }
};$CPP$),
  ('valid-parentheses', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isValid(string& s) {
        
    }
};$CPP$),
  ('search-2d-matrix', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool searchMatrix(vector<vector<int>>& matrix, int target) {
        
    }
};$CPP$),
  ('last-stone-weight', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int lastStoneWeight(vector<int>& stones) {
        
    }
};$CPP$),
  ('permutations', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> permute(vector<int>& nums) {
        
    }
};$CPP$),
  ('longest-increasing-subseq', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int lengthOfLIS(vector<int>& nums) {
        
    }
};$CPP$),
  ('word-break', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool wordBreak(string& s, vector<string>& wordDict) {
        
    }
};$CPP$),
  ('unique-paths', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int uniquePaths(int m, int n) {
        
    }
};$CPP$),
  ('edit-distance', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int minDistance(string& word1, string& word2) {
        
    }
};$CPP$),
  ('target-sum', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int findTargetSumWays(vector<int>& nums, int target) {
        
    }
};$CPP$),
  ('course-schedule', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool canFinish(int numCourses, vector<vector<int>>& prerequisites) {
        
    }
};$CPP$),
  ('rotting-oranges', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int orangesRotting(vector<vector<int>>& grid) {
        
    }
};$CPP$),
  ('swim-in-water', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int swimInWater(vector<vector<int>>& grid) {
        
    }
};$CPP$),
  ('cheapest-flights', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int findCheapestPrice(int n, vector<vector<int>>& flights, int src, int dst, int k) {
        
    }
};$CPP$),
  ('single-number', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int singleNumber(vector<int>& nums) {
        
    }
};$CPP$),
  ('counting-bits', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> countBits(int n) {
        
    }
};$CPP$),
  ('two-sum-ii', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> twoSum(vector<int>& numbers, int target) {
        
    }
};$CPP$),
  ('coin-change', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int coinChange(vector<int>& coins, int amount) {
        
    }
};$CPP$),
  ('k-closest-points', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> kClosest(vector<vector<int>>& points, int k) {
        
    }
};$CPP$),
  ('valid-sudoku', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isValidSudoku(vector<vector<string>>& board) {
        
    }
};$CPP$),
  ('majority-element', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int majorityElement(vector<int>& nums) {
        
    }
};$CPP$),
  ('missing-number', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int missingNumber(vector<int>& nums) {
        
    }
};$CPP$),
  ('pascals-triangle', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> generate(int numRows) {
        
    }
};$CPP$),
  ('interleaving-string', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isInterleave(string& s1, string& s2, string& s3) {
        
    }
};$CPP$),
  ('implement-queue-stacks', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    List MyQueue(List[List] operations) {
        
    }
};$CPP$),
  ('sliding-window-maximum', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> maxSlidingWindow(vector<int>& nums, int k) {
        
    }
};$CPP$),
  ('number-recent-calls', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    List RecentCounter(List[List] operations) {
        
    }
};$CPP$),
  ('dota2-senate', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string predictPartyVictory(string& senate) {
        
    }
};$CPP$),
  ('find-median-data-stream', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    List MedianFinder(List[List] operations) {
        
    }
};$CPP$),
  ('moving-average', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    List MovingAverage(List[List] operations) {
        
    }
};$CPP$),
  ('word-ladder', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int ladderLength(string& beginWord, string& endWord, vector<string>& wordList) {
        
    }
};$CPP$),
  ('design-circular-queue', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    List MyCircularQueue(List[List] operations) {
        
    }
};$CPP$),
  ('valid-palindrome-ii', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool validPalindrome(string& s) {
        
    }
};$CPP$),
  ('top-k-frequent-words', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<string> topKFrequent(vector<string>& words, int k) {
        
    }
};$CPP$),
  ('reorganize-string', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string reorganizeString(string& s) {
        
    }
};$CPP$),
  ('sort-characters-by-frequency', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string frequencySort(string& s) {
        
    }
};$CPP$),
  ('decode-string', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string decodeString(string& s) {
        
    }
};$CPP$),
  ('contains-duplicate', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool containsDuplicate(vector<int>& nums) {
        
    }
};$CPP$),
  ('asteroid-collision', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> asteroidCollision(vector<int>& asteroids) {
        
    }
};$CPP$),
  ('valid-palindrome', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isPalindrome(string& s) {
        
    }
};$CPP$),
  ('remove-all-adjacent-duplicates', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string removeDuplicates(string& s) {
        
    }
};$CPP$),
  ('remove-nth-from-end', 'cpp', $CPP$/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    ListNode* removeNthFromEnd(ListNode* head, int n) {
        
    }
};$CPP$),
  ('add-two-numbers', 'cpp', $CPP$/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
        
    }
};$CPP$),
  ('swap-nodes-pairs', 'cpp', $CPP$/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    ListNode* swapPairs(ListNode* head) {
        
    }
};$CPP$),
  ('merge-k-sorted-lists', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> mergeKLists(vector<vector<int>>& lists) {
        
    }
};$CPP$),
  ('lru-cache', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    List LRUCache(List[List] operations) {
        
    }
};$CPP$),
  ('longest-word-dictionary', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string longestWord(vector<string>& words) {
        
    }
};$CPP$),
  ('search-suggestions-system', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<string>> suggestedProducts(vector<string>& products, string& searchWord) {
        
    }
};$CPP$),
  ('fibonacci-number', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int fib(int n) {
        
    }
};$CPP$),
  ('pow-x-n', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    double myPow(double x, int n) {
        
    }
};$CPP$),
  ('reverse-string', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<string> reverseString(vector<string>& s) {
        
    }
};$CPP$),
  ('merge-sort-array', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> sortArray(vector<int>& nums) {
        
    }
};$CPP$),
  ('generate-parentheses', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<string> generateParenthesis(int n) {
        
    }
};$CPP$),
  ('flatten-nested-list-iterator', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> flatten(List nestedList) {
        
    }
};$CPP$),
  ('decode-ways', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int numDecodings(string& s) {
        
    }
};$CPP$),
  ('partition-equal-subset', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool canPartition(vector<int>& nums) {
        
    }
};$CPP$),
  ('min-cost-climbing-stairs', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int minCostClimbingStairs(vector<int>& cost) {
        
    }
};$CPP$),
  ('house-robber-ii', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int rob(vector<int>& nums) {
        
    }
};$CPP$),
  ('remove-element', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> removeElement(vector<int>& nums, int val) {
        
    }
};$CPP$),
  ('binary-search', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int search(vector<int>& nums, int target) {
        
    }
};$CPP$),
  ('time-based-key-value', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    List TimeMap(List[List] operations) {
        
    }
};$CPP$),
  ('median-two-sorted', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {
        
    }
};$CPP$),
  ('first-last-position', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> searchRange(vector<int>& nums, int target) {
        
    }
};$CPP$),
  ('max-consecutive-ones-iii', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int longestOnes(vector<int>& nums, int k) {
        
    }
};$CPP$),
  ('fruit-into-baskets', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int totalFruit(vector<int>& fruits) {
        
    }
};$CPP$),
  ('minimum-size-subarray', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int minSubArrayLen(int target, vector<int>& nums) {
        
    }
};$CPP$),
  ('longest-common-subseq', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int longestCommonSubsequence(string& text1, string& text2) {
        
    }
};$CPP$),
  ('subarray-product-less-than-k', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int numSubarrayProductLessThanK(vector<int>& nums, int k) {
        
    }
};$CPP$),
  ('max-product-subarray', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int maxProduct(vector<int>& nums) {
        
    }
};$CPP$),
  ('longest-palindromic-subseq', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int longestPalindromeSubseq(string& s) {
        
    }
};$CPP$),
  ('jump-game-ii', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int jump(vector<int>& nums) {
        
    }
};$CPP$),
  ('network-delay', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int networkDelayTime(vector<vector<int>>& times, int n, int k) {
        
    }
};$CPP$),
  ('validate-bst', 'cpp', $CPP$/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isValidBST(TreeNode* root) {
        
    }
};$CPP$),
  ('kth-smallest-bst', 'cpp', $CPP$/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int kthSmallest(TreeNode* root, int k) {
        
    }
};$CPP$),
  ('construct-from-preorder-inorder', 'cpp', $CPP$/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    TreeNode* buildTree(vector<int>& preorder, vector<int>& inorder) {
        
    }
};$CPP$),
  ('binary-tree-right-side', 'cpp', $CPP$/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> rightSideView(TreeNode* root) {
        
    }
};$CPP$),
  ('diameter-binary-tree', 'cpp', $CPP$/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int diameterOfBinaryTree(TreeNode* root) {
        
    }
};$CPP$),
  ('number-of-1-bits', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int hammingWeight(int n) {
        
    }
};$CPP$),
  ('letter-combinations', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<string> letterCombinations(string& digits) {
        
    }
};$CPP$),
  ('n-queens', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int totalNQueens(int n) {
        
    }
};$CPP$),
  ('palindrome-partitioning', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<string>> partition(string& s) {
        
    }
};$CPP$),
  ('combination-sum-ii', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> combinationSum2(vector<int>& candidates, int target) {
        
    }
};$CPP$),
  ('partition-labels', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> partitionLabels(string& s) {
        
    }
};$CPP$),
  ('valid-parenthesis-string', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool checkValidString(string& s) {
        
    }
};$CPP$),
  ('minimum-number-of-platforms', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int findPlatform(vector<int>& arrival, vector<int>& departure) {
        
    }
};$CPP$),
  ('meeting-rooms-i', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool canAttendMeetings(vector<vector<int>>& intervals) {
        
    }
};$CPP$),
  ('minimum-arrows', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int findMinArrowShots(vector<vector<int>>& points) {
        
    }
};$CPP$),
  ('interval-list-intersections', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> intervalIntersection(vector<vector<int>>& firstList, vector<vector<int>>& secondList) {
        
    }
};$CPP$),
  ('balanced-binary-tree', 'cpp', $CPP$/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isBalanced(TreeNode* root) {
        
    }
};$CPP$),
  ('distinct-subsequences', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int numDistinct(string& s, string& t) {
        
    }
};$CPP$),
  ('burst-balloons', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int maxCoins(vector<int>& nums) {
        
    }
};$CPP$),
  ('coin-change-2', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int change(int amount, vector<int>& coins) {
        
    }
};$CPP$),
  ('regular-expression-matching', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isMatch(string& s, string& p) {
        
    }
};$CPP$),
  ('power-of-three', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isPowerOfThree(int n) {
        
    }
};$CPP$),
  ('reconstruct-itinerary', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<string> findItinerary(vector<vector<string>>& tickets) {
        
    }
};$CPP$),
  ('min-cost-connect-points', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int minCostConnectPoints(vector<vector<int>>& points) {
        
    }
};$CPP$),
  ('course-schedule-ii', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> findOrder(int numCourses, vector<vector<int>>& prerequisites) {
        
    }
};$CPP$),
  ('accounts-merge', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<string>> accountsMerge(vector<vector<string>>& accounts) {
        
    }
};$CPP$),
  ('plus-one', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> plusOne(vector<int>& digits) {
        
    }
};$CPP$),
  ('integer-to-roman', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string intToRoman(int num) {
        
    }
};$CPP$),
  ('multiply-strings', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string multiply(string& num1, string& num2) {
        
    }
};$CPP$),
  ('sum-of-two-integers', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int getSum(int a, int b) {
        
    }
};$CPP$),
  ('missing-number-xor', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int missingNumber(vector<int>& nums) {
        
    }
};$CPP$),
  ('reverse-integer', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int reverse(int x) {
        
    }
};$CPP$),
  ('power-of-two', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isPowerOfTwo(int n) {
        
    }
};$CPP$),
  ('valid-square', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool validSquare(vector<int>& p1, vector<int>& p2, vector<int>& p3, vector<int>& p4) {
        
    }
};$CPP$),
  ('max-points-on-line', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int maxPoints(vector<vector<int>>& points) {
        
    }
};$CPP$),
  ('interval-scheduling-maximization', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int maxEvents(vector<vector<int>>& intervals) {
        
    }
};$CPP$),
  ('rectangle-overlap', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isRectangleOverlap(vector<int>& rec1, vector<int>& rec2) {
        
    }
};$CPP$),
  ('k-closest-origin', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> kClosest(vector<vector<int>>& points, int k) {
        
    }
};$CPP$),
  ('minimum-area-rectangle', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int minAreaRect(vector<vector<int>>& points) {
        
    }
};$CPP$),
  ('rotate-array', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> rotate(vector<int>& nums, int k) {
        
    }
};$CPP$),
  ('implement-stack-queues', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    List MyStack(List[List] operations) {
        
    }
};$CPP$),
  ('power-set-iterative', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<int>> subsets(vector<int>& nums) {
        
    }
};$CPP$),
  ('climbing-stairs-k', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int climbStairs(int n, int k) {
        
    }
};$CPP$),
  ('replace-words', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string replaceWords(vector<string>& dictionary, string& sentence) {
        
    }
};$CPP$),
  ('check-if-straight-line', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool checkStraightLine(vector<vector<int>>& coordinates) {
        
    }
};$CPP$),
  ('longest-subarray-ones-deletion', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int longestSubarray(vector<int>& nums) {
        
    }
};$CPP$),
  ('count-sorted-vowel-strings', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int countVowelStrings(int n) {
        
    }
};$CPP$),
  ('remove-k-digits', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string removeKdigits(string& num, int k) {
        
    }
};$CPP$),
  ('next-greater-element', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<int> nextGreaterElement(vector<int>& nums1, vector<int>& nums2) {
        
    }
};$CPP$),
  ('longest-happy-string', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    string longestDiverseString(int a, int b, int c) {
        
    }
};$CPP$),
  ('reverse-bits', 'cpp', $CPP$#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    int reverseBits(int n) {
        
    }
};$CPP$)
ON CONFLICT (problem_id, language) DO UPDATE SET code = EXCLUDED.code;
