#!/usr/bin/env node
// Regenerates /blog/feed.xml (RSS 2.0).
//
//     node scripts/generate-feed.mjs
//
// Run it — and commit the result — whenever an essay is added or retitled. The
// POSTS list below is the same set that lives in blog/blog.js and the static
// list in blog/index.html; all three have to agree.
//
// Why a feed at all: it is the one discovery channel a static blog can offer
// that does not depend on Google. Readers subscribe, aggregators pick posts up,
// and <link rel="alternate"> on the index tells browsers and crawlers it exists.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://pushkalgupta.com';

const POSTS = [
  {
    slug: 'ai-and-the-lions-cage',
    title: "AI and the Lion's Cage — The Last Tool We Build",
    date: '2026-03-11',
    description:
      'Humans never beat lions on strength — we beat them with tools. AI is the first tool that improves itself, which is why it breaks the old pattern.',
  },
  {
    slug: 'the-architecture-of-power',
    title: 'The Architecture of Power — How Society Actually Works',
    date: '2026-04-08',
    description:
      'Why does hierarchy work? Not who sits at the top, but how millions of people organise into layers where some give orders and it all feels natural.',
  },
  {
    slug: 'why-work-matters-in-the-age-of-ai',
    title: 'The Golden Cage — Why Work Matters in the Age of AI',
    date: '2026-04-27',
    description:
      'A perfect cage where every want is met and no effort is allowed — and what it reveals about why work and contact with other minds are not optional.',
  },
  {
    slug: 'does-ai-actually-think',
    title: 'Does AI Actually Think — Why Architecture Matters More Than Data',
    date: '2026-05-18',
    description:
      'Your brain recognises a hummed melody in milliseconds on 20 watts. Energy-based models explain why that is architecture, not data scale.',
  },
  {
    slug: 'the-one-way-mind',
    title: 'The One-Way Mind — Why AI Imitates Understanding',
    date: '2026-06-29',
    description:
      'A model names Tom Cruise’s mother, then fails to name her son. The reversal curse shows language models learn directions, not facts.',
  },
];

const esc = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// RSS wants RFC-822. Noon UTC, so no reader's timezone shifts the date a day.
const rfc822 = (d) => new Date(`${d}T12:00:00Z`).toUTCString();

const newest = POSTS.reduce((a, b) => (a.date > b.date ? a : b));

const items = [...POSTS]
  .sort((a, b) => b.date.localeCompare(a.date))
  .map(
    (p) => `    <item>
      <title>${esc(p.title)}</title>
      <link>${ORIGIN}/blog/${p.slug}/</link>
      <guid isPermaLink="true">${ORIGIN}/blog/${p.slug}/</guid>
      <pubDate>${rfc822(p.date)}</pubDate>
      <description>${esc(p.description)}</description>
    </item>`,
  )
  .join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-feed.mjs — do not edit by hand. -->
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>PG.Blog — Pushkal Gupta</title>
    <link>${ORIGIN}/blog/</link>
    <atom:link href="${ORIGIN}/blog/feed.xml" rel="self" type="application/rss+xml" />
    <description>Essays on artificial intelligence, power, and how systems actually work — argued from first principles.</description>
    <language>en</language>
    <lastBuildDate>${rfc822(newest.date)}</lastBuildDate>
${items}
  </channel>
</rss>
`;

writeFileSync(resolve(ROOT, 'blog/feed.xml'), xml);
console.log(`blog/feed.xml written — ${POSTS.length} items`);
