#!/usr/bin/env node
// Regenerates /sitemap.xml.
//
// Run it (and commit the result) whenever a page is added, removed or renamed:
//
//     node scripts/generate-sitemap.mjs
//
// The site is static GitHub Pages, so the sitemap is a committed file rather
// than something generated at request time. `lastmod` comes from each page's
// last commit date — that is what Google actually wants (when the *content*
// changed), and it beats stamping today's date on every URL, which trains the
// crawler to ignore the field.
//
// Only canonical, indexable URLs belong here. Anything carrying `noindex` or a
// canonical pointing elsewhere (the light-theme essay twins) is deliberately
// absent: listing a URL you also tell Google not to index is a contradiction it
// reports as a Search Console warning. The homepage is /PG/main.html (the root
// `/` only redirects there), so we list the real page, not the redirect.

import { execFileSync } from 'node:child_process';
import { writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://pushkalgupta.com';

// [ url path, file whose git history dates it, changefreq, priority ]
const PAGES = [
  ['/PG/main.html',                               'PG/main.html',                                     'weekly',  '1.0'],

  // Apps. These are hash-routed single-page apps, so every in-app route lives
  // behind a `#` and cannot be listed separately — one URL each is all Google
  // can index today. See docs/SEO.md for what it would take to change that.
  ['/PGHub/dist/',                                'PGHub/index.html',                                 'weekly',  '0.9'],
  ['/PG.Play/dist/',                              'PG.Play/index.html',                               'weekly',  '0.9'],
  ['/onlineChess/dist/',                          'onlineChess/index.html',                           'weekly',  '0.9'],

  // Blog.
  ['/blog/',                                      'blog/index.html',                                  'weekly',  '0.9'],
  ['/blog/ai-and-the-lions-cage/',                'blog/ai-and-the-lions-cage/index.html',            'yearly',  '0.8'],
  ['/blog/the-architecture-of-power/',            'blog/the-architecture-of-power/index.html',        'yearly',  '0.8'],
  ['/blog/why-work-matters-in-the-age-of-ai/',    'blog/why-work-matters-in-the-age-of-ai/index.html','yearly',  '0.8'],
  ['/blog/does-ai-actually-think/',               'blog/does-ai-actually-think/index.html',           'yearly',  '0.8'],
  ['/blog/the-one-way-mind/',                     'blog/the-one-way-mind/index.html',                 'yearly',  '0.8'],

  // Older standalone projects.
  ['/chess/p3.html',                              'chess/p3.html',                                    'yearly',  '0.5'],
  ['/PG.Web_Basics/index.html',                   'PG.Web_Basics/index.html',                         'yearly',  '0.4'],
  ['/employeeSystem/p2.html',                     'employeeSystem/p2.html',                           'yearly',  '0.4'],
  ['/studentSystem/p1.html',                      'studentSystem/p1.html',                            'yearly',  '0.4'],
  ['/PG.Quiz/Quiz.html',                          'PG.Quiz/Quiz.html',                                'yearly',  '0.4'],
];

const today = new Date().toISOString().slice(0, 10);

function lastmod(file) {
  try {
    // Uncommitted edits are newer than any commit date, so a dirty file is
    // "changed today". Without this, running the generator before committing a
    // rewrite stamps the page with the date of the version it just replaced.
    const dirty = execFileSync('git', ['status', '--porcelain', '--', file], {
      cwd: ROOT,
      encoding: 'utf8',
    }).trim();
    if (dirty) return today;

    const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', file], {
      cwd: ROOT,
      encoding: 'utf8',
    }).trim();
    return out || today;
  } catch {
    return today;
  }
}

const missing = PAGES.filter(([, file]) => !existsSync(resolve(ROOT, file)));
if (missing.length) {
  console.error('Sitemap references files that do not exist:');
  for (const [url, file] of missing) console.error(`  ${url}  ->  ${file}`);
  process.exit(1);
}

const body = PAGES.map(([path, file, changefreq, priority]) =>
  [
    '  <url>',
    `    <loc>${ORIGIN}${path}</loc>`,
    `    <lastmod>${lastmod(file)}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n'),
).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

writeFileSync(resolve(ROOT, 'sitemap.xml'), xml);
console.log(`sitemap.xml written — ${PAGES.length} URLs`);
