export const KAGGLE_CATEGORIES = [
  'Computer Vision',
  'NLP',
  'Tabular',
  'Time Series',
  'Reinforcement Learning',
  'Recommendation',
  'Audio',
  'Generative',
];

export const DIFFICULTY_ORDER = { Entry: 0, Intermediate: 1, Expert: 2 };

export const KAGGLE_COMPETITIONS = [
  {
    title: 'Coral Reef Health Segmentation',
    slug: 'coral-reef-segmentation',
    category: 'Computer Vision',
    prize: '$60,000',
    prizeValue: 60000,
    deadlineLabel: 'in 18 days',
    daysLeft: 18,
    teams: 842,
    metric: 'mAP',
    difficulty: 'Expert',
    summary: 'Segment bleached and healthy coral from drone imagery to map ecosystem decline at scale.',
  },
  {
    title: 'Clinical Note Intent Tagging',
    slug: 'clinical-note-intent',
    category: 'NLP',
    prize: '$35,000',
    prizeValue: 35000,
    deadlineLabel: 'in 5 days',
    daysLeft: 5,
    teams: 1204,
    metric: 'F1',
    difficulty: 'Intermediate',
    summary: 'Classify physician shorthand into structured intents without leaking patient identifiers.',
  },
  {
    title: 'Retail Demand Forecasting Sprint',
    slug: 'retail-demand-forecast',
    category: 'Time Series',
    prize: '$25,000',
    prizeValue: 25000,
    deadlineLabel: 'in 31 days',
    daysLeft: 31,
    teams: 2310,
    metric: 'RMSE',
    difficulty: 'Intermediate',
    summary: 'Predict weekly SKU demand across thousands of stores with sparse promotional signals.',
  },
  {
    title: 'Credit Default Risk Ranking',
    slug: 'credit-default-risk',
    category: 'Tabular',
    prize: '$80,000',
    prizeValue: 80000,
    deadlineLabel: 'in 12 days',
    daysLeft: 12,
    teams: 3940,
    metric: 'AUC',
    difficulty: 'Intermediate',
    summary: 'Rank borrowers by repayment risk from anonymized transaction and bureau features.',
  },
  {
    title: 'Warehouse Robot Pathing Challenge',
    slug: 'warehouse-robot-pathing',
    category: 'Reinforcement Learning',
    prize: '$50,000',
    prizeValue: 50000,
    deadlineLabel: 'in 44 days',
    daysLeft: 44,
    teams: 318,
    metric: 'Reward',
    difficulty: 'Expert',
    summary: 'Train agents to route fleets of pickers through a dense warehouse without collisions.',
  },
  {
    title: 'Podcast Topic Recommendation',
    slug: 'podcast-recommendation',
    category: 'Recommendation',
    prize: '$20,000',
    prizeValue: 20000,
    deadlineLabel: 'in 27 days',
    daysLeft: 27,
    teams: 1110,
    metric: 'NDCG',
    difficulty: 'Intermediate',
    summary: 'Surface the next episode a listener will finish given partial play histories.',
  },
  {
    title: 'Urban Bird Call Identification',
    slug: 'urban-bird-call-id',
    category: 'Audio',
    prize: '$15,000',
    prizeValue: 15000,
    deadlineLabel: 'in 9 days',
    daysLeft: 9,
    teams: 676,
    metric: 'F1',
    difficulty: 'Intermediate',
    summary: 'Detect overlapping bird species from noisy city soundscapes recorded on cheap sensors.',
  },
  {
    title: 'Sketch-to-Render Image Synthesis',
    slug: 'sketch-to-render',
    category: 'Generative',
    prize: '$100,000',
    prizeValue: 100000,
    deadlineLabel: 'in 56 days',
    daysLeft: 56,
    teams: 524,
    metric: 'FID',
    difficulty: 'Expert',
    summary: 'Generate photoreal product renders from rough designer sketches and a short text brief.',
  },
  {
    title: 'Handwritten Digit Starter',
    slug: 'handwritten-digit-starter',
    category: 'Computer Vision',
    prize: 'Knowledge',
    prizeValue: 0,
    deadlineLabel: 'in 90 days',
    daysLeft: 90,
    teams: 5820,
    metric: 'Accuracy',
    difficulty: 'Entry',
    summary: 'Classify scanned digits in a friendly first competition built for newcomers to vision.',
  },
  {
    title: 'Sentiment in Product Reviews',
    slug: 'review-sentiment-starter',
    category: 'NLP',
    prize: 'Knowledge',
    prizeValue: 0,
    deadlineLabel: 'in 75 days',
    daysLeft: 75,
    teams: 4410,
    metric: 'Accuracy',
    difficulty: 'Entry',
    summary: 'Label short product reviews as positive or negative to learn the text pipeline basics.',
  },
  {
    title: 'Energy Grid Load Prediction',
    slug: 'energy-grid-load',
    category: 'Time Series',
    prize: '$45,000',
    prizeValue: 45000,
    deadlineLabel: 'in 3 days',
    daysLeft: 3,
    teams: 1530,
    metric: 'MAE',
    difficulty: 'Expert',
    summary: 'Forecast regional electricity load an hour ahead under shifting weather conditions.',
  },
  {
    title: 'Insurance Claim Severity',
    slug: 'insurance-claim-severity',
    category: 'Tabular',
    prize: '$30,000',
    prizeValue: 30000,
    deadlineLabel: 'in 22 days',
    daysLeft: 22,
    teams: 2080,
    metric: 'RMSE',
    difficulty: 'Intermediate',
    summary: 'Estimate payout severity from mixed categorical and numeric claim records.',
  },
  {
    title: 'Atari Skill Transfer Cup',
    slug: 'atari-skill-transfer',
    category: 'Reinforcement Learning',
    prize: '$40,000',
    prizeValue: 40000,
    deadlineLabel: 'in 38 days',
    daysLeft: 38,
    teams: 264,
    metric: 'Reward',
    difficulty: 'Expert',
    summary: 'Build agents that carry learned skills across a suite of unseen arcade environments.',
  },
  {
    title: 'Streaming Movie Cold-Start',
    slug: 'movie-cold-start',
    category: 'Recommendation',
    prize: '$55,000',
    prizeValue: 55000,
    deadlineLabel: 'in 15 days',
    daysLeft: 15,
    teams: 1390,
    metric: 'MAP@K',
    difficulty: 'Expert',
    summary: 'Recommend titles to brand-new accounts with no watch history and minimal metadata.',
  },
  {
    title: 'Speaker Diarization in Meetings',
    slug: 'speaker-diarization',
    category: 'Audio',
    prize: '$28,000',
    prizeValue: 28000,
    deadlineLabel: 'in 6 days',
    daysLeft: 6,
    teams: 488,
    metric: 'DER',
    difficulty: 'Expert',
    summary: 'Separate who spoke when in overlapping multi-party meeting recordings.',
  },
  {
    title: 'Molecule Generation for Solubility',
    slug: 'molecule-generation',
    category: 'Generative',
    prize: '$70,000',
    prizeValue: 70000,
    deadlineLabel: 'in 49 days',
    daysLeft: 49,
    teams: 392,
    metric: 'Validity',
    difficulty: 'Expert',
    summary: 'Propose novel valid molecules that maximize aqueous solubility under chemical constraints.',
  },
  {
    title: 'Satellite Crop Type Mapping',
    slug: 'satellite-crop-mapping',
    category: 'Computer Vision',
    prize: '$48,000',
    prizeValue: 48000,
    deadlineLabel: 'in 20 days',
    daysLeft: 20,
    teams: 920,
    metric: 'mIoU',
    difficulty: 'Intermediate',
    summary: 'Map field-level crop types from multi-band satellite tiles across a full growing season.',
  },
  {
    title: 'Multilingual Toxicity Detection',
    slug: 'multilingual-toxicity',
    category: 'NLP',
    prize: '$32,000',
    prizeValue: 32000,
    deadlineLabel: 'in 11 days',
    daysLeft: 11,
    teams: 1760,
    metric: 'AUC',
    difficulty: 'Intermediate',
    summary: 'Flag harmful comments across languages while keeping false positives on dialects low.',
  },
  {
    title: 'Sensor Anomaly Detection',
    slug: 'sensor-anomaly-detection',
    category: 'Time Series',
    prize: '$22,000',
    prizeValue: 22000,
    deadlineLabel: 'in 4 days',
    daysLeft: 4,
    teams: 1015,
    metric: 'F1',
    difficulty: 'Intermediate',
    summary: 'Spot rare equipment faults in long industrial sensor streams before they cascade.',
  },
  {
    title: 'Housing Price Playground',
    slug: 'housing-price-playground',
    category: 'Tabular',
    prize: 'Knowledge',
    prizeValue: 0,
    deadlineLabel: 'in 120 days',
    daysLeft: 120,
    teams: 6210,
    metric: 'RMSE',
    difficulty: 'Entry',
    summary: 'Predict home sale prices from tidy features in a gentle on-ramp to regression modeling.',
  },
];
