// C Basics course — standalone module. The orchestrator (src/content/courses.js)
// imports C_BASICS_COURSE and wires it into COURSES + COURSE_CARDS.
// Lesson shape matches the existing courses:
//   { id, title, intro, code, runnable, exercise: { prompt, starter, expected },
//     takeaways, mistakes, next }
// exercise.expected is the EXACT stdout the intended solution prints (auto-graded).

const C_LESSONS = [
  {
    id: "c1",
    title: "1. Hello, printf",
    intro: "Every C program starts at one function: `main`. The compiler links your code so that `main` runs first and its return value becomes the program's exit status — `return 0;` means success. Unlike scripting languages, nothing happens until you compile a source file (`gcc hello.c -o hello`) into a native executable and run it. There is no interpreter reading your file line by line; the machine runs translated instructions directly, which is exactly why C is fast and why mistakes surface as crashes rather than friendly tracebacks.\n\nTo print text you need `printf`, declared in the standard I/O header. That is why the first line of almost every C file is `#include <stdio.h>`. The `#include` is a preprocessor directive: before compilation, the preprocessor literally pastes the contents of `stdio.h` into your file so the compiler knows what `printf` looks like. Forget that include and you get an implicit-declaration warning at best, undefined behaviour at worst.\n\n`printf` takes a format string and optional arguments. The format string is plain text plus conversion specifiers that start with `%`. `printf(\"Hello\\n\")` prints `Hello` followed by a newline. The `\\n` is an escape sequence — a backslash plus a letter that encodes a character you cannot type literally. `\\n` is newline, `\\t` is tab, `\\\\` is a single backslash, and `\\\"` is a double quote inside a string. Crucially, `printf` does NOT add a newline for you. If you print three strings without `\\n`, they land on one line.\n\nC statements end in a semicolon. Leaving one off is the most common beginner error and the compiler's error message often points at the NEXT line, which is confusing until you learn to read one line up. Curly braces `{ }` group the body of `main`. Indentation is purely cosmetic in C — the compiler ignores it — but consistent indentation is how humans read the structure, so treat it as mandatory anyway.\n\nThe canonical first program prints a greeting and returns 0. Compile it, run it, and you have proven your toolchain works end to end: preprocessor, compiler, linker, loader. From here every other concept builds on this same compile-and-run loop, so get comfortable with it before moving on.",
    code: "#include <stdio.h>\n\nint main(void) {\n    printf(\"Hello, C!\\n\");\n    return 0;\n}",
    runnable: true,
    exercise: {
      prompt: "Print exactly two lines: `Line one` then `Line two`, each on its own line.",
      starter: "#include <stdio.h>\n\nint main(void) {\n    /* print the two lines here */\n    return 0;\n}\n",
      expected: "Line one\nLine two",
    },
    takeaways: [
      "Execution begins at main; return 0 signals success to the OS.",
      "#include <stdio.h> brings in printf before you can call it.",
      "printf does not add a newline — write \\n yourself.",
      "Every statement ends in a semicolon; braces group a block.",
    ],
    mistakes: [
      "Forgetting #include <stdio.h>, then wondering why printf warns about implicit declaration.",
      "Expecting printf to add a newline automatically — it does not.",
      "Dropping the semicolon at the end of a statement; the error often points at the next line.",
    ],
    next: { label: "Variables & types", href: "#/courses/c-basics/c2" },
  },
  {
    id: "c2",
    title: "2. Variables & types",
    intro: "C is statically typed: every variable has a fixed type chosen at compile time, and that type decides how many bytes it occupies and how the bits are interpreted. You declare a variable by writing its type then its name: `int count;`. Until you assign a value, the contents are whatever garbage happened to be in that memory — C does NOT zero-initialize local variables for you. Reading an uninitialized variable is undefined behaviour, so always initialize: `int count = 0;`.\n\nThe integer family is `char`, `short`, `int`, `long`, and `long long`, in non-decreasing size. A plain `int` is almost always 32 bits, holding roughly -2.1 billion to 2.1 billion. Add `unsigned` and the sign bit becomes another value bit, doubling the positive range but disallowing negatives — `unsigned int u = -1;` wraps around to the largest unsigned value, a classic source of surprise. `char` is one byte and doubles as a tiny integer; whether it is signed by default is implementation-defined, so use `signed char` or `unsigned char` when the sign matters.\n\nFor decimals you have `float` (32-bit, ~7 significant digits) and `double` (64-bit, ~15 digits). Prefer `double` unless memory is tight; the extra precision avoids a category of rounding bugs. Floating-point numbers cannot represent most decimals exactly, so `0.1 + 0.2` is not exactly `0.3` here either — never compare floats with `==`.\n\nTo print a variable you match a conversion specifier to its type: `%d` for `int`, `%u` for `unsigned`, `%ld` for `long`, `%f` for `double` (and `float`, which promotes to double when passed to printf), `%c` for a single character, and `%x` for hexadecimal. Mismatching the specifier and the argument is undefined behaviour — `printf(\"%d\", 3.5)` prints garbage because printf reads the wrong number of bytes.\n\nConstants that never change get the `const` qualifier: `const double PI = 3.14159;`. The compiler then rejects any attempt to reassign them, documenting intent and catching bugs. Use uppercase by convention. The `sizeof` operator reports how many bytes a type or value occupies, which is how you confirm an `int` is four bytes on your platform and how you compute allocation sizes later on. Type conversions happen automatically in mixed expressions — an `int` next to a `double` is promoted to `double` before the operation — but you can force a conversion with a cast: `(double)a / b` makes the division floating point even when both operands are integers. With `int`, `double`, `char`, `const`, casts, and the right printf specifiers you can already model most beginner programs.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int age = 21;\n    double gpa = 3.75;\n    char grade = 'A';\n\n    printf(\"%d %.2f %c\\n\", age, gpa, grade);\n    return 0;\n}",
    runnable: true,
    exercise: {
      prompt: "Declare int `apples = 4` and int `boxes = 3`, then print their product on one line. Expect 12.",
      starter: "#include <stdio.h>\n\nint main(void) {\n    int apples = 4;\n    int boxes = 3;\n    /* print apples * boxes */\n    return 0;\n}\n",
      expected: "12",
    },
    takeaways: [
      "Every variable has a fixed type; declare it before use.",
      "Local variables are NOT zero-initialized — set them yourself.",
      "Match printf specifiers to types: %d int, %f double, %c char.",
      "Use const for values that must never change.",
    ],
    mistakes: [
      "Reading an uninitialized local — its value is garbage (undefined behaviour).",
      "Using %d for a double or %f for an int — the specifier must match the argument type.",
      "Comparing floats with == instead of checking a small tolerance.",
    ],
    next: { label: "Operators", href: "#/courses/c-basics/c3" },
  },
  {
    id: "c3",
    title: "3. Operators",
    intro: "Operators are how you compute. C gives you the arithmetic set `+ - * /` and the modulo `%`, which yields the remainder of integer division. The single most important rule for beginners: `/` between two integers does INTEGER division and discards the fraction. `7 / 2` is `3`, not `3.5`. To get the fraction, at least one operand must be floating point: `7.0 / 2` is `3.5`. Modulo only works on integers, so `7 % 2` is `1` and is the standard way to test evenness (`x % 2 == 0`) or to wrap an index around an array length.\n\nComparison operators `== != < > <= >=` produce an `int`: `1` for true, `0` for false. C has no dedicated boolean type in the classic dialect, so any non-zero value counts as true in a condition and zero counts as false. This is why `if (x)` means \"if x is non-zero.\" The logical operators `&&` (and), `||` (or), and `!` (not) combine conditions and short-circuit: `a && b` never evaluates `b` if `a` is false, and `a || b` skips `b` if `a` is true. That short-circuit is not just an optimization; it lets you guard against invalid work, as in `if (p != NULL && p->value > 0)`.\n\nCompound assignment shortens the common read-modify-write pattern: `x += 5` is `x = x + 5`, and the same shape works for `-= *= /= %=`. The increment and decrement operators `++` and `--` add or subtract one. Their pre- and post-forms differ in the VALUE of the expression: `++x` increments then yields the new value; `x++` yields the old value then increments. As standalone statements they are identical, but inside a larger expression like `a[i++]` the difference matters a great deal.\n\nOperator precedence decides grouping when you omit parentheses. `*` and `/` bind tighter than `+` and `-`, just like in math, and comparisons bind looser than arithmetic. When in doubt, add parentheses — they cost nothing and prevent the subtle bug where `a & 1 == 0` parses as `a & (1 == 0)` because `==` outranks the bitwise `&`. Clear grouping is cheaper than a debugging session.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int a = 17, b = 5;\n    printf(\"%d %d %d\\n\", a + b, a / b, a % b);\n    printf(\"%.2f\\n\", (double)a / b);\n    return 0;\n}",
    runnable: true,
    exercise: {
      prompt: "Given int seconds = 137, print minutes and leftover seconds as `2 17` using / and %.",
      starter: "#include <stdio.h>\n\nint main(void) {\n    int seconds = 137;\n    /* print minutes and remaining seconds, space-separated */\n    return 0;\n}\n",
      expected: "2 17",
    },
    takeaways: [
      "Integer / discards the fraction; cast to double for a real quotient.",
      "% gives the remainder and only works on integers.",
      "Comparisons and logical ops yield int 1 (true) or 0 (false).",
      "&& and || short-circuit; use that to guard against invalid work.",
    ],
    mistakes: [
      "Expecting 7 / 2 to be 3.5 — it is 3 until you make an operand a double.",
      "Confusing pre-increment (++x) and post-increment (x++) inside a larger expression.",
      "Relying on precedence with bitwise ops: a & 1 == 0 is not (a & 1) == 0 — parenthesize.",
    ],
    next: { label: "Control flow", href: "#/courses/c-basics/c4" },
  },
  {
    id: "c4",
    title: "4. Control flow",
    intro: "Branching is how a program makes decisions. The core construct is `if (condition) { ... }`, optionally followed by `else if` and `else`. The condition is any expression; C treats zero as false and any non-zero value as true. The braces are technically optional when the body is a single statement, but omit them at your peril — the infamous `goto fail` bug shipped because an unbraced `if` only guarded one line while the author expected it to guard two. Always brace your blocks.\n\nThe equality operator is `==`. Writing a single `=` inside a condition is an assignment, not a comparison: `if (x = 5)` assigns 5 to x and then tests 5, which is always true. Compilers warn about this, but the habit of putting the constant first (`if (5 == x)`) turns the typo into a hard compile error, since you cannot assign to a literal. That defensive style is worth adopting early.\n\nFor selecting among many constant values, `switch` is cleaner than a long `if/else` chain. It evaluates an integer (or char) expression once and jumps to the matching `case` label. The critical gotcha is fall-through: after a matching case runs, execution continues into the next case unless you write `break`. Forgetting `break` is a classic bug, though deliberate fall-through is occasionally useful for grouping cases that share behaviour. The `default` label catches anything that matches no case and should usually be present.\n\nConditions combine with `&&`, `||`, and `!`. Because these short-circuit, order them so the cheap or guarding test comes first: `if (n > 0 && expensive(n))` skips the expensive call when `n` is not positive. The conditional (ternary) operator `cond ? a : b` is a compact expression form of if/else, handy for choosing between two values inline, as in `int max = a > b ? a : b;`.\n\nC also has `goto`, which jumps to a label. It is mostly discouraged because it makes control flow hard to follow, but one accepted use is cleanup-on-error in functions that acquire several resources: jump to a single cleanup block that frees everything. For everyday logic, `if`, `switch`, and the ternary cover the field.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int score = 84;\n    if (score >= 90) {\n        printf(\"A\\n\");\n    } else if (score >= 80) {\n        printf(\"B\\n\");\n    } else {\n        printf(\"C\\n\");\n    }\n    return 0;\n}",
    runnable: true,
    exercise: {
      prompt: "Given int n = 12, print `even` if n is divisible by 2, otherwise `odd`.",
      starter: "#include <stdio.h>\n\nint main(void) {\n    int n = 12;\n    /* print even or odd */\n    return 0;\n}\n",
      expected: "even",
    },
    takeaways: [
      "Zero is false, non-zero is true; always brace your if/else bodies.",
      "Use == for comparison; = is assignment and a common bug.",
      "switch needs break in each case or it falls through.",
      "The ternary cond ? a : b is if/else as an expression.",
    ],
    mistakes: [
      "Writing if (x = 5) instead of if (x == 5) — assignment, always true.",
      "Forgetting break in a switch case, causing unintended fall-through.",
      "Omitting braces and assuming an if guards more than its one next statement.",
    ],
    next: { label: "Loops", href: "#/courses/c-basics/c5" },
  },
  {
    id: "c5",
    title: "5. Loops",
    intro: "Loops repeat work. C offers three: `for`, `while`, and `do/while`. The `for` loop packs initialization, condition, and update into one header: `for (int i = 0; i < n; i++) { ... }`. It runs the init once, tests the condition before each pass, executes the body, then runs the update. When the condition becomes false the loop stops. This shape is the right choice when you know the count up front — iterating an array, repeating something n times, walking an index range.\n\nThe `while` loop is the condition-first loop with no built-in counter: `while (condition) { ... }`. Use it when the number of iterations depends on something computed inside the loop — reading input until end-of-file, shrinking a value until it hits zero, retrying until success. Because the test happens before the body, a `while` may run zero times. Its cousin `do { ... } while (condition);` tests AFTER the body, so it always runs at least once — useful for menu prompts where you must ask before you can check the answer.\n\nTwo keywords steer a loop mid-flight. `break` exits the innermost loop immediately, skipping the rest of the body and the condition. `continue` skips the rest of the current iteration and jumps to the next test (in a `for` loop, the update still runs). Reach for `break` to stop early once you have found what you wanted, and `continue` to skip elements that fail a filter without nesting another `if`.\n\nThe number-one loop bug is the off-by-one error. `for (i = 0; i <= n; i++)` runs n+1 times, one too many, and for an array of length n it reads one element past the end — undefined behaviour. The disciplined pattern is half-open: start at 0, use `< length`, and the index `i` ranges over exactly the valid positions. The second classic bug is the infinite loop: forgetting to advance the loop variable inside a `while`, so the condition never changes. If your program hangs, check that every loop makes measurable progress toward its exit condition.\n\nLoops nest freely — a loop inside a loop is how you walk a grid or compare every pair. Just remember `break` and `continue` only affect the innermost loop they sit in.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int total = 0;\n    for (int i = 1; i <= 5; i++) {\n        total += i;\n    }\n    printf(\"%d\\n\", total);\n    return 0;\n}",
    runnable: true,
    exercise: {
      prompt: "Use a loop to compute the product 1*2*3*4*5 (5 factorial) and print it. Expect 120.",
      starter: "#include <stdio.h>\n\nint main(void) {\n    int fact = 1;\n    /* loop from 1 to 5, multiply into fact, then print */\n    return 0;\n}\n",
      expected: "120",
    },
    takeaways: [
      "for is for known counts; while is for condition-driven repetition.",
      "do/while tests after the body, so it always runs at least once.",
      "break exits the loop; continue skips to the next iteration.",
      "Use half-open ranges (i < length) to avoid off-by-one bugs.",
    ],
    mistakes: [
      "Off-by-one: i <= n runs one extra time and can read past an array.",
      "Forgetting to advance the variable in a while loop — it hangs forever.",
      "Assuming break or continue escapes more than the innermost loop.",
    ],
    next: { label: "Functions", href: "#/courses/c-basics/c6" },
  },
  {
    id: "c6",
    title: "6. Functions",
    intro: "A function is a named, reusable block of code with a fixed signature: a return type, a name, and a parenthesized list of typed parameters. `int add(int a, int b)` declares a function returning an `int` and taking two `int`s. The body computes a result and hands it back with `return`. A function whose return type is `void` returns nothing — you call it for its side effects, like printing — and you may use a bare `return;` to leave early.\n\nC is a single-pass compiler in spirit: it must know a function's signature before the point where you call it. If you define `add` below `main`, then `main` calls a function the compiler has not seen yet. The fix is a prototype (forward declaration) near the top: `int add(int a, int b);` — note the semicolon and the absent body. This promises the compiler that the full definition exists somewhere, and the linker resolves it later. In larger projects these prototypes live in header files. Define a function above its first use and you can skip the prototype, which is why small examples often put helpers before `main`.\n\nArguments in C are passed BY VALUE. The function receives a private copy of each argument, so assigning to a parameter inside the function does not change the caller's variable. A function that tries to `swap(int a, int b)` by exchanging its parameters changes nothing in the caller — a famous beginner trap. To let a function modify a caller's variable you pass its ADDRESS (a pointer) and the function writes through it, a pattern you will meet in the pointers lesson. By-value semantics also mean returning a value is the clean way to get a result out; reach for pointers only when you need to mutate or return several things.\n\nKeep functions small and single-purpose. A good function does one thing, has a name that says what it does, and is short enough to read at a glance. Parameter order should be predictable (inputs first, outputs last by convention). Avoid global variables as a back channel between functions; pass what you need explicitly so each function is testable in isolation. Mastering by-value parameters, return values, and prototypes is most of what you need to structure a C program cleanly.",
    code: "#include <stdio.h>\n\nint square(int n) {\n    return n * n;\n}\n\nint main(void) {\n    printf(\"%d\\n\", square(9));\n    return 0;\n}",
    runnable: true,
    exercise: {
      prompt: "Write a function int cube(int n) returning n*n*n, then print cube(4). Expect 64.",
      starter: "#include <stdio.h>\n\nint cube(int n) {\n    /* return n cubed */\n}\n\nint main(void) {\n    printf(\"%d\\n\", cube(4));\n    return 0;\n}\n",
      expected: "64",
    },
    takeaways: [
      "A function has a return type, a name, and typed parameters.",
      "Declare a prototype before use, or define the function above its caller.",
      "Arguments are passed by value — the function gets a copy.",
      "Return a value to get a result out; pass a pointer to mutate the caller's data.",
    ],
    mistakes: [
      "Calling a function before the compiler has seen its prototype or definition.",
      "Expecting a by-value swap to change the caller's variables — it cannot.",
      "Forgetting a return in a non-void function, leaving the result undefined.",
    ],
    next: { label: "Arrays", href: "#/courses/c-basics/c7" },
  },
  {
    id: "c7",
    title: "7. Arrays",
    intro: "An array is a contiguous block of elements of the same type, laid out back to back in memory. `int scores[5];` reserves room for five ints; you access them with a zero-based index, `scores[0]` through `scores[4]`. The index is an offset from the start, so element `i` lives `i` slots past the first. This contiguity is why arrays are fast — the address of any element is a single multiply-and-add — and it is also why C arrays have a fixed size fixed at declaration. You cannot grow `scores` to six elements later; for that you need dynamic memory, covered soon.\n\nYou can initialize an array inline: `int a[] = {10, 20, 30};` lets the compiler count the elements and size the array to 3. A partial initializer like `int b[5] = {1, 2};` sets the first two and ZERO-fills the rest, a handy idiom for a cleared buffer (`int z[100] = {0};`). Reading an element before you assign it gives garbage for uninitialized arrays, the same rule as scalar locals.\n\nThe defining danger of C arrays is that there is NO bounds checking. `scores[5]` or `scores[-1]` compiles fine and reads or writes memory that does not belong to the array. That is undefined behaviour: it might print rubbish, corrupt a nearby variable, or crash. The language trusts you to stay in range, so every loop over an array must stop at `< length`, never `<= length`. Keep the length in a separate variable or constant, because once an array is passed to a function it decays to a pointer and `sizeof` no longer tells you the element count — you must pass the length alongside it.\n\nTo walk an array you pair an index loop with the length: `for (int i = 0; i < n; i++) sum += a[i];`. Multidimensional arrays exist too — `int grid[3][4]` is three rows of four — and are stored row by row in memory, which is why iterating rows-then-columns is cache-friendly. For most beginner work a single dimension and a careful loop bound are all you need. Internalize one habit above all: never let an index reach the array's length.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int a[5] = {4, 8, 15, 16, 23};\n    int sum = 0;\n    for (int i = 0; i < 5; i++) {\n        sum += a[i];\n    }\n    printf(\"%d\\n\", sum);\n    return 0;\n}",
    runnable: true,
    exercise: {
      prompt: "Find and print the largest value in int a[] = {3, 9, 2, 7, 5}. Expect 9.",
      starter: "#include <stdio.h>\n\nint main(void) {\n    int a[] = {3, 9, 2, 7, 5};\n    int n = 5;\n    /* find the maximum and print it */\n    return 0;\n}\n",
      expected: "9",
    },
    takeaways: [
      "Arrays are contiguous, fixed-size, and zero-indexed.",
      "int a[] = {...} lets the compiler count the elements.",
      "There is no bounds checking — staying in range is your job.",
      "Pass the length alongside the array; it decays to a pointer in functions.",
    ],
    mistakes: [
      "Indexing a[length] or a[-1] — out of bounds is undefined behaviour.",
      "Looping with i <= length instead of i < length.",
      "Using sizeof(arr) inside a function to count elements — arr is just a pointer there.",
    ],
    next: { label: "Strings", href: "#/courses/c-basics/c8" },
  },
  {
    id: "c8",
    title: "8. Strings (char arrays)",
    intro: "C has no built-in string type. A string is simply an array of `char` terminated by a special zero byte, the null terminator `'\\0'`. So the literal `\"hi\"` occupies three bytes: `'h'`, `'i'`, and `'\\0'`. That trailing zero is what marks the end; library functions walk the bytes until they hit it. This is the single most important fact about C strings — every string bug traces back to a missing, misplaced, or overwritten null terminator.\n\nYou store a string in a `char` array large enough for the text PLUS the terminator: `char name[6] = \"hello\";` needs six slots, five for the letters and one for `'\\0'`. Writing a string literal into a char array copies the bytes including the terminator. Print one with the `%s` specifier, which prints characters from the array's start until it reaches the null byte. If the terminator is missing, `%s` keeps reading past your buffer into whatever follows — a leak or crash.\n\nString operations live in `<string.h>`. `strlen(s)` counts characters up to but not including the terminator, so `strlen(\"hi\")` is 2. `strcpy(dst, src)` copies one string into another, `strcat(dst, src)` appends, and `strcmp(a, b)` compares lexicographically, returning 0 when equal, negative or positive otherwise. The catch shared by `strcpy` and `strcat` is that they do NOT check the destination's capacity; if `src` is longer than `dst` can hold, they write past the end — a buffer overflow, historically the root of countless security holes. The safer cousins `strncpy` and `snprintf` take a size limit; prefer them once you handle untrusted input.\n\nComparing strings with `==` does NOT compare their contents. `==` on two char arrays compares their addresses, which are almost never equal, so the test is silently wrong. Always use `strcmp(a, b) == 0` to test equality. Likewise you cannot assign one string to another with `=`; you must `strcpy`. Individual characters are fair game: `s[0] = 'H'` capitalizes the first letter, since a string is just a mutable array. Treat strings as arrays-with-a-terminator and the rules fall out naturally: size for the extra byte, keep the terminator intact, never overflow the destination.",
    code: "#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char name[20] = \"PGcode\";\n    printf(\"%s has %zu letters\\n\", name, strlen(name));\n    return 0;\n}",
    runnable: true,
    exercise: {
      prompt: "Store \"hello\" in a char array and print its length with strlen. Expect 5.",
      starter: "#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char word[10] = \"hello\";\n    /* print strlen(word) as a number */\n    return 0;\n}\n",
      expected: "5",
    },
    takeaways: [
      "A C string is a char array ending in the null byte '\\0'.",
      "Size the array for the text plus one for the terminator.",
      "Use %s to print and strlen / strcpy / strcmp from <string.h>.",
      "Compare strings with strcmp(a, b) == 0, never with ==.",
    ],
    mistakes: [
      "Forgetting to leave room for the '\\0', so the buffer has no terminator.",
      "Comparing strings with == (compares addresses, not contents).",
      "Using strcpy / strcat into a buffer too small — a buffer overflow.",
    ],
    next: { label: "Pointers", href: "#/courses/c-basics/c9" },
  },
  {
    id: "c9",
    title: "9. Pointers",
    intro: "A pointer is a variable that holds the memory ADDRESS of another variable. Every byte of memory has a numeric address, and a pointer stores one of those numbers along with the type of thing it points at. You declare one with a star: `int *p;` means \"p is a pointer to int.\" Two operators make pointers work. The address-of operator `&` gives you the address of a variable: `p = &x;` makes `p` point at `x`. The dereference operator `*` follows the pointer to the value it addresses: `*p` is `x` itself, readable and writable, so `*p = 10;` stores 10 into `x` through the pointer.\n\nWhy bother? Because passing a pointer is how a function modifies the caller's data. Recall that C passes arguments by value, so a normal `swap(int a, int b)` is powerless. But `swap(int *a, int *b)` receives the ADDRESSES of two variables and exchanges the values they point at with `*a` and `*b`, and the change is visible in the caller. Every function that must return more than one result, or edit something in place, takes pointers. The same mechanism underlies arrays (an array name is essentially a pointer to its first element) and strings (a `char *`).\n\nThe value `NULL` is a pointer that points at nothing — a deliberate \"no address here\" marker. Functions that might fail to produce a pointer return `NULL`, and you must check before dereferencing. Dereferencing a `NULL` pointer, or a pointer to memory that no longer exists, is undefined behaviour and usually a segmentation fault. The discipline is simple to state: never dereference a pointer you have not set to a valid address, and check for `NULL` whenever a pointer's validity is in doubt.\n\nPointer arithmetic is the other superpower. Adding 1 to an `int *` advances it by one int (four bytes), not one byte, because the compiler scales by the pointed-to type's size. That is exactly why `a[i]` and `*(a + i)` are equivalent — array indexing is sugar for pointer arithmetic. Walking an array with a moving pointer (`for (int *q = a; q < a + n; q++)`) is idiomatic C. Pointers are the feature that makes C powerful and the feature that makes C dangerous; respect the two rules — valid target, check for NULL — and they become a precise tool rather than a footgun.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int x = 42;\n    int *p = &x;\n    *p = 99;\n    printf(\"%d\\n\", x);\n    return 0;\n}",
    runnable: true,
    exercise: {
      prompt: "Make int *p point at int n = 8, then add 5 through the pointer (*p += 5) and print n. Expect 13.",
      starter: "#include <stdio.h>\n\nint main(void) {\n    int n = 8;\n    int *p = &n;\n    /* add 5 to n through p, then print n */\n    return 0;\n}\n",
      expected: "13",
    },
    takeaways: [
      "A pointer stores the address of another variable.",
      "& takes an address; * dereferences to read or write the target.",
      "Pass pointers to let a function modify the caller's data.",
      "Check for NULL and never dereference an invalid pointer.",
    ],
    mistakes: [
      "Dereferencing an uninitialized or NULL pointer — usually a segfault.",
      "Confusing the declaration star (int *p) with the dereference star (*p = ...).",
      "Forgetting that p + 1 advances by the type's size, not by one byte.",
    ],
    next: { label: "Structs", href: "#/courses/c-basics/c10" },
  },
  {
    id: "c10",
    title: "10. Structs",
    intro: "A struct groups several related variables into one named type so you can treat them as a single unit. Where an array holds many values of the SAME type, a struct holds a fixed set of values of POSSIBLY DIFFERENT types, each with its own name. You define the layout once: `struct Point { int x; int y; };`. That declares a new type, `struct Point`, with two members. You then create instances: `struct Point p;` and set members with the dot operator: `p.x = 3; p.y = 4;`. Reading is the same: `printf(\"%d\", p.x);`.\n\nStructs are how you model a thing with several attributes — a point with x and y, a student with a name, an id, and a gpa, a date with day, month, year. Without them you would juggle parallel arrays or a pile of loosely related variables; with them the related data travels together, which makes functions cleaner (pass one `struct Point` instead of two ints) and intent clearer. You can initialize a struct at creation with a brace list, `struct Point p = {3, 4};`, or with designated initializers that name each member, `struct Point p = {.x = 3, .y = 4};`, which is self-documenting and order-independent.\n\nWhen a struct is large, copying it by value to a function is wasteful, so you usually pass a POINTER to it. Through a pointer you cannot write `(*sp).x` comfortably, so C provides the arrow operator: `sp->x` means \"the member x of the struct that sp points to.\" Arrow is just shorthand for dereference-then-dot; you will see it constantly. Passing a struct pointer also lets the function modify the original rather than a copy, the same by-reference trick from the pointers lesson.\n\nThe `typedef` keyword removes the repetitive `struct` prefix. Writing `typedef struct { int x; int y; } Point;` lets you declare variables as plain `Point p;`. This is idiomatic in most C codebases and reads better. Structs can nest (a struct member can itself be a struct) and can contain arrays and pointers, which is how you build linked lists, trees, and every richer data structure in C — a node is a struct holding a value plus a pointer to the next node. Master the dot operator, the arrow operator, and brace initialization, and you can model essentially any record-shaped data.",
    code: "#include <stdio.h>\n\ntypedef struct {\n    int x;\n    int y;\n} Point;\n\nint main(void) {\n    Point p = {.x = 3, .y = 4};\n    printf(\"(%d, %d)\\n\", p.x, p.y);\n    return 0;\n}",
    runnable: true,
    exercise: {
      prompt: "Define a struct with int width and int height, set them to 6 and 7, print width*height. Expect 42.",
      starter: "#include <stdio.h>\n\ntypedef struct {\n    int width;\n    int height;\n} Rect;\n\nint main(void) {\n    Rect r = {6, 7};\n    /* print the area r.width * r.height */\n    return 0;\n}\n",
      expected: "42",
    },
    takeaways: [
      "A struct bundles related values of possibly different types under one name.",
      "Access members with the dot operator: p.x.",
      "Through a pointer, use the arrow operator: sp->x.",
      "typedef removes the repetitive 'struct' prefix on every declaration.",
    ],
    mistakes: [
      "Using . on a struct pointer instead of -> (or forgetting to dereference).",
      "Forgetting the semicolon after the closing brace of a struct definition.",
      "Passing a large struct by value when a pointer would avoid the copy.",
    ],
    next: { label: "Dynamic memory", href: "#/courses/c-basics/c11" },
  },
  {
    id: "c11",
    title: "11. Dynamic memory (malloc / free)",
    intro: "Arrays so far have had a size fixed at compile time. But often you do not know how much memory you need until the program runs — the user enters a count, a file's length is read at runtime, a list grows. Dynamic memory solves this. The function `malloc(n)`, declared in `<stdlib.h>`, asks the operating system for `n` bytes of memory on the HEAP and returns a pointer to the start of that block. You size the request by multiplying a count by the element size: `int *a = malloc(count * sizeof(int));`. The memory lives until you explicitly release it, independent of any function's lifetime — that is the whole point.\n\n`malloc` can fail when memory is exhausted, in which case it returns `NULL`. Production code checks: `if (a == NULL) { /* handle */ }`. The freshly allocated block is UNINITIALIZED — it holds garbage — so either fill it before reading or use `calloc(count, size)`, which allocates and zeroes in one call. To resize an existing block, `realloc(ptr, newsize)` grows or shrinks it, copying the old contents and possibly returning a new address, so always assign its result back: `a = realloc(a, bigger)` (technically to a temp first, to avoid losing the pointer on failure).\n\nThe iron rule of dynamic memory is that every `malloc` must be matched by exactly one `free`. `free(a)` returns the block to the system so it can be reused. Forget to free and you have a memory LEAK — the program holds memory it no longer uses, and a long-running process slowly consumes all available RAM. Free the same block twice (a double free) and you corrupt the allocator's bookkeeping, often crashing. Use a pointer after freeing it (a use-after-free) and you read or write memory that may now belong to something else — a classic security vulnerability.\n\nThe discipline that prevents these bugs: pair every allocation with its free in the same mental scope, set a pointer to `NULL` after freeing so an accidental reuse faults loudly instead of silently corrupting, and never return a pointer to a local (stack) variable, because that memory vanishes when the function returns — return heap memory or have the caller pass in a buffer. Tools like Valgrind and AddressSanitizer catch leaks and misuse during testing; lean on them. Dynamic memory is what lets C build growable, runtime-sized data structures — and the free discipline is the price of that power.",
    code: "#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    int n = 4;\n    int *a = malloc(n * sizeof(int));\n    int sum = 0;\n    for (int i = 0; i < n; i++) {\n        a[i] = (i + 1) * 10;\n        sum += a[i];\n    }\n    printf(\"%d\\n\", sum);\n    free(a);\n    return 0;\n}",
    runnable: true,
    exercise: {
      prompt: "malloc an int array of size 3, store 5, 10, 15, print their sum, then free. Expect 30.",
      starter: "#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    int *a = malloc(3 * sizeof(int));\n    /* store 5, 10, 15; print the sum; free(a) */\n    return 0;\n}\n",
      expected: "30",
    },
    takeaways: [
      "malloc(n) grabs n heap bytes at runtime and returns a pointer (or NULL).",
      "malloc'd memory is uninitialized; calloc zeroes it for you.",
      "Every malloc needs exactly one free — unmatched frees leak memory.",
      "After free, set the pointer to NULL to avoid use-after-free bugs.",
    ],
    mistakes: [
      "Not checking malloc's result for NULL before using it.",
      "Leaking memory by forgetting free, or corrupting the heap with a double free.",
      "Using a pointer after free, or returning a pointer to a local variable.",
    ],
    next: { label: "The preprocessor", href: "#/courses/c-basics/c12" },
  },
  {
    id: "c12",
    title: "12. The preprocessor",
    intro: "Before the compiler ever sees your code, a separate program called the PREPROCESSOR runs over it and performs pure text transformations driven by lines that start with `#`. Understanding this phase explains a lot of C's structure. The preprocessor does three main jobs: file inclusion, macro substitution, and conditional compilation. None of it knows anything about C's grammar — it manipulates text and hands the result to the compiler.\n\nThe `#include` directive you have used since lesson one literally pastes the named file's contents in place. `#include <stdio.h>` pulls in the standard library's declarations from a system directory; `#include \"myheader.h\"` pulls from your project, searching the current directory first. This is how a function declared in one file becomes usable in another: the header carries the prototypes, and every source file that includes it sees them. Headers should contain declarations, not definitions, to avoid duplicating code across files.\n\nMacros are defined with `#define`. An object-like macro `#define MAX 100` replaces every later `MAX` token with `100` — a named constant with no runtime cost. A function-like macro `#define SQUARE(x) ((x) * (x))` substitutes the argument text into a template. The parentheses are not decoration: without them, `SQUARE(a + b)` would expand to `a + b * a + b`, computing the wrong thing, and a macro used in a larger expression needs outer parentheses too. Macros are textual, so they have no type checking and can evaluate their arguments more than once — `SQUARE(i++)` increments `i` twice. For constants, modern C often prefers `const` or `enum`; for true constants the macro is still common and harmless.\n\nConditional compilation lets you include or exclude code at build time. `#ifdef DEBUG ... #endif` keeps the enclosed lines only when `DEBUG` is defined, perfect for debug logging you can switch off in release builds. The most important use is the INCLUDE GUARD at the top of every header: `#ifndef MYHEADER_H` / `#define MYHEADER_H` / ... / `#endif`. Without it, a header included twice (directly and through another header) would paste its declarations twice and the compiler would complain about redefinitions. The guard ensures the body is processed exactly once per translation unit. Knowing the preprocessor is a distinct text phase demystifies headers, constants, and the build errors that mention line numbers in files you never wrote a bug in.",
    code: "#include <stdio.h>\n\n#define MAX 100\n#define DOUBLE(x) ((x) * 2)\n\nint main(void) {\n    printf(\"%d\\n\", MAX + DOUBLE(9));\n    return 0;\n}",
    runnable: true,
    exercise: {
      prompt: "Define a macro TRIPLE(x) as ((x) * 3) and print TRIPLE(7). Expect 21.",
      starter: "#include <stdio.h>\n\n/* #define TRIPLE(x) ... */\n\nint main(void) {\n    printf(\"%d\\n\", TRIPLE(7));\n    return 0;\n}\n",
      expected: "21",
    },
    takeaways: [
      "The preprocessor does text substitution before the compiler runs.",
      "#include pastes a file's contents in place; headers carry declarations.",
      "#define makes constants and function-like macros — parenthesize every argument.",
      "Include guards (#ifndef/#define/#endif) stop a header being pasted twice.",
    ],
    mistakes: [
      "Macro without parentheses: #define SQ(x) x*x breaks on SQ(a+b).",
      "Passing side effects to a macro (SQUARE(i++)) — the argument evaluates twice.",
      "Omitting the include guard, causing duplicate-declaration errors.",
    ],
    next: { label: "Back to courses", href: "#/courses" },
  },
];

export const C_BASICS_COURSE = {
  id: "c-basics",
  title: "C Basics",
  language: "c",
  color: "#A8B9CC",
  blurb: "From printf to pointers, structs, and malloc — the language that runs underneath everything else.",
  estimatedHours: 4,
  externalResources: [
    { title: "The C Programming Language (Kernighan & Ritchie)", url: "https://en.wikipedia.org/wiki/The_C_Programming_Language", type: "book" },
    { title: "MIT OCW 6.S096 — Effective Programming in C/C++", url: "https://ocw.mit.edu/courses/6-s096-effective-programming-in-c-and-c-january-iap-2014/", type: "course" },
    { title: "cppreference — C language reference", url: "https://en.cppreference.com/w/c/language", type: "book" },
    { title: "Beej's Guide to C Programming", url: "https://beej.us/guide/bgc/", type: "book" },
    { title: "GNU C Reference Manual", url: "https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html", type: "book" },
  ],
  lessons: C_LESSONS,
};
