// C# Basics course module. Wired into the registry by src/content/courses.js.
// Lesson shape matches the other language courses:
//   { id, title, intro, code, runnable, exercise: { prompt, starter, expected },
//     takeaways, mistakes, next }
// `expected` is the exact stdout the grader compares against (trimmed both sides).
// C# runs on Judge0 (Mono, id 51), so every sample uses the
// `class Program { static void Main() {...} }` entry-point wrapper.

const CSHARP_LESSONS = [
  {
    id: "cs1",
    title: "1. Hello + Main",
    intro: "A C# program is organized into types, and the type that runs first holds a method called `Main`. The runtime looks for a `static` method named `Main` and calls it to begin execution. The classic shape is a `class Program` with `static void Main()` inside it, and everything your program does flows out of that one method. Newer versions of the language allow top-level statements that drop the ceremony, but the explicit wrapper is what you will see in most codebases, in interview questions, and on Mono-based judges, so it is the form worth learning first.\n\nThe `static` keyword on `Main` matters. It means the method belongs to the type itself rather than to an instance you have to construct. The runtime cannot create a `Program` object before any of your code has run, so the entry point must be callable without one. `void` means `Main` returns nothing; you can also declare it to return an `int` exit code if a script or shell needs to inspect success.\n\nOutput goes through `System.Console`. `Console.WriteLine(x)` prints the text form of `x` followed by a newline; `Console.Write(x)` prints without the newline. The `using System;` line at the top lets you write `Console` instead of the fully qualified `System.Console`, which is the namespace where the console type lives. Leave the `using` out and the compiler will still accept the fully qualified name, but every reference gets longer.\n\nEvery statement ends with a semicolon, and blocks are delimited by curly braces, not indentation. The compiler ignores whitespace, so formatting is for humans; the convention is four spaces per level and braces on their own lines for types and methods. Names follow PascalCase for types and methods (`Program`, `Main`, `WriteLine`) and camelCase for local variables (`message`, `count`).\n\nC# is compiled, not interpreted. The compiler turns your source into an intermediate language that the runtime then executes, which is why a misspelled method name or a missing semicolon stops you before the program ever runs. That up-front checking is a feature: a large class of mistakes becomes a compile error you fix immediately instead of a crash you discover later. Treat the compiler as a strict but fast collaborator, and lean on its messages rather than guessing.",
    code: "using System;\n\nclass Program {\n    static void Main() {\n        string name = \"PGcode\";\n        Console.WriteLine(\"Hello from \" + name);\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "Print exactly: Math: 95",
      starter: "using System;\n\nclass Program {\n    static void Main() {\n        // declare subject and score, then print \"Math: 95\"\n    }\n}\n",
      expected: "Math: 95",
    },
    takeaways: [
      "Execution starts at a static method named Main.",
      "Console.WriteLine prints a line; Console.Write omits the newline.",
      "`using System;` lets you write Console instead of System.Console.",
      "Statements end with semicolons; braces define blocks, not indentation.",
    ],
    mistakes: [
      "Forgetting `static` on Main — the runtime cannot find an instance entry point.",
      "Leaving off the semicolon at the end of a statement.",
      "Lowercasing Main — the entry point name is case-sensitive.",
    ],
    next: { label: "Variables & types", href: "#/courses/csharp-basics/cs2" },
  },
  {
    id: "cs2",
    title: "2. Variables & types",
    intro: "C# is statically typed: every variable has a type fixed at compile time, and the compiler enforces it. Declaring `int count = 0;` says `count` holds a 32-bit integer and nothing else for the rest of its life. Try to assign a string to it and the program will not compile. That strictness is the whole point — type errors surface at build time instead of as runtime surprises.\n\nThe value types you reach for daily are `int` (32-bit signed integer), `long` (64-bit), `double` (64-bit floating point), `decimal` (128-bit, exact base-10, for money), `bool` (`true`/`false`), and `char` (a single UTF-16 code unit, written with single quotes like `'A'`). `string` is a reference type holding immutable text in double quotes. The literal `3.14` is a `double`; to write a `decimal` literal you append `m`, as in `9.99m`, and to write a `float` you append `f`. Mixing these up is a common early bug: money math in `double` accumulates rounding error, which is exactly why `decimal` exists.\n\nThe `var` keyword lets the compiler infer the type from the right-hand side: `var total = 0;` is identical to `int total = 0;`. It is not dynamic typing — the type is still fixed, you just did not spell it out. Use `var` when the initializer makes the type obvious (`var list = new List<int>();`) and write the type explicitly when it adds clarity. A `var` declaration with no initializer is illegal, because there is nothing to infer from.\n\nNumeric types have documented bounds. An `int` ranges from about negative two billion to positive two billion; exceed it and, by default, the value silently wraps around rather than throwing. When a calculation might overflow, either use `long` or wrap the arithmetic in a `checked` block so overflow throws instead of wrapping. Integer division truncates toward zero: `7 / 2` is `3`, not `3.5`. To get the fractional result, at least one operand must be floating point: `7.0 / 2` is `3.5`.\n\nConstants use `const` for compile-time values that never change (`const double Pi = 3.14159;`) and `readonly` for values fixed once at construction. Reach for `const` whenever a number has a name and a fixed meaning; a named constant reads far better than a bare literal buried in an expression, and the compiler inlines it with zero runtime cost.",
    code: "using System;\n\nclass Program {\n    static void Main() {\n        int count = 42;\n        double price = 9.5;\n        bool ready = true;\n        char grade = 'A';\n        Console.WriteLine(count);\n        Console.WriteLine(price);\n        Console.WriteLine(ready);\n        Console.WriteLine(grade);\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "Declare two ints a=12 and b=5, then print their sum on one line. Expected: 17",
      starter: "using System;\n\nclass Program {\n    static void Main() {\n        // declare a and b, print a + b\n    }\n}\n",
      expected: "17",
    },
    takeaways: [
      "Every variable has a compile-time type the compiler enforces.",
      "Daily types: int, long, double, decimal, bool, char, string.",
      "`var` infers the type from the initializer; it is still static.",
      "Integer division truncates: 7 / 2 is 3, not 3.5.",
    ],
    mistakes: [
      "Using double for money — use decimal to avoid rounding error.",
      "Expecting 7 / 2 to be 3.5 — integer division truncates.",
      "Declaring `var x;` with no initializer — there is nothing to infer.",
    ],
    next: { label: "Strings & interpolation", href: "#/courses/csharp-basics/cs3" },
  },
  {
    id: "cs3",
    title: "3. Strings & interpolation",
    intro: "A `string` in C# is an immutable sequence of UTF-16 characters. Immutable means every operation that looks like it changes a string actually returns a new one: `s.ToUpper()` leaves `s` untouched and hands back a fresh uppercase copy. That immutability makes strings safe to share and pass around, but it also means building a long string by repeated concatenation in a loop creates a pile of throwaway intermediates. For that case, reach for `StringBuilder`, whose `Append` mutates an internal buffer and produces the final string once.\n\nString interpolation is the modern, readable way to build text from values. Prefix the literal with `$` and drop expressions inside braces: `$\"{name} scored {score}\"`. The compiler evaluates each braced expression, converts it to text, and splices it into the result. You can format inside the braces too: `$\"{price:F2}\"` formats a number with two decimal places, and `$\"{ratio:P0}\"` formats it as a whole-number percentage. Interpolation reads far better than the older `string.Format(\"{0} scored {1}\", name, score)` with positional placeholders, though that form still works and is occasionally clearer when the same value repeats.\n\nConcatenation with `+` is fine for joining a handful of pieces (`\"Hello, \" + name`) but interpolation wins the moment more than two values are involved. When one operand is a non-string, `+` calls `ToString()` on it automatically, so `\"count: \" + 5` produces `\"count: 5\"` without an explicit conversion.\n\nThe type carries a rich method set. `Length` is a property, not a method, so no parentheses. `Substring(start, length)` slices, `IndexOf` finds, `Contains` tests membership, `Replace` swaps, `Split` breaks on a delimiter into an array, and `string.Join(\", \", items)` stitches a collection back together. `Trim` removes surrounding whitespace. Comparison uses `==`, which on strings compares characters rather than references, so `\"abc\" == \"abc\"` is `true` regardless of how each string was built — a deliberate convenience the language layers on top of normal reference equality.\n\nTwo escape conveniences are worth knowing. A verbatim string, written `@\"C:\\path\\file\"`, turns off backslash escapes so you do not have to double every one — ideal for file paths and regex patterns. And the index/access of a single character returns a `char`: `s[0]` is the first character. Because strings are immutable you can read `s[0]` but you cannot assign to it; build a new string instead.",
    code: "using System;\n\nclass Program {\n    static void Main() {\n        string name = \"Ada\";\n        int score = 95;\n        Console.WriteLine($\"{name} scored {score}\");\n        double price = 9.5;\n        Console.WriteLine($\"Price: {price:F2}\");\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "Given subject = \"Math\" and score = 95, use interpolation to print exactly: Math: 95",
      starter: "using System;\n\nclass Program {\n    static void Main() {\n        string subject = \"Math\";\n        int score = 95;\n        // print \"Math: 95\" using interpolation\n    }\n}\n",
      expected: "Math: 95",
    },
    takeaways: [
      "Strings are immutable; methods return new strings.",
      "Interpolation: $\"{expr}\" splices values into text.",
      "Format specs inside braces: $\"{price:F2}\" gives two decimals.",
      "Length is a property; s[0] reads (but cannot assign) a char.",
    ],
    mistakes: [
      "Forgetting the $ prefix — the braces print literally instead.",
      "Building long strings with += in a loop — use StringBuilder.",
      "Calling s.Length() — Length is a property, no parentheses.",
    ],
    next: { label: "Operators & control flow", href: "#/courses/csharp-basics/cs4" },
  },
  {
    id: "cs4",
    title: "4. Operators & control flow",
    intro: "Control flow decides which statements run. The workhorse is `if` / `else if` / `else`, where each condition must be a `bool` — C# will not coerce an `int` to a truth value the way C does, so `if (count)` is a compile error and you must write `if (count != 0)`. That strictness removes a whole family of accidental bugs.\n\nComparison operators return `bool`: `==`, `!=`, `<`, `>`, `<=`, `>=`. Combine conditions with the logical operators `&&` (and), `||` (or), and `!` (not). Both `&&` and `||` short-circuit, meaning the right side is skipped when the left side already decides the outcome. That is what makes `if (s != null && s.Length > 0)` safe: if `s` is null, the length check never runs. The single-character `&` and `|` evaluate both sides always and are bitwise operators; reaching for them in a boolean condition is a classic mistake.\n\nThe ternary operator `cond ? a : b` is an expression that evaluates to one of two values, perfect for a short conditional assignment: `string label = score >= 60 ? \"pass\" : \"fail\";`. Both branches must produce compatible types. The null-coalescing operator `??` supplies a fallback when the left side is null (`name ?? \"unknown\"`), and `??=` assigns the fallback only when the target is currently null.\n\n`switch` handles dispatch on a single value cleanly. The modern switch expression form is concise and exhaustive: `var word = n switch { 1 => \"one\", 2 => \"two\", _ => \"many\" };`, where `_` is the catch-all. The older switch statement uses `case` labels and requires `break` (or `return`) at the end of each case — fall-through between non-empty cases is a compile error in C#, which spares you the silent fall-through bug that plagues C.\n\nA few operators round out daily work. `%` is the remainder, the standard tool for \"every Nth\" and parity checks (`i % 2 == 0` is even). Compound assignment (`+=`, `-=`, `*=`, `/=`, `%=`) updates a variable in place. The increment and decrement operators `++` and `--` adjust by one; pre-form (`++i`) updates before the surrounding expression reads it, post-form (`i++`) reads the old value first. When in doubt, split the increment onto its own line — clarity beats cleverness, and a reader should never have to puzzle out evaluation order.",
    code: "using System;\n\nclass Program {\n    static void Main() {\n        int score = 73;\n        string label = score >= 90 ? \"A\" : score >= 70 ? \"B\" : \"C\";\n        Console.WriteLine(label);\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "Given age = 17, print \"minor\" if age < 18, otherwise \"adult\". Expected: minor",
      starter: "using System;\n\nclass Program {\n    static void Main() {\n        int age = 17;\n        // print \"minor\" or \"adult\"\n    }\n}\n",
      expected: "minor",
    },
    takeaways: [
      "Conditions must be bool — C# will not coerce int or null.",
      "&& and || short-circuit; & and | are bitwise and always evaluate both.",
      "Ternary cond ? a : b and ?? for null fallbacks read cleanly.",
      "switch expressions are concise and exhaustive with _ as catch-all.",
    ],
    mistakes: [
      "Writing if (count) instead of if (count != 0) — bool is required.",
      "Using & or | where you meant && or || — both sides evaluate.",
      "Forgetting break in a classic switch statement case.",
    ],
    next: { label: "Loops", href: "#/courses/csharp-basics/cs5" },
  },
  {
    id: "cs5",
    title: "5. Loops",
    intro: "C# offers four looping forms, each suited to a different shape of work. The counted `for` loop is the classic when you need an index: `for (int i = 0; i < n; i++)` runs the body with `i` walking from `0` up to `n - 1`. The three clauses — initializer, condition, and step — are evaluated in a fixed order, and the condition is checked before each iteration, so a loop whose condition is false at the start runs zero times.\n\nThe `foreach` loop walks the elements of any collection without exposing an index: `foreach (int x in numbers)`. Reach for it whenever you only care about the values, which is most of the time; it reads cleanly and removes off-by-one risk entirely. The catch is that you cannot modify the collection's structure while iterating it with `foreach` — adding or removing throws an `InvalidOperationException` mid-loop. When you need to delete during traversal, loop by index backward, or build a list of survivors and replace.\n\nThe `while` loop checks its condition before each pass and is the right tool when the number of iterations is not known up front: read until end-of-input, retry until success, converge until stable. The `do`/`while` loop is the mirror image — it runs the body once before checking the condition, guaranteeing at least one pass. Use it for menus and prompts where you always want one attempt before deciding whether to repeat.\n\nTwo keywords steer a loop from inside. `break` exits the nearest enclosing loop immediately, skipping any remaining iterations — ideal once you have found what you were searching for. `continue` skips the rest of the current iteration and jumps to the next one, which keeps the body flat instead of wrapping everything in an `if`. Both apply to the innermost loop only; to break out of nested loops, either restructure into a method and `return`, or set a flag.\n\nLoops are where complexity creeps in. A single loop over `n` items is `O(n)`; a loop nested inside another is `O(n^2)`, which is fine for small inputs and a disaster for large ones. When you find yourself scanning the whole collection inside another scan, ask whether a dictionary lookup or a single pass with running state could replace the inner loop. And watch the boundary conditions: `<` versus `<=` and starting at `0` versus `1` are the source of nearly every off-by-one bug, so reason through the first and last iteration explicitly before trusting the loop.",
    code: "using System;\n\nclass Program {\n    static void Main() {\n        int sum = 0;\n        for (int i = 1; i <= 5; i++) {\n            sum += i;\n        }\n        Console.WriteLine(sum);\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "Sum the even numbers from 1 to 10 and print the total. Expected: 30",
      starter: "using System;\n\nclass Program {\n    static void Main() {\n        int total = 0;\n        for (int i = 1; i <= 10; i++) {\n            // add only even numbers\n        }\n        Console.WriteLine(total);\n    }\n}\n",
      expected: "30",
    },
    takeaways: [
      "for with an index, foreach over values, while and do/while for unknown counts.",
      "do/while always runs the body at least once.",
      "break exits the loop; continue skips to the next iteration.",
      "Nested loops multiply cost — watch for O(n^2).",
    ],
    mistakes: [
      "Off-by-one from < vs <= or starting at 0 vs 1.",
      "Modifying a collection inside foreach — throws InvalidOperationException.",
      "Assuming break leaves all nested loops — it exits only the innermost.",
    ],
    next: { label: "Methods", href: "#/courses/csharp-basics/cs6" },
  },
  {
    id: "cs6",
    title: "6. Methods",
    intro: "A method bundles a reusable piece of behavior behind a name. Its signature spells out everything: an access modifier, an optional `static`, the return type, the name, and a parenthesized list of typed parameters. `static int Add(int a, int b)` declares a method that takes two integers and returns one. A return type of `void` means the method produces no value and is called for its side effects, like printing.\n\nWhen a method has a non-void return type, every path that can reach the end must return a value of that type, or the program will not compile. That definite-return rule catches the bug where one branch of an `if` forgets to return. Inside `Main` and other static methods, the methods you call must themselves be `static` (or be called on an object), because a static context has no instance to borrow.\n\nArguments are passed by value by default. For value types like `int`, the method receives a copy, so changing the parameter inside the method leaves the caller's variable untouched. For reference types like arrays and objects, the *reference* is copied — the method cannot make your variable point somewhere else, but it can mutate the object the reference points at, and that change is visible to the caller. Understanding this split is the key to predicting what a method call will and will not change.\n\nC# gives you several ways to shape a parameter list. Default values let a parameter be optional: `void Log(string msg, int level = 1)` can be called with one or two arguments. Named arguments let the caller pass values out of order for clarity: `Log(level: 3, msg: \"hi\")`. The `params` keyword accepts any number of trailing arguments as an array: `int Sum(params int[] nums)` can be called as `Sum(1, 2, 3)`. And method overloading lets several methods share a name as long as their parameter lists differ in type or count; the compiler picks the best match at the call site.\n\nFor short methods, expression-bodied syntax trims the noise: `static int Square(int x) => x * x;` is the whole method. Use it when the body is a single expression; fall back to a brace block when there is real logic. Whatever the form, keep methods focused on one job — a method that does one thing well is easy to name, easy to test, and easy to reuse, and a good name (`IsEligible`, `ParseScore`) often documents the intent better than a comment ever could.",
    code: "using System;\n\nclass Program {\n    static int Square(int x) => x * x;\n\n    static int AddAll(params int[] nums) {\n        int total = 0;\n        foreach (int n in nums) total += n;\n        return total;\n    }\n\n    static void Main() {\n        Console.WriteLine(Square(6));\n        Console.WriteLine(AddAll(1, 2, 3, 4));\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "Write a static method Triple(int n) returning n * 3, then print Triple(7). Expected: 21",
      starter: "using System;\n\nclass Program {\n    // define Triple here\n\n    static void Main() {\n        // print Triple(7)\n    }\n}\n",
      expected: "21",
    },
    takeaways: [
      "Signature: modifiers, return type, name, typed parameters.",
      "Value types pass a copy; reference types pass a copy of the reference.",
      "Optional defaults, named args, params, and overloading shape call sites.",
      "Expression-bodied `=> expr` is concise for one-line methods.",
    ],
    mistakes: [
      "A non-void method with a path that does not return.",
      "Expecting an int parameter change to reach the caller — it is a copy.",
      "Calling a non-static method from a static context with no instance.",
    ],
    next: { label: "Arrays & List<T>", href: "#/courses/csharp-basics/cs7" },
  },
  {
    id: "cs7",
    title: "7. Arrays & List<T>",
    intro: "An array is a fixed-size, zero-indexed block of elements of one type. Declare and size it with `int[] xs = new int[5];`, which allocates five slots all initialized to `0`, or write the contents directly with `int[] xs = { 1, 2, 3 };`. The element count is the `Length` property — no parentheses, because it is a property, not a method. Access is `O(1)` by index, but the size is locked at creation: to hold more you must allocate a new, larger array and copy. Indexing past the end throws `IndexOutOfRangeException`, which is the array's way of refusing to read memory it does not own.\n\nWhen the size is not known ahead of time, reach for `List<T>`, the resizable array of the standard library. `var nums = new List<int>();` starts empty; `nums.Add(7)` appends in amortized `O(1)` time, growing the backing array automatically when it fills. The list mirrors the array for reads — `nums[0]` indexes, `nums.Count` is the size (note: `Count`, not `Length`) — and adds the mutation methods arrays lack: `Insert(i, x)` places an element at a position, `Remove(x)` deletes the first matching value, `RemoveAt(i)` deletes by index, and `Contains(x)` tests membership. Inserting or removing in the middle is `O(n)` because the following elements shift, so prefer appending and removing at the end in hot paths.\n\nThe angle brackets in `List<int>` are generics: the type inside the brackets is the element type, fixed at compile time. A `List<int>` holds only integers, and the compiler rejects an attempt to add a string. That type safety means you never cast on the way out, and a mistyped element is caught at build time rather than as a runtime cast failure.\n\nBoth arrays and lists work seamlessly with `foreach`, which is the cleanest way to walk every element when you do not need the index. When you do need positions, use an indexed `for` over `Length` or `Count`. Converting between the two is a one-liner: `list.ToArray()` produces an array, and `new List<int>(array)` wraps an array in a list.\n\nA practical rule of thumb: choose an array when the size is known and fixed and you want the smallest footprint, and choose `List<T>` whenever the collection grows, shrinks, or starts at an unknown size — which, in everyday code, is most of the time. Useful helpers like `Sort`, `Reverse`, `IndexOf`, and `Find` live on `List<T>` directly, and the static `Array.Sort` and `Array.IndexOf` cover the array side.",
    code: "using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        int[] arr = { 3, 1, 4, 1, 5 };\n        Console.WriteLine(arr.Length);\n\n        var nums = new List<int>();\n        nums.Add(10);\n        nums.Add(20);\n        nums.Add(30);\n        Console.WriteLine(nums.Count);\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "Create a List<int> with 2, 4, 6, 8, sum it with a loop, and print the total. Expected: 20",
      starter: "using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        var nums = new List<int> { 2, 4, 6, 8 };\n        int total = 0;\n        // sum the list, then print total\n    }\n}\n",
      expected: "20",
    },
    takeaways: [
      "Arrays are fixed-size and zero-indexed; Length is a property.",
      "List<T> resizes automatically; Add is amortized O(1).",
      "Array uses Length, List<T> uses Count.",
      "Insert/remove in the middle of a list is O(n) — prefer the end.",
    ],
    mistakes: [
      "Calling arr.Length() — Length has no parentheses.",
      "Indexing past the end — throws IndexOutOfRangeException.",
      "Confusing Count (list) with Length (array).",
    ],
    next: { label: "Dictionaries", href: "#/courses/csharp-basics/cs8" },
  },
  {
    id: "cs8",
    title: "8. Dictionaries",
    intro: "`Dictionary<TKey, TValue>` is C#'s hash table: a collection of key/value pairs with average `O(1)` lookup, insertion, and removal. Declare the key and value types in the angle brackets — `var counts = new Dictionary<string, int>();` maps strings to integers. Set a value with the indexer, `counts[\"apple\"] = 3;`, and read it back the same way, `int n = counts[\"apple\"];`. The hash table places each key in a bucket derived from its hash code, which is why lookups do not have to scan the whole collection.\n\nThe single most important rule: reading a key that does not exist with the indexer throws `KeyNotFoundException`. Guard against it. `ContainsKey(key)` tells you whether a key is present before you read. `TryGetValue(key, out var value)` is the idiomatic combined check — it returns `true` and fills `value` when the key exists, and returns `false` otherwise, all in one lookup instead of two. For a simple fallback, `GetValueOrDefault(key)` returns the value or the type's default (`0` for `int`) without throwing. Writing with the indexer, by contrast, never throws: `counts[key] = v` inserts the pair if the key is new and overwrites it if the key already exists.\n\nThe counting pattern is worth memorizing because it appears constantly. To tally occurrences, the concise form is `counts[c] = counts.GetValueOrDefault(c) + 1;` — read the current count (zero if absent), add one, and store it back. This single line replaces the older `if (counts.ContainsKey(c)) ... else ...` branch and is the standard tool for frequency maps, grouping, and de-duplication.\n\nKeys must be unique and are compared by their `Equals` and `GetHashCode`. The built-in types — `string`, `int`, and the rest — implement both correctly, so they work as keys out of the box. If you ever use a custom class as a key, you must override both methods consistently, or two \"equal\" keys will land in different buckets and the dictionary will silently misbehave.\n\nIteration yields `KeyValuePair` entries: `foreach (var kv in counts)` gives you `kv.Key` and `kv.Value`. You can also walk `counts.Keys` or `counts.Values` alone. The order is unspecified and may change as the dictionary grows, so never rely on insertion order from a plain `Dictionary`. When you need keys kept in sorted order, use `SortedDictionary<TKey, TValue>`, which is a balanced tree with `O(log n)` operations and ordered traversal.",
    code: "using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        var counts = new Dictionary<char, int>();\n        foreach (char c in \"banana\") {\n            counts[c] = counts.GetValueOrDefault(c) + 1;\n        }\n        Console.WriteLine(counts['a']);\n        Console.WriteLine(counts['n']);\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "Count occurrences in the array {1,2,2,3,3,3} and print the count of 3. Expected: 3",
      starter: "using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        int[] arr = { 1, 2, 2, 3, 3, 3 };\n        var counts = new Dictionary<int, int>();\n        // tally, then print counts[3]\n    }\n}\n",
      expected: "3",
    },
    takeaways: [
      "Dictionary<TKey, TValue> gives average O(1) lookup and insert.",
      "Reading a missing key with [] throws KeyNotFoundException.",
      "TryGetValue / GetValueOrDefault / ContainsKey avoid the throw.",
      "Counting: counts[c] = counts.GetValueOrDefault(c) + 1.",
    ],
    mistakes: [
      "Indexing a missing key — guard with TryGetValue or GetValueOrDefault.",
      "Relying on iteration order — a plain Dictionary is unordered.",
      "Using a custom key without overriding Equals and GetHashCode.",
    ],
    next: { label: "Classes & properties", href: "#/courses/csharp-basics/cs9" },
  },
  {
    id: "cs9",
    title: "9. Classes & properties",
    intro: "A class is a blueprint for objects that bundle data (fields) with behavior (methods). `class Point { ... }` defines a type; `new Point()` constructs an instance on the heap and hands you a reference to it. Classes are reference types, so assigning one variable to another copies the reference, not the object — both names then point at the same instance, and a change through one is visible through the other. That aliasing is the defining difference from value types like `int` and `struct`.\n\nA constructor initializes a new instance. It shares the class name, takes no return type, and runs once when you call `new`. `public Point(int x, int y) { X = x; Y = y; }` lets the caller supply starting values. If you write no constructor, C# provides a parameterless default; the moment you define any constructor, that free default disappears, so add one back explicitly if you still want `new Point()` to work.\n\nProperties are the idiomatic way to expose data. Rather than a public field, you declare `public int X { get; set; }`, an auto-property that the compiler backs with a hidden field and a getter/setter pair. This looks like a field at the call site (`p.X = 5;`) but routes every read and write through methods, so you can later add validation or computation without changing any caller. Make the setter `private` (`{ get; private set; }`) for read-only-from-outside data, or drop the setter entirely for a computed, get-only property: `public double DistanceFromOrigin => Math.Sqrt(X * X + Y * Y);`.\n\nThe `this` keyword refers to the current instance and disambiguates a field from a same-named parameter (`this.x = x;`). Members are `private` by default — accessible only inside the class — and you opt into wider visibility with `public` (everywhere), `protected` (the class and its subclasses), or `internal` (the same assembly). Defaulting to `private` and exposing only what callers genuinely need is the core of encapsulation: the class controls its own invariants instead of trusting every caller to respect them.\n\nOverriding `ToString()` controls how an instance prints, which is invaluable for debugging: `public override string ToString() => $\"({X}, {Y})\";` makes `Console.WriteLine(p)` produce `(3, 4)` instead of the type name. For small immutable data bundles, the `record` keyword generates a constructor, properties, value equality, and a readable `ToString` for you in a single line — reach for it when the type is mostly data and you want two equal-valued instances to compare equal.",
    code: "using System;\n\nclass Point {\n    public int X { get; set; }\n    public int Y { get; set; }\n\n    public Point(int x, int y) {\n        X = x;\n        Y = y;\n    }\n\n    public override string ToString() => $\"({X}, {Y})\";\n}\n\nclass Program {\n    static void Main() {\n        var p = new Point(3, 4);\n        Console.WriteLine(p);\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "Define a class Box with an int property Size and a constructor, then create Box(5) and print its Size. Expected: 5",
      starter: "using System;\n\nclass Box {\n    // add a Size property and a constructor\n}\n\nclass Program {\n    static void Main() {\n        // create a Box(5) and print its Size\n    }\n}\n",
      expected: "5",
    },
    takeaways: [
      "Classes are reference types; assignment copies the reference.",
      "Constructors share the class name and run once at new.",
      "Auto-properties { get; set; } look like fields but route through methods.",
      "Override ToString() to control how an instance prints.",
    ],
    mistakes: [
      "Forgetting that defining any constructor removes the free default one.",
      "Exposing public fields instead of properties — no room to add validation later.",
      "Expecting reference assignment to copy the object — both names alias one instance.",
    ],
    next: { label: "Inheritance & interfaces", href: "#/courses/csharp-basics/cs10" },
  },
  {
    id: "cs10",
    title: "10. Inheritance & interfaces",
    intro: "Inheritance lets one class build on another. `class Dog : Animal` declares `Dog` as a subclass of `Animal`, inheriting its fields, properties, and methods, then adding or specializing its own. The subclass constructor calls the base constructor with `: base(...)` to initialize the inherited part before running its own. A C# class inherits from at most one base class — single inheritance — which keeps the type hierarchy a tree rather than a tangle.\n\nTo let a subclass replace a base method, mark the base method `virtual` and the subclass version `override`. `public virtual string Speak() => \"...\";` in `Animal` and `public override string Speak() => \"Woof\";` in `Dog` means calling `Speak()` on a `Dog` runs the dog's version even when the variable is typed as `Animal`. That runtime dispatch on the actual object type is polymorphism, and it is what lets one loop over a `List<Animal>` call the right `Speak` for each element without checking types. A method that is not `virtual` cannot be overridden — a subclass `new` method would merely hide it, which dispatches on the variable's compile-time type and is almost always a mistake.\n\nAn `abstract` class cannot be instantiated and may declare `abstract` members with no body that every concrete subclass must implement. Use it when there is shared state or behavior plus a contract the base cannot fulfill on its own — `abstract class Shape` with a concrete `Name` property and an `abstract double Area();`.\n\nAn interface goes further: it is a pure contract of members with no state, written `interface IComparable { int CompareTo(object other); }`. A class promises to fulfill an interface with the same `:` syntax, and unlike base classes, a class can implement any number of interfaces. This is how C# gets the flexibility of multiple inheritance without its ambiguity — you inherit implementation from one base class but capabilities from many interfaces. The convention is to prefix interface names with `I`.\n\nThe practical guidance is \"program to the interface.\" Declare variables and parameters by the interface or base type (`IEnumerable<int>`, `Animal`) rather than the concrete class, so callers depend on the capability, not the implementation, and you can swap implementations freely. Reach for an abstract base class when subclasses share real code; reach for an interface when unrelated types need to offer the same capability. And every subclass should genuinely *be* its base — if a `Square` cannot honor everything a `Rectangle` promises, it should not inherit from it.",
    code: "using System;\nusing System.Collections.Generic;\n\nabstract class Animal {\n    public abstract string Speak();\n}\n\nclass Dog : Animal {\n    public override string Speak() => \"Woof\";\n}\n\nclass Cat : Animal {\n    public override string Speak() => \"Meow\";\n}\n\nclass Program {\n    static void Main() {\n        var animals = new List<Animal> { new Dog(), new Cat() };\n        foreach (Animal a in animals) {\n            Console.WriteLine(a.Speak());\n        }\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "Make a base class Shape with virtual string Name() returning \"shape\", and a subclass Circle overriding it to return \"circle\". Print new Circle().Name(). Expected: circle",
      starter: "using System;\n\nclass Shape {\n    public virtual string Name() => \"shape\";\n}\n\n// define Circle : Shape overriding Name\n\nclass Program {\n    static void Main() {\n        // print new Circle().Name()\n    }\n}\n",
      expected: "circle",
    },
    takeaways: [
      "Single class inheritance: class Sub : Base, base ctor via : base(...).",
      "virtual + override give runtime polymorphism on the actual type.",
      "Abstract classes share code; interfaces are pure contracts.",
      "A class implements many interfaces but inherits one base.",
    ],
    mistakes: [
      "Overriding a method that is not virtual — you only hide it.",
      "Trying to instantiate an abstract class with new.",
      "Forgetting to call : base(...) when the base needs constructor args.",
    ],
    next: { label: "Generics", href: "#/courses/csharp-basics/cs11" },
  },
  {
    id: "cs11",
    title: "11. Generics",
    intro: "Generics let you write a type or method once and reuse it for many element types without giving up type safety. `List<T>` and `Dictionary<TKey, TValue>` are the generics you already use; the `T` is a type parameter, a placeholder filled in at the point of use. `List<int>` substitutes `int` for `T`, `List<string>` substitutes `string`, and each is fully checked at compile time. The alternative — storing everything as `object` and casting on the way out — loses that checking and pays a boxing cost for value types, which is exactly the pain generics were introduced to remove.\n\nYou can write your own generic method by putting the type parameter after the name: `static T First<T>(List<T> items) => items[0];` works for a list of any element type, and the compiler infers `T` from the argument so you call it as `First(numbers)` without spelling out the type. A generic class follows the same pattern at the class level: `class Box<T> { public T Value; }` is a container for one value of whatever type the caller chooses.\n\nBy default a type parameter is opaque — inside the generic code you know nothing about `T`, so you can only do what every type supports (assign it, store it, call `ToString`). Constraints widen what you can do. `where T : IComparable<T>` promises that `T` supports comparison, so you can call `a.CompareTo(b)` inside the method; `where T : class` requires a reference type; `where T : new()` requires a public parameterless constructor so you can write `new T()`; and `where T : SomeBase` requires `T` to derive from a given base. Constraints are the contract that lets generic code do real work while staying type-safe for every concrete `T`.\n\nThe payoff is concrete. A generic `Swap<T>(ref T a, ref T b)` works for integers, strings, and your own types with one definition. A generic `Max<T>(T a, T b) where T : IComparable<T>` returns the larger of any two comparable values. You write the algorithm once; the compiler stamps out a correct, checked version for each type you use it with, and value types avoid the boxing they would suffer in an `object`-based container.\n\nGenerics also power the whole `System.Collections.Generic` namespace — `List<T>`, `Dictionary<TKey, TValue>`, `HashSet<T>`, `Queue<T>`, `Stack<T>` — and the `IEnumerable<T>` interface that LINQ builds on. Understanding the angle-bracket syntax unlocks all of them. A good rule of thumb: when you find yourself about to write the same class or method twice for two different element types, replace the type with a parameter and write it once.",
    code: "using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static T Last<T>(List<T> items) => items[items.Count - 1];\n\n    static void Main() {\n        var nums = new List<int> { 1, 2, 3 };\n        var words = new List<string> { \"a\", \"b\", \"c\" };\n        Console.WriteLine(Last(nums));\n        Console.WriteLine(Last(words));\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "Write a generic method First<T>(List<T> items) returning items[0]. Call it on a List<int> {7, 8, 9} and print the result. Expected: 7",
      starter: "using System;\nusing System.Collections.Generic;\n\nclass Program {\n    // define generic First<T> here\n\n    static void Main() {\n        var nums = new List<int> { 7, 8, 9 };\n        // print First(nums)\n    }\n}\n",
      expected: "7",
    },
    takeaways: [
      "Type parameters like <T> are placeholders filled in at use.",
      "Generics keep compile-time type safety and avoid boxing.",
      "The compiler infers T from arguments in most calls.",
      "Constraints (where T : ...) let generic code do real work safely.",
    ],
    mistakes: [
      "Calling type-specific members on T without a constraint.",
      "Falling back to object + casts where a generic would be safer.",
      "Forgetting where T : new() before writing new T().",
    ],
    next: { label: "LINQ intro", href: "#/courses/csharp-basics/cs12" },
  },
  {
    id: "cs12",
    title: "12. LINQ intro",
    intro: "LINQ — Language Integrated Query — is a set of methods that let you filter, transform, and aggregate collections with readable, composable calls instead of hand-written loops. It lives in `System.Linq`, and once that namespace is in scope, every `IEnumerable<T>` — arrays, lists, dictionaries — gains a fluent query vocabulary. The same operators work whether the source is an in-memory list or a database, which is the \"integrated\" part of the name.\n\nThe three operators you reach for constantly are `Where`, `Select`, and an aggregate. `Where(predicate)` keeps only the elements for which a condition is true: `nums.Where(n => n % 2 == 0)` yields the even numbers. `Select(projection)` transforms each element into something else: `nums.Select(n => n * n)` yields the squares. Both take a lambda — `n => expression` — a compact inline function where `n` is the parameter and the expression is the result. You chain them naturally: `nums.Where(n => n > 0).Select(n => n * 2)` filters then transforms, reading left to right in the order the data flows.\n\nAggregates collapse a sequence to a single value. `Count()` returns the number of elements (and `Count(predicate)` counts only matches); `Sum()`, `Average()`, `Min()`, and `Max()` do the obvious arithmetic; `Any(predicate)` returns true if at least one element matches, and `All(predicate)` if every element does. These end a chain: `nums.Where(n => n > 0).Sum()` adds up the positives in one line that would otherwise be a loop with an accumulator and an `if`.\n\nElement operators pull one item out. `First()` and `FirstOrDefault()` return the first element (or the first match given a predicate); the `OrDefault` variants return the type's default instead of throwing when nothing matches, which is the safer choice when an empty result is legitimate. `OrderBy(keySelector)` sorts ascending and `OrderByDescending` sorts descending, both returning a new ordered sequence without touching the original.\n\nThe one subtlety worth internalizing early is deferred execution. Most LINQ operators are lazy: `Where` and `Select` build a query but do not run it until something forces enumeration — a `foreach`, or a terminal call like `ToList()`, `ToArray()`, `Count()`, or `Sum()`. That laziness is efficient (nothing computes until needed) but surprising if you expect the work to happen at the call. When you want the results materialized and snapshotted, end the chain with `.ToList()`. Used well, LINQ turns a dozen lines of loop-and-accumulate into one declarative line that says *what* you want rather than *how* to compute it.",
    code: "using System;\nusing System.Linq;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        var nums = new List<int> { 1, 2, 3, 4, 5, 6 };\n        int evenSum = nums.Where(n => n % 2 == 0).Sum();\n        Console.WriteLine(evenSum);\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "From the list {1,2,3,4,5}, use LINQ to count how many numbers are greater than 2. Expected: 3",
      starter: "using System;\nusing System.Linq;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        var nums = new List<int> { 1, 2, 3, 4, 5 };\n        // print the count of numbers > 2\n    }\n}\n",
      expected: "3",
    },
    takeaways: [
      "LINQ adds Where/Select/aggregates to any IEnumerable<T>.",
      "Lambdas (n => expr) are the inline functions LINQ takes.",
      "Chain filters and transforms; aggregates collapse to one value.",
      "Most operators are lazy — force them with ToList/Count/Sum.",
    ],
    mistakes: [
      "Forgetting `using System.Linq;` — the methods vanish.",
      "Calling First() on an empty result — throws; use FirstOrDefault().",
      "Expecting deferred queries to run before enumeration.",
    ],
    next: { label: "Exceptions & async", href: "#/courses/csharp-basics/cs13" },
  },
  {
    id: "cs13",
    title: "13. Exceptions & async",
    intro: "When something goes wrong at runtime — a missing dictionary key, a parse failure, a null dereference — C# raises an exception, an object that travels up the call stack until some `catch` handles it or the program terminates. You handle exceptions with a `try`/`catch` block: code that might fail goes in `try`, and the recovery goes in `catch (SomeException e)`. Catch the most specific exception type you can — `FormatException` for a bad parse, `KeyNotFoundException` for a missing key — rather than the base `Exception`, so you only intercept failures you actually know how to handle and let unexpected ones surface.\n\nA `finally` block runs whether or not an exception was thrown, which makes it the place for cleanup that must happen either way — closing a file, releasing a lock. In practice, types that hold resources implement `IDisposable`, and the `using` statement (`using var reader = new StreamReader(path);`) disposes them automatically at the end of the scope, which is cleaner than a hand-written `finally`. You throw your own exception with `throw new ArgumentException(\"message\");` to signal that a caller violated a precondition; throwing early with a clear message is far kinder to the next developer than letting a vague `NullReferenceException` erupt three calls deeper.\n\nThe golden rule is that exceptions are for exceptional conditions, not ordinary control flow. Do not use a `try`/`catch` to test whether a dictionary has a key — that is what `TryGetValue` is for, and the `Try...` pattern (returning a bool plus an `out` value) exists precisely so the expected \"not found\" case costs nothing. Reserve exceptions for genuinely unexpected failures.\n\nAsynchronous programming, the other half of robust real-world code, keeps a program responsive while waiting on slow operations — network calls, disk reads, timers. A method marked `async` can use the `await` keyword to pause until a `Task` completes, then resume, all without blocking the thread the way a synchronous wait would. An `async` method that produces a value returns `Task<T>`; one that produces nothing returns `Task`. `await Task.Delay(1000)` suspends for a second without tying up the thread, freeing it to do other work meanwhile.\n\nThe mental model is that `await` does not block — it yields control back to the caller and registers a continuation that fires when the awaited task finishes. This is why a UI stays interactive during a download and why a server can handle thousands of in-flight requests on a handful of threads. The everyday discipline: mark a method `async` only when it actually awaits something, prefer `await` over the blocking `.Result` or `.Wait()` (which can deadlock), and let asynchrony flow all the way up — \"async all the way\" — rather than bottling it up behind a synchronous wrapper.",
    code: "using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        var counts = new Dictionary<string, int> { [\"a\"] = 1 };\n        try {\n            int n = int.Parse(\"not a number\");\n            Console.WriteLine(n);\n        } catch (FormatException) {\n            Console.WriteLine(\"caught a bad parse\");\n        } finally {\n            Console.WriteLine(\"done\");\n        }\n    }\n}",
    runnable: true,
    exercise: {
      prompt: "In a try block, run int.Parse(\"oops\"); in the catch (FormatException) print \"bad input\". Expected: bad input",
      starter: "using System;\n\nclass Program {\n    static void Main() {\n        try {\n            int n = int.Parse(\"oops\");\n            Console.WriteLine(n);\n        }\n        // add a catch (FormatException) that prints \"bad input\"\n    }\n}\n",
      expected: "bad input",
    },
    takeaways: [
      "try/catch handles runtime exceptions; finally always runs.",
      "Catch the most specific exception type, not bare Exception.",
      "Exceptions are for exceptional cases — use Try-patterns for expected misses.",
      "async/await waits on Tasks without blocking the thread.",
    ],
    mistakes: [
      "Using try/catch as ordinary control flow — prefer TryGetValue.",
      "Catching bare Exception and swallowing it silently.",
      "Blocking on .Result or .Wait() instead of awaiting — risks deadlock.",
    ],
    next: { label: "Back to courses", href: "#/courses" },
  },
];

export const CSHARP_BASICS_COURSE = {
  id: "csharp-basics",
  title: "C# Basics",
  language: "csharp",
  color: "#9b4f96",
  blurb: "Go from your first Main method to LINQ and async, with runnable C# on every page.",
  estimatedHours: 7,
  externalResources: [
    { label: "C# docs — Microsoft Learn", href: "https://learn.microsoft.com/en-us/dotnet/csharp/" },
    { label: "C# tour of the language", href: "https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/" },
    { label: "C# fundamentals tutorials", href: "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/" },
    { label: "LINQ overview", href: "https://learn.microsoft.com/en-us/dotnet/csharp/linq/" },
    { label: "Asynchronous programming with async/await", href: "https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/" },
  ],
  lessons: CSHARP_LESSONS,
};
