// Kotlin Basics course module. Wired into the registry by src/content/courses.js.
// Lesson shape mirrors the other *_LESSONS arrays: each lesson carries a runnable
// Kotlin `code` sample plus an `exercise` whose `expected` is exact stdout that
// CoursePage auto-grades (trimmed, CRLF-normalized) via Judge0 (language 'kotlin').

const KOTLIN_LESSONS = [
  {
    id: "kt1",
    title: "1. Hello & main",
    intro: "A Kotlin program starts at a top-level `fun main()`. Unlike Java, you do not wrap it in a class — the compiler generates the class scaffolding for you, so the smallest runnable file is a single line: `fun main() { println(\"hi\") }`. The `fun` keyword introduces every function, `main` is the entry point the JVM looks for, and the body lives between braces. If you need the command-line tokens, declare `fun main(args: Array<String>)`; most of the time you do not, and the no-argument form is preferred.\n\n`println` writes a line to standard output and appends a newline; `print` writes without the newline. Both accept any value and call its `toString()` for you, so `println(42)` and `println(listOf(1, 2, 3))` both work without manual conversion. This is the single output call you will reach for in every early lesson, so internalize that `println` flushes a trailing newline — it matters when an exercise checks exact output.\n\nString templates are where Kotlin starts to feel modern. Inside a double-quoted string, `$name` interpolates a variable and `${expr}` interpolates an arbitrary expression. So `println(\"sum is ${2 + 3}\")` prints `sum is 5` with no concatenation and no format placeholders. Reach for templates instead of building strings with `+`; they read better and avoid the accidental `Int + String` ordering bugs that plague Java.\n\nStatements do not need semicolons. Kotlin's parser treats newlines as statement terminators, so a trailing `;` is legal but redundant — leave it off. Comments use `//` for a single line and `/* ... */` for a block, exactly as in Java and C.\n\nFunctions can return a value with an explicit `return`, or you can use the expression-body form `fun double(x: Int) = x * 2` when the body is a single expression. The compiler infers the return type from the expression, so you write less. The `Unit` type is Kotlin's `void` — a function that returns nothing actually returns the singleton `Unit`, but you almost never type it.\n\nKotlin compiles to JVM bytecode and interoperates with Java seamlessly, which is why every collection and exception you already know from Java is available here. But the surface syntax is leaner: no class wrapper for `main`, no `public static void`, no semicolons, and string templates instead of `String.format`. Start by getting comfortable printing values and interpolating them — every later lesson builds on that.",
    code: "fun main() {\n    val name = \"PGcode\"\n    val x = 7\n    println(\"$name: $x\")\n    println(\"sum is ${2 + 3}\")\n}",
    runnable: true,
    exercise: {
      prompt: "Set `subject` to \"Math\" and `score` to 95, then print them in the form `Math: 95` using a string template.",
      starter: "fun main() {\n    val subject = ...\n    val score = ...\n    // print \"<subject>: <score>\"\n}\n",
      expected: "Math: 95",
    },
    takeaways: [
      "main is a top-level function; no class wrapper needed.",
      "println flushes a trailing newline; print does not.",
      "String templates: $name and ${expr} interpolate directly.",
      "No semicolons required — newlines terminate statements.",
    ],
    mistakes: [
      "Wrapping main in a class out of Java habit — unnecessary in Kotlin.",
      "Using + concatenation where a $template reads cleaner.",
      "Forgetting that ${} (braces) is required for expressions, not bare $expr.",
    ],
    next: { label: "val / var & types", href: "#/courses/kotlin-basics/kt2" },
  },
  {
    id: "kt2",
    title: "2. val / var & types",
    intro: "Kotlin draws a hard line between read-only and mutable bindings. `val` declares a name you can assign exactly once — the reference cannot be re-pointed afterward. `var` declares a name you can reassign freely. The discipline the language nudges you toward is `val` by default, `var` only when you genuinely need to mutate. Read-only bindings make code easier to reason about: once you see `val total = ...` you know `total` will not change out from under you later in the function.\n\nNote that `val` controls the *binding*, not the object. A `val list = mutableListOf(1, 2)` cannot be reassigned to a different list, but you can still `list.add(3)` because the list object itself is mutable. Immutability of the reference and immutability of the contents are two separate ideas — keep them distinct.\n\nKotlin is statically typed but has powerful type inference. You rarely write the type because the compiler reads it off the initializer: `val x = 7` is `Int`, `val pi = 3.14` is `Double`, `val flag = true` is `Boolean`, `val s = \"hi\"` is `String`. When you do want to be explicit, the syntax is name-colon-type: `val x: Long = 7`. You must annotate when there is no initializer (`val x: Int` then assign later) or when you want a wider type than the literal implies.\n\nThe numeric types are `Byte`, `Short`, `Int`, `Long`, `Float`, `Double`. An integer literal defaults to `Int`; append `L` for `Long`. A decimal literal defaults to `Double`; append `f` for `Float`. Unlike Java, Kotlin does **not** auto-widen `Int` to `Long` in assignments — you call `.toLong()`, `.toDouble()`, etc. explicitly. That looks verbose but it stops the silent-overflow class of bugs where a multiplication happens in `Int` before widening.\n\nUnderscores are legal inside numeric literals for readability: `1_000_000`. Characters use single quotes (`'a'`) and are a distinct `Char` type, not an integer — to get the code point you call `.code`.\n\nConstants known at compile time use `const val` at the top level or inside an `object`/companion: `const val PI = 3.14159`. A plain `val` is computed at runtime; `const val` is inlined by the compiler and must be a primitive or `String`. Reach for `const val` for true constants and plain `val` for everything else.",
    code: "fun main() {\n    val name = \"Kotlin\"\n    var count = 0\n    count += 5\n    val big: Long = 1_000_000L\n    println(\"$name count=$count big=$big\")\n}",
    runnable: true,
    exercise: {
      prompt: "Declare a read-only `base` = 10 and a mutable `acc` starting at 0, add `base` to `acc` three times, then print `acc`. Expected: 30.",
      starter: "fun main() {\n    val base = 10\n    var acc = 0\n    // add base to acc three times\n    println(acc)\n}\n",
      expected: "30",
    },
    takeaways: [
      "val is assign-once; var is reassignable. Prefer val.",
      "Type inference reads the type off the initializer; annotate only when needed.",
      "No implicit numeric widening — call .toLong() / .toDouble() explicitly.",
      "const val is compile-time-inlined; plain val is runtime-computed.",
    ],
    mistakes: [
      "Thinking val makes the object immutable — it only fixes the binding.",
      "Expecting Int to auto-promote to Long like Java does — it does not.",
      "Reaching for var everywhere out of habit when val would do.",
    ],
    next: { label: "Null safety", href: "#/courses/kotlin-basics/kt3" },
  },
  {
    id: "kt3",
    title: "3. Null safety",
    intro: "Kotlin's headline feature is that the type system tracks nullability. A plain `String` can never hold `null`; if you want to allow it you write `String?` with a trailing question mark. The compiler then forces you to handle the null case before you dereference, which eliminates the vast majority of `NullPointerException`s that plague Java code. The non-null type and the nullable type are genuinely different types, and the compiler will not let you mix them carelessly.\n\nGiven a nullable value, you cannot just call `.length` on a `String?` — the compiler rejects it. You have several safe tools. The **safe call** operator `?.` returns `null` if the receiver is null instead of throwing: `name?.length` is `Int?`. Chain them: `user?.address?.city` short-circuits to `null` at the first null link. The **Elvis** operator `?:` supplies a fallback: `name?.length ?: 0` gives the length or `0`. Together they express \"give me the length, or zero if the whole thing is null\" in one line.\n\nWhen you are certain a value is non-null but the type says otherwise, the **not-null assertion** `!!` forces it: `name!!.length` throws an NPE if `name` is null. Treat `!!` as a code smell — every use is a place you have opted out of the safety net. Prefer `?.`, `?:`, or a smart-cast.\n\nThe **smart cast** is the cleanest path. After `if (name != null) { ... }`, inside the block the compiler knows `name` is non-null, so plain `name.length` works with no operator. This works for `val` references (the compiler can prove they did not change). For nullable `var`s captured across calls, smart-cast may not apply and you fall back to `?.`.\n\nFor the common \"do this only if non-null\" pattern, the `let` scope function pairs with `?.`: `name?.let { println(it.length) }` runs the block only when `name` is non-null, binding it to `it`. This is idiomatic Kotlin for guarding a block on nullability.\n\nPlatform types are the one sharp edge: values coming from Java have unknown nullability (shown as `String!` in tooling), and Kotlin trusts you. If a Java method can return null and you treat it as non-null, you get an NPE at the first dereference. When calling into Java, decide the nullability yourself and annotate accordingly.\n\nThe payoff: once your types are honest about nullability, the compiler catches the bug before it ships rather than the user catching it at runtime.",
    code: "fun main() {\n    val name: String? = null\n    println(name?.length ?: -1)\n    val city: String? = \"Pune\"\n    city?.let { println(\"len=${it.length}\") }\n}",
    runnable: true,
    exercise: {
      prompt: "Given `val word: String? = null`, print its length using the Elvis operator with a fallback of 0. Expected: 0.",
      starter: "fun main() {\n    val word: String? = null\n    // print word's length, or 0 if null\n}\n",
      expected: "0",
    },
    takeaways: [
      "String can never be null; String? can — they are different types.",
      "Safe call ?. short-circuits to null; Elvis ?: supplies a fallback.",
      "!! forces non-null and throws on null — treat it as a smell.",
      "Smart casts narrow String? to String inside an if (x != null) block.",
    ],
    mistakes: [
      "Sprinkling !! to silence the compiler instead of handling null.",
      "Trusting platform types from Java without checking for null.",
      "Forgetting smart-cast does not apply to mutable vars captured across calls.",
    ],
    next: { label: "Functions & default args", href: "#/courses/kotlin-basics/kt4" },
  },
  {
    id: "kt4",
    title: "4. Functions & default args",
    intro: "A Kotlin function is `fun name(params): ReturnType { body }`. Parameters are written name-first, `name: Type`, and the return type follows the parameter list after a colon. A function that returns nothing has return type `Unit`, which you omit by convention. When the body is a single expression you drop the braces and the `return` and use the expression-body form: `fun square(x: Int) = x * x`. The compiler infers the return type from the expression, though spelling it out (`fun square(x: Int): Int = x * x`) aids readability in a public API.\n\n**Default arguments** let a parameter carry a fallback value: `fun greet(name: String, greeting: String = \"Hello\")`. Callers can omit `greeting` and get the default. This single feature removes most of the overload explosion you write in Java — instead of five `greet` overloads you write one function with defaults. Defaults are evaluated at the call site, and a default can reference earlier parameters.\n\n**Named arguments** pair beautifully with defaults. At the call site you can pass `greet(name = \"Sam\", greeting = \"Hi\")`, which makes the call self-documenting and lets you skip middle parameters that have defaults: `connect(host, timeout = 30)` while leaving `port`, `retries`, and the rest at their defaults. Named arguments also let you reorder — once you name them, position no longer matters.\n\nParameters are always `val` inside the body — you cannot reassign a parameter. If you need a mutable working copy, declare a local `var`. This is a deliberate constraint that keeps functions easy to read.\n\nKotlin supports **varargs** with the `vararg` modifier: `fun sumAll(vararg nums: Int): Int`. Inside the function `nums` is an `IntArray`. To forward an existing array into a vararg, use the spread operator `*`: `sumAll(*myArray)`.\n\nFunctions can be declared at the top level (no class needed), nested inside other functions (local functions, which can capture the enclosing variables), or as members of a class. Local functions are handy for breaking a long function into named steps without polluting the file's namespace.\n\nReturning multiple values is idiomatic via `Pair` or `Triple`, or a small `data class` when the fields deserve names. Destructuring on the calling side — `val (a, b) = minMax(list)` — unpacks the result cleanly. Reach for default and named arguments first; they collapse the boilerplate that overloading and builder patterns require elsewhere.",
    code: "fun greet(name: String, greeting: String = \"Hello\") = \"$greeting, $name!\"\n\nfun main() {\n    println(greet(\"Sam\"))\n    println(greet(\"Sam\", greeting = \"Hi\"))\n}",
    runnable: true,
    exercise: {
      prompt: "Write `fun power(base: Int, exp: Int = 2): Int` returning base^exp, then print power(5) (uses the default). Expected: 25.",
      starter: "fun power(base: Int, exp: Int = 2): Int {\n    var result = 1\n    // multiply base exp times\n    return result\n}\n\nfun main() {\n    println(power(5))\n}\n",
      expected: "25",
    },
    takeaways: [
      "Expression body: fun f(x) = expr — return type inferred.",
      "Default arguments remove overload explosion; one function does it all.",
      "Named arguments make calls self-documenting and let you skip defaults.",
      "vararg collects extra args into an array; spread with * to forward.",
    ],
    mistakes: [
      "Trying to reassign a parameter — they are val; use a local var.",
      "Writing overloads where a default argument would do.",
      "Forgetting the spread operator * when forwarding an array to a vararg.",
    ],
    next: { label: "Control flow & when", href: "#/courses/kotlin-basics/kt5" },
  },
  {
    id: "kt5",
    title: "5. Control flow & when",
    intro: "In Kotlin, `if` is an **expression**, not just a statement — it returns a value. So `val label = if (temp >= 80) \"hot\" else \"cold\"` assigns directly, replacing Java's ternary. When you use `if` as an expression the `else` branch is mandatory, because every path must produce a value. Used as a plain statement (no assignment) the `else` is optional. The last expression in each branch's block is its value, so a multi-line branch still yields a result.\n\nThe star of Kotlin branching is `when`, a far more powerful `switch`. In its argument form, `when (x) { ... }` matches `x` against each branch: a literal (`1 -> ...`), a set (`2, 3 -> ...`), a range (`in 4..10 -> ...`), a type (`is String -> ...`), or the catch-all `else`. There is no fall-through — exactly one branch runs — so you never write `break`. Like `if`, `when` is an expression: assign its result or `return` it.\n\n`when` also has an argument-less form that reads like a clean `if/else if` chain: `when { temp >= 80 -> \"hot\"; temp >= 60 -> \"nice\"; else -> \"cold\" }`. Each branch is a boolean condition and the first true one wins. This form is the idiomatic replacement for a long `else if` ladder.\n\nWhen `when` is used as an expression, it must be exhaustive — the compiler requires an `else`, unless you are matching over a sealed type or an enum where every case is covered. Exhaustiveness checking is a real safety feature: add a new enum constant and the compiler flags every `when` that no longer covers all cases.\n\nLoops come in the usual shapes but with cleaner ranges. `for (i in 1..5)` iterates inclusively `1` through `5`. `until` excludes the upper bound: `for (i in 0 until n)` is the classic zero-to-n-minus-one. `downTo` counts backward, and `step` changes the stride: `for (i in 10 downTo 0 step 2)`. To iterate a collection with its index, use `for ((i, v) in list.withIndex())`.\n\n`while` and `do-while` work as you expect. `break` and `continue` apply to the nearest loop; labeled forms (`break@outer`) target an enclosing loop when you have nested iteration. Ranges themselves are first-class objects — `val r = 1..100` — and you can test membership with `if (x in r)`, which is the readable way to write a bounds check.",
    code: "fun describe(n: Int) = when {\n    n < 0 -> \"negative\"\n    n == 0 -> \"zero\"\n    n in 1..9 -> \"small\"\n    else -> \"big\"\n}\n\nfun main() {\n    for (x in listOf(-2, 0, 5, 42)) println(describe(x))\n}",
    runnable: true,
    exercise: {
      prompt: "Use a for loop over 1..5 and a `when` to sum only the values in the range 2..4, then print the total. Expected: 9.",
      starter: "fun main() {\n    var total = 0\n    for (i in 1..5) {\n        // add i only when it is in 2..4\n    }\n    println(total)\n}\n",
      expected: "9",
    },
    takeaways: [
      "if is an expression that returns a value; else is required when used so.",
      "when replaces switch: literals, sets, ranges, types, no fall-through.",
      "Argument-less when { cond -> ... } is a clean if/else-if ladder.",
      "Ranges: 1..5 (inclusive), 0 until n (exclusive), downTo, step.",
    ],
    mistakes: [
      "Forgetting the mandatory else when when is used as an expression.",
      "Writing 0..n when you meant 0 until n — off-by-one at the upper bound.",
      "Adding break in a when out of switch habit — there is no fall-through.",
    ],
    next: { label: "Collections", href: "#/courses/kotlin-basics/kt6" },
  },
  {
    id: "kt6",
    title: "6. Collections",
    intro: "Kotlin splits every collection into a read-only interface and a mutable one. `listOf(...)` builds an immutable `List`; `mutableListOf(...)` builds a `MutableList` you can `add` to. Same split for sets (`setOf` / `mutableSetOf`) and maps (`mapOf` / `mutableMapOf`). The read-only versions do not have `add`/`remove` in their interface at all, so the compiler stops accidental mutation. Default to the read-only factory and reach for the mutable one only when you actually modify the collection.\n\n**Lists** are ordered, index-accessible sequences. Build one with `listOf(1, 2, 3)`, read with `list[i]` (sugar for `get`), get the count with `.size`. Useful members: `first()`, `last()`, `isEmpty()`, `contains(x)` (or `x in list`), `indexOf(x)`. For a mutable list, `add`, `removeAt(i)`, and `[i] = v` (sugar for `set`). Slicing with `list.subList(from, to)` returns a view.\n\n**Sets** hold unique elements with no duplicates and fast membership testing. `setOf(1, 1, 2)` collapses to `{1, 2}`. The natural operations read like math: `a union b`, `a intersect b`, `a subtract b`. Use a set whenever you only care whether something is present, not how many times.\n\n**Maps** are key-to-value associations. Build with `mapOf(\"a\" to 1, \"b\" to 2)` — the `to` infix function creates a `Pair`. Read with `map[key]`, which returns a nullable value (`null` if absent), so combine with Elvis: `map[k] ?: 0`. `getOrDefault(k, d)` and `getOrElse(k) { d }` give explicit fallbacks. Iterate with `for ((k, v) in map)` which destructures each entry. On a `MutableMap`, `map[k] = v` inserts or updates, and `getOrPut(k) { default }` lazily initializes.\n\nKotlin ships a deep standard library of functional operations on every collection: `map`, `filter`, `forEach`, `sumOf`, `maxOrNull`, `sorted`, `groupBy`, `associate`. These return new collections and chain fluently — you will see them everywhere in idiomatic Kotlin and the next lesson on lambdas makes them sing.\n\nA few gotchas. The read-only types are read-only *views*, not deep-immutable — a `List` reference obtained from a `MutableList` still reflects the underlying mutations. The element type is part of the type (`List<Int>` vs `List<String>`), and an empty literal needs a hint: `emptyList<Int>()`. And map access returns a nullable, so reaching for `map[k]` and immediately dereferencing without an Elvis or `!!` is the most common beginner null bug here.",
    code: "fun main() {\n    val nums = listOf(3, 1, 4, 1, 5)\n    val unique = nums.toSet()\n    val counts = mutableMapOf<Int, Int>()\n    for (n in nums) counts[n] = (counts[n] ?: 0) + 1\n    println(\"distinct=${unique.size} ones=${counts[1]}\")\n}",
    runnable: true,
    exercise: {
      prompt: "Build a list [1,2,3,4,5], then sum its elements with a loop and print the total. Expected: 15.",
      starter: "fun main() {\n    val nums = listOf(1, 2, 3, 4, 5)\n    var sum = 0\n    // add each element to sum\n    println(sum)\n}\n",
      expected: "15",
    },
    takeaways: [
      "Read-only (listOf/setOf/mapOf) vs mutable (mutableListOf/...) is a type-level split.",
      "Map access map[k] returns a nullable — pair it with Elvis ?: or getOrDefault.",
      "Sets dedupe and give union / intersect / subtract.",
      "Build map entries with the `to` infix: \"a\" to 1.",
    ],
    mistakes: [
      "Calling add on a listOf result — it is read-only; use mutableListOf.",
      "Dereferencing map[k] without handling the null when the key is absent.",
      "Forgetting the type hint on an empty literal: emptyList<Int>().",
    ],
    next: { label: "Lambdas & higher-order fns", href: "#/courses/kotlin-basics/kt7" },
  },
  {
    id: "kt7",
    title: "7. Lambdas & higher-order functions",
    intro: "A lambda is an anonymous function written between braces: `{ x -> x * 2 }`. The parameters come before the arrow, the body after. When a lambda has a single parameter you can drop the declaration entirely and use the implicit name `it`: `{ it * 2 }`. A lambda is a value — you can store it in a `val`, pass it to a function, or return it. Its type is written with an arrow: `(Int) -> Int` is a function taking an `Int` and returning an `Int`.\n\nA **higher-order function** is one that takes a function as a parameter or returns one. The collection library is built from them. `list.map { it * 2 }` transforms every element; `list.filter { it > 0 }` keeps the ones matching a predicate; `list.forEach { println(it) }` runs a side effect per element. These chain: `list.filter { it % 2 == 0 }.map { it * it }.sum()` reads top to bottom as a pipeline. Each call returns a new collection, leaving the original untouched.\n\nKotlin has a **trailing-lambda** convention: when the last argument to a function is a lambda, you move it outside the parentheses. So `list.fold(0) { acc, x -> acc + x }` rather than `list.fold(0, { acc, x -> acc + x })`. If the lambda is the only argument, you drop the parentheses entirely — that is why `map { ... }` has no parens. This convention is what makes Kotlin DSLs and collection chains read so cleanly.\n\nThe heavy hitters beyond `map`/`filter`: `fold(initial) { acc, x -> ... }` reduces a collection to a single value with an explicit accumulator; `reduce { acc, x -> ... }` is the same but seeds with the first element; `sumOf { it.price }` sums a projection; `groupBy { it.category }` builds a map of buckets; `associateWith { compute(it) }` builds a map from keys; `sortedBy { it.age }` orders by a selector; `any`/`all`/`none` test predicates; `count { it > 0 }` counts matches.\n\nLambdas **capture** their enclosing scope — unlike Java, they can read *and* modify local variables of the surrounding function (Kotlin compiles the captured `var` into a wrapper). That makes accumulator patterns natural but means a captured `var` mutated inside a lambda has real effects outside it.\n\nFor passing an existing function where a lambda is expected, use a **function reference**: `list.map(::transform)` or `list.map(String::length)`. It is shorthand for `{ transform(it) }`. Reach for references when a named function already does exactly what the lambda would.",
    code: "fun main() {\n    val nums = listOf(1, 2, 3, 4, 5, 6)\n    val result = nums.filter { it % 2 == 0 }.map { it * it }.sum()\n    println(result)\n}",
    runnable: true,
    exercise: {
      prompt: "From [1,2,3,4,5], keep the odd numbers, double each, and sum them with a chain of filter/map/sum. Expected: 18.",
      starter: "fun main() {\n    val nums = listOf(1, 2, 3, 4, 5)\n    val total = nums\n        // filter odds, map to double, sum\n    println(total)\n}\n",
      expected: "18",
    },
    takeaways: [
      "Lambdas are values: { x -> body }, or { it } for a single param.",
      "Higher-order functions take/return functions — the basis of map/filter/fold.",
      "Trailing-lambda convention moves the last lambda outside the parens.",
      "Function references (::name, Type::member) pass an existing function.",
    ],
    mistakes: [
      "Overusing it in nested lambdas where it becomes ambiguous — name params there.",
      "Forgetting map/filter return NEW collections; the original is unchanged.",
      "Reaching for fold when sum / sumOf / count already express the intent.",
    ],
    next: { label: "Classes & data classes", href: "#/courses/kotlin-basics/kt8" },
  },
  {
    id: "kt8",
    title: "8. Classes & data classes",
    intro: "A Kotlin class is declared with `class Name(...)` where the parentheses hold the **primary constructor**. Declaring a parameter as `val` or `var` inside the primary constructor makes it a property in one stroke: `class Point(val x: Int, val y: Int)` gives you an immutable `x` and `y` with backing fields, getters, and (for `var`) setters — no boilerplate. This collapses the field-plus-constructor-plus-getter ceremony of Java into a single line.\n\nProperties can have custom accessors. A computed property uses a `get()` with no backing field: `val magnitude get() = sqrt((x*x + y*y).toDouble())`. A property with logic on write defines `set(value) { ... }`. The `init { }` block runs as part of the primary constructor for any setup that needs statements rather than a single initializer expression. Secondary constructors use `constructor(...) : this(...)` and must delegate to the primary.\n\nInstantiation needs **no `new` keyword** — just call the class like a function: `val p = Point(3, 4)`. Member functions are declared with `fun` inside the class body and access properties directly by name.\n\nThe **data class** is Kotlin's killer feature for value types. Prefix a class with `data` and the compiler generates `equals`, `hashCode`, `toString`, `copy`, and `componentN` functions from the primary-constructor properties. So `data class User(val name: String, val age: Int)` gives you structural equality (two users with the same fields are `==`), a readable `toString` (`User(name=Sam, age=30)`), and a `copy(age = 31)` that returns a new instance with one field changed. This is exactly what you want for DTOs, records, and immutable value objects — and it is one keyword.\n\nThe generated `componentN` functions enable **destructuring**: `val (name, age) = user` unpacks the data class into locals, in declaration order. This pairs with `for ((k, v) in map)` which is destructuring map entries the same way.\n\nA few rules: data classes need at least one primary-constructor parameter, and only those parameters participate in the generated `equals`/`hashCode`/`toString` — a property declared in the body is excluded. Data classes can have a body with extra functions, but cannot be `abstract`, `open`, `sealed`, or `inner`. Use `copy` rather than mutation to evolve immutable instances; it is the idiomatic way to make a changed version while keeping the original intact.\n\nVisibility defaults to `public`. Use `private`, `protected`, or `internal` (module-visible) to narrow it.",
    code: "data class User(val name: String, val age: Int)\n\nfun main() {\n    val u = User(\"Sam\", 30)\n    val older = u.copy(age = 31)\n    val (name, age) = older\n    println(\"$name is $age — equal? ${u == User(\"Sam\", 30)}\")\n}",
    runnable: true,
    exercise: {
      prompt: "Define `data class Box(val w: Int, val h: Int)`, create Box(4, 5), and print its area (w*h). Expected: 20.",
      starter: "data class Box(val w: Int, val h: Int)\n\nfun main() {\n    val b = Box(4, 5)\n    // print the area\n}\n",
      expected: "20",
    },
    takeaways: [
      "val/var in the primary constructor declares a property in one line.",
      "No new keyword — call the class like a function to instantiate.",
      "data class auto-generates equals, hashCode, toString, copy, componentN.",
      "copy(field = x) evolves an immutable instance; destructure with val (a, b).",
    ],
    mistakes: [
      "Expecting body-declared properties to count in a data class's equals — they don't.",
      "Using == on a non-data class and getting reference equality, not structural.",
      "Mutating a data class instead of using copy to make a changed version.",
    ],
    next: { label: "Inheritance & interfaces", href: "#/courses/kotlin-basics/kt9" },
  },
  {
    id: "kt9",
    title: "9. Inheritance & interfaces",
    intro: "Kotlin classes are **final by default** — you cannot subclass them unless you mark the parent `open`. This is the opposite of Java and a deliberate design choice: inheritance is opt-in, so a class author decides explicitly whether the class is meant to be extended. To allow subclassing, write `open class Animal`. To override a member, the parent member must be `open` and the child must use the `override` keyword. That keyword is mandatory, not decorative — it prevents the accidental-override and accidental-shadow bugs that silent overriding causes.\n\nA subclass declares its parent in the header and calls the parent constructor there: `class Dog(name: String) : Animal(name)`. Inside an overriding member, `super.method()` calls the parent's version. An `abstract class` can declare members without bodies (`abstract fun sound(): String`); abstract members are implicitly open and must be implemented by concrete subclasses. You cannot instantiate an abstract class directly.\n\n**Interfaces** declare a contract and may include default method implementations and abstract properties (but no backing-field state). A class implements one or more interfaces by listing them after the colon, comma-separated: `class Dog : Animal(), Comparable<Dog>, Trackable`. Interfaces are how Kotlin does the \"multiple types\" part that single class inheritance forbids — a class extends at most one class but implements any number of interfaces.\n\nWhen two interfaces supply conflicting default implementations, the implementing class must override the member and disambiguate with the qualified-super syntax `super<InterfaceA>.method()`. The compiler forces you to resolve the diamond rather than picking silently.\n\nProperties can be overridden too, following the same `open`/`override` rules. An interface can declare an abstract `val name: String` that the implementer must provide, either as a constructor property or a custom getter.\n\nFor the common case of a fixed set of subtypes — a closed hierarchy you control — reach for a **sealed class** or **sealed interface**. All direct subclasses must be declared in the same file (or module), which lets a `when (shape)` over the sealed type be **exhaustive without an `else`**: the compiler knows every case and flags any you miss when you add a new subtype later. Sealed hierarchies are the Kotlin idiom for modeling \"one of these known shapes\" — results, AST nodes, UI states — and they pair perfectly with the `when`-as-expression from the control-flow lesson.\n\nPrefer composition and interfaces over deep inheritance trees; Kotlin's defaults nudge you that way.",
    code: "abstract class Shape { abstract fun area(): Double }\nclass Circle(val r: Double) : Shape() {\n    override fun area() = Math.PI * r * r\n}\n\nfun main() {\n    val s: Shape = Circle(2.0)\n    println(\"%.2f\".format(s.area()))\n}",
    runnable: true,
    exercise: {
      prompt: "Define `interface Named { val name: String }` and a class `Cat(override val name: String) : Named`, then print Cat(\"Whiskers\").name. Expected: Whiskers.",
      starter: "interface Named { val name: String }\nclass Cat(override val name: String) : Named\n\nfun main() {\n    val c = Cat(\"Whiskers\")\n    // print the name\n}\n",
      expected: "Whiskers",
    },
    takeaways: [
      "Classes are final by default; mark open to allow subclassing.",
      "override is a required keyword; the parent member must be open or abstract.",
      "A class extends one class but implements any number of interfaces.",
      "sealed classes make when exhaustive without an else for known subtypes.",
    ],
    mistakes: [
      "Forgetting open on a parent and being unable to subclass it.",
      "Omitting the override keyword — it is mandatory, not optional.",
      "Calling the parent constructor with () missing: : Animal() not : Animal.",
    ],
    next: { label: "Generics", href: "#/courses/kotlin-basics/kt10" },
  },
  {
    id: "kt10",
    title: "10. Generics",
    intro: "Generics let a class or function work over a type parameter instead of a fixed type, keeping it both reusable and type-safe. A generic function declares its type parameter before the name: `fun <T> firstOrNull(list: List<T>): T?`. A generic class declares it after the name: `class Box<T>(val value: T)`. At the call site the compiler infers `T` from the arguments, so you write `Box(42)` and get a `Box<Int>` without spelling the type out — annotate only when inference cannot decide.\n\nWithout generics you would either duplicate code per type or fall back to `Any` and lose type information, forcing unsafe casts. With generics, `List<String>` and `List<Int>` share one implementation but the compiler still rejects putting an `Int` into a `List<String>`. This is the same mechanism behind every collection you have used so far.\n\n**Bounds** constrain a type parameter to a supertype: `fun <T : Comparable<T>> maxOf(a: T, b: T): T` requires `T` to be comparable, so inside the function you can call `a > b`. The default upper bound is `Any?` (nullable). Multiple bounds use a `where` clause: `fun <T> f(x: T) where T : Comparable<T>, T : CharSequence`.\n\n**Variance** controls how a generic type relates to subtyping. By default `Box<T>` is *invariant*: `Box<Int>` is not a subtype of `Box<Number>` even though `Int` is a subtype of `Number`. The `out` modifier makes a parameter *covariant* (producer-only): `class Source<out T>` means `Source<Int>` *is* a `Source<Number>`, but `T` can only appear in output positions (return types), never as a parameter. The `in` modifier makes it *contravariant* (consumer-only): `class Sink<in T>` means `Sink<Number>` is a `Sink<Int>`, and `T` appears only in input positions. The mnemonic is \"out for producers, in for consumers\" — `List<out T>` is read-only and covariant for exactly this reason.\n\nAt a single use site you can apply variance with a **type projection**: `fun copy(from: Array<out Any>, to: Array<Any>)` lets `from` be an array of any subtype safely.\n\nKotlin **erases** generic types at runtime, just like Java — `List<Int>` and `List<String>` are the same class at runtime, so `x is List<Int>` is not allowed. The escape hatch is `reified` type parameters on `inline` functions: `inline fun <reified T> isType(x: Any) = x is T` keeps the type available at runtime because the compiler inlines the body with the concrete type substituted. Reach for `reified` when you genuinely need to check or instantiate the type parameter.\n\nThe star projection `Box<*>` means \"a `Box` of some unknown type\" when you do not care about the specific argument.",
    code: "class Box<T>(val value: T) {\n    fun get(): T = value\n}\n\nfun <T : Comparable<T>> larger(a: T, b: T): T = if (a >= b) a else b\n\nfun main() {\n    println(Box(\"hi\").get())\n    println(larger(3, 9))\n}",
    runnable: true,
    exercise: {
      prompt: "Write `fun <T> pairUp(a: T, b: T): List<T>` returning listOf(a, b), then print pairUp(7, 8).sum(). Expected: 15.",
      starter: "fun <T> pairUp(a: T, b: T): List<T> = listOf(a, b)\n\nfun main() {\n    val p = pairUp(7, 8)\n    // print the sum of the pair\n}\n",
      expected: "15",
    },
    takeaways: [
      "fun <T> before the name; class Name<T> after — inference fills T in.",
      "Bounds (T : Comparable<T>) constrain the type and unlock its members.",
      "out = covariant producer, in = contravariant consumer (out/in mnemonic).",
      "Generics are erased at runtime; use inline + reified to keep the type.",
    ],
    mistakes: [
      "Writing x is List<Int> — erasure forbids it; use List<*> or reified.",
      "Expecting Box<Int> to be a Box<Number> by default — it is invariant.",
      "Forgetting that out-typed params can't appear in input positions.",
    ],
    next: { label: "Extension functions", href: "#/courses/kotlin-basics/kt11" },
  },
  {
    id: "kt11",
    title: "11. Extension functions",
    intro: "An extension function adds a method to an existing type **without modifying that type or subclassing it**. You write `fun Type.name(...)` and the function becomes callable as `value.name(...)` on any instance of `Type`. The classic example: `fun String.shout() = this.uppercase() + \"!\"` lets you call `\"hi\".shout()` even though `String` is a final class from the standard library. Inside the body, `this` refers to the receiver — the instance you called it on — and you can access its public members directly.\n\nThis is how Kotlin keeps classes small while still offering rich APIs. Most of the collection operations you have used — `filter`, `map`, `sumOf`, `first` — are extension functions on `Iterable` and `Collection`, not members baked into the interfaces. That is why the standard library can add new operations release after release without changing the core types.\n\nThe crucial mental model: extensions are **resolved statically**, by the declared (compile-time) type of the receiver, not its runtime type. They are syntactic sugar for a top-level function whose first parameter is the receiver. So `fun View.show()` compiles to roughly `show(view)`. Because dispatch is static, an extension does **not** participate in polymorphism — if a base type and a subtype both have an extension of the same name, the one chosen depends on the static type of the variable, not the actual object. And a member function always wins over an extension with the same signature.\n\nExtensions can be generic (`fun <T> List<T>.second(): T = this[1]`), can have a nullable receiver (`fun String?.orEmpty(): String = this ?: \"\"` — handy because the body can handle the null case), and can be **extension properties** with a custom getter: `val String.firstChar: Char get() = this[0]`. Extension properties cannot have backing fields, so they must be computed.\n\nVisibility and imports matter: an extension defined in another file or package must be imported to be used, exactly like any top-level function. Define them at the top level for reuse, or inside a class to scope them to that class's methods.\n\nGood uses: adapting a third-party or standard-library type to your domain, breaking a long chain into a readable named step, or writing small DSL-like helpers. The caution: because they are static, do not reach for extensions when you actually need runtime polymorphism — that is what member functions and interfaces are for. Used well, extensions are the single most ergonomic feature for making code read like the problem domain.",
    code: "fun String.shout(): String = this.uppercase() + \"!\"\nfun <T> List<T>.second(): T = this[1]\n\nfun main() {\n    println(\"hi\".shout())\n    println(listOf(\"a\", \"b\", \"c\").second())\n}",
    runnable: true,
    exercise: {
      prompt: "Write an extension `fun Int.squared(): Int` returning this*this, then print 6.squared(). Expected: 36.",
      starter: "fun Int.squared(): Int = ...\n\nfun main() {\n    // print 6.squared()\n}\n",
      expected: "36",
    },
    takeaways: [
      "fun Type.name(...) adds a method without touching or subclassing Type.",
      "Inside the body, this is the receiver instance you called it on.",
      "Resolved statically by declared type — no polymorphism; members win.",
      "Most collection ops (map/filter/sumOf) are themselves extensions.",
    ],
    mistakes: [
      "Expecting an extension to override a member — members always win.",
      "Assuming runtime-polymorphic dispatch — extensions dispatch on static type.",
      "Forgetting to import an extension defined in another file.",
    ],
    next: { label: "Scope functions", href: "#/courses/kotlin-basics/kt12" },
  },
  {
    id: "kt12",
    title: "12. Scope functions",
    intro: "Kotlin's standard library ships five scope functions — `let`, `run`, `with`, `apply`, `also` — that execute a block in the context of an object. They do not add new capabilities; they restructure code so a short block of operations on one object reads cleanly. Choosing among them comes down to two questions: how is the object referenced inside the block (`it` or `this`), and what does the call return (the object itself or the lambda's result).\n\n**`let`** takes the object as `it` and returns the lambda's result. Its signature pairs with the safe call: `value?.let { ... }` runs the block only when `value` is non-null, which is the idiomatic null-guard. Use it to transform a value into something else, or to scope a non-null check.\n\n**`run`** takes the object as `this` and returns the lambda's result. It is `let` with a `this` receiver — handy when the block calls several members of the object and you want the terminal value: `val len = name.run { trim().length }`. There is also a no-receiver `run { ... }` that just executes a block and returns its value, useful for a local computed `val`.\n\n**`with`** is not an extension — you pass the object as an argument: `with(builder) { append(\"a\"); append(\"b\") }`. Receiver is `this`, returns the lambda result. Reach for it when you make many calls on the same object and do not need a null check.\n\n**`apply`** takes the object as `this` and returns **the object itself**. This makes it the configuration idiom: `Person().apply { name = \"Sam\"; age = 30 }` sets fields and yields the configured `Person`. Use it whenever you build-then-return.\n\n**`also`** takes the object as `it` and returns **the object itself**. It is the side-effect idiom: `list.also { println(\"size=${it.size}\") }` logs or validates without breaking a call chain, passing the original through. Use it for logging, debugging, or any peek-and-continue step.\n\nThe selection table is worth memorizing: returns-object → `apply`/`also`; returns-result → `let`/`run`/`with`. Receiver `this` → `run`/`with`/`apply`; receiver `it` → `let`/`also`. Pick the one whose return and receiver match your intent and the call site reads like a sentence.\n\nThe caution is overuse: nesting scope functions, or chaining four of them, quickly becomes harder to read than plain statements. A single, well-chosen scope function clarifies; a stack of them obscures. Use them to collapse boilerplate and null checks — not to prove you know all five.",
    code: "data class Person(var name: String = \"\", var age: Int = 0)\n\nfun main() {\n    val p = Person().apply {\n        name = \"Sam\"\n        age = 30\n    }\n    val label = p.let { \"${it.name}/${it.age}\" }\n    println(label)\n}",
    runnable: true,
    exercise: {
      prompt: "Use `apply` to build a StringBuilder, append \"go\" then \"!\", and print its toString(). Expected: go!.",
      starter: "fun main() {\n    val sb = StringBuilder().apply {\n        // append \"go\" then \"!\"\n    }\n    println(sb.toString())\n}\n",
      expected: "go!",
    },
    takeaways: [
      "apply/also return the object; let/run/with return the lambda result.",
      "run/with/apply use this as receiver; let/also use it.",
      "value?.let { } is the idiomatic non-null guard block.",
      "apply configures-and-returns; also peeks (logs) and passes through.",
    ],
    mistakes: [
      "Picking let when you wanted the object back — that is apply/also.",
      "Nesting scope functions until the code is harder to read than statements.",
      "Confusing this (run/with/apply) vs it (let/also) inside the block.",
    ],
    next: { label: "Coroutines intro", href: "#/courses/kotlin-basics/kt13" },
  },
  {
    id: "kt13",
    title: "13. Coroutines intro",
    intro: "Coroutines are Kotlin's answer to asynchronous and concurrent code: they let you write sequential-looking logic that can suspend and resume without blocking a thread. A blocked thread is an expensive, scarce OS resource; a *suspended* coroutine costs almost nothing, so you can run hundreds of thousands of concurrent coroutines on a handful of threads. The model replaces callback pyramids and `Future` chaining with straight-line code that reads top to bottom.\n\nThe core keyword is `suspend`. A `suspend fun` is one that may pause partway through and resume later — for example, while waiting on network I/O. The compiler transforms it into a state machine under the hood, but you write it as if it were ordinary code. A `suspend` function can only be called from another `suspend` function or from inside a coroutine; it cannot be called from plain `main` directly, which is the rule that trips up newcomers.\n\nTo bridge from ordinary code into the coroutine world you need a **coroutine builder**. `runBlocking { ... }` starts a coroutine and blocks the current thread until it finishes — it is the standard way to call suspend code from `main` or from a test. Inside a coroutine scope, `launch { ... }` starts a new coroutine that runs concurrently and returns a `Job` you can join or cancel (fire-and-forget work), while `async { ... }` starts one that computes a result, returning a `Deferred<T>` whose value you retrieve with `.await()`. Use `launch` for side effects, `async` when you want a value back.\n\n`delay(ms)` is the suspending counterpart to `Thread.sleep` — it pauses the coroutine without blocking the underlying thread, freeing it to run other coroutines in the meantime. That non-blocking pause is the whole point: a thousand coroutines each `delay`-ing share one thread happily.\n\n**Structured concurrency** is the safety model: every coroutine runs inside a scope, and a scope does not complete until all the coroutines it launched have finished. `coroutineScope { launch {...}; launch {...} }` waits for both children, and if one fails it cancels its siblings and propagates the exception. This means no leaked background work and no orphaned coroutines — the parent owns the lifetime of its children.\n\nDispatchers decide which thread pool runs the work: `Dispatchers.Default` for CPU-bound work, `Dispatchers.IO` for blocking I/O, `Dispatchers.Main` for UI threads (Android). You switch with `withContext(Dispatchers.IO) { ... }`, which moves a block onto another dispatcher and back. Coroutines live in the `kotlinx.coroutines` library, not the standard library, so a real project adds the dependency; the runnable example here uses `runBlocking` and `delay`, which are the two you meet first.",
    code: "import kotlinx.coroutines.*\n\nfun main() = runBlocking {\n    val a = async { delay(10); 7 }\n    val b = async { delay(10); 8 }\n    println(a.await() + b.await())\n}",
    runnable: true,
    exercise: {
      prompt: "Inside runBlocking, use async to compute 6 and 4 concurrently, await both, and print their sum. Expected: 10.",
      starter: "import kotlinx.coroutines.*\n\nfun main() = runBlocking {\n    val x = async { 6 }\n    val y = async { 4 }\n    // print x + y awaited\n}\n",
      expected: "10",
    },
    takeaways: [
      "suspend functions can pause and resume without blocking a thread.",
      "runBlocking bridges plain main into the coroutine world.",
      "launch = fire-and-forget (Job); async = compute a value (Deferred + await).",
      "Structured concurrency: a scope waits for all its children to finish.",
    ],
    mistakes: [
      "Calling a suspend function from non-suspend code without a builder.",
      "Using Thread.sleep instead of delay — sleep blocks the thread.",
      "Forgetting kotlinx.coroutines is a separate library dependency.",
    ],
    next: { label: "Sealed classes & when", href: "#/courses/kotlin-basics/kt14" },
  },
  {
    id: "kt14",
    title: "14. Sealed classes & exhaustive when",
    intro: "A sealed class (or sealed interface) defines a **closed hierarchy**: a fixed, compiler-known set of subtypes, all declared in the same module (and, for sealed classes, the same package). Because the compiler can see every possible subtype, it can prove a `when` over a sealed type is **exhaustive** — covering all cases — and let you omit the `else` branch. Better still, when you add a new subtype later, every non-exhaustive `when` becomes a compile error pointing you at exactly the code that needs updating. That is the safety property sealed types buy you, and it is why they are the idiomatic way to model \"a value that is one of these known shapes.\"\n\nDeclare one with `sealed class Result` and its variants as nested or same-file subclasses: `class Success(val data: String) : Result()` and `class Failure(val error: String) : Result()`. Often the variants are data classes (for `equals`/`copy`) or `object`s when a case carries no data (`object Loading : Result()`). A sealed `interface` works the same and lets a subtype implement other interfaces too.\n\nThe payoff appears at the use site. A `when (result)` with `is Success -> ...`, `is Failure -> ...`, `is Loading -> ...` needs no `else` because the compiler knows those three exhaust the hierarchy. Inside each `is` branch the value is **smart-cast** to that subtype, so in the `Success` branch you can read `result.data` directly with no manual cast. This combination — exhaustive matching plus smart casts — makes sealed hierarchies the cleanest way to handle results, network states, UI states, parser tokens, and abstract-syntax-tree nodes.\n\nContrast with an `enum`: an enum is a fixed set of *instances* that all share the same shape and fields. A sealed class is a fixed set of *subtypes* that can each carry different data and behavior. Reach for an enum when the cases are simple constants (days of the week, log levels); reach for a sealed class when each case needs its own payload (a `Success` with data versus a `Failure` with an error message). Both give exhaustive `when`; sealed adds per-case structure.\n\nSealed classes are abstract by definition — you cannot instantiate the sealed type itself, only its subtypes. They can declare common properties and abstract members that every subtype implements, sharing behavior across the hierarchy while still distinguishing the cases. Used together with the expression form of `when` from the control-flow lesson and the data classes from earlier, sealed types complete the toolkit for modeling domain states precisely — the compiler, not a runtime check, guarantees you handled them all.",
    code: "sealed class Result\ndata class Success(val data: String) : Result()\ndata class Failure(val code: Int) : Result()\n\nfun render(r: Result): String = when (r) {\n    is Success -> \"ok:${r.data}\"\n    is Failure -> \"err:${r.code}\"\n}\n\nfun main() {\n    println(render(Success(\"hi\")))\n    println(render(Failure(404)))\n}",
    runnable: true,
    exercise: {
      prompt: "Given the sealed Result above, write a `when` that returns 1 for a Success and 0 for a Failure, then print it for Success(\"x\"). Expected: 1.",
      starter: "sealed class Result\ndata class Success(val data: String) : Result()\ndata class Failure(val code: Int) : Result()\n\nfun code(r: Result): Int = when (r) {\n    is Success -> ...\n    is Failure -> ...\n}\n\nfun main() {\n    println(code(Success(\"x\")))\n}\n",
      expected: "1",
    },
    takeaways: [
      "Sealed types have a fixed, compiler-known set of subtypes.",
      "when over a sealed type is exhaustive — no else needed.",
      "Each is branch smart-casts the value to that subtype.",
      "Enum = fixed instances of one shape; sealed = fixed subtypes with their own data.",
    ],
    mistakes: [
      "Declaring sealed subtypes outside the allowed module/package.",
      "Adding an else and silencing the exhaustiveness check that catches new cases.",
      "Reaching for enum when each case needs its own distinct payload.",
    ],
    next: { label: "Back to courses", href: "#/courses" },
  },
];

export const KOTLIN_BASICS_COURSE = {
  id: "kotlin-basics",
  title: "Kotlin Basics",
  language: "kotlin",
  color: "#7F52FF",
  blurb: "From a one-line main to coroutines and sealed classes — every core Kotlin idea with runnable code.",
  estimatedHours: 7,
  externalResources: [
    { label: "Kotlin docs — Basic syntax", href: "https://kotlinlang.org/docs/basic-syntax.html" },
    { label: "Kotlin Koans (interactive exercises)", href: "https://play.kotlinlang.org/koans/overview" },
    { label: "Kotlin docs — Null safety", href: "https://kotlinlang.org/docs/null-safety.html" },
    { label: "Kotlin docs — Coroutines guide", href: "https://kotlinlang.org/docs/coroutines-guide.html" },
    { label: "JetBrains Academy — Kotlin Basics track", href: "https://hyperskill.org/tracks/18" },
  ],
  lessons: KOTLIN_LESSONS,
};
