// PHP Basics course module. Wired into the registry by src/content/courses.js.
// Lesson shape matches the existing courses: { id, title, intro, code, runnable,
// exercise: { prompt, starter, expected }, takeaways, mistakes, next }.
// `exercise.expected` is exact stdout — graded as a raw string match by codeRunner.
// All code runs on the PHP CLI (Judge0 language id 68) and must open with <?php.

const PHP_LESSONS = [
  {
    id: "echo-tags",
    title: "1. echo & PHP tags",
    intro: "PHP started life as a templating language, and that history shapes everything about how a script begins. A file is plain text until the parser hits the opening tag `<?php`. Everything before that tag is sent to output verbatim, and everything inside the tag is executed as code. That is why a `.php` file can be mostly HTML with small islands of logic — the engine only pays attention to what sits between `<?php` and the optional closing `?>`. On the command line you rarely emit HTML, so most CLI scripts are a single `<?php` block that runs top to bottom and the closing tag is left off on purpose.\n\nThe workhorse for producing output is `echo`. It is a language construct, not a function, which is why you can write `echo \"hi\";` without parentheses and even pass it several comma-separated arguments: `echo \"a\", \"b\";`. Its cousin `print` behaves almost identically but returns the integer 1, so it can sit inside an expression where `echo` cannot. For anything beyond a literal string you reach for `printf` and `sprintf`, which format values against a template: `printf(\"%d items\\n\", 3)` prints `3 items`. `printf` writes to output directly; `sprintf` returns the formatted string so you can store it.\n\nStatements end with a semicolon. Forgetting it is the single most common beginner error and produces a parse error pointing at the next line, which can be confusing because the real mistake was one line earlier. Newlines are not automatic — `echo \"hi\";` prints `hi` with no trailing line break, so you append `\\n` yourself when you want one. Inside double quotes `\\n` becomes a real newline; inside single quotes it stays the two literal characters backslash-n. That single-versus-double distinction returns again and again in PHP, so it is worth fixing in your mind now.\n\nComments come in three flavours: `//` and `#` for the rest of a line, and `/* ... */` for a block that can span many lines. Use them to explain why, not what. PHP is also famously case-insensitive for keywords and function names — `ECHO`, `Echo`, and `echo` all work — but variable names are case-sensitive, so `$name` and `$Name` are two different variables. Lean on lowercase keywords and consistent variable casing and you will avoid an entire category of silent bugs. With the tag, the statement terminator, and `echo` understood, you have the skeleton every later lesson hangs on.",
    code: "<?php\necho \"Hello, PHP\\n\";\necho \"one\", \" \", \"two\", \"\\n\";\nprintf(\"%d items cost $%.2f\\n\", 3, 4.5);\n// echo is a language construct; printf formats against a template",
    runnable: true,
    exercise: {
      prompt: "Echo the line `PGcode` followed by a newline, then on the next line echo `rocks`.",
      starter: "<?php\n// echo two lines: PGcode then rocks\n",
      expected: "PGcode\nrocks",
    },
    takeaways: [
      "Code lives between <?php and the optional ?>; text outside the tags is printed as-is.",
      "echo is a language construct (no parens needed); printf/sprintf format values.",
      "Every statement ends in a semicolon; newlines need an explicit \\n.",
      "\\n is a newline only inside double quotes, literal backslash-n in single quotes.",
    ],
    mistakes: [
      "Forgetting the trailing semicolon — the parse error points at the next line, not the real one.",
      "Expecting echo to add a newline automatically; you must append \\n yourself.",
      "Putting \\n inside single quotes and wondering why a literal backslash-n prints.",
    ],
    next: { label: "Variables & types", href: "#/courses/php-basics/variables-types" },
  },
  {
    id: "variables-types",
    title: "2. Variables & types",
    intro: "Every variable in PHP starts with a dollar sign: `$count`, `$userName`, `$total`. The dollar is not decoration — it is how the parser tells a variable apart from a constant or a function name, and it is required everywhere the variable is used. Names are case-sensitive, may contain letters, digits, and underscores, and may not begin with a digit. You never declare a type. Assigning `$x = 5` makes `$x` an integer; a later `$x = \"five\"` rebinds it to a string with no complaint. PHP is dynamically typed, and the type travels with the value, not the variable.\n\nThe scalar types are `int`, `float`, `string`, and `bool`. Integers are platform-width (64-bit on any modern build) and silently promote to float on overflow rather than wrapping. Floats are IEEE-754 doubles with the usual rounding surprises, so never compare two floats with `==` after arithmetic. Strings are byte sequences, which matters once you handle multibyte text — the `mb_*` family exists precisely because the core string functions count bytes, not characters. Booleans are `true` and `false`, case-insensitive. Beyond scalars you have `array` (covered later), `object`, `callable`, `null`, and `resource`.\n\nPHP leans hard on type juggling: it converts values automatically when an operation expects a different type. `\"5\" + 3` yields the integer 8 because the arithmetic context coerces the string. This convenience is also a trap, which is why modern PHP gives you the strict comparison operators `===` and `!==` that compare value and type together. The plain `==` applies juggling and produces results that surprise people — historically `\"0\"` and `\"\"` and `0` tangled together in ways that caused real bugs. The rule that keeps you safe is simple: default to `===` unless you have a specific reason to want coercion.\n\nThree functions illuminate what you are holding. `gettype($x)` returns a readable type name. `var_dump($x)` prints the type and value together, including length for strings and structure for arrays — it is your first debugging reflex. `is_int`, `is_string`, `is_array`, and friends return booleans for guard clauses. PHP also supports optional type declarations on function parameters and return values, and a `declare(strict_types=1)` directive at the top of a file that turns silent coercion of those declared types into a `TypeError`. Reaching for declared types plus strict mode early gives you much of the safety of a statically typed language while keeping PHP's quick feedback loop. Constants, defined with `const NAME = ...;` or `define('NAME', ...)`, hold values that never change and carry no dollar sign.",
    code: "<?php\n$count = 5;\n$price = 4.99;\n$name = \"PGcode\";\n$active = true;\n\nvar_dump($count, $price, $name, $active);\necho gettype($count) . \" / \" . gettype($name) . \"\\n\";\necho (\"5\" === 5 ? \"loose\" : \"strict-differ\") . \"\\n\";",
    runnable: true,
    exercise: {
      prompt: "Set $a = 6 and $b = 7, then echo their product followed by a newline (expected: 42).",
      starter: "<?php\n$a = 6;\n$b = 7;\n// echo the product\n",
      expected: "42",
    },
    takeaways: [
      "Every variable is prefixed with $ and is dynamically typed.",
      "Scalars: int, float, string, bool; plus array, object, null.",
      "Prefer === / !== to avoid surprising type-juggling from == .",
      "var_dump shows type + value; gettype names the type for guards.",
    ],
    mistakes: [
      "Omitting the $ on a variable, which the parser reads as an undefined constant.",
      "Comparing floats with == after arithmetic instead of a tolerance check.",
      "Trusting == across types: \"0\" == false is true under juggling — use === .",
    ],
    next: { label: "Strings & interpolation", href: "#/courses/php-basics/strings" },
  },
  {
    id: "strings",
    title: "3. Strings & interpolation",
    intro: "Strings are where PHP's templating roots show most clearly, and the single most important rule is the difference between the two quote styles. Double-quoted strings interpolate variables and interpret escape sequences. Inside `\"Hello $name\\n\"` the `$name` is replaced with its value and `\\n` becomes a real newline. Single-quoted strings do neither: `'Hello $name\\n'` prints the literal text `Hello $name\\n` with the dollar and backslash untouched. The only escapes single quotes honour are `\\'` for an embedded quote and `\\\\` for a literal backslash. Choosing the right quote style up front saves you from the classic bug where a variable name appears verbatim in the output.\n\nWhen a variable is followed immediately by letters that would run into its name, wrap it in curly braces so the parser knows where the name ends: `\"{$user}s\"` prints the value of `$user` followed by an `s`, whereas `\"$users\"` would look up a different variable named `$users`. The brace form also lets you interpolate array elements and object properties cleanly: `\"{$row['name']}\"` and `\"{$obj->title}\"`. For anything more complex than a direct substitution, concatenation with the dot operator is clearer, and `sprintf` is clearer still for numeric formatting.\n\nConcatenation uses the period, not the plus sign. `$a . $b` joins two strings; `$a .= $b` appends in place. Reaching for `+` here is a frequent mistake carried over from other languages — in PHP `+` is arithmetic and will try to add the strings as numbers, often yielding zero. Keep the period firmly associated with strings in your mind.\n\nThe standard library for strings is large and worth browsing. `strlen` returns byte length; `strtoupper` and `strtolower` change case; `trim` removes surrounding whitespace; `str_replace` swaps substrings; `substr` slices; `explode` splits on a delimiter into an array and `implode` joins an array back into a string; `str_contains`, `str_starts_with`, and `str_ends_with` (added in PHP 8) answer membership questions readably; `str_pad` and `number_format` handle alignment and thousands separators. Because core string functions count bytes, use the `mb_` equivalents (`mb_strlen`, `mb_strtoupper`) whenever you process text that may contain accented or non-Latin characters, or your lengths and slices will land mid-character. Heredoc (`<<<EOT`) and nowdoc (`<<<'EOT'`) syntax give you multi-line strings that follow the double- and single-quote interpolation rules respectively, handy for templates and SQL.",
    code: "<?php\n$name = \"Ada\";\n$count = 3;\necho \"Hello $name, you have $count messages\\n\";\necho 'Single quotes keep $name literal' . \"\\n\";\necho \"Items: {$count}x\\n\";\necho strtoupper($name) . \" has \" . strlen($name) . \" letters\\n\";\necho implode(\"-\", [\"a\", \"b\", \"c\"]) . \"\\n\";",
    runnable: true,
    exercise: {
      prompt: "Given $city = \"Paris\", echo the line `Welcome to Paris!` using double-quote interpolation.",
      starter: "<?php\n$city = \"Paris\";\n// echo: Welcome to Paris!\n",
      expected: "Welcome to Paris!",
    },
    takeaways: [
      "Double quotes interpolate $variables and escapes; single quotes stay literal.",
      "Use {$var} braces to bound a name, array element, or object property.",
      "Concatenate with the dot operator (. and .=), never + .",
      "Use mb_* functions for multibyte text; core string functions count bytes.",
    ],
    mistakes: [
      "Putting a variable in single quotes and printing its name instead of its value.",
      "Using + to join strings — PHP treats + as numeric addition.",
      "Forgetting braces in \"$users\" when you meant the value of $user followed by 's'.",
    ],
    next: { label: "Arrays", href: "#/courses/php-basics/arrays" },
  },
  {
    id: "arrays",
    title: "4. Arrays",
    intro: "PHP has exactly one array type, and it is unusually flexible: it is an ordered map that doubles as both a list and a dictionary. An indexed array like `[10, 20, 30]` is really a map with the integer keys 0, 1, 2 assigned automatically. An associative array like `['name' => 'Ada', 'age' => 36]` uses string keys you choose. The two are the same underlying structure, which is why one array can mix integer and string keys freely. The short syntax `[...]` has replaced the older `array(...)` form, though both still work.\n\nFor indexed arrays you append with `$a[] = $value`, which pushes onto the end using the next integer key. You read by index with `$a[2]` and you ask how many elements with `count($a)`. The key detail beginners trip over is that removing an element with `unset($a[1])` deletes the key but does not renumber the remaining keys — you are left with a gap at index 1. When you need a clean zero-based reindex, `array_values($a)` returns a fresh array with sequential keys. Treating arrays as if they always renumber is a reliable source of off-by-one confusion.\n\nAssociative arrays are the JSON-like backbone of PHP. You set with `$user['email'] = '...'`, read with `$user['email']`, and check presence with `isset($user['email'])` or `array_key_exists('email', $user)`. The two presence checks differ in one important way: `isset` returns false if the key exists but holds `null`, while `array_key_exists` returns true regardless of the stored value. Reach for `array_key_exists` when a null value is meaningful. `array_keys` and `array_values` extract the keys or values as their own arrays.\n\nThe functional toolkit is rich. `array_map` transforms every element through a callback; `array_filter` keeps only elements that pass a predicate; `array_reduce` folds an array down to a single value; `in_array` and `array_search` answer membership; `sort`, `rsort`, `asort`, and `ksort` order by value or key, in place. Spreading with `...` merges arrays inside a literal: `[...$a, ...$b]`. Destructuring with `[$first, $second] = $pair` pulls elements into named variables, and `['id' => $id] = $row` does the same for associative keys. Because arrays are copied by value on assignment — a quirk that surprises people coming from reference-based languages — passing a large array to a function copies it lazily (copy-on-write), so you only pay for a copy when you mutate. With one structure covering lists, maps, stacks, and queues, the array is the most-used tool in PHP.",
    code: "<?php\n$nums = [10, 20, 30];\n$nums[] = 40;\necho \"count: \" . count($nums) . \"\\n\";\n\n$user = ['name' => 'Ada', 'age' => 36];\necho $user['name'] . \" is \" . $user['age'] . \"\\n\";\n\n$doubled = array_map(fn($n) => $n * 2, $nums);\necho implode(\",\", $doubled) . \"\\n\";\necho array_sum($nums) . \"\\n\";",
    runnable: true,
    exercise: {
      prompt: "Build $scores = [4, 8, 15], then echo their sum using array_sum (expected: 27).",
      starter: "<?php\n$scores = [4, 8, 15];\n// echo the sum\n",
      expected: "27",
    },
    takeaways: [
      "One array type serves as both an ordered list and an associative map.",
      "Append with $a[]; count with count(); reindex with array_values().",
      "isset() is false for null values; array_key_exists() ignores the value.",
      "array_map / array_filter / array_reduce cover the functional transforms.",
    ],
    mistakes: [
      "Expecting unset() to renumber keys — it leaves a gap; use array_values().",
      "Using isset() to test a key whose stored value might legitimately be null.",
      "Confusing == on arrays (same pairs) with === (same pairs and same order).",
    ],
    next: { label: "Operators & control flow", href: "#/courses/php-basics/control-flow" },
  },
  {
    id: "control-flow",
    title: "5. Operators & control flow",
    intro: "Decisions in PHP are built from `if`, `elseif`, and `else`, with curly braces grouping each branch. The condition is any expression, coerced to a boolean by PHP's truthiness rules: the values that count as false are `false`, `0`, `0.0`, the empty string, the string `\"0\"`, the empty array, and `null`; everything else is true. That string-`\"0\"`-is-falsy rule is a famous gotcha — a perfectly valid input of `\"0\"` will skip an `if ($input)` branch — so when zero is a meaningful value, test it explicitly rather than relying on truthiness.\n\nThe comparison operators are the place beginners get burned, because PHP ships two families. The loose pair `==` and `!=` apply type juggling, so `0 == \"abc\"` and `\"1\" == 1` can both be true depending on the version. The strict pair `===` and `!==` compare value and type with no coercion, and they are what you should reach for by default. PHP 8 also adds the spaceship operator `<=>` which returns -1, 0, or 1 and is built for sorting callbacks. Logical operators are `&&`, `||`, and `!`; the word forms `and` and `or` exist but bind more loosely than `=`, which produces subtle assignment bugs, so stick with the symbol forms.\n\nFor selecting one of many fixed values, `switch` compares the subject against each `case` using loose equality and falls through to the next case unless you `break`. Forgetting `break` is the classic switch bug — execution tumbles into the following case. PHP 8 introduced `match`, a stricter, expression-valued alternative: it compares with `===`, returns a value you can assign, requires no `break`, and throws if no arm matches unless you supply a `default`. Prefer `match` for new code; it is safer and reads better.\n\nTwo operators smooth out common null handling. The ternary `cond ? a : b` chooses between two values inline. Its short form `$a ?: $b` returns `$a` when truthy, otherwise `$b`. The null-coalescing operator `$a ?? $b` returns `$a` only when it is set and not null, and crucially it does not emit a warning when `$a` is an undefined array key or variable — making `$config['timeout'] ?? 30` the idiomatic way to read an optional setting with a default. Its assignment form `$x ??= $default` sets `$x` only if it was null. Master these three — `===`, `match`, and `??` — and most of PHP's historical comparison footguns simply stop firing.",
    code: "<?php\n$score = 72;\nif ($score >= 90) {\n    echo \"A\\n\";\n} elseif ($score >= 70) {\n    echo \"B\\n\";\n} else {\n    echo \"C\\n\";\n}\n\n$day = 3;\nswitch ($day) {\n    case 1:\n    case 7:\n        $name = \"weekend-ish\";\n        break;\n    default:\n        $name = \"weekday\";\n}\necho $name . \"\\n\";\n\n$config = [];\necho ($config['timeout'] ?? 30) . \"\\n\";",
    runnable: true,
    exercise: {
      prompt: "Given $n = 12, echo `even` if it is divisible by 2, otherwise `odd` (expected: even).",
      starter: "<?php\n$n = 12;\n// echo even or odd\n",
      expected: "even",
    },
    takeaways: [
      "Truthiness: false, 0, 0.0, \"\", \"0\", [], and null are falsy.",
      "Default to === / !== ; use the symbol logical operators && || !.",
      "Prefer match (=== compared, value-returning) over switch for new code.",
      "Use ?? for safe defaults on possibly-undefined keys without warnings.",
    ],
    mistakes: [
      "Treating \"0\" as truthy in an if — the string \"0\" is falsy in PHP.",
      "Forgetting break in a switch and falling through into the next case.",
      "Using `or` where `||` is meant — `or` binds looser than =, breaking assignments.",
    ],
    next: { label: "Loops", href: "#/courses/php-basics/loops" },
  },
  {
    id: "loops",
    title: "6. Loops",
    intro: "PHP gives you four looping constructs, and choosing the right one keeps code readable. The classic `for` loop owns three slots in its header: an initializer, a continue-condition, and a step, all separated by semicolons — `for ($i = 0; $i < 10; $i++)`. Use it when you genuinely need the index, for instance to walk an array by position or to count in custom strides. The `while` loop checks its condition before each pass and is the natural fit when you do not know the iteration count in advance, such as reading lines until a stream ends. Its sibling `do ... while` runs the body once before testing, guaranteeing at least one execution — useful for retry loops and menus.\n\nThe loop you will reach for most is `foreach`, built specifically for arrays and iterables. In its value form `foreach ($items as $value)` you get each element in order without managing an index. In its key-value form `foreach ($map as $key => $value)` you also receive the key, which is the clean way to walk an associative array. `foreach` works on any object implementing the `Traversable` interface, including generators, so the same syntax iterates a million-row database cursor lazily without loading it all into memory.\n\nThere is one `foreach` trap worth burning into memory. If you iterate by reference with `foreach ($items as &$value)` so you can modify elements in place, the reference variable `$value` survives after the loop ends, still bound to the last element. A later innocent-looking `foreach ($items as $value)` then overwrites that last element with each pass. The fix is to `unset($value)` immediately after a by-reference loop. When you only read, iterate by value and skip the whole problem.\n\nTwo statements steer a loop from inside. `break` exits the loop entirely; `continue` skips to the next iteration. Both accept an optional integer level — `break 2` exits two nested loops at once, which beats juggling flag variables. Every loop also supports an alternative colon syntax (`foreach (...): ... endforeach;`) intended for templates that interleave HTML, but in CLI scripts the brace form reads better. A final efficiency note: in a `for` loop over an array, call `count()` once into a variable rather than re-evaluating `count($arr)` in the condition on every pass — and where you can, prefer `foreach`, which sidesteps the issue entirely. With these four constructs plus `break`, `continue`, and the by-reference caveat, you can express any iteration PHP needs.",
    code: "<?php\n$total = 0;\nfor ($i = 1; $i <= 5; $i++) {\n    $total += $i;\n}\necho \"for sum: $total\\n\";\n\n$fruits = ['apple', 'pear', 'plum'];\nforeach ($fruits as $i => $fruit) {\n    echo \"$i: $fruit\\n\";\n}\n\n$n = 3;\nwhile ($n > 0) {\n    echo \"countdown $n\\n\";\n    $n--;\n}",
    runnable: true,
    exercise: {
      prompt: "Use a loop to echo the squares 1, 4, 9 each on its own line (1\\n4\\n9).",
      starter: "<?php\n// echo 1, 4, 9 on separate lines\n",
      expected: "1\n4\n9",
    },
    takeaways: [
      "for when you need an index; while when the count is unknown.",
      "foreach ($a as $k => $v) is the clean way to walk arrays and iterables.",
      "After a by-reference foreach (as &$v), call unset($v) to avoid aliasing.",
      "break and continue accept a level: break 2 exits two nested loops.",
    ],
    mistakes: [
      "Leaving a dangling reference after foreach (as &$v) and corrupting the last element.",
      "Re-calling count($arr) in a for condition every iteration instead of caching it.",
      "Confusing while (pre-test) with do...while (runs the body at least once).",
    ],
    next: { label: "Functions & default args", href: "#/courses/php-basics/functions" },
  },
  {
    id: "functions",
    title: "7. Functions & default args",
    intro: "A function is declared with `function name(params) { ... }` and called by name with parentheses. Parameters are positional, and you can give any trailing parameter a default value with `= value` so the caller may omit it: `function greet($name, $greeting = \"Hello\")`. Defaults must be constant expressions and must come after all required parameters — a default in the middle followed by a required one is a syntax error, because positional calls could no longer line up. From PHP 8 you can also pass arguments by name, `greet(name: \"Ada\", greeting: \"Hi\")`, which lets you skip earlier optional arguments and makes call sites self-documenting.\n\nType declarations sharpen a function's contract. You annotate each parameter and the return value: `function add(int $a, int $b): int`. With `declare(strict_types=1)` at the top of the file these are enforced and a mismatched argument throws a `TypeError` rather than being silently coerced. A return type of `void` means the function returns nothing usable; `?int` means an int or null; union types like `int|string` accept either. These annotations are the cheapest documentation you can write and they let editors and static analysers catch bugs before runtime.\n\nScope in PHP is strict and often surprises newcomers: variables defined outside a function are not visible inside it. Unlike many languages, a function cannot read a file-level variable just by naming it. To pull one in you either pass it as an argument (the right answer almost always) or, rarely, declare `global $x` inside the function. By default arguments are passed by value, so a function mutating a scalar parameter does not affect the caller's variable. Prefix a parameter with `&` to pass by reference when you deliberately want the function to modify the caller's variable in place, but use this sparingly — returning a new value is clearer than mutating through a reference.\n\nVariadic functions collect any number of trailing arguments into an array with the spread parameter `function sum(...$nums)`, and the same `...` operator spreads an array into individual arguments at a call site: `sum(...$list)`. Anonymous functions, written `function () use ($captured) { ... }`, capture outer variables explicitly through the `use` clause. Arrow functions, `fn($x) => $x * 2`, are a concise one-expression form that capture the enclosing scope automatically by value — ideal as callbacks to `array_map` and `usort`. Functions are first-class values: you can store one in a variable, pass it around, and return it, which is the foundation of the functional array helpers you met earlier.",
    code: "<?php\nfunction greet(string $name, string $greeting = \"Hello\"): string {\n    return \"$greeting, $name!\";\n}\n\necho greet(\"Ada\") . \"\\n\";\necho greet(\"Lin\", \"Hi\") . \"\\n\";\n// PHP 8 also allows named args: greet(greeting: \"Hey\", name: \"Sam\")\n\nfunction sum(int ...$nums): int {\n    return array_sum($nums);\n}\necho sum(1, 2, 3, 4) . \"\\n\";",
    runnable: true,
    exercise: {
      prompt: "Write a function area($w, $h = 2) returning $w * $h, then echo area(5) (expected: 10).",
      starter: "<?php\nfunction area($w, $h = 2) {\n    // return the area\n}\necho area(5);\n",
      expected: "10",
    },
    takeaways: [
      "Default parameter values must follow all required ones; pass by name to skip.",
      "Type declarations + declare(strict_types=1) turn mismatches into TypeErrors.",
      "Variables outside a function are not visible inside — pass them as arguments.",
      "Variadics collect with ...$args; arrow fns (fn) capture scope automatically.",
    ],
    mistakes: [
      "Putting a defaulted parameter before a required one — a syntax error.",
      "Expecting a function to see file-level variables without passing them in.",
      "Mutating a by-value parameter and expecting the caller's variable to change.",
    ],
    next: { label: "Associative-array iteration", href: "#/courses/php-basics/assoc-iteration" },
  },
  {
    id: "assoc-iteration",
    title: "8. Associative-array iteration",
    intro: "Associative arrays are PHP's everyday data structure — the shape that database rows, JSON payloads, configuration files, and form submissions all take. Iterating them well is a core skill. The primary tool is the key-value `foreach`: `foreach ($map as $key => $value)` hands you both halves of each pair in insertion order. PHP arrays preserve the order keys were added, so iteration is deterministic, which makes them safe to drive ordered output like tables and CSV rows. When you only need the values you can drop the key, and when you only need the keys you can iterate `array_keys($map)`.\n\nFor transforming a map you reach for the same functional helpers as with lists, with a wrinkle. `array_map` by default passes only values to its callback and drops the keys, returning a reindexed array. To keep keys you map the values and reassign, or use `array_combine(array_keys($m), array_map($fn, $m))`. `array_filter`, by contrast, preserves keys when it removes elements, which is why filtering an associative array keeps its labels intact — exactly what you want for a map, but a surprise on a list where you may then want `array_values` to reindex. `array_reduce` folds a map to a single accumulated value and is the clean way to sum a column or build a lookup.\n\nSorting an associative array requires the key-aware functions, because the plain `sort` throws the keys away and reindexes. Use `asort` to sort by value while keeping keys, `arsort` for descending by value, `ksort` to sort by key, and `krsort` for descending by key. For custom orderings, `uasort` sorts by value with your comparison callback while preserving keys, and `uksort` sorts by key with a callback. The callback returns a negative, zero, or positive number — exactly what the spaceship operator `<=>` produces, so `fn($a, $b) => $a <=> $b` is the idiomatic ascending comparator.\n\nSeveral helpers answer questions about a map directly. `array_key_exists` and `isset` test presence (remembering that `isset` is false for a null value). `array_column` plucks one field out of an array of rows into a flat list, the workhorse for reshaping query results. `array_merge` combines maps with later string keys overwriting earlier ones, while the `+` union operator keeps the earlier value on a key clash — a meaningful difference when applying defaults: `$options = $userOptions + $defaults`. Finally, when a map grows large, generators (`yield $key => $value`) let you iterate it lazily without materialising the whole structure, the same `foreach` syntax driving a stream instead of an array. Knowing which helper preserves keys and which reindexes is the difference between clean map code and silent data loss.",
    code: "<?php\n$prices = ['pen' => 2, 'mug' => 8, 'pad' => 5];\n\nforeach ($prices as $item => $price) {\n    echo \"$item costs \\$$price\\n\";\n}\n\narsort($prices);\necho \"Most expensive: \" . array_key_first($prices) . \"\\n\";\n\n$total = array_reduce($prices, fn($c, $p) => $c + $p, 0);\necho \"Total: $total\\n\";",
    runnable: true,
    exercise: {
      prompt: "Given $ages = ['a' => 30, 'b' => 12], echo the sum of the values using array_sum (expected: 42).",
      starter: "<?php\n$ages = ['a' => 30, 'b' => 12];\n// echo the sum of the values\n",
      expected: "42",
    },
    takeaways: [
      "foreach ($map as $k => $v) walks pairs in insertion order, deterministically.",
      "array_filter preserves keys; array_map drops them — reindex when needed.",
      "Sort maps with asort/arsort/ksort (key-aware), not plain sort.",
      "+ union keeps the existing key's value; array_merge lets the later one win.",
    ],
    mistakes: [
      "Using sort() on a map and silently losing every key.",
      "Assuming array_map keeps string keys — it returns a reindexed array.",
      "Mixing up array_merge (later wins) and + (earlier wins) when applying defaults.",
    ],
    next: { label: "Classes & objects", href: "#/courses/php-basics/classes" },
  },
  {
    id: "classes",
    title: "9. Classes & objects",
    intro: "A class is a blueprint; an object is an instance built from it. You declare one with `class Name { ... }`, holding properties (the data) and methods (the behaviour). You create an instance with `new Name(...)` and access members through the arrow operator `$obj->property` and `$obj->method()`. Inside a method, the current instance is `$this`, so `$this->name` reads this object's `name` property. The arrow is for objects; the double-colon `::` is for static and class-level access — confusing the two is a common early mistake.\n\nVisibility modifiers control access. `public` members are reachable from anywhere, `private` only from inside the same class, and `protected` from the class and its subclasses. The convention is to keep properties private and expose controlled access through methods, so the object guards its own invariants rather than letting outside code set fields to nonsense. Each property may carry a type declaration — `private int $count = 0;` — which PHP enforces, and a typed property with no default is in an uninitialised state until you assign it, accessing it before then throws an `Error`.\n\nThe constructor is the special method `__construct`, run automatically by `new`. It is where you accept dependencies and set the object's starting state. PHP 8's constructor promotion collapses the common boilerplate of declaring a property and assigning it: writing the visibility and type directly in the constructor signature, `public function __construct(private string $name) {}`, declares the property, types it, and assigns it in one line. This single feature removes most of the repetitive ceremony older PHP classes were known for, and you should use it.\n\nBeyond `__construct`, PHP offers a family of magic methods that the engine calls on your behalf: `__toString` lets an object render as a string when echoed, `__get` and `__set` intercept access to undefined properties, and `__invoke` makes an object callable like a function. Static members, declared with `static`, belong to the class rather than any instance and are accessed as `ClassName::$prop` or `ClassName::method()`; `self::` refers to the defining class from inside it. Class constants, `const RATE = 0.2;`, hold fixed values accessed as `ClassName::RATE`. Putting these together — typed private properties, a promoting constructor, public methods that enforce rules, and `__toString` for display — gives you small, self-validating objects that read cleanly and fail loudly when misused.",
    code: "<?php\nclass Counter {\n    private int $count;\n\n    public function __construct(int $start = 0) {\n        $this->count = $start;\n    }\n\n    public function increment(int $by = 1): void {\n        $this->count += $by;\n    }\n\n    public function value(): int {\n        return $this->count;\n    }\n}\n\n$c = new Counter(10);\n$c->increment();\n$c->increment(5);\necho \"Count: \" . $c->value() . \"\\n\";",
    runnable: true,
    exercise: {
      prompt: "Give class Box a public $size set in its constructor; create new Box(7) and echo its size (expected: 7).",
      starter: "<?php\nclass Box {\n    public $size;\n    public function __construct($size) {\n        $this->size = $size;\n    }\n}\n$b = new Box(7);\n// echo the size\n",
      expected: "7",
    },
    takeaways: [
      "Instantiate with new; reach members through $obj->prop and $this inside.",
      "Keep properties private; expose controlled access through public methods.",
      "__construct sets up state; constructor promotion declares+assigns in one line.",
      ":: accesses static members and constants; -> accesses instance members.",
    ],
    mistakes: [
      "Using :: where -> is needed (or vice versa) on instance vs static members.",
      "Accessing a typed property before it is initialised — that throws an Error.",
      "Making every property public and letting outside code break the object's invariants.",
    ],
    next: { label: "Inheritance & interfaces", href: "#/courses/php-basics/inheritance" },
  },
  {
    id: "inheritance",
    title: "10. Inheritance & interfaces",
    intro: "Inheritance lets one class build on another. A subclass declared `class Dog extends Animal` gains all of the parent's public and protected members and may add its own or override existing ones. When you override a method you can still call the parent's version with `parent::method()`, which is the standard pattern for extending behaviour rather than replacing it — a subclass constructor commonly calls `parent::__construct(...)` first to let the parent set up its half of the state, then adds its own. PHP supports only single inheritance: a class extends at most one parent, a deliberate constraint that keeps the hierarchy a tree rather than a tangle.\n\nAbstract classes sit between a concrete class and a pure contract. Marked `abstract class Shape`, they cannot be instantiated directly and exist to be extended. They may hold ordinary implemented methods shared by all subclasses plus `abstract` methods that declare a signature with no body, forcing every concrete subclass to supply one. This is how you capture \"all shapes have a name and a colour, but each computes its own area\" — the shared parts live in the abstract base, the varying part is left abstract.\n\nAn interface goes further and defines a pure contract with no implementation at all: a list of method signatures (and, since PHP 8, constants) that any implementing class must provide. You declare `interface Comparable { public function compareTo($other): int; }` and a class promises to honour it with `class Money implements Comparable`. Crucially a class may implement many interfaces at once — `implements Comparable, JsonSerializable` — which is how PHP gets the flexibility of multiple inheritance for behaviour contracts without the diamond problems of multiple implementation inheritance. Interfaces are the seam you program against: a function typed to accept a `Comparable` works with any class that implements it, present or future.\n\nThe payoff of both mechanisms is polymorphism. Because a subclass is a kind of its parent and an implementer is a kind of its interface, you can hold a collection of different concrete types behind a single declared type and call the same method on each, letting every object run its own version. A `$shapes` array of mixed circles and squares can all answer `$shape->area()`. The `instanceof` operator tests whether an object satisfies a class or interface at runtime, useful for narrowing a union type. Mark a method or class `final` to forbid overriding or extension when a contract must not be altered. Lean on interfaces for the public contracts your code depends on, abstract classes to share partial implementation, and keep concrete inheritance chains shallow — deep hierarchies are harder to follow than composition.",
    code: "<?php\nabstract class Shape {\n    abstract public function area(): float;\n    public function describe(): string {\n        return sprintf(\"%s area=%.1f\", static::class, $this->area());\n    }\n}\n\nclass Square extends Shape {\n    private float $side;\n    public function __construct(float $side) { $this->side = $side; }\n    public function area(): float { return $this->side ** 2; }\n}\n\n$s = new Square(4);\necho $s->describe() . \"\\n\";\necho ($s instanceof Shape ? \"is a Shape\" : \"not\") . \"\\n\";",
    runnable: true,
    exercise: {
      prompt: "Make class Cat extends Animal where Animal has speak() returning \"...\"; override speak() to return \"meow\" and echo (new Cat())->speak().",
      starter: "<?php\nclass Animal {\n    public function speak(): string { return \"...\"; }\n}\nclass Cat extends Animal {\n    // override speak() to return \"meow\"\n}\necho (new Cat())->speak();\n",
      expected: "meow",
    },
    takeaways: [
      "extends gives single inheritance; call the parent with parent::method().",
      "Abstract classes share partial implementation and force subclasses to fill gaps.",
      "Interfaces are pure contracts; a class can implement many at once.",
      "Polymorphism: one declared type, many concrete implementations, same call.",
    ],
    mistakes: [
      "Trying to extend two classes — PHP allows only single inheritance.",
      "Forgetting parent::__construct() in a subclass constructor and skipping parent setup.",
      "Instantiating an abstract class or interface directly, which is an error.",
    ],
    next: { label: "Traits", href: "#/courses/php-basics/traits" },
  },
  {
    id: "traits",
    title: "11. Traits",
    intro: "Traits solve a problem single inheritance creates: you often want to share a chunk of implementation across classes that do not belong in the same hierarchy. A logging helper, a timestamp-stamping routine, or a comparison method might be needed by a `User`, an `Order`, and a `Product` that have nothing else in common. Without traits you would either copy the code into each class or contort the hierarchy to share a base. A trait is a reusable bundle of methods (and properties) that you mix into any class with the `use` keyword inside the class body. It is horizontal composition rather than vertical inheritance.\n\nDeclaring one looks like a class: `trait Timestamped { ... }`, holding methods and properties. A class pulls it in with `use Timestamped;` near the top of the class body, and from that point the trait's members behave exactly as if they had been written directly in the class — they can read `$this`, call other methods, and access the class's own properties. A single class may use several traits at once, `use Timestamped, Loggable;`, composing capabilities from multiple sources. This is the closest PHP comes to multiple inheritance of implementation, and it is the idiomatic way to share cross-cutting behaviour.\n\nBecause two traits might define a method with the same name, PHP makes you resolve the collision explicitly rather than silently picking one. When two used traits both define `hello`, you use the `insteadof` operator to choose which wins, and the `as` operator to alias the loser under a different name so it stays reachable. This explicitness is deliberate — an accidental ambiguity becomes a clear, named decision instead of a silent surprise. The precedence rules are worth remembering: a method defined directly in the class overrides a trait's method of the same name, and a trait's method overrides one inherited from a parent class.\n\nTraits can also declare `abstract` methods, demanding that any class using the trait provide an implementation — a way to require the host class to fill in a hook the trait depends on. They may hold static methods and properties too, though each using class gets its own copy of a static trait property. The line to draw is this: reach for inheritance to model an \"is-a\" relationship where a real type hierarchy exists, reach for an interface when you need a contract, and reach for a trait when you simply need to share implementation across unrelated classes without forcing them into a hierarchy they do not belong in. Used with that discipline, traits keep code DRY without the rigidity that overusing inheritance brings.",
    code: "<?php\ntrait Greetable {\n    public function greet(): string {\n        return \"Hi, I am {$this->name}\";\n    }\n}\n\nclass Person {\n    use Greetable;\n    public string $name;\n    public function __construct(string $name) { $this->name = $name; }\n}\n\nclass Robot {\n    use Greetable;\n    public string $name = \"Unit-7\";\n}\n\necho (new Person(\"Ada\"))->greet() . \"\\n\";\necho (new Robot())->greet() . \"\\n\";",
    runnable: true,
    exercise: {
      prompt: "Define a trait Loud with a method shout() returning \"HEY\"; use it in class Speaker and echo (new Speaker())->shout().",
      starter: "<?php\ntrait Loud {\n    // method shout() returns \"HEY\"\n}\nclass Speaker {\n    use Loud;\n}\necho (new Speaker())->shout();\n",
      expected: "HEY",
    },
    takeaways: [
      "Traits share method bundles across unrelated classes via use inside the class.",
      "A class can use several traits at once — horizontal composition.",
      "Resolve same-named trait methods with insteadof (pick) and as (alias).",
      "Class method > trait method > inherited parent method in precedence.",
    ],
    mistakes: [
      "Leaving a method-name collision between two traits unresolved — a fatal error.",
      "Overusing traits as a dumping ground instead of modelling a real type or contract.",
      "Forgetting that each using class gets its own copy of a static trait property.",
    ],
    next: { label: "Errors & exceptions", href: "#/courses/php-basics/exceptions" },
  },
  {
    id: "exceptions",
    title: "12. Errors & exceptions",
    intro: "PHP has two distinct ways things go wrong, and modern code unifies how you handle them. The legacy mechanism is the error system: notices, warnings, and fatal errors that the engine raises for things like using an undefined variable or calling a missing function. The modern mechanism is exceptions: objects you throw and catch with structured `try`/`catch` blocks. Since PHP 7, even most internal fatal errors are thrown as `Error` objects, and both `Error` and `Exception` implement the shared `Throwable` interface — so a single `catch (\\Throwable $e)` can handle either, though you rarely want such a broad net.\n\nYou raise an exception with `throw new Exception(\"message\")` and handle it by wrapping the risky code in `try { ... } catch (Exception $e) { ... }`. The catch block names the type it handles, and you can stack several catch blocks to deal with different exception classes differently, or catch a union `catch (TypeError | ValueError $e)`. Inside the handler, `$e->getMessage()` returns the message, `$e->getCode()` an optional integer code, and `$e->getTrace()` the call stack. The golden rule is to catch specific types you can actually recover from, not a blanket `\\Exception`, so that bugs you did not anticipate surface loudly instead of being swallowed.\n\nThe `finally` block runs whether or not an exception was thrown, after the try and any matching catch complete. It is the right place for cleanup that must happen on every path — closing a file handle, releasing a lock, rolling back a transaction — because it executes even when the catch re-throws or the function returns from inside the try. Pairing `try`/`finally` (with no catch at all) is a clean way to guarantee cleanup while letting the exception propagate to a caller better positioned to handle it.\n\nThe standard library ships a hierarchy of exception types you should use rather than throwing a bare `Exception`. `InvalidArgumentException` signals a bad argument, `RuntimeException` a failure only detectable at run time, `LogicException` a programming mistake that should have been caught in testing, and `TypeError` and `ValueError` come from type and value violations. Define your own by extending one of these — `class PaymentFailed extends RuntimeException {}` — so callers can catch your domain failures precisely. Two configuration notes matter for real applications: in development, set `error_reporting(E_ALL)` and display errors so nothing hides; in production, log errors instead of showing them to users. And prefer exceptions over return codes for exceptional conditions — a function that returns `false` on failure forces every caller to remember to check, whereas an exception cannot be silently ignored.",
    code: "<?php\nfunction divide(int $a, int $b): float {\n    if ($b === 0) {\n        throw new InvalidArgumentException(\"cannot divide by zero\");\n    }\n    return $a / $b;\n}\n\ntry {\n    echo divide(10, 2) . \"\\n\";\n    echo divide(7, 0) . \"\\n\";\n} catch (InvalidArgumentException $e) {\n    echo \"Error: \" . $e->getMessage() . \"\\n\";\n} finally {\n    echo \"done\\n\";\n}",
    runnable: true,
    exercise: {
      prompt: "In a try block, throw new Exception(\"boom\"); in the catch, echo the caught message (expected: boom).",
      starter: "<?php\ntry {\n    // throw new Exception(\"boom\");\n} catch (Exception $e) {\n    // echo the message\n}\n",
      expected: "boom",
    },
    takeaways: [
      "throw new Exception(...) raises; try/catch handles by type.",
      "Error and Exception both implement Throwable since PHP 7.",
      "finally always runs — use it for cleanup on every code path.",
      "Catch specific types you can recover from, not a blanket \\Exception.",
    ],
    mistakes: [
      "Swallowing every exception with a broad catch and hiding real bugs.",
      "Putting cleanup in the try body instead of finally, so it is skipped on throw.",
      "Throwing a bare Exception when a specific SPL type would let callers catch precisely.",
    ],
    next: { label: "Composer & autoloading", href: "#/courses/php-basics/composer" },
  },
  {
    id: "composer",
    title: "13. Composer & autoloading",
    intro: "Composer is PHP's dependency manager, and learning it is the step that turns isolated scripts into real projects. You describe what your project needs in a `composer.json` file and run `composer install`; Composer resolves the full dependency graph, downloads each package into a `vendor/` directory, and writes a `composer.lock` that pins the exact resolved versions. Committing the lock file means every teammate and every deployment gets byte-for-byte the same dependencies, which is the difference between \"works on my machine\" and a reproducible build. You add a new dependency with `composer require vendor/package` and update within your declared version ranges with `composer update`.\n\nThe single most valuable thing Composer generates is the autoloader. Before autoloading, every PHP file had to `require` every class file it used, producing brittle chains of include statements. Composer instead writes `vendor/autoload.php`; you `require` that one file once at your entry point and from then on classes load on demand the first time they are referenced. The mechanism follows the PSR-4 standard, which maps a namespace prefix to a base directory — declare `\"App\\\\\": \"src/\"` in the `autoload` section and Composer knows that `App\\Service\\Mailer` lives in `src/Service/Mailer.php`. After editing the autoload map you run `composer dump-autoload` to regenerate it.\n\nNamespaces are the other half of this story and worth understanding even outside Composer. A namespace, declared `namespace App\\Service;` as the first statement in a file, prevents name collisions between your classes and a library's classes that happen to share a short name. You pull a class from another namespace into scope with a `use` statement at the top of the file — `use App\\Model\\User;` — after which you can write the short name `User`. A leading backslash means \"from the global namespace,\" which is why you sometimes see `\\Exception` or `\\DateTime`: it sidesteps any same-named class in the current namespace. PSR-4 ties namespace structure directly to directory structure, so once you adopt it, file location becomes predictable.\n\nComposer also distinguishes runtime dependencies from development-only ones: `require` for packages your app needs in production, `require-dev` for tools like PHPUnit and static analysers that only matter while building. The `scripts` section lets you define shortcuts — `composer test` running your PHPUnit suite, for instance — so common commands live in one discoverable place. Browsing Packagist, the public registry Composer pulls from, you will find vetted libraries for HTTP clients, logging, date handling, and almost anything else, so you rarely reinvent infrastructure. A typical modern project therefore begins with three moves: `composer init` to scaffold the manifest, `composer require` the libraries you need, and a `require __DIR__ . '/vendor/autoload.php';` at the top of your entry script — after which namespaced, autoloaded classes simply work.",
    code: "<?php\n// In a Composer project this single require wires up autoloading:\n//   require __DIR__ . '/vendor/autoload.php';\n// PSR-4 then maps App\\Service\\Mailer -> src/Service/Mailer.php\n\nnamespace App;\n\nclass Greeter {\n    public function hello(string $who): string {\n        return \"Hello from \" . __NAMESPACE__ . \", $who\";\n    }\n}\n\necho (new Greeter())->hello(\"world\") . \"\\n\";",
    runnable: true,
    exercise: {
      prompt: "Inside namespace Shop, define a class Cart with method count() returning 0; echo (new \\Shop\\Cart())->count() (expected: 0).",
      starter: "<?php\nnamespace Shop;\nclass Cart {\n    // method count() returns 0\n}\necho (new \\Shop\\Cart())->count();\n",
      expected: "0",
    },
    takeaways: [
      "composer.json declares deps; composer.lock pins exact resolved versions.",
      "Require vendor/autoload.php once; classes then load on demand via PSR-4.",
      "PSR-4 maps a namespace prefix to a directory: App\\ -> src/.",
      "Use require for runtime deps, require-dev for build-only tools.",
    ],
    mistakes: [
      "Not committing composer.lock, so teammates resolve different versions.",
      "Editing the autoload map without running composer dump-autoload.",
      "Forgetting a leading backslash and resolving a class in the wrong namespace.",
    ],
    next: { label: "Back to courses", href: "#/courses" },
  },
];

export const PHP_BASICS_COURSE = {
  id: "php-basics",
  title: "PHP Basics",
  language: "php",
  color: "#777BB4",
  blurb: "From <?php tags to classes, traits, and Composer — the server language behind most of the web, with runnable CLI examples.",
  estimatedHours: 4,
  externalResources: [
    { title: "PHP Manual (official)", url: "https://www.php.net/manual/en/", type: "book" },
    { title: "PHP The Right Way", url: "https://phptherightway.com/", type: "book" },
    { title: "PHP language reference", url: "https://www.php.net/manual/en/langref.php", type: "blog" },
    { title: "Composer — getting started", url: "https://getcomposer.org/doc/00-intro.md", type: "course" },
    { title: "PSR-4 autoloading standard", url: "https://www.php-fig.org/psr/psr-4/", type: "blog" },
  ],
  lessons: PHP_LESSONS,
};
