// Ruby Basics course. Standalone module — the orchestrator wires RUBY_BASICS_COURSE
// into the COURSES registry in src/content/courses.js. Do not import this elsewhere.
//
// Lesson shape matches the registry contract:
//   { id, title, intro, code, runnable, exercise: { prompt, starter, expected },
//     takeaways, mistakes, next }
// `expected` is exact stdout; Judge0 runs `code`/the exercise via codeRunner (ruby, id 72).

const RUBY_LESSONS = [
  {
    id: "r1",
    title: "1. puts, p & strings",
    intro: "Ruby gives you three everyday ways to send something to the terminal, and they are not interchangeable. `puts` prints a human-readable form of its argument and then appends a newline. Hand it an array and it prints each element on its own line. Hand it `nil` and it prints a blank line. `print` is the same idea without the trailing newline, so successive `print` calls run together on one line. `p` is the debugging tool: it prints the *inspected* form of the object — the same representation you would type back into source code — and returns the object itself. That is why `p \"hi\"` shows the quotes around the string while `puts \"hi\"` does not. When you are eyeballing data structures, reach for `p`; when you are producing output a person will read, reach for `puts`.\n\nStrings in Ruby come in two flavours. Double-quoted strings support escape sequences like `\\n` and `\\t`, and they support interpolation: `\"Hello, #{name}\"` evaluates the expression inside `#{}` and splices the result in. Single-quoted strings are literal — `'a\\nb'` contains a backslash and an n, not a newline — and they do not interpolate. Default to double quotes unless you specifically want the raw form, because interpolation is the single most common reason you reach for a string in the first place.\n\nStrings are objects with a deep method library. `.length` counts characters, `.upcase` and `.downcase` change case, `.reverse` flips the order, `.strip` trims surrounding whitespace, and `.include?` asks whether a substring appears. You concatenate with `+`, but interpolation reads better and avoids the classic `TypeError` you get when you try to `+` a string with a number. Strings also respond to `*` for repetition: `\"ab\" * 3` is `\"ababab\"`.\n\nRuby strings are mutable, which surprises people coming from Python. Methods that end in a bang, like `.upcase!`, modify the string in place and return `nil` if nothing changed; the non-bang versions return a fresh copy and leave the original alone. Prefer the non-bang form unless you have a concrete reason to mutate. Get comfortable with `puts` versus `p` and with interpolation now — almost every later lesson leans on both.",
    code: "name = \"Ruby\"\nputs \"Hello, #{name}!\"\nputs name.upcase\nputs name.length\np name",
    runnable: true,
    exercise: {
      prompt: "Set `lang` to \"ruby\", then use puts to print it interpolated as `I code in RUBY` (the language uppercased).",
      starter: "lang = \"ruby\"\n# print: I code in RUBY\n",
      expected: "I code in RUBY",
    },
    takeaways: [
      "puts adds a newline, print does not, p shows the inspected form with quotes.",
      "Double quotes interpolate with #{...}; single quotes are literal.",
      "Strings are objects: .length, .upcase, .reverse, .include? and many more.",
      "Bang methods like .upcase! mutate in place; prefer the non-bang copy.",
    ],
    mistakes: [
      "Using single quotes and expecting #{x} to interpolate — it stays literal text.",
      "Concatenating a string and a number with + raises TypeError; interpolate instead.",
      "Assuming p and puts print the same thing — p keeps the quotes and structure.",
    ],
    next: { label: "Variables & types", href: "#/courses/ruby-basics/r2" },
  },
  {
    id: "r2",
    title: "2. Variables & types",
    intro: "A variable in Ruby is a name bound to an object. Assignment with `=` does not copy the object; it points the name at it, so two names can refer to the same underlying value. Ruby is dynamically typed: you never declare a type, and a variable can hold an integer now and a string later. The naming convention is `snake_case` for ordinary local variables, and the first character of the name encodes its scope — lowercase or underscore for locals, `@` for instance variables, `@@` for class variables, and a leading capital for constants. You will meet `@` variables properly in the classes lesson; for now, stick to plain locals.\n\nThe core scalar types are `Integer`, `Float`, `String`, the booleans `true` and `false`, the symbol type you will see next lesson, and the special value `nil` that means \"nothing here.\" Integers are arbitrary precision, so `2 ** 100` computes the exact answer without overflow. Floats are IEEE 754 doubles with the usual rounding quirks, which is why `0.1 + 0.2` is not exactly `0.3`. Crucially, *everything* in Ruby is an object, including numbers and booleans — `5.times`, `true.class`, and `nil.to_s` all work because each value carries methods.\n\nYou inspect a value's type with `.class`, which returns the class object: `7.class` is `Integer`, `\"hi\".class` is `String`. Conversion methods are everywhere and follow a predictable `.to_X` pattern: `.to_s` to string, `.to_i` to integer, `.to_f` to float, `.to_a` to array. These are forgiving — `\"42abc\".to_i` returns `42` rather than raising — which is convenient but can hide bugs if your input is dirtier than you think.\n\nTwo truthiness rules separate Ruby from most languages and trip up newcomers constantly. Only `false` and `nil` are falsy. Everything else is truthy — including `0`, the empty string `\"\"`, and the empty array `[]`. So `if 0` runs its body, and `if \"\"` runs its body. If you came from Python or C, unlearn the habit of treating zero or empty as false. Constants, names that start with a capital letter, are not truly immutable — reassigning one only emits a warning — but treat them as fixed by convention.",
    code: "count = 7\nprice = 3.5\ngreeting = \"hi\"\nflag = true\n\nputs count.class\nputs price.class\nputs greeting.class\nputs flag.class",
    runnable: true,
    exercise: {
      prompt: "Set `score` to the string \"95\", convert it to an integer, add 5, and print the result.",
      starter: "score = \"95\"\n# convert, add 5, print\n",
      expected: "100",
    },
    takeaways: [
      "Variables are names bound to objects; assignment rebinds, it does not copy.",
      "Everything is an object — numbers, booleans, and nil all carry methods.",
      "Inspect a type with .class; convert with .to_s, .to_i, .to_f, .to_a.",
      "Only false and nil are falsy — 0 and \"\" are both truthy in Ruby.",
    ],
    mistakes: [
      "Treating 0 or an empty string as falsy — in Ruby they are truthy.",
      "Forgetting .to_i on string input, then trying to do math on a string.",
      "Naming a local with a leading capital, accidentally creating a constant.",
    ],
    next: { label: "Symbols", href: "#/courses/ruby-basics/r3" },
  },
  {
    id: "r3",
    title: "3. Symbols",
    intro: "A symbol is written with a leading colon, like `:name` or `:status`. It looks like a tiny string, and beginners often treat it as one, but a symbol is a distinct type with a different purpose. The defining property is that a symbol is *interned*: every occurrence of `:name` anywhere in your program refers to the exact same object in memory. Two strings with the same text are usually two separate objects; two symbols with the same name are always one. That makes symbols cheap to compare — checking `:a == :a` is an identity check, not a character-by-character walk — and cheap to store, because the runtime keeps a single copy regardless of how many times you mention it.\n\nThis is why symbols are the idiomatic choice for fixed, known identifiers: hash keys, option flags, method names passed around, and state values from a small fixed set. When you write `{ name: \"Ada\", role: :admin }`, the keys `name` and `role` are symbols, and `:admin` is a symbol value drawn from a closed set of roles. Using strings there would allocate a fresh object every time the literal is evaluated and would make lookups marginally slower. Symbols signal intent, too: a symbol says \"this is a label I chose,\" whereas a string says \"this is data, possibly from the outside world.\"\n\nThe rule of thumb is simple. If the value is a name or a tag that you, the programmer, picked and that will never be edited or shown to a user, use a symbol. If the value is text that came from a file, a form, a network request, or will be displayed, use a string. User input is always a string; an internal status code is a symbol.\n\nConversion runs both ways. `:hello.to_s` gives the string `\"hello\"`, and `\"hello\".to_sym` gives the symbol `:hello`. You will use these when bridging external string data into internal symbol keys. One historical caveat: in very old Ruby, symbols were never garbage collected, so turning unbounded user input into symbols could exhaust memory. Modern Ruby collects unused dynamic symbols, but the habit of not symbolising arbitrary external input is still worth keeping.",
    code: "status = :active\nputs status\nputs status.class\nputs status.to_s\nputs(:active == :active)",
    runnable: true,
    exercise: {
      prompt: "Convert the string \"draft\" to a symbol and print its class (should print `Symbol`).",
      starter: "word = \"draft\"\n# convert to a symbol and print its class\n",
      expected: "Symbol",
    },
    takeaways: [
      "A symbol :name is interned — every use is the same object in memory.",
      "Symbols are ideal for hash keys, flags, and fixed internal labels.",
      "Strings are for data and user input; symbols are for programmer-chosen names.",
      "Convert with :sym.to_s and \"str\".to_sym.",
    ],
    mistakes: [
      "Using a string key in one place and a symbol key in another for the same hash.",
      "Symbolising arbitrary user input out of habit — keep external data as strings.",
      "Assuming :name and \"name\" are equal — they are different types and not ==.",
    ],
    next: { label: "Arrays", href: "#/courses/ruby-basics/r4" },
  },
  {
    id: "r4",
    title: "4. Arrays",
    intro: "An array is an ordered, integer-indexed collection that can hold objects of any type, mixed freely. You write one with square brackets: `nums = [1, 2, 3]`. Indexing is zero-based, so `nums[0]` is the first element. Ruby adds negative indexing, where `nums[-1]` is the last element, `nums[-2]` the second-last, and so on — far cleaner than computing `length - 1` by hand. Asking for an index that does not exist returns `nil` rather than raising, which is convenient but means a stray `nil` can travel a long way before it causes a visible error.\n\nArrays grow and shrink at both ends. `push` (or the shovel operator `<<`) appends, `pop` removes from the end, `unshift` prepends, and `shift` removes from the front. The shovel operator is the most common: `nums << 4` adds `4` and returns the array so you can chain. You combine arrays with `+` (concatenate into a new array) or `concat` / `<<` for in-place growth, and you remove elements with `delete` or by value.\n\nSlicing reads naturally. `nums[1, 2]` takes two elements starting at index 1, and range syntax `nums[1..2]` takes the inclusive slice from index 1 through 2. `first` and `last` take optional counts, so `nums.first(2)` returns the first two elements as a new array. The `.length` (aliased `.size`) method counts elements, `.include?` checks membership, `.index` finds the position of a value, and `.sort`, `.reverse`, `.uniq`, and `.min`/`.max` do exactly what their names say.\n\nA subtlety worth internalising early: many array methods come in pairs — a non-bang version that returns a new array and a bang version that mutates the receiver. `nums.sort` leaves `nums` untouched and returns a sorted copy; `nums.sort!` reorders `nums` in place. Reaching for the bang version when you did not mean to share the mutation is a frequent source of action-at-a-distance bugs, because another variable pointing at the same array sees the change too. Default to the copying version; mutate deliberately. Arrays are the workhorse collection, and the iterators in a later lesson are what make them powerful.",
    code: "nums = [3, 1, 2]\nnums << 4\nputs nums.length\nputs nums.sort.inspect\nputs nums.first\nputs nums.last",
    runnable: true,
    exercise: {
      prompt: "Given `xs = [5, 2, 9, 1]`, print the maximum value followed on the next line by the sorted array's inspect form.",
      starter: "xs = [5, 2, 9, 1]\n# print max, then sorted xs inspected\n",
      expected: "9\n[1, 2, 5, 9]",
    },
    takeaways: [
      "Arrays are ordered, zero-indexed, and can mix types; nums[-1] is the last.",
      "Grow with << / push / unshift; shrink with pop / shift.",
      "Slice with nums[1, 2] (start, count) or nums[1..2] (range).",
      "Bang methods like sort! mutate in place; plain sort returns a copy.",
    ],
    mistakes: [
      "Indexing out of bounds returns nil rather than raising — the nil leaks downstream.",
      "Calling sort! when another variable shares the array and seeing it change too.",
      "Confusing nums[1, 2] (start + count) with nums[1..2] (range of indices).",
    ],
    next: { label: "Hashes", href: "#/courses/ruby-basics/r5" },
  },
  {
    id: "r5",
    title: "5. Hashes",
    intro: "A hash is a collection of key-value pairs, the same idea other languages call a dictionary or map. You write one with curly braces: `person = { name: \"Ada\", age: 36 }`. That literal uses the modern symbol-key shorthand — `name:` is sugar for `:name =>`. You can also write the explicit hash-rocket form `{ :name => \"Ada\" }` or use string keys `{ \"name\" => \"Ada\" }`; all three are valid, but the symbol shorthand is by far the most idiomatic for fixed, known keys. Keys can be any object — symbols, strings, integers, even arrays — but within one hash you should pick one key type and stick to it, because `h[:name]` and `h[\"name\"]` are two different lookups.\n\nYou read a value by indexing with its key: `person[:name]`. If the key is absent, the lookup returns `nil` by default — no error. That default can bite you, so Ruby offers `fetch`, which raises a `KeyError` for a missing key or lets you supply a fallback: `person.fetch(:email, \"none\")`. You can also construct a hash with a default value via `Hash.new(0)`, which is the classic trick for counting: every missing key reads as `0`, so `counts[word] += 1` just works without an existence check.\n\nWriting is symmetric: `person[:email] = \"a@b.co\"` adds or overwrites a pair. `delete` removes a key, `key?` (alias `has_key?`) and `value?` test membership, `keys` and `values` return arrays, and `merge` combines two hashes into a new one with the right-hand side winning on conflicts. The `.size` method counts pairs. Hashes preserve insertion order, so iterating yields pairs in the order you added them — a guarantee you can rely on.\n\nIterating a hash gives you both halves of each pair: `person.each { |key, value| ... }` binds two block parameters per iteration. You will meet blocks fully in the next lessons, but the shape is worth seeing now because hash iteration is everywhere. The combination of symbol keys, `fetch` for safety, and `Hash.new(0)` for counting covers the overwhelming majority of real hash usage you will write.",
    code: "person = { name: \"Ada\", age: 36 }\nputs person[:name]\nperson[:role] = :admin\nputs person.keys.inspect\nputs person.fetch(:email, \"none\")",
    runnable: true,
    exercise: {
      prompt: "Build a hash `h` with key :count set to 0, increment it by 1, and print the value of :count.",
      starter: "h = { count: 0 }\n# increment :count by 1 and print it\n",
      expected: "1",
    },
    takeaways: [
      "Hashes map keys to values; { name: \"Ada\" } uses symbol-key shorthand.",
      "A missing key returns nil; use fetch for an error or a default fallback.",
      "Hash.new(0) gives a counting hash where missing keys read as 0.",
      "Symbol keys and string keys are different — pick one per hash.",
    ],
    mistakes: [
      "Mixing :name and \"name\" keys in the same hash and getting nil on lookup.",
      "Relying on nil for a missing key when fetch would surface the bug sooner.",
      "Expecting h[:name] and h[\"name\"] to be the same entry — they are not.",
    ],
    next: { label: "Conditionals", href: "#/courses/ruby-basics/r6" },
  },
  {
    id: "r6",
    title: "6. Conditionals",
    intro: "Branching in Ruby uses `if`, `elsif` (note the spelling — no second `e`), and `else`, closed with the keyword `end`. There is no significant indentation as in Python; the `end` keyword marks where a block finishes, and you indent only for readability. Each condition is any expression, and Ruby applies its truthiness rule: the branch runs unless the condition evaluates to `false` or `nil`. Remember from the types lesson that `0` and `\"\"` are truthy, so `if 0` runs its body — a frequent surprise.\n\nRuby has two features that make conditionals read like prose. First, `if` is an *expression* that returns a value, so you can assign its result directly: `label = if score >= 60 then \"pass\" else \"fail\" end`. Second, the modifier form lets you append a one-line condition to a statement: `puts \"adult\" if age >= 18`. The modifier reads naturally for simple guards and is preferred over a full block when the body is a single line. Its mirror image is `unless`, which is `if not` — `puts \"locked\" unless open` runs when `open` is falsy. Use `unless` only for simple positive-sounding guards; `unless` with an `else`, or with a compound condition, becomes hard to parse and you should switch back to `if`.\n\nComparison operators are the familiar `==`, `!=`, `<`, `>`, `<=`, `>=`, plus the combined comparison `<=>` (the \"spaceship\") that returns `-1`, `0`, or `1` and powers sorting. Logical operators are `&&`, `||`, and `!`; Ruby also has lower-precedence word forms `and`, `or`, `not` meant for control flow rather than boolean expressions — stick to the symbol forms inside conditions to avoid precedence surprises. Short-circuiting works as expected, and the `||=` operator (\"assign if nil or false\") is a beloved idiom for setting defaults: `name ||= \"guest\"`.\n\nFor dispatching on a single value across many cases, `case`/`when`/`else`/`end` is cleaner than a long `elsif` chain. It uses the `===` case-equality operator under the hood, which lets `when` match ranges (`when 1..10`), classes (`when Integer`), and regular expressions, not just literal equality. Reach for `case` when you are picking a branch by category; reach for `if`/`elsif` when each branch tests a different, unrelated condition.",
    code: "score = 72\nif score >= 90\n  puts \"A\"\nelsif score >= 60\n  puts \"pass\"\nelse\n  puts \"fail\"\nend",
    runnable: true,
    exercise: {
      prompt: "Given `age = 17`, use a modifier-if or if/else to print \"minor\" when age is below 18, otherwise \"adult\".",
      starter: "age = 17\n# print \"minor\" or \"adult\"\n",
      expected: "minor",
    },
    takeaways: [
      "Use if / elsif / else / end; elsif has no second e and end closes the block.",
      "if is an expression that returns a value, so you can assign its result.",
      "Modifier form reads cleanly: puts x if cond; unless is if-not.",
      "case / when dispatches on one value and matches ranges, classes, and regexes.",
    ],
    mistakes: [
      "Writing elseif or else if instead of Ruby's elsif.",
      "Forgetting end and getting a syntax error far from the real spot.",
      "Treating 0 or \"\" as falsy — only false and nil are falsy in Ruby.",
    ],
    next: { label: "Loops & iterators", href: "#/courses/ruby-basics/r7" },
  },
  {
    id: "r7",
    title: "7. Loops & iterators",
    intro: "Ruby has `while` and `until` loops, a bare `loop do ... end`, and a `for` loop, but you will rarely write any of them. The idiomatic way to repeat work is to call an *iterator method* on a collection and hand it a block. `while cond ... end` runs as long as the condition is truthy; `until cond ... end` is its negation. `loop do ... end` runs forever until you `break`. These exist for the genuinely unbounded cases — reading until end-of-input, retrying until success — but for walking a known collection they are the wrong tool, and experienced Ruby reads as a sequence of iterator calls rather than index arithmetic.\n\nThe foundational iterator is `each`, which yields every element to the block in turn: `[1, 2, 3].each { |n| puts n }`. There is no index to manage, no off-by-one risk, no bounds to check. When you do need the position, `each_with_index` yields the element and its index together. To repeat a fixed number of times, integers themselves are iterable: `3.times { |i| ... }` runs the block three times with `i` going 0, 1, 2. Ranges iterate too — `(1..5).each` walks 1 through 5 inclusive, and `1.upto(5)` reads even more plainly. `step` lets you skip: `(0..10).step(2)`.\n\nBlocks come in two syntaxes that mean the same thing. Curly braces `{ |x| ... }` are conventional for single-line blocks; `do |x| ... end` is conventional for multi-line blocks. The variable between the pipes is the block parameter, bound fresh on each iteration. Inside any loop or iterator, `break` exits immediately, `next` skips to the following iteration (Ruby's `continue`), and `redo` re-runs the current iteration — `next` and `break` are the two you will actually use.\n\nThe reason to prefer iterators is not just style. `each` and its relatives eliminate the entire category of index bugs, they compose with the transforming methods (`map`, `select`, `reduce`) you will meet in the enumerable lesson, and they make intent obvious: `users.each` says \"do this for every user\" far more directly than a counter that walks from `0` to `length - 1`. When you catch yourself writing `while i < arr.length`, stop and reach for `each` instead.",
    code: "[10, 20, 30].each { |n| puts n }\n\n3.times { |i| puts \"i=#{i}\" }\n\n(1..3).each { |x| puts x * x }",
    runnable: true,
    exercise: {
      prompt: "Use an iterator to print the squares of 1, 2, 3 — each on its own line (1, 4, 9).",
      starter: "# print 1, then 4, then 9, one per line\n",
      expected: "1\n4\n9",
    },
    takeaways: [
      "Prefer iterator methods (each, times, upto) over manual while/for loops.",
      "each yields every element to a block — no index, no off-by-one bugs.",
      "n.times repeats; (a..b).each walks an inclusive range.",
      "break exits a loop, next skips to the following iteration.",
    ],
    mistakes: [
      "Reaching for while i < arr.length when each is cleaner and safer.",
      "Mixing up { } and do/end precedence — use do/end for multi-line blocks.",
      "Forgetting that a range a..b is inclusive of b (use a...b to exclude it).",
    ],
    next: { label: "Blocks & yield", href: "#/courses/ruby-basics/r8" },
  },
  {
    id: "r8",
    title: "8. Blocks & yield",
    intro: "A block is a chunk of code you pass to a method, written either as `{ |x| ... }` or `do |x| ... end` immediately after the method call. Blocks are the beating heart of Ruby — `each`, `map`, `times`, and almost every iterator you have already used are just methods that accept a block and call it. Understanding how a method receives and runs a block demystifies the whole language. A block is not an argument in the usual comma-separated sense; it is a special trailing construct that at most one block can occupy per call.\n\nInside a method, the keyword `yield` invokes the block that was passed in. Plain `yield` calls the block with no arguments; `yield x` calls it with `x`, which becomes the block's parameter. So a method `def twice; yield; yield; end` calls its block two times, and `twice { puts \"hi\" }` prints `hi` twice. You can pass values out to the block — `def each_pair; yield 1, 2; end` hands `1` and `2` to a block written `{ |a, b| ... }`. The method `block_given?` returns true when a block was supplied, letting a method behave differently with and without one, which is how methods like `fetch` offer an optional block fallback.\n\nThe value a block returns flows back to the method, and the value `yield` evaluates to *is* the block's last expression. This two-way exchange — the method feeds values into the block, the block hands a result back — is what makes blocks so expressive. `map` works exactly this way: it yields each element, takes whatever the block returns, and collects those results into a new array. Once you see `map` as \"call the block on each item and gather the return values,\" the whole enumerable family clicks into place.\n\nIf you want to capture a block as an object — to store it, pass it on, or call it later — prefix the final parameter with an ampersand: `def run(&blk); blk.call; end`. That converts the block into a `Proc` bound to `blk`, and `.call` invokes it. The reverse also works: `&` in front of a Proc or symbol at a call site turns it back into a block, which is why `[1, 2, 3].map(&:to_s)` is shorthand for `map { |x| x.to_s }`. Blocks, `yield`, and the `&` conversion are the three ideas that unlock writing your own iterator-style methods.",
    code: "def repeat(n)\n  n.times { yield }\nend\n\nrepeat(3) { puts \"go\" }\n\ndef greet\n  block_given? ? yield(\"Ada\") : puts(\"no block\")\nend\nputs greet { |name| \"Hi #{name}\" }",
    runnable: true,
    exercise: {
      prompt: "Write a method `shout` that yields the string \"hi\" to its block, then call it with a block that upcases and prints what it receives (prints HI).",
      starter: "def shout\n  # yield \"hi\" to the block\nend\n\n# call shout with a block that upcases and prints\n",
      expected: "HI",
    },
    takeaways: [
      "A block is trailing code ({ } or do/end) passed to a method; at most one per call.",
      "yield calls the block; yield x passes x as the block's parameter.",
      "block_given? checks whether a block was supplied.",
      "&blk captures a block as a Proc; map(&:to_s) is map { |x| x.to_s }.",
    ],
    mistakes: [
      "Calling yield in a method that was given no block raises a LocalJumpError.",
      "Passing more than one block to a method — only one trailing block is allowed.",
      "Forgetting that yield returns the block's value, then ignoring that result.",
    ],
    next: { label: "Methods", href: "#/courses/ruby-basics/r9" },
  },
  {
    id: "r9",
    title: "9. Methods",
    intro: "A method is defined with `def name ... end`. The body runs when the method is called, and methods are the basic unit of reuse. Ruby has a defining quirk: the value of the last expression evaluated is returned automatically, with no `return` keyword needed. `def add(a, b); a + b; end` returns the sum because `a + b` is the last line. You can write an explicit `return` to exit early — guard clauses like `return 0 if items.empty?` are idiomatic — but for the final value, leave it implicit. Writing a needless `return` on the last line marks code as un-idiomatic.\n\nParameters come in several flavours. Positional parameters are the default. Default values let a parameter be optional: `def greet(name = \"guest\")`. The splat operator `*args` gathers any number of trailing positional arguments into an array, so `def sum(*nums)` accepts `sum(1, 2, 3)` and sees `nums == [1, 2, 3]`. Keyword arguments, written `def connect(host:, port: 80)`, are passed by name at the call site — `connect(host: \"x\", port: 9)` — which makes calls self-documenting and order-independent. The double splat `**opts` gathers extra keyword arguments into a hash. Mixing a couple of positional parameters with keyword arguments for the optional, less-obvious settings is the most readable convention.\n\nMethod names carry meaning by their suffix. A trailing `?` marks a predicate that returns a boolean — `empty?`, `include?`, `even?` — and you should name your own boolean methods the same way. A trailing `!` marks a \"dangerous\" or mutating variant, usually the in-place sibling of a safer method, as with `sort` and `sort!`. These are conventions enforced by the community, not the parser, but following them makes your code instantly legible to other Ruby programmers.\n\nArguments are passed by reference to the same object, so a method that mutates a mutable argument — pushing onto an array, say — changes the caller's array too. Reassigning the parameter inside the method does not affect the caller, because that only rebinds the local name. The distinction is exactly the one from the variables lesson: mutation is visible across the binding, rebinding is not. When you want a method to be safe, avoid mutating your arguments and return a new value instead.",
    code: "def add(a, b)\n  a + b\nend\n\ndef greet(name = \"guest\")\n  \"Hi, #{name}\"\nend\n\nputs add(2, 3)\nputs greet\nputs greet(\"Ada\")",
    runnable: true,
    exercise: {
      prompt: "Define a method `double` that takes a number and returns it times two (no return keyword), then print double(21).",
      starter: "def double(n)\n  # return n times 2 implicitly\nend\n\nputs double(21)\n",
      expected: "42",
    },
    takeaways: [
      "Define with def ... end; the last expression is returned automatically.",
      "Use *args to gather positional args and keyword args (name:) for clarity.",
      "Suffix ? for predicates returning booleans, ! for mutating variants.",
      "Mutating a mutable argument is visible to the caller; rebinding is not.",
    ],
    mistakes: [
      "Writing return on the final line — idiomatic Ruby relies on implicit return.",
      "Calling a method that needs arguments without them raises an ArgumentError.",
      "Mutating an array argument and surprising the caller whose array also changed.",
    ],
    next: { label: "Classes & attr_accessor", href: "#/courses/ruby-basics/r10" },
  },
  {
    id: "r10",
    title: "10. Classes & attr_accessor",
    intro: "A class is a blueprint for objects, defined with `class Name ... end` where the name must start with a capital letter. You create an instance with `Name.new(args)`. When you call `.new`, Ruby allocates the object and then calls a special method named `initialize` on it, passing along the arguments — `initialize` is Ruby's constructor. Inside it, you set up the object's state by assigning to *instance variables*, names that begin with `@`. An instance variable like `@name` belongs to one particular object and persists for that object's whole life, distinct from a local variable that vanishes when the method returns.\n\nInstance variables are private to the object: code outside the class cannot read `obj.@name` directly. To expose them, you define accessor methods. Writing them by hand is tedious — a getter `def name; @name; end` and a setter `def name=(v); @name = v; end` for every field — so Ruby provides three macros that generate them for you. `attr_reader :name` creates the getter, `attr_writer :name` creates the setter, and `attr_accessor :name` creates both. You list the symbols you want at the top of the class, and the methods appear as if you had typed them. `attr_accessor` is the one you reach for most; use `attr_reader` for values that should be set once at construction and never reassigned from outside.\n\nMethods defined in the class body are *instance methods*: they run in the context of a particular object and can read and write that object's `@` variables. Inside an instance method, the keyword `self` refers to the current object — the receiver the method was called on. You use `self` to call the object's own setter (`self.name = x`, since a bare `name = x` would create a local) and occasionally to disambiguate, but a plain method call inside a class already runs against `self`, so you rarely need to write it explicitly.\n\nTwo more pieces round out the basics. A method prefixed with `self.`, like `def self.create`, is a *class method* — called on the class itself (`Name.create`) rather than on an instance, useful for factory-style constructors. And defining `to_s` controls how your object prints: `puts obj` calls `to_s`, so giving your class a sensible `to_s` makes debugging output readable. Classes, `initialize`, instance variables, and `attr_accessor` together are everything you need to model real entities.",
    code: "class Dog\n  attr_accessor :name, :age\n\n  def initialize(name, age)\n    @name = name\n    @age = age\n  end\n\n  def to_s\n    \"#{@name} (#{@age})\"\n  end\nend\n\nrex = Dog.new(\"Rex\", 3)\nputs rex.name\nrex.age = 4\nputs rex",
    runnable: true,
    exercise: {
      prompt: "Define a class Point with attr_reader :x, set @x from initialize, create Point.new(7), and print its x.",
      starter: "class Point\n  # attr_reader :x and an initialize that sets @x\nend\n\np1 = Point.new(7)\nputs p1.x\n",
      expected: "7",
    },
    takeaways: [
      "class Name ... end defines a blueprint; Name.new calls initialize.",
      "Instance variables start with @ and hold per-object state.",
      "attr_reader / attr_writer / attr_accessor generate getters and setters.",
      "self is the current object; def self.method defines a class method.",
    ],
    mistakes: [
      "Forgetting attr_accessor and then getting a NoMethodError on obj.name.",
      "Writing name = x inside a method instead of self.name = x, creating a local.",
      "Trying to read @name from outside the object — instance variables are private.",
    ],
    next: { label: "Modules & mixins", href: "#/courses/ruby-basics/r11" },
  },
  {
    id: "r11",
    title: "11. Modules & mixins",
    intro: "A module is defined with `module Name ... end` and serves two distinct purposes. The first is *namespacing*: grouping related constants, classes, and methods under one name so they do not collide with anything else. `Math::PI` and `JSON.parse` use the module-as-namespace pattern, where the `::` operator reaches inside the module to a constant or nested class. When you have a cluster of related code that should not pollute the global space, wrap it in a module. The second purpose is the one that makes modules central to Ruby's design: *mixins*, a way to share behaviour across unrelated classes without inheritance.\n\nRuby has single inheritance — a class has exactly one superclass — which avoids the tangles of multiple inheritance but raises a question: how do you give a method to many classes that do not share a parent? The answer is to put the methods in a module and `include` that module into each class. `include Comparable` injects the module's instance methods as if they were defined in the class itself. A class can include any number of modules, so you compose behaviour from several sources. This is the mixin pattern, and it is how Ruby gets the flexibility of multiple inheritance without the ambiguity.\n\nThe two standard-library mixins you will meet constantly are `Comparable` and `Enumerable`, and both follow the same elegant contract: you define one method, and the module gives you many in return. `Comparable` asks you to implement `<=>` (the spaceship operator), and in exchange it defines `<`, `<=`, `==`, `>`, `>=`, and `between?` for free, all expressed in terms of your `<=>`. `Enumerable` asks you to implement `each`, and in return you get `map`, `select`, `reduce`, `sort`, `min`, `max`, `to_a`, and dozens more — the entire enumerable toolkit from the next lesson — on any class that can iterate itself.\n\nThere are two flavours of mixing in. `include` adds the module's methods as instance methods, available on each object of the class. `extend` adds them as class methods or to a single object. And module methods defined with `module_function` or `def self.x` are callable directly on the module, like `MyUtils.helper`, giving you the namespaced-function style. The mental model to keep: inheritance answers \"what is this,\" while a mixin answers \"what can this do.\" When you find yourself wanting to copy a method into several classes, define it once in a module and include it.",
    code: "module Greetable\n  def greet\n    \"Hi, I am #{name}\"\n  end\nend\n\nclass Person\n  include Greetable\n  attr_reader :name\n  def initialize(name)\n    @name = name\n  end\nend\n\nputs Person.new(\"Ada\").greet",
    runnable: true,
    exercise: {
      prompt: "Define a module Loud with a method `shout` returning \"HI\", include it in a class Speaker, and print Speaker.new.shout.",
      starter: "module Loud\n  # def shout returning \"HI\"\nend\n\nclass Speaker\n  # include Loud\nend\n\nputs Speaker.new.shout\n",
      expected: "HI",
    },
    takeaways: [
      "Modules namespace code (Math::PI) and share behaviour as mixins.",
      "include adds a module's methods as instance methods on a class.",
      "Comparable needs only <=>; Enumerable needs only each — both give many methods.",
      "Inheritance answers 'what is this'; a mixin answers 'what can this do'.",
    ],
    mistakes: [
      "Trying to call Module.new on a plain module — modules are not instantiated.",
      "Using inheritance to share a method across unrelated classes instead of a mixin.",
      "Forgetting to define each (for Enumerable) or <=> (for Comparable) before mixing in.",
    ],
    next: { label: "Enumerable methods", href: "#/courses/ruby-basics/r12" },
  },
  {
    id: "r12",
    title: "12. Enumerable methods",
    intro: "Enumerable is the collection of methods that turns Ruby's arrays and hashes into a data-processing toolkit, and mastering it is the single biggest jump in Ruby fluency. Every method here takes a block and walks the collection for you, so you describe *what* transformation you want rather than writing the loop that performs it. The three you will use most are `map`, `select`, and `reduce`. `map` transforms: it calls the block on each element and collects the return values into a new array, so `[1, 2, 3].map { |n| n * 2 }` is `[2, 4, 6]`. The original is untouched; `map` always returns a fresh array of the same length.\n\n`select` (alias `filter`) keeps only the elements for which the block returns truthy: `[1, 2, 3, 4].select { |n| n.even? }` is `[2, 4]`. Its mirror, `reject`, keeps the elements for which the block is falsy. `reduce` (alias `inject`) folds the whole collection down to a single value by threading an accumulator through it: `[1, 2, 3, 4].reduce(0) { |sum, n| sum + n }` is `10`, and the common cases have shorthands — `reduce(:+)` sums, `reduce(:*)` multiplies. Together, map-select-reduce express the overwhelming majority of collection work you will ever write.\n\nBeyond the big three, a rich supporting cast handles common questions in one call. `each_with_index` gives you element and position together. `find` (alias `detect`) returns the first element matching the block. `count` with a block counts matches. `any?`, `all?`, and `none?` answer membership questions as booleans. `sort_by` orders by a computed key — `words.sort_by(&:length)` sorts by length — and `group_by` partitions into a hash of categories. `min_by` and `max_by` find extremes by a key, `sum` adds numerics directly, and `flat_map` maps then flattens one level. `each_with_object` builds up a result object without the accumulator-return dance that trips people up in `reduce`.\n\nThe defining strength of Enumerable is *chaining*. Because each method returns a new collection, you compose a pipeline: `users.select { |u| u.active? }.map(&:name).sort` reads top to bottom as filter, transform, order. The `&:name` shorthand you saw in the blocks lesson keeps each stage terse. Chaining replaces nested loops and temporary variables with a single readable expression, and it is the style that makes idiomatic Ruby a pleasure to read. When you face any 'do something to every element' task, start by asking which Enumerable method names it.",
    code: "nums = [1, 2, 3, 4, 5]\nputs nums.map { |n| n * n }.inspect\nputs nums.select { |n| n.even? }.inspect\nputs nums.reduce(0) { |sum, n| sum + n }",
    runnable: true,
    exercise: {
      prompt: "Given `nums = [1, 2, 3, 4, 5, 6]`, select the even numbers, double each, and print the resulting array's inspect form.",
      starter: "nums = [1, 2, 3, 4, 5, 6]\n# select evens, double each, print inspected\n",
      expected: "[4, 8, 12]",
    },
    takeaways: [
      "map transforms each element into a new array of the same length.",
      "select keeps matching elements; reject drops them.",
      "reduce folds a collection to one value; reduce(:+) sums.",
      "Methods return collections, so chain them into a readable pipeline.",
    ],
    mistakes: [
      "Reaching for each and a manual accumulator when map or reduce fits better.",
      "Expecting map to filter — it always returns one result per element; use select.",
      "Forgetting reduce needs a starting value (or first element) for the accumulator.",
    ],
    next: { label: "Exceptions", href: "#/courses/ruby-basics/r13" },
  },
  {
    id: "r13",
    title: "13. Exceptions",
    intro: "When something goes wrong at runtime — a missing key fetched, a number divided by zero, a file that is not there — Ruby *raises* an exception. An unhandled exception unwinds the call stack and stops the program, printing the error class and message. You handle exceptions with a `begin ... rescue ... end` block: code in the `begin` section runs, and if it raises, control jumps to the matching `rescue` clause instead of crashing. This is how you write code that recovers from anticipated failures rather than dying on them.\n\nA bare `rescue` catches `StandardError` and its subclasses, which covers the everyday errors — `ArgumentError`, `TypeError`, `ZeroDivisionError`, `KeyError`, and the like. You should almost always rescue a *specific* class rather than catching everything, because a blanket rescue can swallow bugs you wanted to see: `rescue ZeroDivisionError => e` catches only that error and binds the exception object to `e`, whose `.message` and `.class` you can inspect. You can list several `rescue` clauses to handle different error types differently, and they are tried top to bottom like a `case`. Resist the urge to `rescue Exception` — that catches even `Interrupt` and `SystemExit`, breaking Ctrl-C and `exit`.\n\nTwo optional clauses complete the structure. `else` runs only if the `begin` block raised nothing — a place for code that should run on success but should not itself be guarded. `ensure` runs no matter what, exception or not, and is where you put cleanup: closing a file, releasing a lock, restoring state. The `ensure` block is Ruby's answer to `finally` in other languages, and it runs even if a `rescue` itself re-raises.\n\nYou raise your own exceptions with `raise`. `raise \"something broke\"` raises a `RuntimeError` with that message; `raise ArgumentError, \"n must be positive\"` raises a specific class with a message. Inside a `rescue`, a bare `raise` re-raises the current exception, useful for logging then propagating. For domain-specific errors, define your own class inheriting from `StandardError`: `class ValidationError < StandardError; end`. The guiding principle is to use exceptions for genuinely exceptional, unexpected conditions — not for ordinary control flow that a simple `if` or a `nil`-returning method would handle more clearly. Rescue narrowly, clean up in `ensure`, and let truly unexpected errors crash loudly so you find them.",
    code: "def safe_div(a, b)\n  begin\n    a / b\n  rescue ZeroDivisionError => e\n    \"error: #{e.message}\"\n  end\nend\n\nputs safe_div(10, 2)\nputs safe_div(10, 0)",
    runnable: true,
    exercise: {
      prompt: "Write code that tries to divide 8 by 0 inside begin/rescue ZeroDivisionError and prints \"caught\" when it fails.",
      starter: "begin\n  # divide 8 by 0\nrescue ZeroDivisionError\n  # print \"caught\"\nend\n",
      expected: "caught",
    },
    takeaways: [
      "begin / rescue / end catches a raised exception instead of crashing.",
      "Rescue a specific class (rescue ZeroDivisionError => e) — not bare Exception.",
      "ensure always runs for cleanup; else runs only when nothing was raised.",
      "raise Klass, \"msg\" raises your own error; define subclasses of StandardError.",
    ],
    mistakes: [
      "rescue Exception catches Ctrl-C and exit too — rescue StandardError or narrower.",
      "Using exceptions for ordinary control flow that an if would handle clearly.",
      "Swallowing an error silently in rescue and hiding a real bug.",
    ],
    next: { label: "Back to courses", href: "#/courses" },
  },
];

export const RUBY_BASICS_COURSE = {
  id: "ruby-basics",
  title: "Ruby Basics",
  language: "ruby",
  color: "#CC342D",
  blurb: "From puts and strings to classes, mixins, and the Enumerable methods that make Ruby sing.",
  estimatedHours: 3,
  externalResources: [
    { title: "Ruby — Official documentation", url: "https://www.ruby-lang.org/en/documentation/", type: "course" },
    { title: "Ruby core API reference (ruby-doc.org)", url: "https://ruby-doc.org/", type: "docs" },
    { title: "The Odin Project — Ruby course", url: "https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby", type: "course" },
    { title: "Ruby in Twenty Minutes (official quick-start)", url: "https://www.ruby-lang.org/en/documentation/quickstart/", type: "tutorial" },
  ],
  lessons: RUBY_LESSONS,
};
